* `_endurance_bonus`
* `_intelligence_bonus`
* `_strength_bonus`
* `endurance_bonus`
* `endurance_bonus=`
* `careers$Career$init`
* `intelligence_bonus`
* `intelligence_bonus=`
* `strength_bonus`
* `strength_bonus=`
