all:
	msgfmt boilerplate.po -o boilerplate.mo
	msgfmt welcome.po -o welcome.mo
	msgfmt meetup.po -o meetup.mo
	msgfmt meetup_creation.po -o meetup_creation.mo
	msgfmt meetup_confirmation.po -o meetup_confirmation.mo
