../lib/standard/collection/array.nit:24,21--27: Error: No property AbstractArrayRead::length is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:26,12--19: Error: No property AbstractArrayRead::is_empty is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:28,12--14: Error: No property AbstractArrayRead::has is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:39,12--19: Error: No property AbstractArrayRead::has_only is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:50,12--16: Error: No property AbstractArrayRead::count is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:62,12--19: Error: No property AbstractArrayRead::index_of is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/abstract_collection.nit:83,12--19: Error: No property NaiveCollection::is_empty is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/abstract_collection.nit:85,12--17: Error: No property NaiveCollection::length is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/abstract_collection.nit:92,12--14: Error: No property NaiveCollection::has is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/abstract_collection.nit:98,12--19: Error: No property NaiveCollection::has_only is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/abstract_collection.nit:104,12--16: Error: No property NaiveCollection::count is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/abstract_collection.nit:111,12--16: Error: No property NaiveCollection::first is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:128,12--17: Error: No property AbstractArrayRead::output is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/abstract_collection.nit:137,12--16: Error: No property Container::first is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:139,12--19: Error: No property AbstractArrayRead::iterator is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/abstract_collection.nit:139,12--19: Error: No property Container::is_empty is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/abstract_collection.nit:141,12--17: Error: No property Container::length is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:142,12--13: Error: No property AbstractArrayRead::== is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/abstract_collection.nit:143,12--14: Error: No property Container::has is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/abstract_collection.nit:145,12--19: Error: No property Container::has_only is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/abstract_collection.nit:147,12--16: Error: No property Container::count is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/abstract_collection.nit:156,12--19: Error: No property Container::iterator is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:166,12--15: Error: No property AbstractArray::push is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:168,12--14: Error: No property AbstractArray::pop is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/abstract_collection.nit:168,12--15: Error: No property ContainerIterator::item is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/abstract_collection.nit:170,12--15: Error: No property ContainerIterator::next is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/abstract_collection.nit:174,21--26: Error: No property ContainerIterator::is_ok is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:176,12--16: Error: No property AbstractArray::shift is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:190,12--18: Error: No property AbstractArray::unshift is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:212,12--14: Error: No property AbstractArray::add is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:214,12--16: Error: No property AbstractArray::clear is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/abstract_collection.nit:215,12--19: Error: No property Set::has_only is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:216,12--17: Error: No property AbstractArray::remove is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:218,12--21: Error: No property AbstractArray::remove_all is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:227,12--20: Error: No property AbstractArray::remove_at is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/abstract_collection.nit:228,12--16: Error: No property Set::count is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/abstract_collection.nit:238,12--21: Error: No property Set::remove_all is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:266,12--18: Error: No property Array::iterate is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:278,12--13: Error: No property Array::[] is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:284,12--14: Error: No property Array::[]= is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:296,12--14: Error: No property Array::add is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:306,12--18: Error: No property Array::enlarge is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/abstract_collection.nit:321,12--17: Error: No property Map::values is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/abstract_collection.nit:323,12--15: Error: No property Map::keys is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/abstract_collection.nit:375,12--16: Error: No property SequenceRead::first is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/abstract_collection.nit:407,12--19: Error: No property SequenceRead::iterator is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:431,12--15: Error: No property ArrayIterator::item is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/abstract_collection.nit:434,12--14: Error: No property Sequence::add is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:435,12--16: Error: No property ArrayIterator::is_ok is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:437,12--15: Error: No property ArrayIterator::next is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:445,21--26: Error: No property ArrayIterator::index is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:458,12--14: Error: No property ArraySet::has is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:460,12--14: Error: No property ArraySet::add is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:462,12--19: Error: No property ArraySet::is_empty is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:464,12--17: Error: No property ArraySet::length is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:466,12--16: Error: No property ArraySet::first is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:472,12--17: Error: No property ArraySet::remove is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/abstract_collection.nit:473,12--13: Error: No property CoupleMap::[] is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:478,12--21: Error: No property ArraySet::remove_all is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:480,12--16: Error: No property ArraySet::clear is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:482,12--19: Error: No property ArraySet::iterator is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/abstract_collection.nit:489,12--15: Error: No property CoupleMapIterator::item is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/abstract_collection.nit:493,12--14: Error: No property CoupleMapIterator::key is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/abstract_collection.nit:495,12--16: Error: No property CoupleMapIterator::is_ok is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/abstract_collection.nit:497,12--15: Error: No property CoupleMapIterator::next is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:504,12--16: Error: No property ArraySetIterator::is_ok is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:506,12--15: Error: No property ArraySetIterator::next is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:508,12--15: Error: No property ArraySetIterator::item is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:521,12--13: Error: No property ArrayMap::[] is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:532,12--14: Error: No property ArrayMap::[]= is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:542,12--15: Error: No property ArrayMap::keys is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:543,12--17: Error: No property ArrayMap::values is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:546,12--17: Error: No property ArrayMap::length is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:548,12--19: Error: No property ArrayMap::iterator is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:550,12--19: Error: No property ArrayMap::is_empty is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:552,12--16: Error: No property ArrayMap::clear is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:557,12--20: Error: No property ArrayMap::couple_at is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:629,12--16: Error: No property ArrayMapValues::first is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:630,12--19: Error: No property ArrayMapValues::is_empty is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:631,12--17: Error: No property ArrayMapValues::length is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:632,12--19: Error: No property ArrayMapValues::iterator is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:635,12--14: Error: No property ArrayMapValues::has is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:642,12--19: Error: No property ArrayMapValues::has_only is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:649,12--16: Error: No property ArrayMapValues::count is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:656,12--16: Error: No property ArrayMapValues::clear is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:658,12--17: Error: No property ArrayMapValues::remove is inherited. Remove the redef keyword to define a new property.
../lib/standard/collection/array.nit:671,12--21: Error: No property ArrayMapValues::remove_all is inherited. Remove the redef keyword to define a new property.
