Start
  exps
    Nodes[Nexp]
      exp_add
        exp_factor
          factor_term
            term_int
              int@(1:1-1:2)='5'
        '+'@(1:3-1:4)
        factor_mul
          factor_term
            term_int
              int@(1:5-1:6)='4'
          '*'@(1:7-1:8)
          term_int
            int@(1:9-1:10)='2'
      exp_min
        exp_min
          exp_factor
            factor_term
              term_int
                int@(2:1-2:2)='5'
          '-'@(2:3-2:4)
          factor_term
            term_int
              int@(2:5-2:6)='4'
        '-'@(2:7-2:8)
        factor_term
          term_int
            int@(2:9-2:10)='2'
      exp_add
        exp_add
          exp_factor
            factor_term
              term_int
                int@(3:1-3:2)='5'
          '+'@(3:3-3:4)
          factor_term
            term_int
              int@(3:5-3:6)='4'
        '+'@(3:7-3:8)
        factor_term
          term_int
            int@(3:9-3:10)='2'
      exp_factor
        factor_mul
          factor_term
            term_par
              '('@(4:1-4:2)
              exp_add
                exp_factor
                  factor_term
                    term_int
                      int@(4:2-4:3)='5'
                '+'@(4:4-4:5)
                factor_term
                  term_int
                    int@(4:6-4:7)='4'
              ')'@(4:7-4:8)
          '*'@(4:9-4:10)
          term_int
            int@(4:11-4:12)='2'
      exp_add
        exp_factor
          factor_term
            term_int
              int@(5:1-5:2)='5'
        '+'@(5:3-5:4)
        factor_term
          term_par
            '('@(5:5-5:6)
            exp_factor
              factor_mul
                factor_term
                  term_int
                    int@(5:6-5:7)='4'
                '*'@(5:8-5:9)
                term_int
                  int@(5:10-5:11)='2'
            ')'@(5:11-5:12)
  Eof@(6:1-6:1)=''
