NLexerError@(5:38-5:38)='E'
Nodes[Node]
  prods_many
    prods_many
      prods_many
        prods_one
          prod
            id@(1:1-1:6)='prods'
            '='@(1:7-1:8)
            alts_many
              alts_one
                alt_0
                  altid@(1:9-1:16)='{many:}'
                  atoms_many
                    atoms_many
                      atoms_none
                      atom_id
                        id@(1:17-1:22)='prods'
                    atom_id
                      id@(1:23-1:27)='prod'
              '|'@(1:29-1:30)
              alt_0
                altid@(1:31-1:37)='{one:}'
                atoms_many
                  atoms_none
                  atom_id
                    id@(1:38-1:42)='prod'
            ';'@(1:43-1:44)
        prod
          id@(2:1-2:5)='prod'
          '='@(2:6-2:7)
          alts_one
            alt_1
              atoms_many
                atoms_many
                  atoms_many
                    atoms_many
                      atoms_none
                      atom_id
                        id@(2:8-2:10)='id'
                    atom_str
                      str@(2:11-2:14)='\'=\''
                  atom_id
                    id@(2:15-2:19)='alts'
                atom_str
                  str@(2:20-2:23)='\';\''
          ';'@(2:24-2:25)
      prod
        id@(3:1-3:5)='alts'
        '='@(3:6-3:7)
        alts_many
          alts_one
            alt_0
              altid@(3:8-3:15)='{many:}'
              atoms_many
                atoms_many
                  atoms_many
                    atoms_none
                    atom_id
                      id@(3:16-3:20)='alts'
                  atom_str
                    str@(3:21-3:24)='\'|\''
                atom_id
                  id@(3:25-3:28)='alt'
          '|'@(3:29-3:30)
          alt_0
            altid@(3:31-3:37)='{one:}'
            atoms_many
              atoms_none
              atom_id
                id@(3:38-3:41)='alt'
        ';'@(3:42-3:43)
    prod
      id@(4:1-4:4)='alt'
      '='@(4:5-4:6)
      alts_many
        alts_one
          alt_1
            atoms_many
              atoms_many
                atoms_none
                atom_id
                  id@(4:7-4:12)='altid'
              atom_id
                id@(4:13-4:18)='atoms'
        '|'@(4:19-4:20)
        alt_1
          atoms_many
            atoms_none
            atom_id
              id@(4:21-4:26)='atoms'
      ';'@(4:27-4:28)
  id@(5:1-5:6)='atoms'
  '='@(5:7-5:8)
  alts_one
    alt_0
      altid@(5:9-5:16)='{many:}'
      atoms_many
        atoms_many
          atoms_none
          atom_id
            id@(5:17-5:22)='atoms'
        atom_id
          id@(5:23-5:27)='atom'
  '|'@(5:28-5:29)
  altid@(5:30-5:37)='{none:}'
  atoms_none
  NLexerError@(5:38-5:38)='E'
