alt/base_upcast_alt1.nit:26,20--21: Type Error: expected `A[Int]`, got `A[Bool]`.
alt/base_upcast_alt1.nit:28,20--21: Type Error: expected `A[Int]`, got `B[Bool]`.
alt/base_upcast_alt1.nit:33,20--21: Type Error: expected `A[Bool]`, got `A[Int]`.
alt/base_upcast_alt1.nit:35,20--21: Type Error: expected `A[Bool]`, got `B[Int]`.
alt/base_upcast_alt1.nit:37,20--21: Type Error: expected `A[Bool]`, got `C[Int]`.
alt/base_upcast_alt1.nit:38,20--21: Type Error: expected `A[Bool]`, got `C[Bool]`.
alt/base_upcast_alt1.nit:39,20: Type Error: expected `A[Bool]`, got `D`.
alt/base_upcast_alt1.nit:41,20--21: Type Error: expected `B[Int]`, got `A[Int]`.
alt/base_upcast_alt1.nit:42,20--21: Type Error: expected `B[Int]`, got `A[Bool]`.
alt/base_upcast_alt1.nit:44,20--21: Type Error: expected `B[Int]`, got `B[Bool]`.
alt/base_upcast_alt1.nit:49,20--21: Type Error: expected `B[Bool]`, got `A[Int]`.
alt/base_upcast_alt1.nit:50,20--21: Type Error: expected `B[Bool]`, got `A[Bool]`.
alt/base_upcast_alt1.nit:51,20--21: Type Error: expected `B[Bool]`, got `B[Int]`.
alt/base_upcast_alt1.nit:53,20--21: Type Error: expected `B[Bool]`, got `C[Int]`.
alt/base_upcast_alt1.nit:54,20--21: Type Error: expected `B[Bool]`, got `C[Bool]`.
alt/base_upcast_alt1.nit:55,20: Type Error: expected `B[Bool]`, got `D`.
alt/base_upcast_alt1.nit:57,20--21: Type Error: expected `C[Bool]`, got `A[Int]`.
alt/base_upcast_alt1.nit:58,20--21: Type Error: expected `C[Int]`, got `A[Bool]`.
alt/base_upcast_alt1.nit:59,20--21: Type Error: expected `C[Int]`, got `B[Int]`.
alt/base_upcast_alt1.nit:60,20--21: Type Error: expected `C[Int]`, got `B[Bool]`.
alt/base_upcast_alt1.nit:62,20--21: Type Error: expected `C[Int]`, got `C[Bool]`.
alt/base_upcast_alt1.nit:63,20: Type Error: expected `C[Int]`, got `D`.
alt/base_upcast_alt1.nit:65,20--21: Type Error: expected `C[Bool]`, got `A[Int]`.
alt/base_upcast_alt1.nit:66,20--21: Type Error: expected `C[Bool]`, got `A[Bool]`.
alt/base_upcast_alt1.nit:67,20--21: Type Error: expected `C[Bool]`, got `B[Int]`.
alt/base_upcast_alt1.nit:68,20--21: Type Error: expected `C[Bool]`, got `B[Bool]`.
alt/base_upcast_alt1.nit:69,20--21: Type Error: expected `C[Bool]`, got `C[Int]`.
alt/base_upcast_alt1.nit:73,19--20: Type Error: expected `D`, got `A[Int]`.
alt/base_upcast_alt1.nit:74,19--20: Type Error: expected `D`, got `A[Bool]`.
alt/base_upcast_alt1.nit:75,19--20: Type Error: expected `D`, got `B[Int]`.
alt/base_upcast_alt1.nit:76,19--20: Type Error: expected `D`, got `B[Bool]`.
alt/base_upcast_alt1.nit:77,19--20: Type Error: expected `D`, got `C[Int]`.
alt/base_upcast_alt1.nit:78,19--20: Type Error: expected `D`, got `C[Bool]`.
