alt/base_adaptive_full_alt2.nit:55,10: Type Error: expected `B`, got `C`.
alt/base_adaptive_full_alt2.nit:71,10: Type Error: expected `B`, got `C`.
alt/base_adaptive_full_alt2.nit:84,11: Type Error: expected `B`, got `C`.
alt/base_adaptive_full_alt2.nit:91,10: Type Error: expected `A`, got `Object`.
alt/base_adaptive_full_alt2.nit:95,10: Type Error: expected `B`, got `Object`.
alt/base_adaptive_full_alt2.nit:192,9: Type Error: expected `A`, got `Object`.
alt/base_adaptive_full_alt2.nit:201,10: Type Error: expected `A`, got `Object`.
alt/base_adaptive_full_alt2.nit:226,10: Type Error: expected `A`, got `Object`.
alt/base_adaptive_full_alt2.nit:235,9: Type Error: expected `A`, got `Object`.
alt/base_adaptive_full_alt2.nit:247,10: Type Error: expected `A`, got `Object`.
alt/base_adaptive_full_alt2.nit:251,10: Type Error: expected `A`, got `Object`.
alt/base_adaptive_full_alt2.nit:256,9: Type Error: expected `A`, got `Object`.
alt/base_adaptive_full_alt2.nit:297,10: Type Error: expected `B`, got `C`.
alt/base_adaptive_full_alt2.nit:322,9: Type Error: expected `B`, got `C`.
alt/base_adaptive_full_alt2.nit:332,10: Type Error: expected `B`, got `C`.
alt/base_adaptive_full_alt2.nit:358,9: Type Error: expected `B`, got `C`.
