alt/base_init_inherit_alt1.nit:95,2--9: Error: ca is not a constructor in B.
alt/base_init_inherit_alt1.nit:96,2--10: Error: ca2 is not a constructor in B.
alt/base_init_inherit_alt1.nit:98,2--9: Error: ca is not a constructor in C.
alt/base_init_inherit_alt1.nit:99,2--10: Error: ca2 is not a constructor in C.
alt/base_init_inherit_alt1.nit:100,2--9: Error: cb is not a constructor in C.
alt/base_init_inherit_alt1.nit:104,2--9: Error: ca is not a constructor in N.
alt/base_init_inherit_alt1.nit:105,2--10: Error: ca2 is not a constructor in N.
alt/base_init_inherit_alt1.nit:107,2--9: Error: ca is not a constructor in O.
alt/base_init_inherit_alt1.nit:108,2--10: Error: ca2 is not a constructor in O.
alt/base_init_inherit_alt1.nit:109,2--9: Error: cb is not a constructor in O.
alt/base_init_inherit_alt1.nit:110,2--9: Error: cc is not a constructor in O.
