alt/base_scope_alt1.nit:28,20: Error: a variable named `a` already exists.
alt/base_scope_alt1.nit:28,35: Error: a variable named `a` already exists.
alt/base_scope_alt1.nit:30,22: Error: a variable named `a` already exists.
alt/base_scope_alt1.nit:33,12: Error: a variable named `a` already exists.
alt/base_scope_alt1.nit:34,10: Error: a variable named `a` already exists.
alt/base_scope_alt1.nit:36,11: Error: a variable named `b` already exists.
alt/base_scope_alt1.nit:36,26: Error: a variable named `c` already exists.
alt/base_scope_alt1.nit:37,10: Error: a variable named `b` already exists.
alt/base_scope_alt1.nit:39,10: Error: a variable named `c` already exists.
alt/base_scope_alt1.nit:43,9: Error: a variable named `a` already exists.
alt/base_scope_alt1.nit:45,10: Error: a variable named `b` already exists.
alt/base_scope_alt1.nit:45,26: Error: a variable named `c` already exists.
alt/base_scope_alt1.nit:46,10: Error: a variable named `b` already exists.
alt/base_scope_alt1.nit:48,10: Error: a variable named `c` already exists.
alt/base_scope_alt1.nit:52,28: Error: a variable named `a` already exists.
alt/base_scope_alt1.nit:53,10: Error: a variable named `a` already exists.
alt/base_scope_alt1.nit:56,9: Error: a variable named `a` already exists.
alt/base_scope_alt1.nit:59,8: Error: a variable named `a` already exists.
alt/base_scope_alt1.nit:63,7: Error: a variable named `a` already exists.
alt/base_scope_alt1.nit:67,6: Error: a variable named `a` already exists.
alt/base_scope_alt1.nit:70,6: Error: a variable named `a` already exists.
alt/base_scope_alt1.nit:73,6: Error: a variable named `a` already exists.
alt/base_scope_alt1.nit:76,5: Error: a variable named `a` already exists.
