Thread 0 is done
Thread 1 is done
Thread 2 is done
Thread 3 is done
Thread 4 is done
Thread 5 is done
Thread 6 is done
Thread 7 is done
Thread 8 is done
Thread 9 is done
Thread 10 is done
Thread 11 is done
Thread 12 is done
Thread 13 is done
Thread 14 is done
Thread 15 is done
Thread 16 is done
Thread 17 is done
Thread 18 is done
Thread 19 is done
20000 strings inserted
