out/hello_ios.bin
out/hello_ios.bin/Info.plist
out/hello_ios.bin/LaunchScreen.storyboardc
out/hello_ios.bin/LaunchScreen.storyboardc/01J-lp-oVM-view-Ze5-6b-2t3.nib
out/hello_ios.bin/LaunchScreen.storyboardc/Info.plist
out/hello_ios.bin/LaunchScreen.storyboardc/UIViewController-01J-lp-oVM.nib
out/hello_ios.bin/PkgInfo
out/hello_ios.bin/_CodeSignature
out/hello_ios.bin/_CodeSignature/CodeResources
out/hello_ios.bin/assets
out/hello_ios.bin/hello_ios
