# Graph
Edge
=type=4:ROOT
=properties=JsonObject(0):
{}
----
=from=Node
=labels=Array(3):
3:foo
7:MEntity
8:MProject
=properties=JsonObject(1):
{"name":"foo"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(2):
{"full_name":"","name":"foo"}

Edge
=type=7:PROJECT
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(2):
{"full_name":"","name":"foo"}
----
=to=Node
=labels=Array(3):
3:foo
7:MEntity
8:MProject
=properties=JsonObject(1):
{"name":"foo"}

Edge
=type=8:DECLARES
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(2):
{"full_name":"","name":"foo"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
7:MModule
=properties=JsonObject(3):
{"location":"\/dev\/null:1,1--1,1","full_name":"a::b::Bar","name":"Bar"}

Edge
=type=10:INTRODUCES
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
7:MModule
=properties=JsonObject(3):
{"location":"\/dev\/null:1,1--1,1","full_name":"a::b::Bar","name":"Bar"}
----
=to=Entity#12:classa_b_bar
=labels=Array(3):
3:foo
7:MEntity
6:MClass
=properties=JsonObject(4):
{"kind":"class","visibility":"public","full_name":"a::b::Bar","name":"Bar"}

Edge
=type=7:DEFINES
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
7:MModule
=properties=JsonObject(3):
{"location":"\/dev\/null:1,1--1,1","full_name":"a::b::Bar","name":"Bar"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
9:MClassDef
=properties=JsonObject(4):
{"location":"\/dev\/null:1,1--1,1","is_intro":true,"name":"Bar","full_name":"a::b::Bar"}

Edge
=type=8:DECLARES
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(2):
{"full_name":"","name":"foo"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
7:MModule
=properties=JsonObject(3):
{"location":"\/dev\/null:1,1--1,1","full_name":"Bar","name":"Bar"}

Edge
=type=10:INTRODUCES
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
7:MModule
=properties=JsonObject(3):
{"location":"\/dev\/null:1,1--1,1","full_name":"Bar","name":"Bar"}
----
=to=Entity#8:classbaz
=labels=Array(3):
3:foo
7:MEntity
6:MClass
=properties=JsonObject(4):
{"kind":"class","visibility":"public","full_name":"Baz","name":"Baz"}

Edge
=type=7:DEFINES
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
7:MModule
=properties=JsonObject(3):
{"location":"\/dev\/null:1,1--1,1","full_name":"Bar","name":"Bar"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
9:MClassDef
=properties=JsonObject(4):
{"location":"\/dev\/null:1,1--1,1","is_intro":true,"name":"Baz","full_name":"Baz"}

Edge
=type=8:DECLARES
=properties=JsonObject(0):
{}
----
=from=Entity#10:namespacec
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(2):
{"full_name":"c","name":"c"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
7:MModule
=properties=JsonObject(3):
{"location":"\/dev\/null:1,1--1,1","full_name":"c::Bar","name":"Bar"}

Edge
=type=8:DECLARES
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(2):
{"full_name":"","name":"foo"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
7:MModule
=properties=JsonObject(3):
{"location":"\/dev\/null:1,1--1,1","full_name":"d::Bar","name":"Bar"}

Edge
=type=9:CLASSTYPE
=properties=JsonObject(0):
{}
----
=from=Entity#12:classa_b_bar
=labels=Array(3):
3:foo
7:MEntity
6:MClass
=properties=JsonObject(4):
{"kind":"class","visibility":"public","full_name":"a::b::Bar","name":"Bar"}
----
=to=Entity#0:
=labels=Array(4):
3:foo
7:MEntity
5:MType
10:MClassType
=properties=JsonObject(2):
{"name":"Bar","full_name":"a::b::Bar"}

Edge
=type=5:CLASS
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(4):
3:foo
7:MEntity
5:MType
10:MClassType
=properties=JsonObject(2):
{"name":"Bar","full_name":"a::b::Bar"}
----
=to=Entity#12:classa_b_bar
=labels=Array(3):
3:foo
7:MEntity
6:MClass
=properties=JsonObject(4):
{"kind":"class","visibility":"public","full_name":"a::b::Bar","name":"Bar"}

Edge
=type=9:BOUNDTYPE
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
9:MClassDef
=properties=JsonObject(4):
{"location":"\/dev\/null:1,1--1,1","is_intro":true,"name":"Bar","full_name":"a::b::Bar"}
----
=to=Entity#0:
=labels=Array(4):
3:foo
7:MEntity
5:MType
10:MClassType
=properties=JsonObject(2):
{"name":"Bar","full_name":"a::b::Bar"}

Edge
=type=6:MCLASS
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
9:MClassDef
=properties=JsonObject(4):
{"location":"\/dev\/null:1,1--1,1","is_intro":true,"name":"Bar","full_name":"a::b::Bar"}
----
=to=Entity#12:classa_b_bar
=labels=Array(3):
3:foo
7:MEntity
6:MClass
=properties=JsonObject(4):
{"kind":"class","visibility":"public","full_name":"a::b::Bar","name":"Bar"}

Edge
=type=9:CLASSTYPE
=properties=JsonObject(0):
{}
----
=from=Entity#8:classbaz
=labels=Array(3):
3:foo
7:MEntity
6:MClass
=properties=JsonObject(4):
{"kind":"class","visibility":"public","full_name":"Baz","name":"Baz"}
----
=to=Entity#0:
=labels=Array(4):
3:foo
7:MEntity
5:MType
10:MClassType
=properties=JsonObject(2):
{"name":"Baz","full_name":"Baz"}

Edge
=type=5:CLASS
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(4):
3:foo
7:MEntity
5:MType
10:MClassType
=properties=JsonObject(2):
{"name":"Baz","full_name":"Baz"}
----
=to=Entity#8:classbaz
=labels=Array(3):
3:foo
7:MEntity
6:MClass
=properties=JsonObject(4):
{"kind":"class","visibility":"public","full_name":"Baz","name":"Baz"}

Edge
=type=9:BOUNDTYPE
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
9:MClassDef
=properties=JsonObject(4):
{"location":"\/dev\/null:1,1--1,1","is_intro":true,"name":"Baz","full_name":"Baz"}
----
=to=Entity#0:
=labels=Array(4):
3:foo
7:MEntity
5:MType
10:MClassType
=properties=JsonObject(2):
{"name":"Baz","full_name":"Baz"}

Edge
=type=6:MCLASS
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
9:MClassDef
=properties=JsonObject(4):
{"location":"\/dev\/null:1,1--1,1","is_intro":true,"name":"Baz","full_name":"Baz"}
----
=to=Entity#8:classbaz
=labels=Array(3):
3:foo
7:MEntity
6:MClass
=properties=JsonObject(4):
{"kind":"class","visibility":"public","full_name":"Baz","name":"Baz"}

Edge
=type=7:PROJECT
=properties=JsonObject(0):
{}
----
=from=Entity#10:namespacec
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(2):
{"full_name":"c","name":"c"}
----
=to=Node
=labels=Array(3):
3:foo
7:MEntity
8:MProject
=properties=JsonObject(1):
{"name":"foo"}

Edge
=type=6:PARENT
=properties=JsonObject(0):
{}
----
=from=Entity#10:namespacec
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(2):
{"full_name":"c","name":"c"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(2):
{"full_name":"","name":"foo"}

Edge
=type=5:NESTS
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(2):
{"full_name":"","name":"foo"}
----
=to=Entity#10:namespacec
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(2):
{"full_name":"c","name":"c"}


