---===WITHOUT GLOBALS===---
# Graph
Edge
=type=4:ROOT
=properties=JsonObject(0):
{}
----
=from=Node
=labels=Array(3):
3:foo
7:MEntity
8:MProject
=properties=JsonObject(1):
{"name":"foo"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"foo"}

Edge
=type=7:PROJECT
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"foo"}
----
=to=Node
=labels=Array(3):
3:foo
7:MEntity
8:MProject
=properties=JsonObject(1):
{"name":"foo"}

Edge
=type=6:PARENT
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"a"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"foo"}

Edge
=type=5:NESTS
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"foo"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"a"}

Edge
=type=6:PARENT
=properties=JsonObject(0):
{}
----
=from=Entity#10:namespacec
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"c"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"foo"}

Edge
=type=5:NESTS
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"foo"}
----
=to=Entity#10:namespacec
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"c"}

Edge
=type=6:PARENT
=properties=JsonObject(0):
{}
----
=from=Entity#10:namespaced
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"d"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"foo"}

Edge
=type=5:NESTS
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"foo"}
----
=to=Entity#10:namespaced
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"d"}

Edge
=type=8:DECLARES
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"b"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
7:MModule
=properties=JsonObject(2):
{"location":"a\/b\/Bar.java:1,1--1,1","name":"Bar"}

Edge
=type=10:INTRODUCES
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
7:MModule
=properties=JsonObject(2):
{"location":"a\/b\/Bar.java:1,1--1,1","name":"Bar"}
----
=to=Entity#12:classa_b_bar
=labels=Array(3):
3:foo
7:MEntity
6:MClass
=properties=JsonObject(4):
{"kind":"class","visibility":"public","name":"Bar","location":"a\/b\/Bar.class:5,1--100,10"}

Edge
=type=7:DEFINES
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
7:MModule
=properties=JsonObject(2):
{"location":"a\/b\/Bar.java:1,1--1,1","name":"Bar"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
9:MClassDef
=properties=JsonObject(3):
{"location":"a\/b\/Bar.class:5,1--100,10","is_intro":true,"name":"Bar"}

Edge
=type=8:DECLARES
=properties=JsonObject(0):
{}
----
=from=Entity#10:namespacec
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"c"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
7:MModule
=properties=JsonObject(2):
{"location":"Bar.java:1,1--1,1","name":"Bar"}

Edge
=type=8:DECLARES
=properties=JsonObject(0):
{}
----
=from=Entity#10:namespaced
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"d"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
7:MModule
=properties=JsonObject(2):
{"location":"Bar.java:1,1--1,1","name":"Bar"}

Edge
=type=9:CLASSTYPE
=properties=JsonObject(0):
{}
----
=from=Entity#12:classa_b_bar
=labels=Array(3):
3:foo
7:MEntity
6:MClass
=properties=JsonObject(4):
{"kind":"class","visibility":"public","name":"Bar","location":"a\/b\/Bar.class:5,1--100,10"}
----
=to=Entity#0:
=labels=Array(4):
3:foo
7:MEntity
5:MType
10:MClassType
=properties=JsonObject(1):
{"name":"Bar"}

Edge
=type=5:CLASS
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(4):
3:foo
7:MEntity
5:MType
10:MClassType
=properties=JsonObject(1):
{"name":"Bar"}
----
=to=Entity#12:classa_b_bar
=labels=Array(3):
3:foo
7:MEntity
6:MClass
=properties=JsonObject(4):
{"kind":"class","visibility":"public","name":"Bar","location":"a\/b\/Bar.class:5,1--100,10"}

Edge
=type=9:BOUNDTYPE
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
9:MClassDef
=properties=JsonObject(3):
{"location":"a\/b\/Bar.class:5,1--100,10","is_intro":true,"name":"Bar"}
----
=to=Entity#0:
=labels=Array(4):
3:foo
7:MEntity
5:MType
10:MClassType
=properties=JsonObject(1):
{"name":"Bar"}

Edge
=type=6:MCLASS
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
9:MClassDef
=properties=JsonObject(3):
{"location":"a\/b\/Bar.class:5,1--100,10","is_intro":true,"name":"Bar"}
----
=to=Entity#12:classa_b_bar
=labels=Array(3):
3:foo
7:MEntity
6:MClass
=properties=JsonObject(4):
{"kind":"class","visibility":"public","name":"Bar","location":"a\/b\/Bar.class:5,1--100,10"}

Edge
=type=9:CLASSTYPE
=properties=JsonObject(0):
{}
----
=from=Entity#8:classbaz
=labels=Array(3):
3:foo
7:MEntity
6:MClass
=properties=JsonObject(4):
{"kind":"class","visibility":"public","name":"Baz","location":"Baz.jar:1,1--1,1"}
----
=to=Entity#0:
=labels=Array(4):
3:foo
7:MEntity
5:MType
10:MClassType
=properties=JsonObject(1):
{"name":"Baz"}

Edge
=type=5:CLASS
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(4):
3:foo
7:MEntity
5:MType
10:MClassType
=properties=JsonObject(1):
{"name":"Baz"}
----
=to=Entity#8:classbaz
=labels=Array(3):
3:foo
7:MEntity
6:MClass
=properties=JsonObject(4):
{"kind":"class","visibility":"public","name":"Baz","location":"Baz.jar:1,1--1,1"}

Edge
=type=9:BOUNDTYPE
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
9:MClassDef
=properties=JsonObject(3):
{"location":"Baz.jar:1,1--1,1","is_intro":true,"name":"Baz"}
----
=to=Entity#0:
=labels=Array(4):
3:foo
7:MEntity
5:MType
10:MClassType
=properties=JsonObject(1):
{"name":"Baz"}

Edge
=type=6:MCLASS
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
9:MClassDef
=properties=JsonObject(3):
{"location":"Baz.jar:1,1--1,1","is_intro":true,"name":"Baz"}
----
=to=Entity#8:classbaz
=labels=Array(3):
3:foo
7:MEntity
6:MClass
=properties=JsonObject(4):
{"kind":"class","visibility":"public","name":"Baz","location":"Baz.jar:1,1--1,1"}

Edge
=type=7:PROJECT
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"a"}
----
=to=Node
=labels=Array(3):
3:foo
7:MEntity
8:MProject
=properties=JsonObject(1):
{"name":"foo"}

Edge
=type=6:PARENT
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"b"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"a"}

Edge
=type=5:NESTS
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"a"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"b"}

Edge
=type=7:PROJECT
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"b"}
----
=to=Node
=labels=Array(3):
3:foo
7:MEntity
8:MProject
=properties=JsonObject(1):
{"name":"foo"}

Edge
=type=7:PROJECT
=properties=JsonObject(0):
{}
----
=from=Entity#10:namespacec
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"c"}
----
=to=Node
=labels=Array(3):
3:foo
7:MEntity
8:MProject
=properties=JsonObject(1):
{"name":"foo"}

Edge
=type=7:PROJECT
=properties=JsonObject(0):
{}
----
=from=Entity#10:namespaced
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"d"}
----
=to=Node
=labels=Array(3):
3:foo
7:MEntity
8:MProject
=properties=JsonObject(1):
{"name":"foo"}


---===WITH GLOBALS===---
# Graph
Edge
=type=4:ROOT
=properties=JsonObject(0):
{}
----
=from=Node
=labels=Array(3):
3:foo
7:MEntity
8:MProject
=properties=JsonObject(1):
{"name":"foo"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"foo"}

Edge
=type=7:PROJECT
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"foo"}
----
=to=Node
=labels=Array(3):
3:foo
7:MEntity
8:MProject
=properties=JsonObject(1):
{"name":"foo"}

Edge
=type=6:PARENT
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"a"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"foo"}

Edge
=type=5:NESTS
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"foo"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"a"}

Edge
=type=6:PARENT
=properties=JsonObject(0):
{}
----
=from=Entity#10:namespacec
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"c"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"foo"}

Edge
=type=5:NESTS
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"foo"}
----
=to=Entity#10:namespacec
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"c"}

Edge
=type=6:PARENT
=properties=JsonObject(0):
{}
----
=from=Entity#10:namespaced
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"d"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"foo"}

Edge
=type=5:NESTS
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"foo"}
----
=to=Entity#10:namespaced
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"d"}

Edge
=type=8:DECLARES
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"b"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
7:MModule
=properties=JsonObject(2):
{"location":"a\/b\/Bar.java:1,1--1,1","name":"Bar"}

Edge
=type=10:INTRODUCES
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
7:MModule
=properties=JsonObject(2):
{"location":"a\/b\/Bar.java:1,1--1,1","name":"Bar"}
----
=to=Entity#12:classa_b_bar
=labels=Array(3):
3:foo
7:MEntity
6:MClass
=properties=JsonObject(4):
{"kind":"class","visibility":"public","name":"Bar","location":"a\/b\/Bar.class:5,1--100,10"}

Edge
=type=7:DEFINES
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
7:MModule
=properties=JsonObject(2):
{"location":"a\/b\/Bar.java:1,1--1,1","name":"Bar"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
9:MClassDef
=properties=JsonObject(3):
{"location":"a\/b\/Bar.class:5,1--100,10","is_intro":true,"name":"Bar"}

Edge
=type=8:DECLARES
=properties=JsonObject(0):
{}
----
=from=Entity#10:namespacec
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"c"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
7:MModule
=properties=JsonObject(2):
{"location":"Bar.java:1,1--1,1","name":"Bar"}

Edge
=type=8:DECLARES
=properties=JsonObject(0):
{}
----
=from=Entity#10:namespaced
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"d"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
7:MModule
=properties=JsonObject(2):
{"location":"Bar.java:1,1--1,1","name":"Bar"}

Edge
=type=9:CLASSTYPE
=properties=JsonObject(0):
{}
----
=from=Entity#12:classa_b_bar
=labels=Array(3):
3:foo
7:MEntity
6:MClass
=properties=JsonObject(4):
{"kind":"class","visibility":"public","name":"Bar","location":"a\/b\/Bar.class:5,1--100,10"}
----
=to=Entity#0:
=labels=Array(4):
3:foo
7:MEntity
5:MType
10:MClassType
=properties=JsonObject(1):
{"name":"Bar"}

Edge
=type=5:CLASS
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(4):
3:foo
7:MEntity
5:MType
10:MClassType
=properties=JsonObject(1):
{"name":"Bar"}
----
=to=Entity#12:classa_b_bar
=labels=Array(3):
3:foo
7:MEntity
6:MClass
=properties=JsonObject(4):
{"kind":"class","visibility":"public","name":"Bar","location":"a\/b\/Bar.class:5,1--100,10"}

Edge
=type=9:BOUNDTYPE
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
9:MClassDef
=properties=JsonObject(3):
{"location":"a\/b\/Bar.class:5,1--100,10","is_intro":true,"name":"Bar"}
----
=to=Entity#0:
=labels=Array(4):
3:foo
7:MEntity
5:MType
10:MClassType
=properties=JsonObject(1):
{"name":"Bar"}

Edge
=type=6:MCLASS
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
9:MClassDef
=properties=JsonObject(3):
{"location":"a\/b\/Bar.class:5,1--100,10","is_intro":true,"name":"Bar"}
----
=to=Entity#12:classa_b_bar
=labels=Array(3):
3:foo
7:MEntity
6:MClass
=properties=JsonObject(4):
{"kind":"class","visibility":"public","name":"Bar","location":"a\/b\/Bar.class:5,1--100,10"}

Edge
=type=9:CLASSTYPE
=properties=JsonObject(0):
{}
----
=from=Entity#8:classbaz
=labels=Array(3):
3:foo
7:MEntity
6:MClass
=properties=JsonObject(4):
{"kind":"class","visibility":"public","name":"Baz","location":"Baz.jar:1,1--1,1"}
----
=to=Entity#0:
=labels=Array(4):
3:foo
7:MEntity
5:MType
10:MClassType
=properties=JsonObject(1):
{"name":"Baz"}

Edge
=type=5:CLASS
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(4):
3:foo
7:MEntity
5:MType
10:MClassType
=properties=JsonObject(1):
{"name":"Baz"}
----
=to=Entity#8:classbaz
=labels=Array(3):
3:foo
7:MEntity
6:MClass
=properties=JsonObject(4):
{"kind":"class","visibility":"public","name":"Baz","location":"Baz.jar:1,1--1,1"}

Edge
=type=9:BOUNDTYPE
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
9:MClassDef
=properties=JsonObject(3):
{"location":"Baz.jar:1,1--1,1","is_intro":true,"name":"Baz"}
----
=to=Entity#0:
=labels=Array(4):
3:foo
7:MEntity
5:MType
10:MClassType
=properties=JsonObject(1):
{"name":"Baz"}

Edge
=type=6:MCLASS
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
9:MClassDef
=properties=JsonObject(3):
{"location":"Baz.jar:1,1--1,1","is_intro":true,"name":"Baz"}
----
=to=Entity#8:classbaz
=labels=Array(3):
3:foo
7:MEntity
6:MClass
=properties=JsonObject(4):
{"kind":"class","visibility":"public","name":"Baz","location":"Baz.jar:1,1--1,1"}

Edge
=type=7:PROJECT
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"a"}
----
=to=Node
=labels=Array(3):
3:foo
7:MEntity
8:MProject
=properties=JsonObject(1):
{"name":"foo"}

Edge
=type=6:PARENT
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"b"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"a"}

Edge
=type=5:NESTS
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"a"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"b"}

Edge
=type=7:PROJECT
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"b"}
----
=to=Node
=labels=Array(3):
3:foo
7:MEntity
8:MProject
=properties=JsonObject(1):
{"name":"foo"}

Edge
=type=7:PROJECT
=properties=JsonObject(0):
{}
----
=from=Entity#10:namespacec
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"c"}
----
=to=Node
=labels=Array(3):
3:foo
7:MEntity
8:MProject
=properties=JsonObject(1):
{"name":"foo"}

Edge
=type=7:PROJECT
=properties=JsonObject(0):
{}
----
=from=Entity#10:namespaced
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"d"}
----
=to=Node
=labels=Array(3):
3:foo
7:MEntity
8:MProject
=properties=JsonObject(1):
{"name":"foo"}

Edge
=type=8:DECLARES
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
6:MGroup
=properties=JsonObject(1):
{"name":"foo"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
7:MModule
=properties=JsonObject(2):
{"location":"a\/b\/Bar.java:1,1--1,1","name":"Bar"}

Edge
=type=10:INTRODUCES
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
7:MModule
=properties=JsonObject(2):
{"location":"a\/b\/Bar.java:1,1--1,1","name":"Bar"}
----
=to=Entity#8:classbaz
=labels=Array(3):
3:foo
7:MEntity
6:MClass
=properties=JsonObject(4):
{"kind":"class","visibility":"public","name":"Baz","location":"Baz.jar:1,1--1,1"}

Edge
=type=7:DEFINES
=properties=JsonObject(0):
{}
----
=from=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
7:MModule
=properties=JsonObject(2):
{"location":"a\/b\/Bar.java:1,1--1,1","name":"Bar"}
----
=to=Entity#0:
=labels=Array(3):
3:foo
7:MEntity
9:MClassDef
=properties=JsonObject(3):
{"location":"Baz.jar:1,1--1,1","is_intro":true,"name":"Baz"}


