[1mNAME[m
  %PROGRAM_NAME% — Doxygen XML to Neo4j.

[1mSYNOPSIS[m
  %PROGRAM_NAME% [--dest <url>] [--src-lang <lang>]
    [--] <project_name> <doxml_dir>
  %PROGRAM_NAME% [-h|--help]

[1mDESCRIPTION[m
  Convert a Doxygen XML output into a model in Neo4j that is readable by the
  `nx` tool.

[1mARGUMENTS[m
  <project_name>  The internal name of the project. Must the same name as the
                  one specified to the `nx` tool. Must not begin by an upper
                  case letter.

  <doxml_dir>     The directory where the XML documents generated by Doxygen are
                  located.

[1mOPTIONS[m

  --dest       The URL of the destination graph. `http://localhost:7474` by
               default.

  -h, --help   Show the help (this page).

  --src-lang   The programming language to assume when processing chunks in the
               declarations left as-is by Doxygen. Use `any` (the default) to
               disable any language-specific processing. <any, java, python>

