  -W, --warn              Show warnings
  -q, --quiet             Do not show warnings
  --stop-on-first-error   Stop on first error
  --no-color              Do not use color to display errors and warnings
  --log                   Generate various log files
  --log-dir               Directory where to generate log files
  -h, -?, --help          Show Help (This screen)
  --version               Show version and exit
  -v, --verbose           Verbose
  -I, --path              Set include path for loaders (may be used more than once)
  --only-parse            Only proceed to parse step of loaders
  --only-metamodel        Stop after meta-model processing
  --discover-call-trace   Trace calls of the first invocation of a method
  -d                      Launches the target program with the debugger attached to it
  -c                      Launches the target program with the interpreter, such as when the program fails, the debugging prompt is summoned
  --port                  Sets the debug port (Defaults to 22125) - Must be contained between 0 and 65535
  -o                      compatibility (does noting)
