OverviewPage Overview
	# home.article
		## packages.section
			### test_prog.definition

ReadmePage test_prog
	# mdarticle-0

ReadmePage game
	# mdarticle-0

ReadmePage platform
	# mdarticle-0

ReadmePage rpg
	# mdarticle-0

SearchPage Index
	# index.article

MGroupPage test_prog
	# test_prog.section
		## test_prog.intro
		## test_prog.concerns
		## test_prog.concern
		## test_prog.concern
		## test_prog-.concern
			### test_prog-.definition
				#### test_prog-.intros_redefs
					##### list.group
						###### test_prog-.intros
						###### test_prog-.redefs

MModulePage test_prog
	# test_prog.section
		## test_prog-.intro
		## test_prog-.importation
			### test_prog-.graph
			### list.group
				#### test_prog-.imports
				#### test_prog-.clients
		## test_prog-.concerns
		## test_prog.concern
		## test_prog.concern
		## test_prog-.concern
			### test_prog-__Starter.definition-list
				#### test_prog-__Starter.definition
					##### test_prog-__Starter.intros_redefs
						###### list.group
							####### test_prog-__Starter.intros
							####### test_prog-__Starter.redefs
			### test_prog-__Sys.definition-list
				#### test_prog-__Sys.definition
					##### test_prog-__Sys.intros_redefs
						###### list.group
							####### test_prog-__Sys.intros
							####### test_prog-__Sys.redefs

MClassPage Starter
	# Starter.section
		## test_prog-__Starter.intro
		## test_prog-__Starter.inheritance
			### test_prog-__Starter.graph
			### list.group
				#### test_prog-__Starter.parents
				#### test_prog-__Starter.ancestors
				#### test_prog-__Starter.children
				#### test_prog-__Starter.descendants

MClassPage Sys
	# Sys.section
		## test_prog-__Sys.intro
		## test_prog-__Sys.inheritance
			### test_prog-__Sys.graph
			### list.group
				#### test_prog-__Sys.parents
				#### test_prog-__Sys.ancestors
				#### test_prog-__Sys.children
				#### test_prog-__Sys.descendants

MGroupPage game
	# game.section
		## test_prog__game.intro
		## test_prog__game.concerns
		## test_prog.concern
		## test_prog.concern
		## test_prog__game.concern
		## test_prog__game-.concern
			### test_prog__game-.definition
				#### test_prog__game-.intros_redefs
					##### list.group
						###### test_prog__game-.intros
						###### test_prog__game-.redefs

MModulePage game
	# game.section
		## test_prog__game-.intro
		## test_prog__game-.importation
			### test_prog__game-.graph
			### list.group
				#### test_prog__game-.imports
				#### test_prog__game-.clients
		## test_prog__game-.concerns
		## test_prog.concern
		## test_prog.concern
		## test_prog__game.concern
		## test_prog__game-.concern
			### test_prog__game-__Game.definition-list
				#### test_prog__game-__Game.definition
					##### test_prog__game-__Game.intros_redefs
						###### list.group
							####### test_prog__game-__Game.intros
							####### test_prog__game-__Game.redefs

MClassPage Game
	# Game.section
		## test_prog__game-__Game.intro
		## test_prog__game-__Game.inheritance
			### test_prog__game-__Game.graph
			### list.group
				#### test_prog__game-__Game.parents
				#### test_prog__game-__Game.ancestors
				#### test_prog__game-__Game.children
				#### test_prog__game-__Game.descendants

MGroupPage platform
	# platform.section
		## test_prog__platform.intro
		## test_prog__platform.concerns
		## test_prog.concern
		## test_prog.concern
		## test_prog__platform.concern
		## test_prog__platform-.concern
			### test_prog__platform-.definition
				#### test_prog__platform-.intros_redefs
					##### list.group
						###### test_prog__platform-.intros
						###### test_prog__platform-.redefs

MModulePage platform
	# platform.section
		## test_prog__platform-.intro
		## test_prog__platform-.importation
			### test_prog__platform-.graph
			### list.group
				#### test_prog__platform-.imports
				#### test_prog__platform-.clients
		## test_prog__platform-.concerns
		## test_prog.concern
		## test_prog.concern
		## test_prog__platform.concern
		## test_prog__platform-.concern
			### test_prog__platform-__Bool.definition-list
				#### test_prog__platform-__Bool.definition
					##### test_prog__platform-__Bool.intros_redefs
						###### list.group
							####### test_prog__platform-__Bool.intros
							####### test_prog__platform-__Bool.redefs
			### test_prog__platform-__Float.definition-list
				#### test_prog__platform-__Float.definition
					##### test_prog__platform-__Float.intros_redefs
						###### list.group
							####### test_prog__platform-__Float.intros
							####### test_prog__platform-__Float.redefs
			### test_prog__platform-__Int.definition-list
				#### test_prog__platform-__Int.definition
					##### test_prog__platform-__Int.intros_redefs
						###### list.group
							####### test_prog__platform-__Int.intros
							####### test_prog__platform-__Int.redefs
			### test_prog__platform-__List.definition-list
				#### test_prog__platform-__List.definition
					##### test_prog__platform-__List.intros_redefs
						###### list.group
							####### test_prog__platform-__List.intros
							####### test_prog__platform-__List.redefs
			### test_prog__platform-__Object.definition-list
				#### test_prog__platform-__Object.definition
					##### test_prog__platform-__Object.intros_redefs
						###### list.group
							####### test_prog__platform-__Object.intros
							####### test_prog__platform-__Object.redefs
			### test_prog__platform-__String.definition-list
				#### test_prog__platform-__String.definition
					##### test_prog__platform-__String.intros_redefs
						###### list.group
							####### test_prog__platform-__String.intros
							####### test_prog__platform-__String.redefs

MClassPage Bool
	# Bool.section
		## test_prog__platform-__Bool.intro
		## test_prog__platform-__Bool.inheritance
			### test_prog__platform-__Bool.graph
			### list.group
				#### test_prog__platform-__Bool.parents
				#### test_prog__platform-__Bool.ancestors
				#### test_prog__platform-__Bool.children
				#### test_prog__platform-__Bool.descendants

MClassPage Float
	# Float.section
		## test_prog__platform-__Float.intro
		## test_prog__platform-__Float.inheritance
			### test_prog__platform-__Float.graph
			### list.group
				#### test_prog__platform-__Float.parents
				#### test_prog__platform-__Float.ancestors
				#### test_prog__platform-__Float.children
				#### test_prog__platform-__Float.descendants

MClassPage Int
	# Int.section
		## test_prog__platform-__Int.intro
		## test_prog__platform-__Int.inheritance
			### test_prog__platform-__Int.graph
			### list.group
				#### test_prog__platform-__Int.parents
				#### test_prog__platform-__Int.ancestors
				#### test_prog__platform-__Int.children
				#### test_prog__platform-__Int.descendants

MClassPage List
	# List.section
		## test_prog__platform-__List.intro
		## test_prog__platform-__List.inheritance
			### test_prog__platform-__List.graph
			### list.group
				#### test_prog__platform-__List.parents
				#### test_prog__platform-__List.ancestors
				#### test_prog__platform-__List.children
				#### test_prog__platform-__List.descendants

MClassPage Object
	# Object.section
		## test_prog__platform-__Object.intro
		## test_prog__platform-__Object.inheritance
			### test_prog__platform-__Object.graph
			### list.group
				#### test_prog__platform-__Object.parents
				#### test_prog__platform-__Object.ancestors
				#### test_prog__platform-__Object.children
				#### test_prog__platform-__Object.descendants

MClassPage String
	# String.section
		## test_prog__platform-__String.intro
		## test_prog__platform-__String.inheritance
			### test_prog__platform-__String.graph
			### list.group
				#### test_prog__platform-__String.parents
				#### test_prog__platform-__String.ancestors
				#### test_prog__platform-__String.children
				#### test_prog__platform-__String.descendants

MGroupPage rpg
	# rpg.section
		## test_prog__rpg.intro
		## test_prog__rpg.concerns
		## test_prog.concern
		## test_prog.concern
		## test_prog__rpg.concern
		## test_prog__rpg__careers.concern
			### test_prog__rpg__careers.definition
				#### test_prog__rpg__careers.intros_redefs
					##### list.group
						###### test_prog__rpg__careers.intros
						###### test_prog__rpg__careers.redefs
		## test_prog__rpg__races.concern
			### test_prog__rpg__races.definition
				#### test_prog__rpg__races.intros_redefs
					##### list.group
						###### test_prog__rpg__races.intros
						###### test_prog__rpg__races.redefs
		## test_prog__rpg__character.concern
			### test_prog__rpg__character.definition
				#### test_prog__rpg__character.intros_redefs
					##### list.group
						###### test_prog__rpg__character.intros
						###### test_prog__rpg__character.redefs
		## test_prog__rpg__combat.concern
			### test_prog__rpg__combat.definition
				#### test_prog__rpg__combat.intros_redefs
					##### list.group
						###### test_prog__rpg__combat.intros
						###### test_prog__rpg__combat.redefs
		## test_prog__rpg__rpg.concern
			### test_prog__rpg__rpg.definition
				#### test_prog__rpg__rpg.intros_redefs
					##### list.group
						###### test_prog__rpg__rpg.intros
						###### test_prog__rpg__rpg.redefs

MModulePage careers
	# careers.section
		## test_prog__rpg__careers.intro
		## test_prog__rpg__careers.importation
			### test_prog__rpg__careers.graph
			### list.group
				#### test_prog__rpg__careers.imports
				#### test_prog__rpg__careers.clients
		## test_prog__rpg__careers.concerns
		## test_prog.concern
		## test_prog.concern
		## test_prog__rpg.concern
		## test_prog__rpg__careers.concern
			### test_prog__rpg__careers__Alcoholic.definition-list
				#### test_prog__rpg__careers__Alcoholic.definition
					##### test_prog__rpg__careers__Alcoholic.intros_redefs
						###### list.group
							####### test_prog__rpg__careers__Alcoholic.intros
							####### test_prog__rpg__careers__Alcoholic.redefs
			### test_prog__rpg__careers__Career.definition-list
				#### test_prog__rpg__careers__Career.definition
					##### test_prog__rpg__careers__Career.intros_redefs
						###### list.group
							####### test_prog__rpg__careers__Career.intros
							####### test_prog__rpg__careers__Career.redefs
			### test_prog__rpg__careers__Magician.definition-list
				#### test_prog__rpg__careers__Magician.definition
					##### test_prog__rpg__careers__Magician.intros_redefs
						###### list.group
							####### test_prog__rpg__careers__Magician.intros
							####### test_prog__rpg__careers__Magician.redefs
			### test_prog__rpg__careers__Warrior.definition-list
				#### test_prog__rpg__careers__Warrior.definition
					##### test_prog__rpg__careers__Warrior.intros_redefs
						###### list.group
							####### test_prog__rpg__careers__Warrior.intros
							####### test_prog__rpg__careers__Warrior.redefs

MClassPage Alcoholic
	# Alcoholic.section
		## test_prog__rpg__careers__Alcoholic.intro
		## test_prog__rpg__careers__Alcoholic.inheritance
			### test_prog__rpg__careers__Alcoholic.graph
			### list.group
				#### test_prog__rpg__careers__Alcoholic.parents
				#### test_prog__rpg__careers__Alcoholic.ancestors
				#### test_prog__rpg__careers__Alcoholic.children
				#### test_prog__rpg__careers__Alcoholic.descendants

MClassPage Career
	# Career.section
		## test_prog__rpg__careers__Career.intro
		## test_prog__rpg__careers__Career.inheritance
			### test_prog__rpg__careers__Career.graph
			### list.group
				#### test_prog__rpg__careers__Career.parents
				#### test_prog__rpg__careers__Career.ancestors
				#### test_prog__rpg__careers__Career.children
				#### test_prog__rpg__careers__Career.descendants

MClassPage Magician
	# Magician.section
		## test_prog__rpg__careers__Magician.intro
		## test_prog__rpg__careers__Magician.inheritance
			### test_prog__rpg__careers__Magician.graph
			### list.group
				#### test_prog__rpg__careers__Magician.parents
				#### test_prog__rpg__careers__Magician.ancestors
				#### test_prog__rpg__careers__Magician.children
				#### test_prog__rpg__careers__Magician.descendants

MClassPage Warrior
	# Warrior.section
		## test_prog__rpg__careers__Warrior.intro
		## test_prog__rpg__careers__Warrior.inheritance
			### test_prog__rpg__careers__Warrior.graph
			### list.group
				#### test_prog__rpg__careers__Warrior.parents
				#### test_prog__rpg__careers__Warrior.ancestors
				#### test_prog__rpg__careers__Warrior.children
				#### test_prog__rpg__careers__Warrior.descendants

MModulePage character
	# character.section
		## test_prog__rpg__character.intro
		## test_prog__rpg__character.importation
			### test_prog__rpg__character.graph
			### list.group
				#### test_prog__rpg__character.imports
				#### test_prog__rpg__character.clients
		## test_prog__rpg__character.concerns
		## test_prog.concern
		## test_prog.concern
		## test_prog__rpg.concern
		## test_prog__rpg__character.concern
			### test_prog__rpg__character__Character.definition-list
				#### test_prog__rpg__character__Character.definition
					##### test_prog__rpg__character__Character.intros_redefs
						###### list.group
							####### test_prog__rpg__character__Character.intros
							####### test_prog__rpg__character__Character.redefs

MClassPage Character
	# Character.section
		## test_prog__rpg__character__Character.intro
		## test_prog__rpg__character__Character.inheritance
			### test_prog__rpg__character__Character.graph
			### list.group
				#### test_prog__rpg__character__Character.parents
				#### test_prog__rpg__character__Character.ancestors
				#### test_prog__rpg__character__Character.children
				#### test_prog__rpg__character__Character.descendants

MModulePage combat
	# combat.section
		## test_prog__rpg__combat.intro
		## test_prog__rpg__combat.importation
			### test_prog__rpg__combat.graph
			### list.group
				#### test_prog__rpg__combat.imports
				#### test_prog__rpg__combat.clients
		## test_prog__rpg__combat.concerns
		## test_prog.concern
		## test_prog.concern
		## test_prog__rpg.concern
		## test_prog__rpg__combat.concern
			### test_prog__rpg__combat__Combatable.definition-list
				#### test_prog__rpg__combat__Combatable.definition
					##### test_prog__rpg__combat__Combatable.intros_redefs
						###### list.group
							####### test_prog__rpg__combat__Combatable.intros
							####### test_prog__rpg__combat__Combatable.redefs
			### test_prog__rpg__combat__Weapon.definition-list
				#### test_prog__rpg__combat__Weapon.definition
					##### test_prog__rpg__combat__Weapon.intros_redefs
						###### list.group
							####### test_prog__rpg__combat__Weapon.intros
							####### test_prog__rpg__combat__Weapon.redefs
		## test_prog__rpg__races.concern
			### test_prog__rpg__races__Dwarf.definition-list
				#### test_prog__rpg__races__Dwarf.definition
				#### test_prog__rpg__combat__Dwarf.definition
					##### test_prog__rpg__combat__Dwarf.intros_redefs
						###### list.group
							####### test_prog__rpg__combat__Dwarf.intros
							####### test_prog__rpg__combat__Dwarf.redefs
		## test_prog__rpg__character.concern
			### test_prog__rpg__character__Character.definition-list
				#### test_prog__rpg__character__Character.definition
				#### test_prog__rpg__combat__Character.definition
					##### test_prog__rpg__combat__Character.intros_redefs
						###### list.group
							####### test_prog__rpg__combat__Character.intros
							####### test_prog__rpg__combat__Character.redefs

MClassPage Combatable
	# Combatable.section
		## test_prog__rpg__combat__Combatable.intro
		## test_prog__rpg__combat__Combatable.inheritance
			### test_prog__rpg__combat__Combatable.graph
			### list.group
				#### test_prog__rpg__combat__Combatable.parents
				#### test_prog__rpg__combat__Combatable.ancestors
				#### test_prog__rpg__combat__Combatable.children
				#### test_prog__rpg__combat__Combatable.descendants

MClassPage Weapon
	# Weapon.section
		## test_prog__rpg__combat__Weapon.intro
		## test_prog__rpg__combat__Weapon.inheritance
			### test_prog__rpg__combat__Weapon.graph
			### list.group
				#### test_prog__rpg__combat__Weapon.parents
				#### test_prog__rpg__combat__Weapon.ancestors
				#### test_prog__rpg__combat__Weapon.children
				#### test_prog__rpg__combat__Weapon.descendants

MModulePage races
	# races.section
		## test_prog__rpg__races.intro
		## test_prog__rpg__races.importation
			### test_prog__rpg__races.graph
			### list.group
				#### test_prog__rpg__races.imports
				#### test_prog__rpg__races.clients
		## test_prog__rpg__races.concerns
		## test_prog.concern
		## test_prog.concern
		## test_prog__rpg.concern
		## test_prog__rpg__races.concern
			### test_prog__rpg__races__Dwarf.definition-list
				#### test_prog__rpg__races__Dwarf.definition
					##### test_prog__rpg__races__Dwarf.intros_redefs
						###### list.group
							####### test_prog__rpg__races__Dwarf.intros
							####### test_prog__rpg__races__Dwarf.redefs
			### test_prog__rpg__races__Elf.definition-list
				#### test_prog__rpg__races__Elf.definition
					##### test_prog__rpg__races__Elf.intros_redefs
						###### list.group
							####### test_prog__rpg__races__Elf.intros
							####### test_prog__rpg__races__Elf.redefs
			### test_prog__rpg__races__Human.definition-list
				#### test_prog__rpg__races__Human.definition
					##### test_prog__rpg__races__Human.intros_redefs
						###### list.group
							####### test_prog__rpg__races__Human.intros
							####### test_prog__rpg__races__Human.redefs
			### test_prog__rpg__races__Race.definition-list
				#### test_prog__rpg__races__Race.definition
					##### test_prog__rpg__races__Race.intros_redefs
						###### list.group
							####### test_prog__rpg__races__Race.intros
							####### test_prog__rpg__races__Race.redefs

MClassPage Dwarf
	# Dwarf.section
		## test_prog__rpg__races__Dwarf.intro
		## test_prog__rpg__races__Dwarf.inheritance
			### test_prog__rpg__races__Dwarf.graph
			### list.group
				#### test_prog__rpg__races__Dwarf.parents
				#### test_prog__rpg__races__Dwarf.ancestors
				#### test_prog__rpg__races__Dwarf.children
				#### test_prog__rpg__races__Dwarf.descendants

MClassPage Elf
	# Elf.section
		## test_prog__rpg__races__Elf.intro
		## test_prog__rpg__races__Elf.inheritance
			### test_prog__rpg__races__Elf.graph
			### list.group
				#### test_prog__rpg__races__Elf.parents
				#### test_prog__rpg__races__Elf.ancestors
				#### test_prog__rpg__races__Elf.children
				#### test_prog__rpg__races__Elf.descendants

MClassPage Human
	# Human.section
		## test_prog__rpg__races__Human.intro
		## test_prog__rpg__races__Human.inheritance
			### test_prog__rpg__races__Human.graph
			### list.group
				#### test_prog__rpg__races__Human.parents
				#### test_prog__rpg__races__Human.ancestors
				#### test_prog__rpg__races__Human.children
				#### test_prog__rpg__races__Human.descendants

MClassPage Race
	# Race.section
		## test_prog__rpg__races__Race.intro
		## test_prog__rpg__races__Race.inheritance
			### test_prog__rpg__races__Race.graph
			### list.group
				#### test_prog__rpg__races__Race.parents
				#### test_prog__rpg__races__Race.ancestors
				#### test_prog__rpg__races__Race.children
				#### test_prog__rpg__races__Race.descendants

MModulePage rpg
	# rpg.section
		## test_prog__rpg__rpg.intro
		## test_prog__rpg__rpg.importation
			### test_prog__rpg__rpg.graph
			### list.group
				#### test_prog__rpg__rpg.imports
				#### test_prog__rpg__rpg.clients

Generated 38 pages
 list:
  MClassPage: 20 (52.63%)
  MModulePage: 8 (21.05%)
  MGroupPage: 4 (10.52%)
  ReadmePage: 4 (10.52%)
  SearchPage: 1 (2.63%)
  OverviewPage: 1 (2.63%)
Found 55 mentities
 list:
  MClassDef: 22 (40.00%)
  MClass: 20 (36.36%)
  MModule: 8 (14.54%)
  MGroup: 4 (7.27%)
  MPackage: 1 (1.81%)
quicksearch-list.js
