  -W, --warn                  Show warnings
  -q, --quiet                 Do not show warnings
  --stop-on-first-error       Stop on first error
  --no-color                  Do not use color to display errors and warnings
  --log                       Generate various log files
  --log-dir                   Directory where to generate log files
  -h, -?, --help              Show Help (This screen)
  --version                   Show version and exit
  -v, --verbose               Verbose
  -I, --path                  Set include path for loaders (may be used more than once)
  --only-parse                Only proceed to parse step of loaders
  --only-metamodel            Stop after meta-model processing
  -o, --output                Output file
  --no-cc                     Do not invoke C compiler
  --make-flags                Additional options to make
  --compile-dir               Directory used to generate temporary files
  --hardening                 Generate contracts in the C code against bugs in the compiler
  --no-shortcut-range         Always insantiate a range and its iterator on 'for' loops
  --no-check-covariance       Disable type tests of covariant parameters (dangerous)
  --no-check-initialization   Disable isset tests at the end of constructors (dangerous)
  --no-check-assert           Disable the evaluation of explicit 'assert' and 'as' (dangerous)
  --no-check-autocast         Disable implicit casts on unsafe expression usage (dangerous)
  --no-check-other            Disable implicit tests: unset attribute, null receiver (dangerous)
  --typing-test-metrics       Enable static and dynamic count of all type tests
  --nit-stacktrace            Enables the use of gperf to bind C to Nit function names when encountering a Stack trace at runtime
  --no-stacktrace             Disables libunwind and generation of C stack traces (can be problematic when compiling to targets such as Android or NaCl)
  --separate                  Use separate compilation
  --no-inline-intern          Do not inline call to intern methods
  --no-union-attribute        Put primitive attibutes in a box instead of an union
  --no-shortcut-equal         Always call == in a polymorphic way
  --inline-coloring-numbers   Inline colors and ids
  --bm-typing                 Colorize items incrementaly, used to simulate binary matrix typing
  --phmod-typing              Replace coloration by perfect hashing (with mod operator)
  --phand-typing              Replace coloration by perfect hashing (with and operator)
  --tables-metrics            Enable static size measuring of tables used for vft, typing and resolution
  --erasure                   Erase generic types
  --no-check-erasure-cast     Disable implicit casts on unsafe return with erasure-typing policy (dangerous)
  --global                    Use global compilation
  -m                          Additionals module to min-in
