test_prog: Test program for model tools. (test_prog)
|--examples (test_prog/examples)
|  `--game_examples (test_prog/examples/game_examples.nit)
|--game: Gaming group (test_prog/game)
|  `--game: A game abstraction for RPG. (test_prog/game/game.nit)
|--platform: Fictive Crappy Platform. (test_prog/platform)
|  `--platform: Declares base types allowed on the platform. (test_prog/platform/platform.nit)
|--rpg: Role Playing Game group (test_prog/rpg)
|  |--careers: Careers of the game. (test_prog/rpg/careers.nit)
|  |--character: Characters are playable entity in the world. (test_prog/rpg/character.nit)
|  |--combat: COmbat interactions between characters. (test_prog/rpg/combat.nit)
|  |--races: Races of the game. (test_prog/rpg/races.nit)
|  `--rpg: A worlg RPG abstraction. (test_prog/rpg/rpg.nit)
|--test_prog: A test program with a fake model to check model tools. (test_prog/test_prog.nit)
`--tests (test_prog/tests)
   `--test_game (test_prog/tests/test_game.nit)
