test_prog: Test program for model tools. (test_prog)
|--examples (test_prog/examples)
|  `--[1mgame_examples[m (test_prog/examples/game_examples.nit)
|--game: Gaming group (test_prog/game)
|  `--[1mgame[m: A game abstraction for RPG. (test_prog/game/game.nit)
|--platform: Fictive Crappy Platform. (test_prog/platform)
|  `--[1mplatform[m: Declares base types allowed on the platform. (test_prog/platform/platform.nit)
|--rpg: Role Playing Game group (test_prog/rpg)
|  |--[1mcareers[m: Careers of the game. (test_prog/rpg/careers.nit)
|  |--[1mcharacter[m: Characters are playable entity in the world. (test_prog/rpg/character.nit)
|  |--[1mcombat[m: COmbat interactions between characters. (test_prog/rpg/combat.nit)
|  |--[1mraces[m: Races of the game. (test_prog/rpg/races.nit)
|  `--[1mrpg[m: A worlg RPG abstraction. (test_prog/rpg/rpg.nit)
`--[1mtest_prog[m: A test program with a fake model to check model tools. (test_prog/test_prog.nit)
