usage: nitunit [options] file.nit...
  -W, --warn              Show warnings
  -q, --quiet             Do not show warnings
  --stop-on-first-error   Stop on first error
  --no-color              Do not use color to display errors and warnings
  --log                   Generate various log files
  --log-dir               Directory where to generate log files
  -h, -?, --help          Show Help (This screen)
  --version               Show version and exit
  -v, --verbose           Verbose
  -I, --path              Set include path for loaders (may be used more than once)
  --only-parse            Only proceed to parse step of loaders
  --only-metamodel        Stop after meta-model processing
  --full                  Process also imported modules
  -o, --output            Output name (default is 'nitunit.xml')
  --dir                   Working directory (default is '.nitunit')
