syntax_annotations2.nit:16,2--6: Warning: unprocessed annotation.
syntax_annotations2.nit:17,2--7: Warning: unprocessed annotation.
syntax_annotations2.nit:20,18--22: Warning: unprocessed annotation.
syntax_annotations2.nit:21,18--22: Warning: unprocessed annotation.
syntax_annotations2.nit:21,25--30: Warning: unprocessed annotation.
syntax_annotations2.nit:23,2--6: Warning: unprocessed annotation.
syntax_annotations2.nit:24,2--7: Warning: unprocessed annotation.
syntax_annotations2.nit:28,2--6: Warning: unprocessed annotation.
syntax_annotations2.nit:29,16--20: Warning: unprocessed annotation.
syntax_annotations2.nit:30,16--20: Warning: unprocessed annotation.
syntax_annotations2.nit:30,23--28: Warning: unprocessed annotation.
syntax_annotations2.nit:32,3--7: Warning: unprocessed annotation.
syntax_annotations2.nit:33,3--8: Warning: unprocessed annotation.
syntax_annotations2.nit:36,3--7: Warning: unprocessed annotation.
syntax_annotations2.nit:38,15--17: Warning: unprocessed annotation.
syntax_annotations2.nit:40,14--18: Warning: unprocessed annotation.
syntax_annotations2.nit:41,14--18: Warning: unprocessed annotation.
syntax_annotations2.nit:41,21--26: Warning: unprocessed annotation.
syntax_annotations2.nit:43,3--7: Warning: unprocessed annotation.
syntax_annotations2.nit:44,3--8: Warning: unprocessed annotation.
syntax_annotations2.nit:46,18--22: Warning: unprocessed annotation.
syntax_annotations2.nit:46,25--30: Warning: unprocessed annotation.
syntax_annotations2.nit:48,3--7: Warning: unprocessed annotation.
syntax_annotations2.nit:49,3--8: Warning: unprocessed annotation.
