syntax_annotations3.nit:16,2--20: Warning: unprocessed annotation.
syntax_annotations3.nit:19,3--12: Warning: unprocessed annotation.
syntax_annotations3.nit:20,3--22: Warning: unprocessed annotation.
syntax_annotations3.nit:21,3--19: Warning: unprocessed annotation.
syntax_annotations3.nit:28,3--7: Warning: unprocessed annotation.
syntax_annotations3.nit:33,16--18: Warning: unprocessed annotation.
syntax_annotations3.nit:34,19--36: Warning: unprocessed annotation.
syntax_annotations3.nit:34,12--36: Warning: unprocessed annotation.
syntax_annotations3.nit:34,3--37: Warning: unprocessed annotation.
syntax_annotations3.nit:35,3--7: Warning: unprocessed annotation.
syntax_annotations3.nit:38,28--35: Warning: unprocessed annotation.
syntax_annotations3.nit:38,38--45: Warning: unprocessed annotation.
syntax_annotations3.nit:38,48--56: Warning: unprocessed annotation.
syntax_annotations3.nit:42,20--28: Warning: unprocessed annotation.
