syntax_annotations.nit:15,10--12: Warning: unprocessed annotation.
syntax_annotations.nit:16,10--17: Warning: unprocessed annotation.
syntax_annotations.nit:17,10--15: Warning: unprocessed annotation.
syntax_annotations.nit:18,10--17: Warning: unprocessed annotation.
syntax_annotations.nit:19,10--25: Warning: unprocessed annotation.
syntax_annotations.nit:20,10--17: Warning: unprocessed annotation.
syntax_annotations.nit:21,15--17: Warning: unprocessed annotation.
syntax_annotations.nit:21,10--18: Warning: unprocessed annotation.
syntax_annotations.nit:22,16--18: Warning: unprocessed annotation.
syntax_annotations.nit:22,20--22: Warning: unprocessed annotation.
syntax_annotations.nit:22,10--24: Warning: unprocessed annotation.
syntax_annotations.nit:23,25--27: Warning: unprocessed annotation.
syntax_annotations.nit:23,32--34: Warning: unprocessed annotation.
syntax_annotations.nit:23,36--38: Warning: unprocessed annotation.
syntax_annotations.nit:23,10--40: Warning: unprocessed annotation.
syntax_annotations.nit:24,12--14: Warning: unprocessed annotation.
syntax_annotations.nit:24,17--19: Warning: unprocessed annotation.
syntax_annotations.nit:25,27--29: Warning: unprocessed annotation.
syntax_annotations.nit:25,34--36: Warning: unprocessed annotation.
syntax_annotations.nit:25,38--40: Warning: unprocessed annotation.
syntax_annotations.nit:25,12--42: Warning: unprocessed annotation.
syntax_annotations.nit:25,60--67: Warning: unprocessed annotation.
syntax_annotations.nit:25,72--79: Warning: unprocessed annotation.
syntax_annotations.nit:25,81--88: Warning: unprocessed annotation.
syntax_annotations.nit:25,45--90: Warning: unprocessed annotation.
