out/test_platform_ios.bin
out/test_platform_ios.bin/Info.plist
out/test_platform_ios.bin/LaunchScreen.storyboardc
out/test_platform_ios.bin/LaunchScreen.storyboardc/01J-lp-oVM-view-Ze5-6b-2t3.nib
out/test_platform_ios.bin/LaunchScreen.storyboardc/Info.plist
out/test_platform_ios.bin/LaunchScreen.storyboardc/UIViewController-01J-lp-oVM.nib
out/test_platform_ios.bin/PkgInfo
out/test_platform_ios.bin/_CodeSignature
out/test_platform_ios.bin/_CodeSignature/CodeResources
out/test_platform_ios.bin/assets
out/test_platform_ios.bin/test_platform_ios
