Read token at ../src/test_parser.nit:1,1--2,0 text='# This file is part of NIT ( http://www.nitlanguage.org ).
'
Read token at ../src/test_parser.nit:2,1--3,0 text='#
'
Read token at ../src/test_parser.nit:3,1--4,0 text='# Copyright 2008 Jean Privat <jean@pryen.org>
'
Read token at ../src/test_parser.nit:4,1--5,0 text='#
'
Read token at ../src/test_parser.nit:5,1--6,0 text='# Licensed under the Apache License, Version 2.0 (the "License");
'
Read token at ../src/test_parser.nit:6,1--7,0 text='# you may not use this file except in compliance with the License.
'
Read token at ../src/test_parser.nit:7,1--8,0 text='# You may obtain a copy of the License at
'
Read token at ../src/test_parser.nit:8,1--9,0 text='#
'
Read token at ../src/test_parser.nit:9,1--10,0 text='#     http://www.apache.org/licenses/LICENSE-2.0
'
Read token at ../src/test_parser.nit:10,1--11,0 text='#
'
Read token at ../src/test_parser.nit:11,1--12,0 text='# Unless required by applicable law or agreed to in writing, software
'
Read token at ../src/test_parser.nit:12,1--13,0 text='# distributed under the License is distributed on an "AS IS" BASIS,
'
Read token at ../src/test_parser.nit:13,1--14,0 text='# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
'
Read token at ../src/test_parser.nit:14,1--15,0 text='# See the License for the specific language governing permissions and
'
Read token at ../src/test_parser.nit:15,1--16,0 text='# limitations under the License.
'
Read token at ../src/test_parser.nit:16,1--17,0 text='
'
Read token at ../src/test_parser.nit:17,1--18,0 text='# Program used to test the NIT parser
'
Read token at ../src/test_parser.nit:18,1--7 text='package'
Read token at ../src/test_parser.nit:18,9--19 text='test_parser'
Read token at ../src/test_parser.nit:18,20--19,0 text='
'
Read token at ../src/test_parser.nit:19,1--20,0 text='
'
Read token at ../src/test_parser.nit:20,1--6 text='import'
Read token at ../src/test_parser.nit:20,8--13 text='parser'
Read token at ../src/test_parser.nit:20,14--21,0 text='
'
Read token at ../src/test_parser.nit:21,1--22,0 text='
'
Read token at ../src/test_parser.nit:22,1--5 text='class'
Read token at ../src/test_parser.nit:22,7--22 text='PrintTreeVisitor'
Read token at ../src/test_parser.nit:22,23--23,0 text='
'
Read token at ../src/test_parser.nit:23,2--6 text='super'
Read token at ../src/test_parser.nit:23,8--14 text='Visitor'
Read token at ../src/test_parser.nit:23,15--24,0 text='
'
Read token at ../src/test_parser.nit:24,2--4 text='var'
Read token at ../src/test_parser.nit:24,6--10 text='_rank'
Read token at ../src/test_parser.nit:24,11 text=':'
Read token at ../src/test_parser.nit:24,13--15 text='Int'
Read token at ../src/test_parser.nit:24,16--25,0 text='
'
Read token at ../src/test_parser.nit:25,2--6 text='redef'
Read token at ../src/test_parser.nit:25,8--10 text='fun'
Read token at ../src/test_parser.nit:25,12--16 text='visit'
Read token at ../src/test_parser.nit:25,17 text='('
Read token at ../src/test_parser.nit:25,18 text='n'
Read token at ../src/test_parser.nit:25,19 text=')'
Read token at ../src/test_parser.nit:25,20--26,0 text='
'
Read token at ../src/test_parser.nit:26,2--3 text='do'
Read token at ../src/test_parser.nit:26,4--27,0 text='
'
Read token at ../src/test_parser.nit:27,3--4 text='if'
Read token at ../src/test_parser.nit:27,6 text='n'
Read token at ../src/test_parser.nit:27,8--10 text='isa'
Read token at ../src/test_parser.nit:27,12--16 text='Token'
Read token at ../src/test_parser.nit:27,18--21 text='then'
Read token at ../src/test_parser.nit:27,22--28,0 text='
'
Read token at ../src/test_parser.nit:28,4--9 text='printn'
Read token at ../src/test_parser.nit:28,10 text='('
Read token at ../src/test_parser.nit:28,11--14 text='"  "'
Read token at ../src/test_parser.nit:28,16 text='*'
Read token at ../src/test_parser.nit:28,18--22 text='_rank'
Read token at ../src/test_parser.nit:28,23 text=','
Read token at ../src/test_parser.nit:28,25 text='n'
Read token at ../src/test_parser.nit:28,26 text='.'
Read token at ../src/test_parser.nit:28,27--30 text='to_s'
Read token at ../src/test_parser.nit:28,31 text=','
Read token at ../src/test_parser.nit:28,33--39 text='" ... "'
Read token at ../src/test_parser.nit:28,40 text=','
Read token at ../src/test_parser.nit:28,42 text='n'
Read token at ../src/test_parser.nit:28,43 text='.'
Read token at ../src/test_parser.nit:28,44--51 text='location'
Read token at ../src/test_parser.nit:28,52 text=','
Read token at ../src/test_parser.nit:28,54--57 text='"\n"'
Read token at ../src/test_parser.nit:28,58 text=')'
Read token at ../src/test_parser.nit:28,59--29,0 text='
'
Read token at ../src/test_parser.nit:29,3--6 text='else'
Read token at ../src/test_parser.nit:29,7--30,0 text='
'
Read token at ../src/test_parser.nit:30,4--9 text='printn'
Read token at ../src/test_parser.nit:30,10 text='('
Read token at ../src/test_parser.nit:30,11--14 text='"  "'
Read token at ../src/test_parser.nit:30,16 text='*'
Read token at ../src/test_parser.nit:30,18--22 text='_rank'
Read token at ../src/test_parser.nit:30,23 text=','
Read token at ../src/test_parser.nit:30,25 text='n'
Read token at ../src/test_parser.nit:30,26 text='.'
Read token at ../src/test_parser.nit:30,27--34 text='location'
Read token at ../src/test_parser.nit:30,35 text=','
Read token at ../src/test_parser.nit:30,37--40 text='"\n"'
Read token at ../src/test_parser.nit:30,41 text=')'
Read token at ../src/test_parser.nit:30,42--31,0 text='
'
Read token at ../src/test_parser.nit:31,3--5 text='end'
Read token at ../src/test_parser.nit:31,6--32,0 text='
'
Read token at ../src/test_parser.nit:32,3--7 text='_rank'
Read token at ../src/test_parser.nit:32,9 text='='
Read token at ../src/test_parser.nit:32,11--15 text='_rank'
Read token at ../src/test_parser.nit:32,17 text='+'
Read token at ../src/test_parser.nit:32,19 text='1'
Read token at ../src/test_parser.nit:32,20--33,0 text='
'
Read token at ../src/test_parser.nit:33,3 text='n'
Read token at ../src/test_parser.nit:33,4 text='.'
Read token at ../src/test_parser.nit:33,5--13 text='visit_all'
Read token at ../src/test_parser.nit:33,14 text='('
Read token at ../src/test_parser.nit:33,15--18 text='self'
Read token at ../src/test_parser.nit:33,19 text=')'
Read token at ../src/test_parser.nit:33,20--34,0 text='
'
Read token at ../src/test_parser.nit:34,3--7 text='_rank'
Read token at ../src/test_parser.nit:34,9 text='='
Read token at ../src/test_parser.nit:34,11--15 text='_rank'
Read token at ../src/test_parser.nit:34,17 text='-'
Read token at ../src/test_parser.nit:34,19 text='1'
Read token at ../src/test_parser.nit:34,20--35,0 text='
'
Read token at ../src/test_parser.nit:35,2--4 text='end'
Read token at ../src/test_parser.nit:35,5--36,0 text='
'
Read token at ../src/test_parser.nit:36,1--37,0 text='
'
Read token at ../src/test_parser.nit:37,2--5 text='init'
Read token at ../src/test_parser.nit:37,6--38,0 text='
'
Read token at ../src/test_parser.nit:38,2--3 text='do'
Read token at ../src/test_parser.nit:38,4--39,0 text='
'
Read token at ../src/test_parser.nit:39,3--7 text='_rank'
Read token at ../src/test_parser.nit:39,9 text='='
Read token at ../src/test_parser.nit:39,11 text='0'
Read token at ../src/test_parser.nit:39,12--40,0 text='
'
Read token at ../src/test_parser.nit:40,2--4 text='end'
Read token at ../src/test_parser.nit:40,5--41,0 text='
'
Read token at ../src/test_parser.nit:41,1--3 text='end'
Read token at ../src/test_parser.nit:41,4--42,0 text='
'
Read token at ../src/test_parser.nit:42,1--43,0 text='
'
Read token at ../src/test_parser.nit:43,1--3 text='var'
Read token at ../src/test_parser.nit:43,5--12 text='no_print'
Read token at ../src/test_parser.nit:43,14 text='='
Read token at ../src/test_parser.nit:43,16--20 text='false'
Read token at ../src/test_parser.nit:43,21--44,0 text='
'
Read token at ../src/test_parser.nit:44,1--3 text='var'
Read token at ../src/test_parser.nit:44,5--14 text='only_lexer'
Read token at ../src/test_parser.nit:44,16 text='='
Read token at ../src/test_parser.nit:44,18--22 text='false'
Read token at ../src/test_parser.nit:44,23--45,0 text='
'
Read token at ../src/test_parser.nit:45,1--3 text='var'
Read token at ../src/test_parser.nit:45,5--13 text='need_help'
Read token at ../src/test_parser.nit:45,15 text='='
Read token at ../src/test_parser.nit:45,17--21 text='false'
Read token at ../src/test_parser.nit:45,22--46,0 text='
'
Read token at ../src/test_parser.nit:46,1--3 text='var'
Read token at ../src/test_parser.nit:46,5--11 text='no_file'
Read token at ../src/test_parser.nit:46,13 text='='
Read token at ../src/test_parser.nit:46,15--19 text='false'
Read token at ../src/test_parser.nit:46,20--47,0 text='
'
Read token at ../src/test_parser.nit:47,1--48,0 text='
'
Read token at ../src/test_parser.nit:48,1--5 text='while'
Read token at ../src/test_parser.nit:48,7--9 text='not'
Read token at ../src/test_parser.nit:48,11--14 text='args'
Read token at ../src/test_parser.nit:48,15 text='.'
Read token at ../src/test_parser.nit:48,16--23 text='is_empty'
Read token at ../src/test_parser.nit:48,25--27 text='and'
Read token at ../src/test_parser.nit:48,29--32 text='args'
Read token at ../src/test_parser.nit:48,33 text='.'
Read token at ../src/test_parser.nit:48,34--38 text='first'
Read token at ../src/test_parser.nit:48,39 text='.'
Read token at ../src/test_parser.nit:48,40--44 text='first'
Read token at ../src/test_parser.nit:48,46--47 text='=='
Read token at ../src/test_parser.nit:48,49--51 text=''-''
Read token at ../src/test_parser.nit:48,53--54 text='do'
Read token at ../src/test_parser.nit:48,55--49,0 text='
'
Read token at ../src/test_parser.nit:49,2--3 text='if'
Read token at ../src/test_parser.nit:49,5--8 text='args'
Read token at ../src/test_parser.nit:49,9 text='.'
Read token at ../src/test_parser.nit:49,10--14 text='first'
Read token at ../src/test_parser.nit:49,16--17 text='=='
Read token at ../src/test_parser.nit:49,19--22 text='"-n"'
Read token at ../src/test_parser.nit:49,24--27 text='then'
Read token at ../src/test_parser.nit:49,28--50,0 text='
'
Read token at ../src/test_parser.nit:50,3--10 text='no_print'
Read token at ../src/test_parser.nit:50,12 text='='
Read token at ../src/test_parser.nit:50,14--17 text='true'
Read token at ../src/test_parser.nit:50,18--51,0 text='
'
Read token at ../src/test_parser.nit:51,2--5 text='else'
Read token at ../src/test_parser.nit:51,7--8 text='if'
Read token at ../src/test_parser.nit:51,10--13 text='args'
Read token at ../src/test_parser.nit:51,14 text='.'
Read token at ../src/test_parser.nit:51,15--19 text='first'
Read token at ../src/test_parser.nit:51,21--22 text='=='
Read token at ../src/test_parser.nit:51,24--27 text='"-l"'
Read token at ../src/test_parser.nit:51,29--32 text='then'
Read token at ../src/test_parser.nit:51,33--52,0 text='
'
Read token at ../src/test_parser.nit:52,3--12 text='only_lexer'
Read token at ../src/test_parser.nit:52,14 text='='
Read token at ../src/test_parser.nit:52,16--19 text='true'
Read token at ../src/test_parser.nit:52,20--53,0 text='
'
Read token at ../src/test_parser.nit:53,2--5 text='else'
Read token at ../src/test_parser.nit:53,7--8 text='if'
Read token at ../src/test_parser.nit:53,10--13 text='args'
Read token at ../src/test_parser.nit:53,14 text='.'
Read token at ../src/test_parser.nit:53,15--19 text='first'
Read token at ../src/test_parser.nit:53,21--22 text='=='
Read token at ../src/test_parser.nit:53,24--27 text='"-p"'
Read token at ../src/test_parser.nit:53,29--32 text='then'
Read token at ../src/test_parser.nit:53,33--54,0 text='
'
Read token at ../src/test_parser.nit:54,3--12 text='only_lexer'
Read token at ../src/test_parser.nit:54,14 text='='
Read token at ../src/test_parser.nit:54,16--20 text='false'
Read token at ../src/test_parser.nit:54,21--55,0 text='
'
Read token at ../src/test_parser.nit:55,2--5 text='else'
Read token at ../src/test_parser.nit:55,7--8 text='if'
Read token at ../src/test_parser.nit:55,10--13 text='args'
Read token at ../src/test_parser.nit:55,14 text='.'
Read token at ../src/test_parser.nit:55,15--19 text='first'
Read token at ../src/test_parser.nit:55,21--22 text='=='
Read token at ../src/test_parser.nit:55,24--27 text='"-e"'
Read token at ../src/test_parser.nit:55,29--32 text='then'
Read token at ../src/test_parser.nit:55,33--56,0 text='
'
Read token at ../src/test_parser.nit:56,3--9 text='no_file'
Read token at ../src/test_parser.nit:56,11 text='='
Read token at ../src/test_parser.nit:56,13--16 text='true'
Read token at ../src/test_parser.nit:56,17--57,0 text='
'
Read token at ../src/test_parser.nit:57,2--5 text='else'
Read token at ../src/test_parser.nit:57,7--8 text='if'
Read token at ../src/test_parser.nit:57,10--13 text='args'
Read token at ../src/test_parser.nit:57,14 text='.'
Read token at ../src/test_parser.nit:57,15--19 text='first'
Read token at ../src/test_parser.nit:57,21--22 text='=='
Read token at ../src/test_parser.nit:57,24--27 text='"-h"'
Read token at ../src/test_parser.nit:57,29--30 text='or'
Read token at ../src/test_parser.nit:57,32--35 text='args'
Read token at ../src/test_parser.nit:57,36 text='.'
Read token at ../src/test_parser.nit:57,37--41 text='first'
Read token at ../src/test_parser.nit:57,43--44 text='=='
Read token at ../src/test_parser.nit:57,46--49 text='"-?"'
Read token at ../src/test_parser.nit:57,51--54 text='then'
Read token at ../src/test_parser.nit:57,55--58,0 text='
'
Read token at ../src/test_parser.nit:58,3--11 text='need_help'
Read token at ../src/test_parser.nit:58,13 text='='
Read token at ../src/test_parser.nit:58,15--18 text='true'
Read token at ../src/test_parser.nit:58,19--59,0 text='
'
Read token at ../src/test_parser.nit:59,2--5 text='else'
Read token at ../src/test_parser.nit:59,6--60,0 text='
'
Read token at ../src/test_parser.nit:60,3--8 text='stderr'
Read token at ../src/test_parser.nit:60,9 text='.'
Read token at ../src/test_parser.nit:60,10--14 text='write'
Read token at ../src/test_parser.nit:60,15 text='('
Read token at ../src/test_parser.nit:60,16--32 text='"Unknown option {'
Read token at ../src/test_parser.nit:60,33--36 text='args'
Read token at ../src/test_parser.nit:60,37 text='.'
Read token at ../src/test_parser.nit:60,38--42 text='first'
Read token at ../src/test_parser.nit:60,43--47 text='}.\n"'
Read token at ../src/test_parser.nit:60,48 text=')'
Read token at ../src/test_parser.nit:60,49--61,0 text='
'
Read token at ../src/test_parser.nit:61,3--6 text='exit'
Read token at ../src/test_parser.nit:61,7 text='('
Read token at ../src/test_parser.nit:61,8 text='0'
Read token at ../src/test_parser.nit:61,9 text=')'
Read token at ../src/test_parser.nit:61,10--62,0 text='
'
Read token at ../src/test_parser.nit:62,2--4 text='end'
Read token at ../src/test_parser.nit:62,5--63,0 text='
'
Read token at ../src/test_parser.nit:63,2--5 text='args'
Read token at ../src/test_parser.nit:63,6 text='.'
Read token at ../src/test_parser.nit:63,7--11 text='shift'
Read token at ../src/test_parser.nit:63,12--64,0 text='
'
Read token at ../src/test_parser.nit:64,1--3 text='end'
Read token at ../src/test_parser.nit:64,4--65,0 text='
'
Read token at ../src/test_parser.nit:65,1--66,0 text='
'
Read token at ../src/test_parser.nit:66,1--2 text='if'
Read token at ../src/test_parser.nit:66,4--7 text='args'
Read token at ../src/test_parser.nit:66,8 text='.'
Read token at ../src/test_parser.nit:66,9--16 text='is_empty'
Read token at ../src/test_parser.nit:66,18--19 text='or'
Read token at ../src/test_parser.nit:66,21--29 text='need_help'
Read token at ../src/test_parser.nit:66,31--34 text='then'
Read token at ../src/test_parser.nit:66,35--67,0 text='
'
Read token at ../src/test_parser.nit:67,2--6 text='print'
Read token at ../src/test_parser.nit:67,7 text='('
Read token at ../src/test_parser.nit:67,8--15 text='"usage:"'
Read token at ../src/test_parser.nit:67,16 text=')'
Read token at ../src/test_parser.nit:67,17--68,0 text='
'
Read token at ../src/test_parser.nit:68,2--6 text='print'
Read token at ../src/test_parser.nit:68,7 text='('
Read token at ../src/test_parser.nit:68,8--53 text='"  test_parser [options]... <filename.nit>..."'
Read token at ../src/test_parser.nit:68,54 text=')'
Read token at ../src/test_parser.nit:68,55--69,0 text='
'
Read token at ../src/test_parser.nit:69,2--6 text='print'
Read token at ../src/test_parser.nit:69,7 text='('
Read token at ../src/test_parser.nit:69,8--17 text='"options:"'
Read token at ../src/test_parser.nit:69,18 text=')'
Read token at ../src/test_parser.nit:69,19--70,0 text='
'
Read token at ../src/test_parser.nit:70,2--6 text='print'
Read token at ../src/test_parser.nit:70,7 text='('
Read token at ../src/test_parser.nit:70,8--35 text='"  -n	do not print anything"'
Read token at ../src/test_parser.nit:70,36 text=')'
Read token at ../src/test_parser.nit:70,37--71,0 text='
'
Read token at ../src/test_parser.nit:71,2--6 text='print'
Read token at ../src/test_parser.nit:71,7 text='('
Read token at ../src/test_parser.nit:71,8--24 text='"  -l	only lexer"'
Read token at ../src/test_parser.nit:71,25 text=')'
Read token at ../src/test_parser.nit:71,26--72,0 text='
'
Read token at ../src/test_parser.nit:72,2--6 text='print'
Read token at ../src/test_parser.nit:72,7 text='('
Read token at ../src/test_parser.nit:72,8--40 text='"  -p	lexer and parser (default)"'
Read token at ../src/test_parser.nit:72,41 text=')'
Read token at ../src/test_parser.nit:72,42--73,0 text='
'
Read token at ../src/test_parser.nit:73,2--6 text='print'
Read token at ../src/test_parser.nit:73,7 text='('
Read token at ../src/test_parser.nit:73,8--67 text='"  -e	instead on files, each argument is a content to parse"'
Read token at ../src/test_parser.nit:73,68 text=')'
Read token at ../src/test_parser.nit:73,69--74,0 text='
'
Read token at ../src/test_parser.nit:74,2--6 text='print'
Read token at ../src/test_parser.nit:74,7 text='('
Read token at ../src/test_parser.nit:74,8--29 text='"  -h	print this help"'
Read token at ../src/test_parser.nit:74,30 text=')'
Read token at ../src/test_parser.nit:74,31--75,0 text='
'
Read token at ../src/test_parser.nit:75,1--4 text='else'
Read token at ../src/test_parser.nit:75,5--76,0 text='
'
Read token at ../src/test_parser.nit:76,2--4 text='for'
Read token at ../src/test_parser.nit:76,6 text='a'
Read token at ../src/test_parser.nit:76,8--9 text='in'
Read token at ../src/test_parser.nit:76,11--14 text='args'
Read token at ../src/test_parser.nit:76,16--17 text='do'
Read token at ../src/test_parser.nit:76,18--77,0 text='
'
Read token at ../src/test_parser.nit:77,3--5 text='var'
Read token at ../src/test_parser.nit:77,7--12 text='source'
Read token at ../src/test_parser.nit:77,13--78,0 text='
'
Read token at ../src/test_parser.nit:78,3--4 text='if'
Read token at ../src/test_parser.nit:78,6--12 text='no_file'
Read token at ../src/test_parser.nit:78,14--17 text='then'
Read token at ../src/test_parser.nit:78,18--79,0 text='
'
Read token at ../src/test_parser.nit:79,4--9 text='source'
Read token at ../src/test_parser.nit:79,11 text='='
Read token at ../src/test_parser.nit:79,13--15 text='new'
Read token at ../src/test_parser.nit:79,17--26 text='SourceFile'
Read token at ../src/test_parser.nit:79,27 text='.'
Read token at ../src/test_parser.nit:79,28--38 text='from_string'
Read token at ../src/test_parser.nit:79,39 text='('
Read token at ../src/test_parser.nit:79,40--41 text='""'
Read token at ../src/test_parser.nit:79,42 text=','
Read token at ../src/test_parser.nit:79,44 text='a'
Read token at ../src/test_parser.nit:79,45 text=')'
Read token at ../src/test_parser.nit:79,46--80,0 text='
'
Read token at ../src/test_parser.nit:80,3--6 text='else'
Read token at ../src/test_parser.nit:80,7--81,0 text='
'
Read token at ../src/test_parser.nit:81,4--6 text='var'
Read token at ../src/test_parser.nit:81,8 text='f'
Read token at ../src/test_parser.nit:81,10 text='='
Read token at ../src/test_parser.nit:81,12--14 text='new'
Read token at ../src/test_parser.nit:81,16--23 text='IFStream'
Read token at ../src/test_parser.nit:81,24 text='.'
Read token at ../src/test_parser.nit:81,25--28 text='open'
Read token at ../src/test_parser.nit:81,29 text='('
Read token at ../src/test_parser.nit:81,30 text='a'
Read token at ../src/test_parser.nit:81,31 text=')'
Read token at ../src/test_parser.nit:81,32--82,0 text='
'
Read token at ../src/test_parser.nit:82,4--9 text='source'
Read token at ../src/test_parser.nit:82,11 text='='
Read token at ../src/test_parser.nit:82,13--15 text='new'
Read token at ../src/test_parser.nit:82,17--26 text='SourceFile'
Read token at ../src/test_parser.nit:82,27 text='('
Read token at ../src/test_parser.nit:82,28 text='a'
Read token at ../src/test_parser.nit:82,29 text=','
Read token at ../src/test_parser.nit:82,31 text='f'
Read token at ../src/test_parser.nit:82,32 text=')'
Read token at ../src/test_parser.nit:82,33--83,0 text='
'
Read token at ../src/test_parser.nit:83,4 text='f'
Read token at ../src/test_parser.nit:83,5 text='.'
Read token at ../src/test_parser.nit:83,6--10 text='close'
Read token at ../src/test_parser.nit:83,11--84,0 text='
'
Read token at ../src/test_parser.nit:84,3--5 text='end'
Read token at ../src/test_parser.nit:84,6--85,0 text='
'
Read token at ../src/test_parser.nit:85,3--5 text='var'
Read token at ../src/test_parser.nit:85,7--11 text='lexer'
Read token at ../src/test_parser.nit:85,13 text='='
Read token at ../src/test_parser.nit:85,15--17 text='new'
Read token at ../src/test_parser.nit:85,19--23 text='Lexer'
Read token at ../src/test_parser.nit:85,24 text='('
Read token at ../src/test_parser.nit:85,25--30 text='source'
Read token at ../src/test_parser.nit:85,31 text=')'
Read token at ../src/test_parser.nit:85,32--86,0 text='
'
Read token at ../src/test_parser.nit:86,3--4 text='if'
Read token at ../src/test_parser.nit:86,6--15 text='only_lexer'
Read token at ../src/test_parser.nit:86,17--20 text='then'
Read token at ../src/test_parser.nit:86,21--87,0 text='
'
Read token at ../src/test_parser.nit:87,4--6 text='var'
Read token at ../src/test_parser.nit:87,8--12 text='token'
Read token at ../src/test_parser.nit:87,14 text='='
Read token at ../src/test_parser.nit:87,16--20 text='lexer'
Read token at ../src/test_parser.nit:87,21 text='.'
Read token at ../src/test_parser.nit:87,22--25 text='next'
Read token at ../src/test_parser.nit:87,26--88,0 text='
'
Read token at ../src/test_parser.nit:88,4--8 text='while'
Read token at ../src/test_parser.nit:88,10--12 text='not'
Read token at ../src/test_parser.nit:88,14--18 text='token'
Read token at ../src/test_parser.nit:88,20--22 text='isa'
Read token at ../src/test_parser.nit:88,24--26 text='EOF'
Read token at ../src/test_parser.nit:88,28--29 text='do'
Read token at ../src/test_parser.nit:88,30--89,0 text='
'
Read token at ../src/test_parser.nit:89,5--6 text='if'
Read token at ../src/test_parser.nit:89,8--10 text='not'
Read token at ../src/test_parser.nit:89,12--19 text='no_print'
Read token at ../src/test_parser.nit:89,21--24 text='then'
Read token at ../src/test_parser.nit:89,25--90,0 text='
'
Read token at ../src/test_parser.nit:90,6--10 text='print'
Read token at ../src/test_parser.nit:90,11 text='('
Read token at ../src/test_parser.nit:90,12--27 text='"Read token at {'
Read token at ../src/test_parser.nit:90,28--32 text='token'
Read token at ../src/test_parser.nit:90,33 text='.'
Read token at ../src/test_parser.nit:90,34--41 text='location'
Read token at ../src/test_parser.nit:90,42--50 text='} text='{'
Read token at ../src/test_parser.nit:90,51--55 text='token'
Read token at ../src/test_parser.nit:90,56 text='.'
Read token at ../src/test_parser.nit:90,57--60 text='text'
Read token at ../src/test_parser.nit:90,61--63 text='}'"'
Read token at ../src/test_parser.nit:90,64 text=')'
Read token at ../src/test_parser.nit:90,65--91,0 text='
'
Read token at ../src/test_parser.nit:91,5--7 text='end'
Read token at ../src/test_parser.nit:91,8--92,0 text='
'
Read token at ../src/test_parser.nit:92,5--9 text='token'
Read token at ../src/test_parser.nit:92,11 text='='
Read token at ../src/test_parser.nit:92,13--17 text='lexer'
Read token at ../src/test_parser.nit:92,18 text='.'
Read token at ../src/test_parser.nit:92,19--22 text='next'
Read token at ../src/test_parser.nit:92,23--93,0 text='
'
Read token at ../src/test_parser.nit:93,4--6 text='end'
Read token at ../src/test_parser.nit:93,7--94,0 text='
'
Read token at ../src/test_parser.nit:94,3--6 text='else'
Read token at ../src/test_parser.nit:94,7--95,0 text='
'
Read token at ../src/test_parser.nit:95,4--6 text='var'
Read token at ../src/test_parser.nit:95,8--13 text='parser'
Read token at ../src/test_parser.nit:95,15 text='='
Read token at ../src/test_parser.nit:95,17--19 text='new'
Read token at ../src/test_parser.nit:95,21--26 text='Parser'
Read token at ../src/test_parser.nit:95,27 text='('
Read token at ../src/test_parser.nit:95,28--32 text='lexer'
Read token at ../src/test_parser.nit:95,33 text=')'
Read token at ../src/test_parser.nit:95,34--96,0 text='
'
Read token at ../src/test_parser.nit:96,4--6 text='var'
Read token at ../src/test_parser.nit:96,8--11 text='tree'
Read token at ../src/test_parser.nit:96,13 text='='
Read token at ../src/test_parser.nit:96,15--20 text='parser'
Read token at ../src/test_parser.nit:96,21 text='.'
Read token at ../src/test_parser.nit:96,22--26 text='parse'
Read token at ../src/test_parser.nit:96,27--97,0 text='
'
Read token at ../src/test_parser.nit:97,1--98,0 text='
'
Read token at ../src/test_parser.nit:98,4--6 text='var'
Read token at ../src/test_parser.nit:98,8--12 text='error'
Read token at ../src/test_parser.nit:98,14 text='='
Read token at ../src/test_parser.nit:98,16--19 text='tree'
Read token at ../src/test_parser.nit:98,20 text='.'
Read token at ../src/test_parser.nit:98,21--25 text='n_eof'
Read token at ../src/test_parser.nit:98,26--99,0 text='
'
Read token at ../src/test_parser.nit:99,4--5 text='if'
Read token at ../src/test_parser.nit:99,7--11 text='error'
Read token at ../src/test_parser.nit:99,13--15 text='isa'
Read token at ../src/test_parser.nit:99,17--22 text='AError'
Read token at ../src/test_parser.nit:99,24--27 text='then'
Read token at ../src/test_parser.nit:99,28--100,0 text='
'
Read token at ../src/test_parser.nit:100,5--9 text='print'
Read token at ../src/test_parser.nit:100,10 text='('
Read token at ../src/test_parser.nit:100,11--21 text='"Error at {'
Read token at ../src/test_parser.nit:100,22--26 text='error'
Read token at ../src/test_parser.nit:100,27 text='.'
Read token at ../src/test_parser.nit:100,28--35 text='location'
Read token at ../src/test_parser.nit:100,36--42 text='}:\n\t{'
Read token at ../src/test_parser.nit:100,43--47 text='error'
Read token at ../src/test_parser.nit:100,48 text='.'
Read token at ../src/test_parser.nit:100,49--55 text='message'
Read token at ../src/test_parser.nit:100,56--57 text='}"'
Read token at ../src/test_parser.nit:100,58 text=')'
Read token at ../src/test_parser.nit:100,59--101,0 text='
'
Read token at ../src/test_parser.nit:101,5--10 text='return'
Read token at ../src/test_parser.nit:101,11--102,0 text='
'
Read token at ../src/test_parser.nit:102,4--6 text='end'
Read token at ../src/test_parser.nit:102,7--103,0 text='
'
Read token at ../src/test_parser.nit:103,1--104,0 text='
'
Read token at ../src/test_parser.nit:104,4--5 text='if'
Read token at ../src/test_parser.nit:104,7--9 text='not'
Read token at ../src/test_parser.nit:104,11--18 text='no_print'
Read token at ../src/test_parser.nit:104,20--23 text='then'
Read token at ../src/test_parser.nit:104,24--105,0 text='
'
Read token at ../src/test_parser.nit:105,5 text='('
Read token at ../src/test_parser.nit:105,6--8 text='new'
Read token at ../src/test_parser.nit:105,10--25 text='PrintTreeVisitor'
Read token at ../src/test_parser.nit:105,26 text=')'
Read token at ../src/test_parser.nit:105,27 text='.'
Read token at ../src/test_parser.nit:105,28--38 text='enter_visit'
Read token at ../src/test_parser.nit:105,39 text='('
Read token at ../src/test_parser.nit:105,40--43 text='tree'
Read token at ../src/test_parser.nit:105,44 text=')'
Read token at ../src/test_parser.nit:105,45--106,0 text='
'
Read token at ../src/test_parser.nit:106,4--6 text='end'
Read token at ../src/test_parser.nit:106,7--107,0 text='
'
Read token at ../src/test_parser.nit:107,3--5 text='end'
Read token at ../src/test_parser.nit:107,6--108,0 text='
'
Read token at ../src/test_parser.nit:108,2--4 text='end'
Read token at ../src/test_parser.nit:108,5--109,0 text='
'
Read token at ../src/test_parser.nit:109,1--3 text='end'
Read token at ../src/test_parser.nit:109,4--110,0 text='
'
