Usage: test_toolcontext [OPTION]...
Test for ToolContext, try --bash-completion.
  -W, --warn              Show additional warnings (advices)
  -w, --warning           Show/hide a specific warning
  -q, --quiet             Do not show warnings
  --stop-on-first-error   Just display the first encountered error then stop
  --keep-going            Continue after errors, whatever the consequences
  --no-color              Do not use color to display errors and warnings
  --log                   Generate various log files
  --log-dir               Directory where to generate log files
  --nit-dir               Base directory of the Nit installation
  -h, -?, --help          Show Help (This screen)
  --version               Show version and exit
  -v, --verbose           Additional messages from the tool
  --no-contract           Disable the contracts usage
  --full-contract         Enable all contracts usage
  --in-out-invariant      Enable the verification of invariant contracts in enter and exit
  --no-self-contract      Disable the verification of contracts in self
  -a, --option-a          option a, do nothing
  -b, --option-b          option b, do nothing
  -c                      option c, do nothing
