Read token at ../src/test_parser.nit:1,1--2,0 text='# This file is part of NIT ( http://www.nitlanguage.org ).
'
Read token at ../src/test_parser.nit:2,1--3,0 text='#
'
Read token at ../src/test_parser.nit:3,1--4,0 text='# Copyright 2008 Jean Privat <jean@pryen.org>
'
Read token at ../src/test_parser.nit:4,1--5,0 text='#
'
Read token at ../src/test_parser.nit:5,1--6,0 text='# Licensed under the Apache License, Version 2.0 (the "License");
'
Read token at ../src/test_parser.nit:6,1--7,0 text='# you may not use this file except in compliance with the License.
'
Read token at ../src/test_parser.nit:7,1--8,0 text='# You may obtain a copy of the License at
'
Read token at ../src/test_parser.nit:8,1--9,0 text='#
'
Read token at ../src/test_parser.nit:9,1--10,0 text='#     http://www.apache.org/licenses/LICENSE-2.0
'
Read token at ../src/test_parser.nit:10,1--11,0 text='#
'
Read token at ../src/test_parser.nit:11,1--12,0 text='# Unless required by applicable law or agreed to in writing, software
'
Read token at ../src/test_parser.nit:12,1--13,0 text='# distributed under the License is distributed on an "AS IS" BASIS,
'
Read token at ../src/test_parser.nit:13,1--14,0 text='# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
'
Read token at ../src/test_parser.nit:14,1--15,0 text='# See the License for the specific language governing permissions and
'
Read token at ../src/test_parser.nit:15,1--16,0 text='# limitations under the License.
'
Read token at ../src/test_parser.nit:16,1--17,0 text='
'
Read token at ../src/test_parser.nit:17,1--18,0 text='# Program used to test the NIT parser
'
Read token at ../src/test_parser.nit:18,1--7 text='package'
Read token at ../src/test_parser.nit:18,9--19 text='test_parser'
Read token at ../src/test_parser.nit:18,20--19,0 text='
'
Read token at ../src/test_parser.nit:19,1--20,0 text='
'
Read token at ../src/test_parser.nit:20,1--6 text='import'
Read token at ../src/test_parser.nit:20,8--13 text='parser'
Read token at ../src/test_parser.nit:20,14--21,0 text='
'
Read token at ../src/test_parser.nit:21,1--22,0 text='
'
Read token at ../src/test_parser.nit:22,1--5 text='class'
Read token at ../src/test_parser.nit:22,7--22 text='PrintTreeVisitor'
Read token at ../src/test_parser.nit:22,23--23,0 text='
'
Read token at ../src/test_parser.nit:23,2--6 text='super'
Read token at ../src/test_parser.nit:23,8--14 text='Visitor'
Read token at ../src/test_parser.nit:23,15--24,0 text='
'
Read token at ../src/test_parser.nit:24,2--4 text='var'
Read token at ../src/test_parser.nit:24,6--10 text='_rank'
Read token at ../src/test_parser.nit:24,11 text=':'
Read token at ../src/test_parser.nit:24,13--15 text='Int'
Read token at ../src/test_parser.nit:24,16--25,0 text='
'
Read token at ../src/test_parser.nit:25,2--6 text='redef'
Read token at ../src/test_parser.nit:25,8--10 text='fun'
Read token at ../src/test_parser.nit:25,12--16 text='visit'
Read token at ../src/test_parser.nit:25,17 text='('
Read token at ../src/test_parser.nit:25,18 text='n'
Read token at ../src/test_parser.nit:25,19 text=':'
Read token at ../src/test_parser.nit:25,21--28 text='nullable'
Read token at ../src/test_parser.nit:25,30--34 text='ANode'
Read token at ../src/test_parser.nit:25,35 text=')'
Read token at ../src/test_parser.nit:25,36--26,0 text='
'
Read token at ../src/test_parser.nit:26,2--3 text='do'
Read token at ../src/test_parser.nit:26,4--27,0 text='
'
Read token at ../src/test_parser.nit:27,3--4 text='if'
Read token at ../src/test_parser.nit:27,6 text='n'
Read token at ../src/test_parser.nit:27,8--9 text='=='
Read token at ../src/test_parser.nit:27,11--14 text='null'
Read token at ../src/test_parser.nit:27,16--19 text='then'
Read token at ../src/test_parser.nit:27,21--26 text='return'
Read token at ../src/test_parser.nit:27,27--28,0 text='
'
Read token at ../src/test_parser.nit:28,3--4 text='if'
Read token at ../src/test_parser.nit:28,6 text='n'
Read token at ../src/test_parser.nit:28,8--10 text='isa'
Read token at ../src/test_parser.nit:28,12--16 text='Token'
Read token at ../src/test_parser.nit:28,18--21 text='then'
Read token at ../src/test_parser.nit:28,22--29,0 text='
'
Read token at ../src/test_parser.nit:29,4--9 text='printn'
Read token at ../src/test_parser.nit:29,10 text='('
Read token at ../src/test_parser.nit:29,11--14 text='"  "'
Read token at ../src/test_parser.nit:29,16 text='*'
Read token at ../src/test_parser.nit:29,18--22 text='_rank'
Read token at ../src/test_parser.nit:29,23 text=','
Read token at ../src/test_parser.nit:29,25 text='n'
Read token at ../src/test_parser.nit:29,26 text='.'
Read token at ../src/test_parser.nit:29,27--30 text='to_s'
Read token at ../src/test_parser.nit:29,31 text=','
Read token at ../src/test_parser.nit:29,33--39 text='" ... "'
Read token at ../src/test_parser.nit:29,40 text=','
Read token at ../src/test_parser.nit:29,42 text='n'
Read token at ../src/test_parser.nit:29,43 text='.'
Read token at ../src/test_parser.nit:29,44--51 text='location'
Read token at ../src/test_parser.nit:29,52 text=','
Read token at ../src/test_parser.nit:29,54--57 text='"\n"'
Read token at ../src/test_parser.nit:29,58 text=')'
Read token at ../src/test_parser.nit:29,59--30,0 text='
'
Read token at ../src/test_parser.nit:30,3--6 text='else'
Read token at ../src/test_parser.nit:30,7--31,0 text='
'
Read token at ../src/test_parser.nit:31,4--9 text='printn'
Read token at ../src/test_parser.nit:31,10 text='('
Read token at ../src/test_parser.nit:31,11--14 text='"  "'
Read token at ../src/test_parser.nit:31,16 text='*'
Read token at ../src/test_parser.nit:31,18--22 text='_rank'
Read token at ../src/test_parser.nit:31,23 text=','
Read token at ../src/test_parser.nit:31,25 text='n'
Read token at ../src/test_parser.nit:31,26 text='.'
Read token at ../src/test_parser.nit:31,27--34 text='location'
Read token at ../src/test_parser.nit:31,35 text=','
Read token at ../src/test_parser.nit:31,37--40 text='"\n"'
Read token at ../src/test_parser.nit:31,41 text=')'
Read token at ../src/test_parser.nit:31,42--32,0 text='
'
Read token at ../src/test_parser.nit:32,3--5 text='end'
Read token at ../src/test_parser.nit:32,6--33,0 text='
'
Read token at ../src/test_parser.nit:33,3--7 text='_rank'
Read token at ../src/test_parser.nit:33,9 text='='
Read token at ../src/test_parser.nit:33,11--15 text='_rank'
Read token at ../src/test_parser.nit:33,17 text='+'
Read token at ../src/test_parser.nit:33,19 text='1'
Read token at ../src/test_parser.nit:33,20--34,0 text='
'
Read token at ../src/test_parser.nit:34,3 text='n'
Read token at ../src/test_parser.nit:34,4 text='.'
Read token at ../src/test_parser.nit:34,5--13 text='visit_all'
Read token at ../src/test_parser.nit:34,14 text='('
Read token at ../src/test_parser.nit:34,15--18 text='self'
Read token at ../src/test_parser.nit:34,19 text=')'
Read token at ../src/test_parser.nit:34,20--35,0 text='
'
Read token at ../src/test_parser.nit:35,3--7 text='_rank'
Read token at ../src/test_parser.nit:35,9 text='='
Read token at ../src/test_parser.nit:35,11--15 text='_rank'
Read token at ../src/test_parser.nit:35,17 text='-'
Read token at ../src/test_parser.nit:35,19 text='1'
Read token at ../src/test_parser.nit:35,20--36,0 text='
'
Read token at ../src/test_parser.nit:36,2--4 text='end'
Read token at ../src/test_parser.nit:36,5--37,0 text='
'
Read token at ../src/test_parser.nit:37,1--38,0 text='
'
Read token at ../src/test_parser.nit:38,2--5 text='init'
Read token at ../src/test_parser.nit:38,6--39,0 text='
'
Read token at ../src/test_parser.nit:39,2--3 text='do'
Read token at ../src/test_parser.nit:39,4--40,0 text='
'
Read token at ../src/test_parser.nit:40,3--7 text='_rank'
Read token at ../src/test_parser.nit:40,9 text='='
Read token at ../src/test_parser.nit:40,11 text='0'
Read token at ../src/test_parser.nit:40,12--41,0 text='
'
Read token at ../src/test_parser.nit:41,2--4 text='end'
Read token at ../src/test_parser.nit:41,5--42,0 text='
'
Read token at ../src/test_parser.nit:42,1--3 text='end'
Read token at ../src/test_parser.nit:42,4--43,0 text='
'
Read token at ../src/test_parser.nit:43,1--44,0 text='
'
Read token at ../src/test_parser.nit:44,1--3 text='var'
Read token at ../src/test_parser.nit:44,5--12 text='no_print'
Read token at ../src/test_parser.nit:44,14 text='='
Read token at ../src/test_parser.nit:44,16--20 text='false'
Read token at ../src/test_parser.nit:44,21--45,0 text='
'
Read token at ../src/test_parser.nit:45,1--3 text='var'
Read token at ../src/test_parser.nit:45,5--14 text='only_lexer'
Read token at ../src/test_parser.nit:45,16 text='='
Read token at ../src/test_parser.nit:45,18--22 text='false'
Read token at ../src/test_parser.nit:45,23--46,0 text='
'
Read token at ../src/test_parser.nit:46,1--3 text='var'
Read token at ../src/test_parser.nit:46,5--13 text='need_help'
Read token at ../src/test_parser.nit:46,15 text='='
Read token at ../src/test_parser.nit:46,17--21 text='false'
Read token at ../src/test_parser.nit:46,22--47,0 text='
'
Read token at ../src/test_parser.nit:47,1--3 text='var'
Read token at ../src/test_parser.nit:47,5--11 text='no_file'
Read token at ../src/test_parser.nit:47,13 text='='
Read token at ../src/test_parser.nit:47,15--19 text='false'
Read token at ../src/test_parser.nit:47,20--48,0 text='
'
Read token at ../src/test_parser.nit:48,1--49,0 text='
'
Read token at ../src/test_parser.nit:49,1--5 text='while'
Read token at ../src/test_parser.nit:49,7--9 text='not'
Read token at ../src/test_parser.nit:49,11--14 text='args'
Read token at ../src/test_parser.nit:49,15 text='.'
Read token at ../src/test_parser.nit:49,16--23 text='is_empty'
Read token at ../src/test_parser.nit:49,25--27 text='and'
Read token at ../src/test_parser.nit:49,29--32 text='args'
Read token at ../src/test_parser.nit:49,33 text='.'
Read token at ../src/test_parser.nit:49,34--38 text='first'
Read token at ../src/test_parser.nit:49,39 text='.'
Read token at ../src/test_parser.nit:49,40--44 text='first'
Read token at ../src/test_parser.nit:49,46--47 text='=='
Read token at ../src/test_parser.nit:49,49--51 text=''-''
Read token at ../src/test_parser.nit:49,53--54 text='do'
Read token at ../src/test_parser.nit:49,55--50,0 text='
'
Read token at ../src/test_parser.nit:50,2--3 text='if'
Read token at ../src/test_parser.nit:50,5--8 text='args'
Read token at ../src/test_parser.nit:50,9 text='.'
Read token at ../src/test_parser.nit:50,10--14 text='first'
Read token at ../src/test_parser.nit:50,16--17 text='=='
Read token at ../src/test_parser.nit:50,19--22 text='"-n"'
Read token at ../src/test_parser.nit:50,24--27 text='then'
Read token at ../src/test_parser.nit:50,28--51,0 text='
'
Read token at ../src/test_parser.nit:51,3--10 text='no_print'
Read token at ../src/test_parser.nit:51,12 text='='
Read token at ../src/test_parser.nit:51,14--17 text='true'
Read token at ../src/test_parser.nit:51,18--52,0 text='
'
Read token at ../src/test_parser.nit:52,2--5 text='else'
Read token at ../src/test_parser.nit:52,7--8 text='if'
Read token at ../src/test_parser.nit:52,10--13 text='args'
Read token at ../src/test_parser.nit:52,14 text='.'
Read token at ../src/test_parser.nit:52,15--19 text='first'
Read token at ../src/test_parser.nit:52,21--22 text='=='
Read token at ../src/test_parser.nit:52,24--27 text='"-l"'
Read token at ../src/test_parser.nit:52,29--32 text='then'
Read token at ../src/test_parser.nit:52,33--53,0 text='
'
Read token at ../src/test_parser.nit:53,3--12 text='only_lexer'
Read token at ../src/test_parser.nit:53,14 text='='
Read token at ../src/test_parser.nit:53,16--19 text='true'
Read token at ../src/test_parser.nit:53,20--54,0 text='
'
Read token at ../src/test_parser.nit:54,2--5 text='else'
Read token at ../src/test_parser.nit:54,7--8 text='if'
Read token at ../src/test_parser.nit:54,10--13 text='args'
Read token at ../src/test_parser.nit:54,14 text='.'
Read token at ../src/test_parser.nit:54,15--19 text='first'
Read token at ../src/test_parser.nit:54,21--22 text='=='
Read token at ../src/test_parser.nit:54,24--27 text='"-p"'
Read token at ../src/test_parser.nit:54,29--32 text='then'
Read token at ../src/test_parser.nit:54,33--55,0 text='
'
Read token at ../src/test_parser.nit:55,3--12 text='only_lexer'
Read token at ../src/test_parser.nit:55,14 text='='
Read token at ../src/test_parser.nit:55,16--20 text='false'
Read token at ../src/test_parser.nit:55,21--56,0 text='
'
Read token at ../src/test_parser.nit:56,2--5 text='else'
Read token at ../src/test_parser.nit:56,7--8 text='if'
Read token at ../src/test_parser.nit:56,10--13 text='args'
Read token at ../src/test_parser.nit:56,14 text='.'
Read token at ../src/test_parser.nit:56,15--19 text='first'
Read token at ../src/test_parser.nit:56,21--22 text='=='
Read token at ../src/test_parser.nit:56,24--27 text='"-e"'
Read token at ../src/test_parser.nit:56,29--32 text='then'
Read token at ../src/test_parser.nit:56,33--57,0 text='
'
Read token at ../src/test_parser.nit:57,3--9 text='no_file'
Read token at ../src/test_parser.nit:57,11 text='='
Read token at ../src/test_parser.nit:57,13--16 text='true'
Read token at ../src/test_parser.nit:57,17--58,0 text='
'
Read token at ../src/test_parser.nit:58,2--5 text='else'
Read token at ../src/test_parser.nit:58,7--8 text='if'
Read token at ../src/test_parser.nit:58,10--13 text='args'
Read token at ../src/test_parser.nit:58,14 text='.'
Read token at ../src/test_parser.nit:58,15--19 text='first'
Read token at ../src/test_parser.nit:58,21--22 text='=='
Read token at ../src/test_parser.nit:58,24--27 text='"-h"'
Read token at ../src/test_parser.nit:58,29--30 text='or'
Read token at ../src/test_parser.nit:58,32--35 text='args'
Read token at ../src/test_parser.nit:58,36 text='.'
Read token at ../src/test_parser.nit:58,37--41 text='first'
Read token at ../src/test_parser.nit:58,43--44 text='=='
Read token at ../src/test_parser.nit:58,46--49 text='"-?"'
Read token at ../src/test_parser.nit:58,51--54 text='then'
Read token at ../src/test_parser.nit:58,55--59,0 text='
'
Read token at ../src/test_parser.nit:59,3--11 text='need_help'
Read token at ../src/test_parser.nit:59,13 text='='
Read token at ../src/test_parser.nit:59,15--18 text='true'
Read token at ../src/test_parser.nit:59,19--60,0 text='
'
Read token at ../src/test_parser.nit:60,2--5 text='else'
Read token at ../src/test_parser.nit:60,6--61,0 text='
'
Read token at ../src/test_parser.nit:61,3--8 text='stderr'
Read token at ../src/test_parser.nit:61,9 text='.'
Read token at ../src/test_parser.nit:61,10--14 text='write'
Read token at ../src/test_parser.nit:61,15 text='('
Read token at ../src/test_parser.nit:61,16--32 text='"Unknown option {'
Read token at ../src/test_parser.nit:61,33--36 text='args'
Read token at ../src/test_parser.nit:61,37 text='.'
Read token at ../src/test_parser.nit:61,38--42 text='first'
Read token at ../src/test_parser.nit:61,43--47 text='}.\n"'
Read token at ../src/test_parser.nit:61,48 text=')'
Read token at ../src/test_parser.nit:61,49--62,0 text='
'
Read token at ../src/test_parser.nit:62,3--6 text='exit'
Read token at ../src/test_parser.nit:62,7 text='('
Read token at ../src/test_parser.nit:62,8 text='0'
Read token at ../src/test_parser.nit:62,9 text=')'
Read token at ../src/test_parser.nit:62,10--63,0 text='
'
Read token at ../src/test_parser.nit:63,2--4 text='end'
Read token at ../src/test_parser.nit:63,5--64,0 text='
'
Read token at ../src/test_parser.nit:64,2--5 text='args'
Read token at ../src/test_parser.nit:64,6 text='.'
Read token at ../src/test_parser.nit:64,7--11 text='shift'
Read token at ../src/test_parser.nit:64,12--65,0 text='
'
Read token at ../src/test_parser.nit:65,1--3 text='end'
Read token at ../src/test_parser.nit:65,4--66,0 text='
'
Read token at ../src/test_parser.nit:66,1--67,0 text='
'
Read token at ../src/test_parser.nit:67,1--2 text='if'
Read token at ../src/test_parser.nit:67,4--7 text='args'
Read token at ../src/test_parser.nit:67,8 text='.'
Read token at ../src/test_parser.nit:67,9--16 text='is_empty'
Read token at ../src/test_parser.nit:67,18--19 text='or'
Read token at ../src/test_parser.nit:67,21--29 text='need_help'
Read token at ../src/test_parser.nit:67,31--34 text='then'
Read token at ../src/test_parser.nit:67,35--68,0 text='
'
Read token at ../src/test_parser.nit:68,2--6 text='print'
Read token at ../src/test_parser.nit:68,7 text='('
Read token at ../src/test_parser.nit:68,8--15 text='"usage:"'
Read token at ../src/test_parser.nit:68,16 text=')'
Read token at ../src/test_parser.nit:68,17--69,0 text='
'
Read token at ../src/test_parser.nit:69,2--6 text='print'
Read token at ../src/test_parser.nit:69,7 text='('
Read token at ../src/test_parser.nit:69,8--53 text='"  test_parser [options]... <filename.nit>..."'
Read token at ../src/test_parser.nit:69,54 text=')'
Read token at ../src/test_parser.nit:69,55--70,0 text='
'
Read token at ../src/test_parser.nit:70,2--6 text='print'
Read token at ../src/test_parser.nit:70,7 text='('
Read token at ../src/test_parser.nit:70,8--17 text='"options:"'
Read token at ../src/test_parser.nit:70,18 text=')'
Read token at ../src/test_parser.nit:70,19--71,0 text='
'
Read token at ../src/test_parser.nit:71,2--6 text='print'
Read token at ../src/test_parser.nit:71,7 text='('
Read token at ../src/test_parser.nit:71,8--35 text='"  -n	do not print anything"'
Read token at ../src/test_parser.nit:71,36 text=')'
Read token at ../src/test_parser.nit:71,37--72,0 text='
'
Read token at ../src/test_parser.nit:72,2--6 text='print'
Read token at ../src/test_parser.nit:72,7 text='('
Read token at ../src/test_parser.nit:72,8--24 text='"  -l	only lexer"'
Read token at ../src/test_parser.nit:72,25 text=')'
Read token at ../src/test_parser.nit:72,26--73,0 text='
'
Read token at ../src/test_parser.nit:73,2--6 text='print'
Read token at ../src/test_parser.nit:73,7 text='('
Read token at ../src/test_parser.nit:73,8--40 text='"  -p	lexer and parser (default)"'
Read token at ../src/test_parser.nit:73,41 text=')'
Read token at ../src/test_parser.nit:73,42--74,0 text='
'
Read token at ../src/test_parser.nit:74,2--6 text='print'
Read token at ../src/test_parser.nit:74,7 text='('
Read token at ../src/test_parser.nit:74,8--67 text='"  -e	instead on files, each argument is a content to parse"'
Read token at ../src/test_parser.nit:74,68 text=')'
Read token at ../src/test_parser.nit:74,69--75,0 text='
'
Read token at ../src/test_parser.nit:75,2--6 text='print'
Read token at ../src/test_parser.nit:75,7 text='('
Read token at ../src/test_parser.nit:75,8--29 text='"  -h	print this help"'
Read token at ../src/test_parser.nit:75,30 text=')'
Read token at ../src/test_parser.nit:75,31--76,0 text='
'
Read token at ../src/test_parser.nit:76,1--4 text='else'
Read token at ../src/test_parser.nit:76,5--77,0 text='
'
Read token at ../src/test_parser.nit:77,2--4 text='for'
Read token at ../src/test_parser.nit:77,6 text='a'
Read token at ../src/test_parser.nit:77,8--9 text='in'
Read token at ../src/test_parser.nit:77,11--14 text='args'
Read token at ../src/test_parser.nit:77,16--17 text='do'
Read token at ../src/test_parser.nit:77,18--78,0 text='
'
Read token at ../src/test_parser.nit:78,3--5 text='var'
Read token at ../src/test_parser.nit:78,7--12 text='source'
Read token at ../src/test_parser.nit:78,13--79,0 text='
'
Read token at ../src/test_parser.nit:79,3--4 text='if'
Read token at ../src/test_parser.nit:79,6--12 text='no_file'
Read token at ../src/test_parser.nit:79,14--17 text='then'
Read token at ../src/test_parser.nit:79,18--80,0 text='
'
Read token at ../src/test_parser.nit:80,4--9 text='source'
Read token at ../src/test_parser.nit:80,11 text='='
Read token at ../src/test_parser.nit:80,13--15 text='new'
Read token at ../src/test_parser.nit:80,17--26 text='SourceFile'
Read token at ../src/test_parser.nit:80,27 text='.'
Read token at ../src/test_parser.nit:80,28--38 text='from_string'
Read token at ../src/test_parser.nit:80,39 text='('
Read token at ../src/test_parser.nit:80,40--41 text='""'
Read token at ../src/test_parser.nit:80,42 text=','
Read token at ../src/test_parser.nit:80,44 text='a'
Read token at ../src/test_parser.nit:80,45 text=')'
Read token at ../src/test_parser.nit:80,46--81,0 text='
'
Read token at ../src/test_parser.nit:81,3--6 text='else'
Read token at ../src/test_parser.nit:81,7--82,0 text='
'
Read token at ../src/test_parser.nit:82,4--6 text='var'
Read token at ../src/test_parser.nit:82,8 text='f'
Read token at ../src/test_parser.nit:82,10 text='='
Read token at ../src/test_parser.nit:82,12--14 text='new'
Read token at ../src/test_parser.nit:82,16--23 text='IFStream'
Read token at ../src/test_parser.nit:82,24 text='.'
Read token at ../src/test_parser.nit:82,25--28 text='open'
Read token at ../src/test_parser.nit:82,29 text='('
Read token at ../src/test_parser.nit:82,30 text='a'
Read token at ../src/test_parser.nit:82,31 text=')'
Read token at ../src/test_parser.nit:82,32--83,0 text='
'
Read token at ../src/test_parser.nit:83,4--9 text='source'
Read token at ../src/test_parser.nit:83,11 text='='
Read token at ../src/test_parser.nit:83,13--15 text='new'
Read token at ../src/test_parser.nit:83,17--26 text='SourceFile'
Read token at ../src/test_parser.nit:83,27 text='('
Read token at ../src/test_parser.nit:83,28 text='a'
Read token at ../src/test_parser.nit:83,29 text=','
Read token at ../src/test_parser.nit:83,31 text='f'
Read token at ../src/test_parser.nit:83,32 text=')'
Read token at ../src/test_parser.nit:83,33--84,0 text='
'
Read token at ../src/test_parser.nit:84,4 text='f'
Read token at ../src/test_parser.nit:84,5 text='.'
Read token at ../src/test_parser.nit:84,6--10 text='close'
Read token at ../src/test_parser.nit:84,11--85,0 text='
'
Read token at ../src/test_parser.nit:85,3--5 text='end'
Read token at ../src/test_parser.nit:85,6--86,0 text='
'
Read token at ../src/test_parser.nit:86,3--5 text='var'
Read token at ../src/test_parser.nit:86,7--11 text='lexer'
Read token at ../src/test_parser.nit:86,13 text='='
Read token at ../src/test_parser.nit:86,15--17 text='new'
Read token at ../src/test_parser.nit:86,19--23 text='Lexer'
Read token at ../src/test_parser.nit:86,24 text='('
Read token at ../src/test_parser.nit:86,25--30 text='source'
Read token at ../src/test_parser.nit:86,31 text=')'
Read token at ../src/test_parser.nit:86,32--87,0 text='
'
Read token at ../src/test_parser.nit:87,3--4 text='if'
Read token at ../src/test_parser.nit:87,6--15 text='only_lexer'
Read token at ../src/test_parser.nit:87,17--20 text='then'
Read token at ../src/test_parser.nit:87,21--88,0 text='
'
Read token at ../src/test_parser.nit:88,4--6 text='var'
Read token at ../src/test_parser.nit:88,8--12 text='token'
Read token at ../src/test_parser.nit:88,14 text='='
Read token at ../src/test_parser.nit:88,16--20 text='lexer'
Read token at ../src/test_parser.nit:88,21 text='.'
Read token at ../src/test_parser.nit:88,22--25 text='next'
Read token at ../src/test_parser.nit:88,26--89,0 text='
'
Read token at ../src/test_parser.nit:89,4--8 text='while'
Read token at ../src/test_parser.nit:89,10--12 text='not'
Read token at ../src/test_parser.nit:89,14--18 text='token'
Read token at ../src/test_parser.nit:89,20--22 text='isa'
Read token at ../src/test_parser.nit:89,24--26 text='EOF'
Read token at ../src/test_parser.nit:89,28--29 text='do'
Read token at ../src/test_parser.nit:89,30--90,0 text='
'
Read token at ../src/test_parser.nit:90,5--6 text='if'
Read token at ../src/test_parser.nit:90,8--10 text='not'
Read token at ../src/test_parser.nit:90,12--19 text='no_print'
Read token at ../src/test_parser.nit:90,21--24 text='then'
Read token at ../src/test_parser.nit:90,25--91,0 text='
'
Read token at ../src/test_parser.nit:91,6--10 text='print'
Read token at ../src/test_parser.nit:91,11 text='('
Read token at ../src/test_parser.nit:91,12--27 text='"Read token at {'
Read token at ../src/test_parser.nit:91,28--32 text='token'
Read token at ../src/test_parser.nit:91,33 text='.'
Read token at ../src/test_parser.nit:91,34--41 text='location'
Read token at ../src/test_parser.nit:91,42--50 text='} text='{'
Read token at ../src/test_parser.nit:91,51--55 text='token'
Read token at ../src/test_parser.nit:91,56 text='.'
Read token at ../src/test_parser.nit:91,57--60 text='text'
Read token at ../src/test_parser.nit:91,61--63 text='}'"'
Read token at ../src/test_parser.nit:91,64 text=')'
Read token at ../src/test_parser.nit:91,65--92,0 text='
'
Read token at ../src/test_parser.nit:92,5--7 text='end'
Read token at ../src/test_parser.nit:92,8--93,0 text='
'
Read token at ../src/test_parser.nit:93,5--9 text='token'
Read token at ../src/test_parser.nit:93,11 text='='
Read token at ../src/test_parser.nit:93,13--17 text='lexer'
Read token at ../src/test_parser.nit:93,18 text='.'
Read token at ../src/test_parser.nit:93,19--22 text='next'
Read token at ../src/test_parser.nit:93,23--94,0 text='
'
Read token at ../src/test_parser.nit:94,4--6 text='end'
Read token at ../src/test_parser.nit:94,7--95,0 text='
'
Read token at ../src/test_parser.nit:95,3--6 text='else'
Read token at ../src/test_parser.nit:95,7--96,0 text='
'
Read token at ../src/test_parser.nit:96,4--6 text='var'
Read token at ../src/test_parser.nit:96,8--13 text='parser'
Read token at ../src/test_parser.nit:96,15 text='='
Read token at ../src/test_parser.nit:96,17--19 text='new'
Read token at ../src/test_parser.nit:96,21--26 text='Parser'
Read token at ../src/test_parser.nit:96,27 text='('
Read token at ../src/test_parser.nit:96,28--32 text='lexer'
Read token at ../src/test_parser.nit:96,33 text=')'
Read token at ../src/test_parser.nit:96,34--97,0 text='
'
Read token at ../src/test_parser.nit:97,4--6 text='var'
Read token at ../src/test_parser.nit:97,8--11 text='tree'
Read token at ../src/test_parser.nit:97,13 text='='
Read token at ../src/test_parser.nit:97,15--20 text='parser'
Read token at ../src/test_parser.nit:97,21 text='.'
Read token at ../src/test_parser.nit:97,22--26 text='parse'
Read token at ../src/test_parser.nit:97,27--98,0 text='
'
Read token at ../src/test_parser.nit:98,1--99,0 text='
'
Read token at ../src/test_parser.nit:99,4--6 text='var'
Read token at ../src/test_parser.nit:99,8--12 text='error'
Read token at ../src/test_parser.nit:99,14 text='='
Read token at ../src/test_parser.nit:99,16--19 text='tree'
Read token at ../src/test_parser.nit:99,20 text='.'
Read token at ../src/test_parser.nit:99,21--25 text='n_eof'
Read token at ../src/test_parser.nit:99,26--100,0 text='
'
Read token at ../src/test_parser.nit:100,4--5 text='if'
Read token at ../src/test_parser.nit:100,7--11 text='error'
Read token at ../src/test_parser.nit:100,13--15 text='isa'
Read token at ../src/test_parser.nit:100,17--22 text='AError'
Read token at ../src/test_parser.nit:100,24--27 text='then'
Read token at ../src/test_parser.nit:100,28--101,0 text='
'
Read token at ../src/test_parser.nit:101,5--9 text='print'
Read token at ../src/test_parser.nit:101,10 text='('
Read token at ../src/test_parser.nit:101,11--21 text='"Error at {'
Read token at ../src/test_parser.nit:101,22--26 text='error'
Read token at ../src/test_parser.nit:101,27 text='.'
Read token at ../src/test_parser.nit:101,28--35 text='location'
Read token at ../src/test_parser.nit:101,36--42 text='}:\n\t{'
Read token at ../src/test_parser.nit:101,43--47 text='error'
Read token at ../src/test_parser.nit:101,48 text='.'
Read token at ../src/test_parser.nit:101,49--55 text='message'
Read token at ../src/test_parser.nit:101,56--57 text='}"'
Read token at ../src/test_parser.nit:101,58 text=')'
Read token at ../src/test_parser.nit:101,59--102,0 text='
'
Read token at ../src/test_parser.nit:102,5--10 text='return'
Read token at ../src/test_parser.nit:102,11--103,0 text='
'
Read token at ../src/test_parser.nit:103,4--6 text='end'
Read token at ../src/test_parser.nit:103,7--104,0 text='
'
Read token at ../src/test_parser.nit:104,1--105,0 text='
'
Read token at ../src/test_parser.nit:105,4--5 text='if'
Read token at ../src/test_parser.nit:105,7--9 text='not'
Read token at ../src/test_parser.nit:105,11--18 text='no_print'
Read token at ../src/test_parser.nit:105,20--23 text='then'
Read token at ../src/test_parser.nit:105,24--106,0 text='
'
Read token at ../src/test_parser.nit:106,5 text='('
Read token at ../src/test_parser.nit:106,6--8 text='new'
Read token at ../src/test_parser.nit:106,10--25 text='PrintTreeVisitor'
Read token at ../src/test_parser.nit:106,26 text=')'
Read token at ../src/test_parser.nit:106,27 text='.'
Read token at ../src/test_parser.nit:106,28--38 text='enter_visit'
Read token at ../src/test_parser.nit:106,39 text='('
Read token at ../src/test_parser.nit:106,40--43 text='tree'
Read token at ../src/test_parser.nit:106,44 text=')'
Read token at ../src/test_parser.nit:106,45--107,0 text='
'
Read token at ../src/test_parser.nit:107,4--6 text='end'
Read token at ../src/test_parser.nit:107,7--108,0 text='
'
Read token at ../src/test_parser.nit:108,3--5 text='end'
Read token at ../src/test_parser.nit:108,6--109,0 text='
'
Read token at ../src/test_parser.nit:109,2--4 text='end'
Read token at ../src/test_parser.nit:109,5--110,0 text='
'
Read token at ../src/test_parser.nit:110,1--3 text='end'
Read token at ../src/test_parser.nit:110,4--111,0 text='
'
