Read token at ../src/test_parser.nit:1,1--2,0 text='# This file is part of NIT ( http://www.nitlanguage.org ).
'
Read token at ../src/test_parser.nit:2,1--3,0 text='#
'
Read token at ../src/test_parser.nit:3,1--4,0 text='# Copyright 2008 Jean Privat <jean@pryen.org>
'
Read token at ../src/test_parser.nit:4,1--5,0 text='#
'
Read token at ../src/test_parser.nit:5,1--6,0 text='# Licensed under the Apache License, Version 2.0 (the "License");
'
Read token at ../src/test_parser.nit:6,1--7,0 text='# you may not use this file except in compliance with the License.
'
Read token at ../src/test_parser.nit:7,1--8,0 text='# You may obtain a copy of the License at
'
Read token at ../src/test_parser.nit:8,1--9,0 text='#
'
Read token at ../src/test_parser.nit:9,1--10,0 text='#     http://www.apache.org/licenses/LICENSE-2.0
'
Read token at ../src/test_parser.nit:10,1--11,0 text='#
'
Read token at ../src/test_parser.nit:11,1--12,0 text='# Unless required by applicable law or agreed to in writing, software
'
Read token at ../src/test_parser.nit:12,1--13,0 text='# distributed under the License is distributed on an "AS IS" BASIS,
'
Read token at ../src/test_parser.nit:13,1--14,0 text='# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
'
Read token at ../src/test_parser.nit:14,1--15,0 text='# See the License for the specific language governing permissions and
'
Read token at ../src/test_parser.nit:15,1--16,0 text='# limitations under the License.
'
Read token at ../src/test_parser.nit:16,1--17,0 text='
'
Read token at ../src/test_parser.nit:17,1--18,0 text='# Program used to test the NIT parser
'
Read token at ../src/test_parser.nit:18,1--6 text='module'
Read token at ../src/test_parser.nit:18,8--18 text='test_parser'
Read token at ../src/test_parser.nit:18,19--19,0 text='
'
Read token at ../src/test_parser.nit:19,1--20,0 text='
'
Read token at ../src/test_parser.nit:20,1--6 text='import'
Read token at ../src/test_parser.nit:20,8--13 text='parser'
Read token at ../src/test_parser.nit:20,14--21,0 text='
'
Read token at ../src/test_parser.nit:21,1--6 text='import'
Read token at ../src/test_parser.nit:21,8--18 text='parser_util'
Read token at ../src/test_parser.nit:21,19--22,0 text='
'
Read token at ../src/test_parser.nit:22,1--6 text='import'
Read token at ../src/test_parser.nit:22,8--14 text='astutil'
Read token at ../src/test_parser.nit:22,15--23,0 text='
'
Read token at ../src/test_parser.nit:23,1--24,0 text='
'
Read token at ../src/test_parser.nit:24,1--25,0 text='# A basic visitor that prints AST trees to the screen
'
Read token at ../src/test_parser.nit:25,1--5 text='class'
Read token at ../src/test_parser.nit:25,7--22 text='PrintTreeVisitor'
Read token at ../src/test_parser.nit:25,23--26,0 text='
'
Read token at ../src/test_parser.nit:26,2--6 text='super'
Read token at ../src/test_parser.nit:26,8--14 text='Visitor'
Read token at ../src/test_parser.nit:26,15--27,0 text='
'
Read token at ../src/test_parser.nit:27,2--8 text='private'
Read token at ../src/test_parser.nit:27,10--12 text='var'
Read token at ../src/test_parser.nit:27,14--17 text='rank'
Read token at ../src/test_parser.nit:27,18 text=':'
Read token at ../src/test_parser.nit:27,20--22 text='Int'
Read token at ../src/test_parser.nit:27,24 text='='
Read token at ../src/test_parser.nit:27,26 text='0'
Read token at ../src/test_parser.nit:27,27--28,0 text='
'
Read token at ../src/test_parser.nit:28,2--6 text='redef'
Read token at ../src/test_parser.nit:28,8--10 text='fun'
Read token at ../src/test_parser.nit:28,12--16 text='visit'
Read token at ../src/test_parser.nit:28,17 text='('
Read token at ../src/test_parser.nit:28,18 text='n'
Read token at ../src/test_parser.nit:28,19 text=')'
Read token at ../src/test_parser.nit:28,20--29,0 text='
'
Read token at ../src/test_parser.nit:29,2--3 text='do'
Read token at ../src/test_parser.nit:29,4--30,0 text='
'
Read token at ../src/test_parser.nit:30,3--4 text='if'
Read token at ../src/test_parser.nit:30,6 text='n'
Read token at ../src/test_parser.nit:30,8--10 text='isa'
Read token at ../src/test_parser.nit:30,12--16 text='Token'
Read token at ../src/test_parser.nit:30,18--21 text='then'
Read token at ../src/test_parser.nit:30,22--31,0 text='
'
Read token at ../src/test_parser.nit:31,4--9 text='printn'
Read token at ../src/test_parser.nit:31,10 text='('
Read token at ../src/test_parser.nit:31,11--14 text='"  "'
Read token at ../src/test_parser.nit:31,16 text='*'
Read token at ../src/test_parser.nit:31,18--21 text='rank'
Read token at ../src/test_parser.nit:31,22 text=','
Read token at ../src/test_parser.nit:31,24 text='n'
Read token at ../src/test_parser.nit:31,25 text='.'
Read token at ../src/test_parser.nit:31,26--35 text='class_name'
Read token at ../src/test_parser.nit:31,36 text=','
Read token at ../src/test_parser.nit:31,38--42 text='" \""'
Read token at ../src/test_parser.nit:31,43 text=','
Read token at ../src/test_parser.nit:31,45 text='n'
Read token at ../src/test_parser.nit:31,46 text='.'
Read token at ../src/test_parser.nit:31,47--50 text='text'
Read token at ../src/test_parser.nit:31,51 text='.'
Read token at ../src/test_parser.nit:31,52--62 text='escape_to_c'
Read token at ../src/test_parser.nit:31,63 text=','
Read token at ../src/test_parser.nit:31,65--69 text='"\" "'
Read token at ../src/test_parser.nit:31,70 text=','
Read token at ../src/test_parser.nit:31,72 text='n'
Read token at ../src/test_parser.nit:31,73 text='.'
Read token at ../src/test_parser.nit:31,74--81 text='location'
Read token at ../src/test_parser.nit:31,82 text=','
Read token at ../src/test_parser.nit:31,84--87 text='"\n"'
Read token at ../src/test_parser.nit:31,88 text=')'
Read token at ../src/test_parser.nit:31,89--32,0 text='
'
Read token at ../src/test_parser.nit:32,3--6 text='else'
Read token at ../src/test_parser.nit:32,7--33,0 text='
'
Read token at ../src/test_parser.nit:33,4--9 text='printn'
Read token at ../src/test_parser.nit:33,10 text='('
Read token at ../src/test_parser.nit:33,11--14 text='"  "'
Read token at ../src/test_parser.nit:33,16 text='*'
Read token at ../src/test_parser.nit:33,18--21 text='rank'
Read token at ../src/test_parser.nit:33,22 text=','
Read token at ../src/test_parser.nit:33,24 text='n'
Read token at ../src/test_parser.nit:33,25 text='.'
Read token at ../src/test_parser.nit:33,26--35 text='class_name'
Read token at ../src/test_parser.nit:33,36 text=','
Read token at ../src/test_parser.nit:33,38--40 text='" "'
Read token at ../src/test_parser.nit:33,41 text=','
Read token at ../src/test_parser.nit:33,43 text='n'
Read token at ../src/test_parser.nit:33,44 text='.'
Read token at ../src/test_parser.nit:33,45--52 text='location'
Read token at ../src/test_parser.nit:33,53 text=','
Read token at ../src/test_parser.nit:33,55--58 text='"\n"'
Read token at ../src/test_parser.nit:33,59 text=')'
Read token at ../src/test_parser.nit:33,60--34,0 text='
'
Read token at ../src/test_parser.nit:34,3--5 text='end'
Read token at ../src/test_parser.nit:34,6--35,0 text='
'
Read token at ../src/test_parser.nit:35,3--6 text='rank'
Read token at ../src/test_parser.nit:35,8 text='='
Read token at ../src/test_parser.nit:35,10--13 text='rank'
Read token at ../src/test_parser.nit:35,15 text='+'
Read token at ../src/test_parser.nit:35,17 text='1'
Read token at ../src/test_parser.nit:35,18--36,0 text='
'
Read token at ../src/test_parser.nit:36,3 text='n'
Read token at ../src/test_parser.nit:36,4 text='.'
Read token at ../src/test_parser.nit:36,5--13 text='visit_all'
Read token at ../src/test_parser.nit:36,14 text='('
Read token at ../src/test_parser.nit:36,15--18 text='self'
Read token at ../src/test_parser.nit:36,19 text=')'
Read token at ../src/test_parser.nit:36,20--37,0 text='
'
Read token at ../src/test_parser.nit:37,3--6 text='rank'
Read token at ../src/test_parser.nit:37,8 text='='
Read token at ../src/test_parser.nit:37,10--13 text='rank'
Read token at ../src/test_parser.nit:37,15 text='-'
Read token at ../src/test_parser.nit:37,17 text='1'
Read token at ../src/test_parser.nit:37,18--38,0 text='
'
Read token at ../src/test_parser.nit:38,2--4 text='end'
Read token at ../src/test_parser.nit:38,5--39,0 text='
'
Read token at ../src/test_parser.nit:39,1--3 text='end'
Read token at ../src/test_parser.nit:39,4--40,0 text='
'
Read token at ../src/test_parser.nit:40,1--41,0 text='
'
Read token at ../src/test_parser.nit:41,1--3 text='var'
Read token at ../src/test_parser.nit:41,5--12 text='no_print'
Read token at ../src/test_parser.nit:41,14 text='='
Read token at ../src/test_parser.nit:41,16--20 text='false'
Read token at ../src/test_parser.nit:41,21--42,0 text='
'
Read token at ../src/test_parser.nit:42,1--3 text='var'
Read token at ../src/test_parser.nit:42,5--14 text='only_lexer'
Read token at ../src/test_parser.nit:42,16 text='='
Read token at ../src/test_parser.nit:42,18--22 text='false'
Read token at ../src/test_parser.nit:42,23--43,0 text='
'
Read token at ../src/test_parser.nit:43,1--3 text='var'
Read token at ../src/test_parser.nit:43,5--13 text='need_help'
Read token at ../src/test_parser.nit:43,15 text='='
Read token at ../src/test_parser.nit:43,17--21 text='false'
Read token at ../src/test_parser.nit:43,22--44,0 text='
'
Read token at ../src/test_parser.nit:44,1--3 text='var'
Read token at ../src/test_parser.nit:44,5--11 text='no_file'
Read token at ../src/test_parser.nit:44,13 text='='
Read token at ../src/test_parser.nit:44,15--19 text='false'
Read token at ../src/test_parser.nit:44,20--45,0 text='
'
Read token at ../src/test_parser.nit:45,1--3 text='var'
Read token at ../src/test_parser.nit:45,5--15 text='interactive'
Read token at ../src/test_parser.nit:45,17 text='='
Read token at ../src/test_parser.nit:45,19--23 text='false'
Read token at ../src/test_parser.nit:45,24--46,0 text='
'
Read token at ../src/test_parser.nit:46,1--3 text='var'
Read token at ../src/test_parser.nit:46,5--7 text='xml'
Read token at ../src/test_parser.nit:46,9 text='='
Read token at ../src/test_parser.nit:46,11--15 text='false'
Read token at ../src/test_parser.nit:46,16--47,0 text='
'
Read token at ../src/test_parser.nit:47,1--48,0 text='
'
Read token at ../src/test_parser.nit:48,1--5 text='while'
Read token at ../src/test_parser.nit:48,7--9 text='not'
Read token at ../src/test_parser.nit:48,11--14 text='args'
Read token at ../src/test_parser.nit:48,15 text='.'
Read token at ../src/test_parser.nit:48,16--23 text='is_empty'
Read token at ../src/test_parser.nit:48,25--27 text='and'
Read token at ../src/test_parser.nit:48,29--32 text='args'
Read token at ../src/test_parser.nit:48,33 text='.'
Read token at ../src/test_parser.nit:48,34--38 text='first'
Read token at ../src/test_parser.nit:48,39 text='.'
Read token at ../src/test_parser.nit:48,40--44 text='chars'
Read token at ../src/test_parser.nit:48,45 text='.'
Read token at ../src/test_parser.nit:48,46--50 text='first'
Read token at ../src/test_parser.nit:48,52--53 text='=='
Read token at ../src/test_parser.nit:48,55--57 text=''-''
Read token at ../src/test_parser.nit:48,59--60 text='do'
Read token at ../src/test_parser.nit:48,61--49,0 text='
'
Read token at ../src/test_parser.nit:49,2--3 text='if'
Read token at ../src/test_parser.nit:49,5--8 text='args'
Read token at ../src/test_parser.nit:49,9 text='.'
Read token at ../src/test_parser.nit:49,10--14 text='first'
Read token at ../src/test_parser.nit:49,16--17 text='=='
Read token at ../src/test_parser.nit:49,19--22 text='"-n"'
Read token at ../src/test_parser.nit:49,24--27 text='then'
Read token at ../src/test_parser.nit:49,28--50,0 text='
'
Read token at ../src/test_parser.nit:50,3--10 text='no_print'
Read token at ../src/test_parser.nit:50,12 text='='
Read token at ../src/test_parser.nit:50,14--17 text='true'
Read token at ../src/test_parser.nit:50,18--51,0 text='
'
Read token at ../src/test_parser.nit:51,2--5 text='else'
Read token at ../src/test_parser.nit:51,7--8 text='if'
Read token at ../src/test_parser.nit:51,10--13 text='args'
Read token at ../src/test_parser.nit:51,14 text='.'
Read token at ../src/test_parser.nit:51,15--19 text='first'
Read token at ../src/test_parser.nit:51,21--22 text='=='
Read token at ../src/test_parser.nit:51,24--27 text='"-l"'
Read token at ../src/test_parser.nit:51,29--32 text='then'
Read token at ../src/test_parser.nit:51,33--52,0 text='
'
Read token at ../src/test_parser.nit:52,3--12 text='only_lexer'
Read token at ../src/test_parser.nit:52,14 text='='
Read token at ../src/test_parser.nit:52,16--19 text='true'
Read token at ../src/test_parser.nit:52,20--53,0 text='
'
Read token at ../src/test_parser.nit:53,2--5 text='else'
Read token at ../src/test_parser.nit:53,7--8 text='if'
Read token at ../src/test_parser.nit:53,10--13 text='args'
Read token at ../src/test_parser.nit:53,14 text='.'
Read token at ../src/test_parser.nit:53,15--19 text='first'
Read token at ../src/test_parser.nit:53,21--22 text='=='
Read token at ../src/test_parser.nit:53,24--27 text='"-p"'
Read token at ../src/test_parser.nit:53,29--32 text='then'
Read token at ../src/test_parser.nit:53,33--54,0 text='
'
Read token at ../src/test_parser.nit:54,3--12 text='only_lexer'
Read token at ../src/test_parser.nit:54,14 text='='
Read token at ../src/test_parser.nit:54,16--20 text='false'
Read token at ../src/test_parser.nit:54,21--55,0 text='
'
Read token at ../src/test_parser.nit:55,2--5 text='else'
Read token at ../src/test_parser.nit:55,7--8 text='if'
Read token at ../src/test_parser.nit:55,10--13 text='args'
Read token at ../src/test_parser.nit:55,14 text='.'
Read token at ../src/test_parser.nit:55,15--19 text='first'
Read token at ../src/test_parser.nit:55,21--22 text='=='
Read token at ../src/test_parser.nit:55,24--27 text='"-x"'
Read token at ../src/test_parser.nit:55,29--32 text='then'
Read token at ../src/test_parser.nit:55,33--56,0 text='
'
Read token at ../src/test_parser.nit:56,3--5 text='xml'
Read token at ../src/test_parser.nit:56,7 text='='
Read token at ../src/test_parser.nit:56,9--12 text='true'
Read token at ../src/test_parser.nit:56,13--57,0 text='
'
Read token at ../src/test_parser.nit:57,2--5 text='else'
Read token at ../src/test_parser.nit:57,7--8 text='if'
Read token at ../src/test_parser.nit:57,10--13 text='args'
Read token at ../src/test_parser.nit:57,14 text='.'
Read token at ../src/test_parser.nit:57,15--19 text='first'
Read token at ../src/test_parser.nit:57,21--22 text='=='
Read token at ../src/test_parser.nit:57,24--27 text='"-e"'
Read token at ../src/test_parser.nit:57,29--32 text='then'
Read token at ../src/test_parser.nit:57,33--58,0 text='
'
Read token at ../src/test_parser.nit:58,3--9 text='no_file'
Read token at ../src/test_parser.nit:58,11 text='='
Read token at ../src/test_parser.nit:58,13--16 text='true'
Read token at ../src/test_parser.nit:58,17--59,0 text='
'
Read token at ../src/test_parser.nit:59,2--5 text='else'
Read token at ../src/test_parser.nit:59,7--8 text='if'
Read token at ../src/test_parser.nit:59,10--13 text='args'
Read token at ../src/test_parser.nit:59,14 text='.'
Read token at ../src/test_parser.nit:59,15--19 text='first'
Read token at ../src/test_parser.nit:59,21--22 text='=='
Read token at ../src/test_parser.nit:59,24--27 text='"-i"'
Read token at ../src/test_parser.nit:59,29--32 text='then'
Read token at ../src/test_parser.nit:59,33--60,0 text='
'
Read token at ../src/test_parser.nit:60,3--13 text='interactive'
Read token at ../src/test_parser.nit:60,15 text='='
Read token at ../src/test_parser.nit:60,17--20 text='true'
Read token at ../src/test_parser.nit:60,21--61,0 text='
'
Read token at ../src/test_parser.nit:61,2--5 text='else'
Read token at ../src/test_parser.nit:61,7--8 text='if'
Read token at ../src/test_parser.nit:61,10--13 text='args'
Read token at ../src/test_parser.nit:61,14 text='.'
Read token at ../src/test_parser.nit:61,15--19 text='first'
Read token at ../src/test_parser.nit:61,21--22 text='=='
Read token at ../src/test_parser.nit:61,24--27 text='"-h"'
Read token at ../src/test_parser.nit:61,29--30 text='or'
Read token at ../src/test_parser.nit:61,32--35 text='args'
Read token at ../src/test_parser.nit:61,36 text='.'
Read token at ../src/test_parser.nit:61,37--41 text='first'
Read token at ../src/test_parser.nit:61,43--44 text='=='
Read token at ../src/test_parser.nit:61,46--49 text='"-?"'
Read token at ../src/test_parser.nit:61,51--54 text='then'
Read token at ../src/test_parser.nit:61,55--62,0 text='
'
Read token at ../src/test_parser.nit:62,3--11 text='need_help'
Read token at ../src/test_parser.nit:62,13 text='='
Read token at ../src/test_parser.nit:62,15--18 text='true'
Read token at ../src/test_parser.nit:62,19--63,0 text='
'
Read token at ../src/test_parser.nit:63,2--5 text='else'
Read token at ../src/test_parser.nit:63,6--64,0 text='
'
Read token at ../src/test_parser.nit:64,3--8 text='stderr'
Read token at ../src/test_parser.nit:64,9 text='.'
Read token at ../src/test_parser.nit:64,10--14 text='write'
Read token at ../src/test_parser.nit:64,15 text='('
Read token at ../src/test_parser.nit:64,16--32 text='"Unknown option {'
Read token at ../src/test_parser.nit:64,33--36 text='args'
Read token at ../src/test_parser.nit:64,37 text='.'
Read token at ../src/test_parser.nit:64,38--42 text='first'
Read token at ../src/test_parser.nit:64,43--47 text='}.\n"'
Read token at ../src/test_parser.nit:64,48 text=')'
Read token at ../src/test_parser.nit:64,49--65,0 text='
'
Read token at ../src/test_parser.nit:65,3--6 text='exit'
Read token at ../src/test_parser.nit:65,7 text='('
Read token at ../src/test_parser.nit:65,8 text='0'
Read token at ../src/test_parser.nit:65,9 text=')'
Read token at ../src/test_parser.nit:65,10--66,0 text='
'
Read token at ../src/test_parser.nit:66,2--4 text='end'
Read token at ../src/test_parser.nit:66,5--67,0 text='
'
Read token at ../src/test_parser.nit:67,2--5 text='args'
Read token at ../src/test_parser.nit:67,6 text='.'
Read token at ../src/test_parser.nit:67,7--11 text='shift'
Read token at ../src/test_parser.nit:67,12--68,0 text='
'
Read token at ../src/test_parser.nit:68,1--3 text='end'
Read token at ../src/test_parser.nit:68,4--69,0 text='
'
Read token at ../src/test_parser.nit:69,1--70,0 text='
'
Read token at ../src/test_parser.nit:70,1--2 text='if'
Read token at ../src/test_parser.nit:70,4 text='('
Read token at ../src/test_parser.nit:70,5--8 text='args'
Read token at ../src/test_parser.nit:70,9 text='.'
Read token at ../src/test_parser.nit:70,10--17 text='is_empty'
Read token at ../src/test_parser.nit:70,19--21 text='and'
Read token at ../src/test_parser.nit:70,23--25 text='not'
Read token at ../src/test_parser.nit:70,27--37 text='interactive'
Read token at ../src/test_parser.nit:70,38 text=')'
Read token at ../src/test_parser.nit:70,40--41 text='or'
Read token at ../src/test_parser.nit:70,43--51 text='need_help'
Read token at ../src/test_parser.nit:70,53--56 text='then'
Read token at ../src/test_parser.nit:70,57--71,0 text='
'
Read token at ../src/test_parser.nit:71,2--6 text='print'
Read token at ../src/test_parser.nit:71,7 text='('
Read token at ../src/test_parser.nit:71,8--15 text='"usage:"'
Read token at ../src/test_parser.nit:71,16 text=')'
Read token at ../src/test_parser.nit:71,17--72,0 text='
'
Read token at ../src/test_parser.nit:72,2--6 text='print'
Read token at ../src/test_parser.nit:72,7 text='('
Read token at ../src/test_parser.nit:72,8--53 text='"  test_parser [options]... <filename.nit>..."'
Read token at ../src/test_parser.nit:72,54 text=')'
Read token at ../src/test_parser.nit:72,55--73,0 text='
'
Read token at ../src/test_parser.nit:73,2--6 text='print'
Read token at ../src/test_parser.nit:73,7 text='('
Read token at ../src/test_parser.nit:73,8--48 text='"  test_parser -e [options]... <text>..."'
Read token at ../src/test_parser.nit:73,49 text=')'
Read token at ../src/test_parser.nit:73,50--74,0 text='
'
Read token at ../src/test_parser.nit:74,2--6 text='print'
Read token at ../src/test_parser.nit:74,7 text='('
Read token at ../src/test_parser.nit:74,8--38 text='"  test_parser -i [options]..."'
Read token at ../src/test_parser.nit:74,39 text=')'
Read token at ../src/test_parser.nit:74,40--75,0 text='
'
Read token at ../src/test_parser.nit:75,2--6 text='print'
Read token at ../src/test_parser.nit:75,7 text='('
Read token at ../src/test_parser.nit:75,8--17 text='"options:"'
Read token at ../src/test_parser.nit:75,18 text=')'
Read token at ../src/test_parser.nit:75,19--76,0 text='
'
Read token at ../src/test_parser.nit:76,2--6 text='print'
Read token at ../src/test_parser.nit:76,7 text='('
Read token at ../src/test_parser.nit:76,8--35 text='"  -n	do not print anything"'
Read token at ../src/test_parser.nit:76,36 text=')'
Read token at ../src/test_parser.nit:76,37--77,0 text='
'
Read token at ../src/test_parser.nit:77,2--6 text='print'
Read token at ../src/test_parser.nit:77,7 text='('
Read token at ../src/test_parser.nit:77,8--24 text='"  -l	only lexer"'
Read token at ../src/test_parser.nit:77,25 text=')'
Read token at ../src/test_parser.nit:77,26--78,0 text='
'
Read token at ../src/test_parser.nit:78,2--6 text='print'
Read token at ../src/test_parser.nit:78,7 text='('
Read token at ../src/test_parser.nit:78,8--40 text='"  -p	lexer and parser (default)"'
Read token at ../src/test_parser.nit:78,41 text=')'
Read token at ../src/test_parser.nit:78,42--79,0 text='
'
Read token at ../src/test_parser.nit:79,2--6 text='print'
Read token at ../src/test_parser.nit:79,7 text='('
Read token at ../src/test_parser.nit:79,8--60 text='"  -x	instead of a ascii tree, output a XML document"'
Read token at ../src/test_parser.nit:79,61 text=')'
Read token at ../src/test_parser.nit:79,62--80,0 text='
'
Read token at ../src/test_parser.nit:80,2--6 text='print'
Read token at ../src/test_parser.nit:80,7 text='('
Read token at ../src/test_parser.nit:80,8--67 text='"  -e	instead on files, each argument is a content to parse"'
Read token at ../src/test_parser.nit:80,68 text=')'
Read token at ../src/test_parser.nit:80,69--81,0 text='
'
Read token at ../src/test_parser.nit:81,2--6 text='print'
Read token at ../src/test_parser.nit:81,7 text='('
Read token at ../src/test_parser.nit:81,8--50 text='"  -i	tree to parse are read interactively"'
Read token at ../src/test_parser.nit:81,51 text=')'
Read token at ../src/test_parser.nit:81,52--82,0 text='
'
Read token at ../src/test_parser.nit:82,2--6 text='print'
Read token at ../src/test_parser.nit:82,7 text='('
Read token at ../src/test_parser.nit:82,8--29 text='"  -h	print this help"'
Read token at ../src/test_parser.nit:82,30 text=')'
Read token at ../src/test_parser.nit:82,31--83,0 text='
'
Read token at ../src/test_parser.nit:83,1--4 text='else'
Read token at ../src/test_parser.nit:83,6--7 text='if'
Read token at ../src/test_parser.nit:83,9--19 text='interactive'
Read token at ../src/test_parser.nit:83,21--24 text='then'
Read token at ../src/test_parser.nit:83,25--84,0 text='
'
Read token at ../src/test_parser.nit:84,2--3 text='if'
Read token at ../src/test_parser.nit:84,5--14 text='only_lexer'
Read token at ../src/test_parser.nit:84,16--19 text='then'
Read token at ../src/test_parser.nit:84,20--85,0 text='
'
Read token at ../src/test_parser.nit:85,3--7 text='print'
Read token at ../src/test_parser.nit:85,9--43 text='"Error: -l and -i are incompatible"'
Read token at ../src/test_parser.nit:85,44--86,0 text='
'
Read token at ../src/test_parser.nit:86,3--6 text='exit'
Read token at ../src/test_parser.nit:86,8 text='1'
Read token at ../src/test_parser.nit:86,9--87,0 text='
'
Read token at ../src/test_parser.nit:87,2--5 text='else'
Read token at ../src/test_parser.nit:87,7--8 text='if'
Read token at ../src/test_parser.nit:87,10--16 text='no_file'
Read token at ../src/test_parser.nit:87,18--21 text='then'
Read token at ../src/test_parser.nit:87,22--88,0 text='
'
Read token at ../src/test_parser.nit:88,3--7 text='print'
Read token at ../src/test_parser.nit:88,9--43 text='"Error: -e and -i are incompatible"'
Read token at ../src/test_parser.nit:88,44--89,0 text='
'
Read token at ../src/test_parser.nit:89,3--6 text='exit'
Read token at ../src/test_parser.nit:89,8 text='1'
Read token at ../src/test_parser.nit:89,9--90,0 text='
'
Read token at ../src/test_parser.nit:90,2--5 text='else'
Read token at ../src/test_parser.nit:90,7--8 text='if'
Read token at ../src/test_parser.nit:90,10--12 text='not'
Read token at ../src/test_parser.nit:90,14--17 text='args'
Read token at ../src/test_parser.nit:90,18 text='.'
Read token at ../src/test_parser.nit:90,19--26 text='is_empty'
Read token at ../src/test_parser.nit:90,28--31 text='then'
Read token at ../src/test_parser.nit:90,32--91,0 text='
'
Read token at ../src/test_parser.nit:91,3--7 text='print'
Read token at ../src/test_parser.nit:91,9--43 text='"Error: -i works without arguments"'
Read token at ../src/test_parser.nit:91,44--92,0 text='
'
Read token at ../src/test_parser.nit:92,3--6 text='exit'
Read token at ../src/test_parser.nit:92,8 text='1'
Read token at ../src/test_parser.nit:92,9--93,0 text='
'
Read token at ../src/test_parser.nit:93,2--4 text='end'
Read token at ../src/test_parser.nit:93,5--94,0 text='
'
Read token at ../src/test_parser.nit:94,1--95,0 text='
'
Read token at ../src/test_parser.nit:95,2--4 text='var'
Read token at ../src/test_parser.nit:95,6--7 text='tc'
Read token at ../src/test_parser.nit:95,9 text='='
Read token at ../src/test_parser.nit:95,11--13 text='new'
Read token at ../src/test_parser.nit:95,15--25 text='ToolContext'
Read token at ../src/test_parser.nit:95,26--96,0 text='
'
Read token at ../src/test_parser.nit:96,1--97,0 text='
'
Read token at ../src/test_parser.nit:97,2--5 text='loop'
Read token at ../src/test_parser.nit:97,6--98,0 text='
'
Read token at ../src/test_parser.nit:98,3--5 text='var'
Read token at ../src/test_parser.nit:98,7 text='n'
Read token at ../src/test_parser.nit:98,9 text='='
Read token at ../src/test_parser.nit:98,11--12 text='tc'
Read token at ../src/test_parser.nit:98,13 text='.'
Read token at ../src/test_parser.nit:98,14--30 text='interactive_parse'
Read token at ../src/test_parser.nit:98,31 text='('
Read token at ../src/test_parser.nit:98,32--36 text='"-->"'
Read token at ../src/test_parser.nit:98,37 text=')'
Read token at ../src/test_parser.nit:98,38--99,0 text='
'
Read token at ../src/test_parser.nit:99,3--4 text='if'
Read token at ../src/test_parser.nit:99,6 text='n'
Read token at ../src/test_parser.nit:99,8--10 text='isa'
Read token at ../src/test_parser.nit:99,12--18 text='TString'
Read token at ../src/test_parser.nit:99,20--23 text='then'
Read token at ../src/test_parser.nit:99,24--100,0 text='
'
Read token at ../src/test_parser.nit:100,4--6 text='var'
Read token at ../src/test_parser.nit:100,8 text='s'
Read token at ../src/test_parser.nit:100,10 text='='
Read token at ../src/test_parser.nit:100,12 text='n'
Read token at ../src/test_parser.nit:100,13 text='.'
Read token at ../src/test_parser.nit:100,14--17 text='text'
Read token at ../src/test_parser.nit:100,18--101,0 text='
'
Read token at ../src/test_parser.nit:101,4--5 text='if'
Read token at ../src/test_parser.nit:101,7 text='s'
Read token at ../src/test_parser.nit:101,9--10 text='=='
Read token at ../src/test_parser.nit:101,12--15 text='":q"'
Read token at ../src/test_parser.nit:101,17--20 text='then'
Read token at ../src/test_parser.nit:101,21--102,0 text='
'
Read token at ../src/test_parser.nit:102,5--9 text='break'
Read token at ../src/test_parser.nit:102,10--103,0 text='
'
Read token at ../src/test_parser.nit:103,4--7 text='else'
Read token at ../src/test_parser.nit:103,8--104,0 text='
'
Read token at ../src/test_parser.nit:104,5--9 text='print'
Read token at ../src/test_parser.nit:104,11--24 text='"`:q` to quit"'
Read token at ../src/test_parser.nit:104,25--105,0 text='
'
Read token at ../src/test_parser.nit:105,4--6 text='end'
Read token at ../src/test_parser.nit:105,7--106,0 text='
'
Read token at ../src/test_parser.nit:106,4--11 text='continue'
Read token at ../src/test_parser.nit:106,12--107,0 text='
'
Read token at ../src/test_parser.nit:107,3--5 text='end'
Read token at ../src/test_parser.nit:107,6--108,0 text='
'
Read token at ../src/test_parser.nit:108,1--109,0 text='
'
Read token at ../src/test_parser.nit:109,3--4 text='if'
Read token at ../src/test_parser.nit:109,6 text='n'
Read token at ../src/test_parser.nit:109,8--10 text='isa'
Read token at ../src/test_parser.nit:109,12--17 text='AError'
Read token at ../src/test_parser.nit:109,19--22 text='then'
Read token at ../src/test_parser.nit:109,23--110,0 text='
'
Read token at ../src/test_parser.nit:110,4--8 text='print'
Read token at ../src/test_parser.nit:110,10--11 text='"{'
Read token at ../src/test_parser.nit:110,12 text='n'
Read token at ../src/test_parser.nit:110,13 text='.'
Read token at ../src/test_parser.nit:110,14--21 text='location'
Read token at ../src/test_parser.nit:110,22 text='.'
Read token at ../src/test_parser.nit:110,23--34 text='colored_line'
Read token at ../src/test_parser.nit:110,35 text='('
Read token at ../src/test_parser.nit:110,36--41 text='"0;31"'
Read token at ../src/test_parser.nit:110,42 text=')'
Read token at ../src/test_parser.nit:110,43--46 text='}: {'
Read token at ../src/test_parser.nit:110,47 text='n'
Read token at ../src/test_parser.nit:110,48 text='.'
Read token at ../src/test_parser.nit:110,49--55 text='message'
Read token at ../src/test_parser.nit:110,56--57 text='}"'
Read token at ../src/test_parser.nit:110,58--111,0 text='
'
Read token at ../src/test_parser.nit:111,4--11 text='continue'
Read token at ../src/test_parser.nit:111,12--112,0 text='
'
Read token at ../src/test_parser.nit:112,3--5 text='end'
Read token at ../src/test_parser.nit:112,6--113,0 text='
'
Read token at ../src/test_parser.nit:113,1--114,0 text='
'
Read token at ../src/test_parser.nit:114,3--4 text='if'
Read token at ../src/test_parser.nit:114,6--8 text='not'
Read token at ../src/test_parser.nit:114,10--17 text='no_print'
Read token at ../src/test_parser.nit:114,19--22 text='then'
Read token at ../src/test_parser.nit:114,23--115,0 text='
'
Read token at ../src/test_parser.nit:115,4 text='('
Read token at ../src/test_parser.nit:115,5--7 text='new'
Read token at ../src/test_parser.nit:115,9--24 text='PrintTreeVisitor'
Read token at ../src/test_parser.nit:115,25 text=')'
Read token at ../src/test_parser.nit:115,26 text='.'
Read token at ../src/test_parser.nit:115,27--37 text='enter_visit'
Read token at ../src/test_parser.nit:115,38 text='('
Read token at ../src/test_parser.nit:115,39 text='n'
Read token at ../src/test_parser.nit:115,40 text=')'
Read token at ../src/test_parser.nit:115,41--116,0 text='
'
Read token at ../src/test_parser.nit:116,3--5 text='end'
Read token at ../src/test_parser.nit:116,6--117,0 text='
'
Read token at ../src/test_parser.nit:117,2--4 text='end'
Read token at ../src/test_parser.nit:117,5--118,0 text='
'
Read token at ../src/test_parser.nit:118,1--4 text='else'
Read token at ../src/test_parser.nit:118,5--119,0 text='
'
Read token at ../src/test_parser.nit:119,2--4 text='for'
Read token at ../src/test_parser.nit:119,6 text='a'
Read token at ../src/test_parser.nit:119,8--9 text='in'
Read token at ../src/test_parser.nit:119,11--14 text='args'
Read token at ../src/test_parser.nit:119,16--17 text='do'
Read token at ../src/test_parser.nit:119,18--120,0 text='
'
Read token at ../src/test_parser.nit:120,3--5 text='var'
Read token at ../src/test_parser.nit:120,7--12 text='source'
Read token at ../src/test_parser.nit:120,13--121,0 text='
'
Read token at ../src/test_parser.nit:121,3--4 text='if'
Read token at ../src/test_parser.nit:121,6--12 text='no_file'
Read token at ../src/test_parser.nit:121,14--17 text='then'
Read token at ../src/test_parser.nit:121,18--122,0 text='
'
Read token at ../src/test_parser.nit:122,4--9 text='source'
Read token at ../src/test_parser.nit:122,11 text='='
Read token at ../src/test_parser.nit:122,13--15 text='new'
Read token at ../src/test_parser.nit:122,17--26 text='SourceFile'
Read token at ../src/test_parser.nit:122,27 text='.'
Read token at ../src/test_parser.nit:122,28--38 text='from_string'
Read token at ../src/test_parser.nit:122,39 text='('
Read token at ../src/test_parser.nit:122,40--41 text='""'
Read token at ../src/test_parser.nit:122,42 text=','
Read token at ../src/test_parser.nit:122,44 text='a'
Read token at ../src/test_parser.nit:122,45 text=')'
Read token at ../src/test_parser.nit:122,46--123,0 text='
'
Read token at ../src/test_parser.nit:123,3--6 text='else'
Read token at ../src/test_parser.nit:123,7--124,0 text='
'
Read token at ../src/test_parser.nit:124,4--6 text='var'
Read token at ../src/test_parser.nit:124,8 text='f'
Read token at ../src/test_parser.nit:124,10 text='='
Read token at ../src/test_parser.nit:124,12--14 text='new'
Read token at ../src/test_parser.nit:124,16--25 text='FileReader'
Read token at ../src/test_parser.nit:124,26 text='.'
Read token at ../src/test_parser.nit:124,27--30 text='open'
Read token at ../src/test_parser.nit:124,31 text='('
Read token at ../src/test_parser.nit:124,32 text='a'
Read token at ../src/test_parser.nit:124,33 text=')'
Read token at ../src/test_parser.nit:124,34--125,0 text='
'
Read token at ../src/test_parser.nit:125,4--9 text='source'
Read token at ../src/test_parser.nit:125,11 text='='
Read token at ../src/test_parser.nit:125,13--15 text='new'
Read token at ../src/test_parser.nit:125,17--26 text='SourceFile'
Read token at ../src/test_parser.nit:125,27 text='('
Read token at ../src/test_parser.nit:125,28 text='a'
Read token at ../src/test_parser.nit:125,29 text=','
Read token at ../src/test_parser.nit:125,31 text='f'
Read token at ../src/test_parser.nit:125,32 text=')'
Read token at ../src/test_parser.nit:125,33--126,0 text='
'
Read token at ../src/test_parser.nit:126,4 text='f'
Read token at ../src/test_parser.nit:126,5 text='.'
Read token at ../src/test_parser.nit:126,6--10 text='close'
Read token at ../src/test_parser.nit:126,11--127,0 text='
'
Read token at ../src/test_parser.nit:127,3--5 text='end'
Read token at ../src/test_parser.nit:127,6--128,0 text='
'
Read token at ../src/test_parser.nit:128,3--5 text='var'
Read token at ../src/test_parser.nit:128,7--11 text='lexer'
Read token at ../src/test_parser.nit:128,13 text='='
Read token at ../src/test_parser.nit:128,15--17 text='new'
Read token at ../src/test_parser.nit:128,19--23 text='Lexer'
Read token at ../src/test_parser.nit:128,24 text='('
Read token at ../src/test_parser.nit:128,25--30 text='source'
Read token at ../src/test_parser.nit:128,31 text=')'
Read token at ../src/test_parser.nit:128,32--129,0 text='
'
Read token at ../src/test_parser.nit:129,3--4 text='if'
Read token at ../src/test_parser.nit:129,6--15 text='only_lexer'
Read token at ../src/test_parser.nit:129,17--20 text='then'
Read token at ../src/test_parser.nit:129,21--130,0 text='
'
Read token at ../src/test_parser.nit:130,4--6 text='var'
Read token at ../src/test_parser.nit:130,8--12 text='token'
Read token at ../src/test_parser.nit:130,14 text='='
Read token at ../src/test_parser.nit:130,16--20 text='lexer'
Read token at ../src/test_parser.nit:130,21 text='.'
Read token at ../src/test_parser.nit:130,22--25 text='next'
Read token at ../src/test_parser.nit:130,26--131,0 text='
'
Read token at ../src/test_parser.nit:131,4--8 text='while'
Read token at ../src/test_parser.nit:131,10--12 text='not'
Read token at ../src/test_parser.nit:131,14--18 text='token'
Read token at ../src/test_parser.nit:131,20--22 text='isa'
Read token at ../src/test_parser.nit:131,24--26 text='EOF'
Read token at ../src/test_parser.nit:131,28--29 text='do'
Read token at ../src/test_parser.nit:131,30--132,0 text='
'
Read token at ../src/test_parser.nit:132,5--6 text='if'
Read token at ../src/test_parser.nit:132,8--10 text='not'
Read token at ../src/test_parser.nit:132,12--19 text='no_print'
Read token at ../src/test_parser.nit:132,21--24 text='then'
Read token at ../src/test_parser.nit:132,25--133,0 text='
'
Read token at ../src/test_parser.nit:133,6--10 text='print'
Read token at ../src/test_parser.nit:133,11 text='('
Read token at ../src/test_parser.nit:133,12--27 text='"Read token at {'
Read token at ../src/test_parser.nit:133,28--32 text='token'
Read token at ../src/test_parser.nit:133,33 text='.'
Read token at ../src/test_parser.nit:133,34--41 text='location'
Read token at ../src/test_parser.nit:133,42--50 text='} text='{'
Read token at ../src/test_parser.nit:133,51--55 text='token'
Read token at ../src/test_parser.nit:133,56 text='.'
Read token at ../src/test_parser.nit:133,57--60 text='text'
Read token at ../src/test_parser.nit:133,61--63 text='}'"'
Read token at ../src/test_parser.nit:133,64 text=')'
Read token at ../src/test_parser.nit:133,65--134,0 text='
'
Read token at ../src/test_parser.nit:134,5--7 text='end'
Read token at ../src/test_parser.nit:134,8--135,0 text='
'
Read token at ../src/test_parser.nit:135,5--9 text='token'
Read token at ../src/test_parser.nit:135,11 text='='
Read token at ../src/test_parser.nit:135,13--17 text='lexer'
Read token at ../src/test_parser.nit:135,18 text='.'
Read token at ../src/test_parser.nit:135,19--22 text='next'
Read token at ../src/test_parser.nit:135,23--136,0 text='
'
Read token at ../src/test_parser.nit:136,4--6 text='end'
Read token at ../src/test_parser.nit:136,7--137,0 text='
'
Read token at ../src/test_parser.nit:137,3--6 text='else'
Read token at ../src/test_parser.nit:137,7--138,0 text='
'
Read token at ../src/test_parser.nit:138,4--6 text='var'
Read token at ../src/test_parser.nit:138,8--13 text='parser'
Read token at ../src/test_parser.nit:138,15 text='='
Read token at ../src/test_parser.nit:138,17--19 text='new'
Read token at ../src/test_parser.nit:138,21--26 text='Parser'
Read token at ../src/test_parser.nit:138,27 text='('
Read token at ../src/test_parser.nit:138,28--32 text='lexer'
Read token at ../src/test_parser.nit:138,33 text=')'
Read token at ../src/test_parser.nit:138,34--139,0 text='
'
Read token at ../src/test_parser.nit:139,4--6 text='var'
Read token at ../src/test_parser.nit:139,8--11 text='tree'
Read token at ../src/test_parser.nit:139,13 text='='
Read token at ../src/test_parser.nit:139,15--20 text='parser'
Read token at ../src/test_parser.nit:139,21 text='.'
Read token at ../src/test_parser.nit:139,22--26 text='parse'
Read token at ../src/test_parser.nit:139,27--140,0 text='
'
Read token at ../src/test_parser.nit:140,1--141,0 text='
'
Read token at ../src/test_parser.nit:141,4--6 text='var'
Read token at ../src/test_parser.nit:141,8--12 text='error'
Read token at ../src/test_parser.nit:141,14 text='='
Read token at ../src/test_parser.nit:141,16--19 text='tree'
Read token at ../src/test_parser.nit:141,20 text='.'
Read token at ../src/test_parser.nit:141,21--25 text='n_eof'
Read token at ../src/test_parser.nit:141,26--142,0 text='
'
Read token at ../src/test_parser.nit:142,4--5 text='if'
Read token at ../src/test_parser.nit:142,7--11 text='error'
Read token at ../src/test_parser.nit:142,13--15 text='isa'
Read token at ../src/test_parser.nit:142,17--22 text='AError'
Read token at ../src/test_parser.nit:142,24--27 text='then'
Read token at ../src/test_parser.nit:142,28--143,0 text='
'
Read token at ../src/test_parser.nit:143,5--9 text='print'
Read token at ../src/test_parser.nit:143,10 text='('
Read token at ../src/test_parser.nit:143,11--21 text='"Error at {'
Read token at ../src/test_parser.nit:143,22--26 text='error'
Read token at ../src/test_parser.nit:143,27 text='.'
Read token at ../src/test_parser.nit:143,28--35 text='location'
Read token at ../src/test_parser.nit:143,36--42 text='}:\n\t{'
Read token at ../src/test_parser.nit:143,43--47 text='error'
Read token at ../src/test_parser.nit:143,48 text='.'
Read token at ../src/test_parser.nit:143,49--55 text='message'
Read token at ../src/test_parser.nit:143,56--57 text='}"'
Read token at ../src/test_parser.nit:143,58 text=')'
Read token at ../src/test_parser.nit:143,59--144,0 text='
'
Read token at ../src/test_parser.nit:144,5--10 text='return'
Read token at ../src/test_parser.nit:144,11--145,0 text='
'
Read token at ../src/test_parser.nit:145,4--6 text='end'
Read token at ../src/test_parser.nit:145,7--146,0 text='
'
Read token at ../src/test_parser.nit:146,1--147,0 text='
'
Read token at ../src/test_parser.nit:147,4--5 text='if'
Read token at ../src/test_parser.nit:147,7--9 text='xml'
Read token at ../src/test_parser.nit:147,11--14 text='then'
Read token at ../src/test_parser.nit:147,15--148,0 text='
'
Read token at ../src/test_parser.nit:148,5--8 text='tree'
Read token at ../src/test_parser.nit:148,9 text='.'
Read token at ../src/test_parser.nit:148,10--25 text='parentize_tokens'
Read token at ../src/test_parser.nit:148,26--149,0 text='
'
Read token at ../src/test_parser.nit:149,5--8 text='tree'
Read token at ../src/test_parser.nit:149,9 text='.'
Read token at ../src/test_parser.nit:149,10--15 text='to_xml'
Read token at ../src/test_parser.nit:149,16 text='.'
Read token at ../src/test_parser.nit:149,17--24 text='write_to'
Read token at ../src/test_parser.nit:149,25 text='('
Read token at ../src/test_parser.nit:149,26--31 text='stdout'
Read token at ../src/test_parser.nit:149,32 text=')'
Read token at ../src/test_parser.nit:149,33--150,0 text='
'
Read token at ../src/test_parser.nit:150,4--7 text='else'
Read token at ../src/test_parser.nit:150,9--10 text='if'
Read token at ../src/test_parser.nit:150,12--14 text='not'
Read token at ../src/test_parser.nit:150,16--23 text='no_print'
Read token at ../src/test_parser.nit:150,25--28 text='then'
Read token at ../src/test_parser.nit:150,29--151,0 text='
'
Read token at ../src/test_parser.nit:151,5 text='('
Read token at ../src/test_parser.nit:151,6--8 text='new'
Read token at ../src/test_parser.nit:151,10--25 text='PrintTreeVisitor'
Read token at ../src/test_parser.nit:151,26 text=')'
Read token at ../src/test_parser.nit:151,27 text='.'
Read token at ../src/test_parser.nit:151,28--38 text='enter_visit'
Read token at ../src/test_parser.nit:151,39 text='('
Read token at ../src/test_parser.nit:151,40--43 text='tree'
Read token at ../src/test_parser.nit:151,44 text=')'
Read token at ../src/test_parser.nit:151,45--152,0 text='
'
Read token at ../src/test_parser.nit:152,4--6 text='end'
Read token at ../src/test_parser.nit:152,7--153,0 text='
'
Read token at ../src/test_parser.nit:153,3--5 text='end'
Read token at ../src/test_parser.nit:153,6--154,0 text='
'
Read token at ../src/test_parser.nit:154,2--4 text='end'
Read token at ../src/test_parser.nit:154,5--155,0 text='
'
Read token at ../src/test_parser.nit:155,1--3 text='end'
Read token at ../src/test_parser.nit:155,4--156,0 text='
'
