all:
	mkdir -p bin/
	../../bin/nitg --dir bin src/nitcorn_hello_world.nit src/file_server_on_port_80.nit

xymus.net:
	mkdir -p bin/
	../../bin/nitg --dir bin/ -I ../../contrib/tnitter/src/ -I ../../contrib/benitlux/src/ src/xymus_net.nit
