#include "nit.common.h"
val* string__NativeString__to_s_with_length(char* self, long p0);
extern const int COLOR_kernel__Object___61d_61d;
val* NEW_android_platform__AndroidPlatform(const struct type* type);
extern const struct type type_android_platform__AndroidPlatform;
extern const int COLOR_android_platform__AndroidPlatform__init;
extern const int COLOR_android_platform__ToolContext__platform_from_name;
val* android_platform__ToolContext__platform_from_name(val* self, val* p0);
extern const int COLOR_abstract_collection__Collection__first;
extern const int COLOR_abstract_collection__Sequence__remove_at;
val* NEW_exec__IProcess(const struct type* type);
extern const struct type type_exec__IProcess;
val* NEW_array__Array(const struct type* type);
extern const struct type type_array__Arraystring__String;
extern const int COLOR_array__Array__with_capacity;
extern const int COLOR_abstract_collection__Sequence__push;
extern const int COLOR_exec__IProcess__from_a;
extern const int COLOR_exec__Process__wait;
extern const int COLOR_exec__Process__status;
extern const struct type type_array__Arraykernel__Object;
val* NEW_array__NativeArray(int length, const struct type* type);
extern const struct type type_array__NativeArraykernel__Object;
extern const int COLOR_array__Array__with_native;
extern const int COLOR_string__Object__to_s;
extern const int COLOR_file__Object__print;
extern const int COLOR_kernel__Object__exit;
val* NEW_exec__Process(const struct type* type);
extern const struct type type_exec__Process;
extern const int COLOR_exec__Process__from_a;
extern const int COLOR_string__Collection__join;
void android_platform__ToolContext__exec_and_check(val* self, val* p0);
short int android_platform__AndroidPlatform__supports_libunwind(val* self);
val* NEW_android_platform__AndroidToolchain(const struct type* type);
extern const struct type type_android_platform__AndroidToolchain;
extern const int COLOR_abstract_compiler__Toolchain__init;
val* android_platform__AndroidPlatform__toolchain(val* self, val* p0);
extern const int COLOR_platform__Platform__init;
void android_platform__AndroidPlatform__init(val* self);
extern const int COLOR_android_platform__AndroidToolchain___64dandroid_project_root;
val* android_platform__AndroidToolchain__android_project_root(val* self);
void android_platform__AndroidToolchain__android_project_root_61d(val* self, val* p0);
extern const int COLOR_android_platform__AndroidToolchain__compile_dir;
extern const int COLOR_android_platform__AndroidToolchain__android_project_root_61d;
extern const int COLOR_abstract_collection__SimpleCollection__add;
val* android_platform__AndroidToolchain__compile_dir(val* self);
extern const int COLOR_abstract_compiler__AbstractCompiler__mainmodule;
extern const int COLOR_mmodule__MModule__name;
extern const int COLOR_android_platform__AndroidToolchain__android_project_root;
extern const int COLOR_abstract_compiler__Toolchain__toolcontext;
extern const int COLOR_android_platform__ToolContext__exec_and_check;
extern const int COLOR_file__String__file_exists;
extern const int COLOR_file__String__mkdir;
extern const int COLOR_android_platform__AndroidToolchain__write_files;
extern const int COLOR_abstract_compiler__AbstractCompiler__extern_bodies;
extern const int COLOR_abstract_collection__Collection__iterator;
extern const int COLOR_abstract_collection__Iterator__is_ok;
extern const int COLOR_abstract_collection__Iterator__item;
extern const struct type type_c__ExternCFile;
extern const int COLOR_ffi_base__ExternFile__filename;
extern const int COLOR_file__String__basename;
extern const int COLOR_abstract_collection__Iterator__next;
val* NEW_file__OFStream(const struct type* type);
extern const struct type type_file__OFStream;
extern const int COLOR_file__OFStream__open;
extern const int COLOR_stream__OStream__write;
extern const int COLOR_stream__IOS__close;
extern const int COLOR_environ__String__environ;
extern const int COLOR_abstract_collection__Collection__is_empty;
extern const int COLOR_kernel__Object__sys;
extern const int COLOR_string__Sys__program_name;
extern const int COLOR_file__String__dirname;
extern const int COLOR_file__String__realpath;
extern const struct type type_array__NativeArraystring__String;
extern const int COLOR_mmodule__MModule__location;
extern const int COLOR_location__Location__file;
extern const int COLOR_location__SourceFile__filename;
void android_platform__AndroidToolchain__write_files(val* self, val* p0, val* p1, val* p2);
void android_platform__AndroidToolchain__write_makefile(val* self, val* p0, val* p1, val* p2);
extern const int COLOR_string__String___43d;
extern const int COLOR_abstract_compiler__ToolContext__opt_output;
extern const int COLOR_opts__Option__value;
void android_platform__AndroidToolchain__compile_c_code(val* self, val* p0, val* p1);
