#include "nit.common.h"
extern const int COLOR_astvalidation__ASTValidationVisitor__path;
extern const int COLOR_abstract_collection__Sequence__unshift;
extern const int COLOR_astvalidation__ANode__accept_ast_validation;
extern const int COLOR_abstract_collection__Sequence__shift;
void astvalidation__ASTValidationVisitor__visit(val* self, val* p0);
extern const int COLOR_astvalidation__ASTValidationVisitor___64dpath;
val* astvalidation__ASTValidationVisitor__path(val* self);
void astvalidation__ASTValidationVisitor__path_61d(val* self, val* p0);
extern const int COLOR_astvalidation__ASTValidationVisitor___64dseen;
val* astvalidation__ASTValidationVisitor__seen(val* self);
void astvalidation__ASTValidationVisitor__seen_61d(val* self, val* p0);
extern const int COLOR_parser_nodes__Visitor__init;
void astvalidation__ASTValidationVisitor__init(val* self);
extern const int COLOR_parser_nodes__ANode__parent;
extern const int COLOR_abstract_collection__Collection__length;
extern const struct type type_kernel__Int;
extern const int COLOR_abstract_collection__SequenceRead___91d_93d;
extern const int COLOR_parser_nodes__ANode__parent_61d;
extern const int COLOR_kernel__Object___33d_61d;
val* string__NativeString__to_s_with_length(char* self, long p0);
val* NEW_array__Array(const struct type* type);
extern const struct type type_array__Arraykernel__Object;
val* NEW_array__NativeArray(int length, const struct type* type);
extern const struct type type_array__NativeArraykernel__Object;
extern const int COLOR_array__Array__with_native;
extern const int COLOR_string__Object__to_s;
extern const int COLOR_parser_nodes__ANode__debug;
extern const int COLOR_astvalidation__ASTValidationVisitor__seen;
extern const int COLOR_abstract_collection__Collection__has;
extern const int COLOR_abstract_collection__SimpleCollection__add;
extern const int COLOR_parser_nodes__ANode___location;
extern const int COLOR_parser_nodes__ANode__location;
extern const int COLOR_parser_nodes__ANode__visit_all;
void astvalidation__ANode__accept_ast_validation(val* self, val* p0);
void astvalidation__AAnnotations__accept_ast_validation(val* self, val* p0);
extern const int COLOR_astvalidation__AExpr__accept_ast_validation;
extern const int COLOR_typing__AExpr__mtype;
extern const int COLOR_typing__AExpr__is_typed;
void astvalidation__AExpr__accept_ast_validation(val* self, val* p0);
extern const int COLOR_astvalidation__APlaceholderExpr__accept_ast_validation;
void astvalidation__APlaceholderExpr__accept_ast_validation(val* self, val* p0);
