#include "nit.common.h"
extern const int COLOR_auto_super_init__ToolContext___64dauto_super_init_phase;
val* auto_super_init__ToolContext__auto_super_init_phase(val* self);
void auto_super_init__ToolContext__auto_super_init_phase_61d(val* self, val* p0);
extern const struct type type_parser_nodes__AConcreteMethPropdef;
extern const int COLOR_phase__Phase__toolcontext;
extern const int COLOR_modelbuilder__ToolContext__modelbuilder;
extern const int COLOR_auto_super_init__AConcreteMethPropdef__do_auto_super_init;
void auto_super_init__AutoSuperInitPhase__process_npropdef(val* self, val* p0);
extern const int COLOR_parser_nodes__Visitor__init;
void auto_super_init__AutoSuperInitVisitor__init(val* self);
extern const int COLOR_auto_super_init__ANode__accept_auto_super_init;
extern const int COLOR_parser_nodes__ANode__visit_all;
void auto_super_init__AutoSuperInitVisitor__visit(val* self, val* p0);
extern const int COLOR_auto_super_init__AutoSuperInitVisitor___64dhas_explicit_super_init;
short int auto_super_init__AutoSuperInitVisitor__has_explicit_super_init(val* self);
void auto_super_init__AutoSuperInitVisitor__has_explicit_super_init_61d(val* self, short int p0);
extern const int COLOR_auto_super_init__AConcreteMethPropdef___64dauto_super_inits;
val* auto_super_init__AConcreteMethPropdef__auto_super_inits(val* self);
void auto_super_init__AConcreteMethPropdef__auto_super_inits_61d(val* self, val* p0);
extern const int COLOR_parser_nodes__ANode__parent;
extern const struct type type_parser_nodes__AClassdef;
extern const int COLOR_modelize_class__AClassdef__mclassdef;
extern const int COLOR_modelize_property__APropdef__mpropdef;
extern const int COLOR_model__MPropDef__mclassdef;
extern const int COLOR_model__MClassDef__mmodule;
extern const int COLOR_model__MPropDef__mproperty;
extern const int COLOR_model__MMethod__is_init;
extern const int COLOR_model__MClassDef__is_intro;
extern const int COLOR_model__MClassDef__in_hierarchy;
extern const int COLOR_poset__POSetElement__direct_greaters;
extern const int COLOR_abstract_collection__Collection__iterator;
extern const int COLOR_abstract_collection__Iterator__is_ok;
extern const int COLOR_abstract_collection__Iterator__item;
extern const int COLOR_model__MClassDef__mclass;
extern const int COLOR_model__MClass__kind;
extern const int COLOR_model__MClassKind__need_init;
extern const int COLOR_abstract_collection__Iterator__next;
extern const int COLOR_parser_nodes__AConcreteMethPropdef__n_block;
val* NEW_auto_super_init__AutoSuperInitVisitor(const struct type* type);
extern const struct type type_auto_super_init__AutoSuperInitVisitor;
extern const int COLOR_auto_super_init__AutoSuperInitVisitor__init;
extern const int COLOR_parser_nodes__Visitor__enter_visit;
extern const int COLOR_auto_super_init__AutoSuperInitVisitor__has_explicit_super_init;
val* NEW_array__Array(const struct type* type);
extern const struct type type_array__Arraymodel__MMethod;
extern const int COLOR_array__Array__init;
extern const int COLOR_model__MClassDef__supertypes;
extern const int COLOR_model__MClassType__mclass;
extern const int COLOR_model__MClassDef__bound_mtype;
extern const int COLOR_model__MType__anchor_to;
extern const int COLOR_model__MProperty__name;
extern const int COLOR_modelbuilder__ModelBuilder__try_get_mproperty_by_name2;
val* string__NativeString__to_s_with_length(char* self, long p0);
extern const struct type type_array__Arraykernel__Object;
val* NEW_array__NativeArray(int length, const struct type* type);
extern const struct type type_array__NativeArraykernel__Object;
extern const int COLOR_array__Array__with_native;
extern const int COLOR_string__Object__to_s;
extern const int COLOR_modelbuilder__ModelBuilder__error;
extern const struct type type_model__MMethod;
extern const int COLOR_abstract_collection__SimpleCollection__add;
extern const int COLOR_abstract_collection__Collection__is_empty;
extern const int COLOR_model__MProperty__intro;
extern const int COLOR_model__MMethodDef__msignature;
extern const int COLOR_model__MSignature__arity;
extern const int COLOR_auto_super_init__AConcreteMethPropdef__auto_super_inits_61d;
void auto_super_init__AConcreteMethPropdef__do_auto_super_init(val* self, val* p0);
void auto_super_init__ANode__accept_auto_super_init(val* self, val* p0);
extern const int COLOR_typing__ASendExpr__mproperty;
extern const int COLOR_auto_super_init__AutoSuperInitVisitor__has_explicit_super_init_61d;
void auto_super_init__ASendExpr__accept_auto_super_init(val* self, val* p0);
void auto_super_init__ASuperExpr__accept_auto_super_init(val* self, val* p0);
