#include "nit.common.h"
extern const int COLOR_c__FFILanguageAssignationPhase___64dc_language;
val* c__FFILanguageAssignationPhase__c_language(val* self);
void c__FFILanguageAssignationPhase__c_language_61d(val* self, val* p0);
extern const int COLOR_c__AExternCodeBlock__is_c;
short int c__CLanguage__identify_language(val* self, val* p0);
extern const int COLOR_c__AExternCodeBlock__is_c_header;
extern const int COLOR_c_tools__CCompilationUnit__header_custom;
extern const int COLOR_parser_nodes__ANode__location;
extern const int COLOR_c__Location__as_line_pragma;
extern const int COLOR_compiling_writer__Writer__add;
extern const int COLOR_ffi_base__AExternCodeBlock__code;
extern const int COLOR_c__AExternCodeBlock__is_c_body;
extern const int COLOR_c_tools__CCompilationUnit__body_custom;
extern const int COLOR_c_tools__CCompilationUnit__body_impl;
void c__CLanguage__compile_module_block(val* self, val* p0, val* p1, val* p2);
val* NEW_c__ExternCFunction(const struct type* type);
extern const struct type type_c__ExternCFunction;
extern const int COLOR_modelbuilder__AModule__mmodule;
extern const int COLOR_c__ExternCFunction__init;
void CHECK_NEW_c__ExternCFunction(val*);
extern const int COLOR_c_tools__CFunction__decls;
extern const int COLOR_c_tools__CFunction__exprs;
extern const int COLOR_c_tools__CCompilationUnit__add_exported_function;
void c__CLanguage__compile_extern_method(val* self, val* p0, val* p1, val* p2, val* p3);
void c__CLanguage__compile_extern_class(val* self, val* p0, val* p1, val* p2, val* p3);
val* NEW_c__ForeignCType(const struct type* type);
extern const struct type type_c__ForeignCType;
extern const int COLOR_c__ForeignCType__init;
void CHECK_NEW_c__ForeignCType(val*);
val* c__CLanguage__get_ftype(val* self, val* p0, val* p1);
extern const int COLOR_c__NitniCallback__compile_callback_to_c;
void c__CLanguage__compile_callback(val* self, val* p0, val* p1, val* p2, val* p3);
extern const int COLOR_ffi_base__AExternCodeBlock__language_name;
extern const int COLOR_ffi_base__AExternCodeBlock__language_name_lowered;
val* string__NativeString__to_s_with_length(char* self, long p0);
extern const int COLOR_kernel__Object___61d_61d;
extern const int COLOR_string__AbstractString__has_prefix;
short int c__AExternCodeBlock__is_c(val* self);
short int c__AExternCodeBlock__is_c_body(val* self);
short int c__AExternCodeBlock__is_c_header(val* self);
val* c__Location__as_line_pragma(val* self);
extern const int COLOR_c__AModule___64dc_compiler_options;
val* c__AModule__c_compiler_options(val* self);
void c__AModule__c_compiler_options_61d(val* self, val* p0);
extern const int COLOR_c__AModule___64dc_linker_options;
val* c__AModule__c_linker_options(val* self);
void c__AModule__c_linker_options_61d(val* self, val* p0);
extern const int COLOR_ffi_base__ExternFile__init;
extern const int COLOR_c__ExternCFile__cflags_61d;
void c__ExternCFile__init(val* self, val* p0, val* p1);
extern const int COLOR_c__ExternCFile___64dcflags;
val* c__ExternCFile__cflags(val* self);
void c__ExternCFile__cflags_61d(val* self, val* p0);
extern const int COLOR_ffi_base__ExternFile__filename;
extern const int COLOR_kernel__Object__hash;
long c__ExternCFile__hash(val* self);
extern const struct type type_c__ExternCFile;
short int c__ExternCFile___61d_61d(val* self, val* p0);
extern const int COLOR_c__ForeignCType___64dctype;
val* c__ForeignCType__ctype(val* self);
void c__ForeignCType__ctype_61d(val* self, val* p0);
extern const int COLOR_ffi_base__ForeignType__init;
extern const int COLOR_c__ForeignCType__ctype_61d;
void c__ForeignCType__init(val* self, val* p0);
void c__NitniCallback__compile_callback_to_c(val* self, val* p0, val* p1);
val* NEW_c__ToCCallContext(const struct type* type);
extern const struct type type_c__ToCCallContext;
extern const int COLOR_c__ToCCallContext__init;
void CHECK_NEW_c__ToCCallContext(val*);
val* c__Object__to_c_call_context(val* self);
val* NEW_c__FromCCallContext(const struct type* type);
extern const struct type type_c__FromCCallContext;
extern const int COLOR_c__FromCCallContext__init;
void CHECK_NEW_c__FromCCallContext(val*);
val* c__Object__from_c_call_context(val* self);
extern const int COLOR_nitni_callbacks__MExplicitCall__mproperty;
extern const struct type type_model__MMethod;
extern const int COLOR_nitni_callbacks__MExplicitCall__recv_mtype;
extern const int COLOR_nitni_utilities__Object__long_signature;
extern const int COLOR_c__Object__from_c_call_context;
extern const int COLOR_nitni_utilities__MMethod__build_cname;
extern const int COLOR_nitni_utilities__Object__short_signature;
extern const int COLOR_c__Object__to_c_call_context;
extern const int COLOR_c_tools__CCompilationUnit__body_decl;
val* NEW_array__Array(const struct type* type);
extern const struct type type_array__Arraykernel__Object;
val* NEW_array__NativeArray(int length, const struct type* type);
extern const struct type type_array__NativeArraykernel__Object;
extern const int COLOR_array__Array__with_native;
void CHECK_NEW_array__Array(val*);
extern const int COLOR_string__Object__to_s;
void c__MExplicitCall__compile_callback_to_c(val* self, val* p0, val* p1);
extern const int COLOR_nitni_utilities__CallContext__init;
void c__CCallContext__init(val* self);
extern const struct type type_model__MClassType;
extern const int COLOR_model__MClassType__mclass;
extern const int COLOR_model__MClass__kind;
extern const int COLOR_model__Object__extern_kind;
extern const int COLOR_nitni_base__MType__cname;
val* c__ToCCallContext__name_mtype(val* self, val* p0);
extern const int COLOR_c__CCallContext__init;
void c__ToCCallContext__init(val* self);
val* c__FromCCallContext__name_mtype(val* self, val* p0);
void c__FromCCallContext__init(val* self);
extern const int COLOR_c__ExternCFunction___64dmethod;
val* c__ExternCFunction__method(val* self);
void c__ExternCFunction__method_61d(val* self, val* p0);
extern const int COLOR_c__ExternCFunction__method_61d;
extern const int COLOR_modelize_property__APropdef__mpropdef;
extern const int COLOR_model__MPropDef__mclassdef;
extern const int COLOR_model__MClassDef__bound_mtype;
extern const int COLOR_model__MPropDef__mproperty;
extern const int COLOR_nitni_utilities__MMethod__build_csignature;
extern const int COLOR_c_tools__CFunction__init;
void c__ExternCFunction__init(val* self, val* p0, val* p1);
