#include "nit.common.h"
extern const int COLOR_cached__ToolContext___64dcached_phase;
val* cached__ToolContext__cached_phase(val* self);
void cached__ToolContext__cached_phase_61d(val* self, val* p0);
extern const int COLOR_phase__Phase__init;
extern const int COLOR_phase__ToolContext__phases;
extern const int COLOR_simple_misc_analysis__ToolContext__simple_misc_analysis_phase;
extern const int COLOR_poset__POSet__add_edge;
void cached__CachedPhase__init(val* self, val* p0, val* p1);
extern const int COLOR_parser_nodes__AAnnotation__n_atid;
extern const int COLOR_parser_nodes__AAtid__n_id;
extern const int COLOR_parser_nodes__Token__text;
val* string__NativeString__to_s_with_length(char* self, long p0);
extern const int COLOR_kernel__Object___33d_61d;
extern const int COLOR_phase__Phase__toolcontext;
extern const int COLOR_modelbuilder__ToolContext__modelbuilder;
extern const struct type type_parser_nodes__AConcreteMethPropdef;
extern const int COLOR_modelbuilder__ModelBuilder__error;
extern const int COLOR_modelize_property__APropdef__mpropdef;
extern const int COLOR_model__MMethodDef__msignature;
extern const int COLOR_model__MSignature__return_mtype;
extern const int COLOR_parser_nodes__AMethPropdef__n_signature;
extern const int COLOR_parser_nodes__ASignature__n_params;
extern const int COLOR_abstract_collection__Collection__is_empty;
extern const int COLOR_parser_nodes__ANode__location;
extern const int COLOR_model__MPropDef__mproperty;
extern const int COLOR_model__MProperty__name;
extern const int COLOR_parser_nodes__ANode__parent;
extern const struct type type_parser_nodes__AStdClassdef;
extern const int COLOR_modelize_class__AClassdef__mclassdef;
val* NEW_model__MAttributeDef(const struct type* type);
extern const struct type type_model__MAttributeDef;
val* NEW_model__MAttribute(const struct type* type);
extern const struct type type_model__MAttribute;
val* NEW_array__Array(const struct type* type);
extern const struct type type_array__Arraykernel__Object;
extern const int COLOR_array__Array__with_capacity;
extern const int COLOR_abstract_collection__SimpleCollection__add;
extern const int COLOR_string__Object__to_s;
extern const int COLOR_model_base__Object__private_visibility;
extern const int COLOR_model__MAttribute__init;
extern const int COLOR_model__MAttributeDef__init;
extern const int COLOR_model__MType__as_nullable;
extern const int COLOR_model__MAttributeDef__static_mtype_61d;
extern const int COLOR_model__MClassDef__mmodule;
extern const int COLOR_model__MModule__get_primitive_class;
extern const int COLOR_model__MClass__mclass_type;
extern const int COLOR_parser_util__ToolContext__parse_propdef;
extern const struct type type_parser_nodes__AAttrPropdef;
extern const int COLOR_cached__CachedPhase__associate_propdef;
val* NEW_model__MMethodDef(const struct type* type);
extern const struct type type_model__MMethodDef;
val* NEW_model__MMethod(const struct type* type);
extern const struct type type_model__MMethod;
extern const int COLOR_model__MMethod__init;
extern const int COLOR_model__MMethodDef__init;
extern const int COLOR_model__MMethodDef__msignature_61d;
extern const int COLOR_parser_nodes__AConcreteMethPropdef__n_block;
extern const int COLOR_parser_util__ToolContext__parse_stmts;
extern const int COLOR_parser_nodes__ANode__replace_with;
extern const int COLOR_parser_util__ANode__collect_tokens_by_text;
extern const int COLOR_abstract_collection__Collection__first;
extern const int COLOR_parser_nodes__Token__text_61d;
void cached__CachedPhase__process_annotated_node(val* self, val* p0, val* p1);
extern const int COLOR_modelize_property__APropdef__mpropdef_61d;
extern const int COLOR_modelize_property__ModelBuilder__mpropdef2npropdef;
extern const int COLOR_abstract_collection__MapRead__has_key;
extern const int COLOR_abstract_collection__Map___91d_93d_61d;
extern const int COLOR_model__MPropDef__mclassdef;
extern const int COLOR_modelize_class__ModelBuilder__mclassdef2nclassdef;
extern const int COLOR_abstract_collection__MapRead___91d_93d;
extern const int COLOR_kernel__Object___61d_61d;
extern const int COLOR_parser_nodes__AClassdef__n_propdefs;
extern const int COLOR_abstract_collection__Collection__has;
void cached__CachedPhase__associate_propdef(val* self, val* p0, val* p1);
