#include "nit.common.h"
extern const int COLOR_common_ffi__MModule___64duses_ffi;
short int common_ffi__MModule__uses_ffi(val* self);
void common_ffi__MModule__uses_ffi_61d(val* self, short int p0);
extern const int COLOR_common_ffi__AModule___64dffi_ccu;
val* common_ffi__AModule__ffi_ccu(val* self);
void common_ffi__AModule__ffi_ccu_61d(val* self, val* p0);
extern const int COLOR_common_ffi__AModule___64dpresent_languages;
val* common_ffi__AModule__present_languages(val* self);
void common_ffi__AModule__present_languages_61d(val* self, val* p0);
extern const int COLOR_common_ffi__AModule___64dffi_callbacks;
val* common_ffi__AModule__ffi_callbacks(val* self);
void common_ffi__AModule__ffi_callbacks_61d(val* self, val* p0);
extern const int COLOR_common_ffi__AModule__ffi_ccu;
val* NEW_c_tools__CCompilationUnit(const struct type* type);
extern const struct type type_c_tools__CCompilationUnit;
extern const int COLOR_c_tools__CCompilationUnit__init;
void CHECK_NEW_c_tools__CCompilationUnit(val*);
extern const int COLOR_common_ffi__AModule__ffi_ccu_61d;
extern const int COLOR_parser_nodes__AModule__n_extern_code_blocks;
extern const int COLOR_abstract_collection__Collection__iterator;
extern const int COLOR_abstract_collection__Iterator__is_ok;
extern const int COLOR_abstract_collection__Iterator__item;
extern const int COLOR_ffi_base__AExternCodeBlock__language;
extern const int COLOR_common_ffi__AModule__present_languages;
extern const int COLOR_abstract_collection__SimpleCollection__add;
extern const int COLOR_ffi_base__FFILanguage__compile_module_block;
extern const int COLOR_abstract_collection__Iterator__next;
extern const int COLOR_c_tools__CCompilationUnit__header_c_base;
val* string__NativeString__to_s_with_length(char* self, long p0);
extern const int COLOR_modelbuilder__AModule__mmodule;
extern const int COLOR_model_base__MModule__name;
val* NEW_array__Array(const struct type* type);
extern const struct type type_array__Arraykernel__Object;
val* NEW_array__NativeArray(int length, const struct type* type);
extern const struct type type_array__NativeArraykernel__Object;
extern const int COLOR_array__Array__with_native;
void CHECK_NEW_array__Array(val*);
extern const int COLOR_string__Object__to_s;
extern const int COLOR_compiling_writer__Writer__add;
extern const int COLOR_header_dependency__MModule__header_dependencies;
extern const int COLOR_common_ffi__MModule__uses_ffi;
extern const int COLOR_c_tools__CCompilationUnit__header_custom;
extern const int COLOR_parser_nodes__AModule__n_classdefs;
extern const struct type type_parser_nodes__AStdClassdef;
extern const int COLOR_parser_nodes__AStdClassdef__n_extern_code_block;
extern const int COLOR_common_ffi__MModule__uses_ffi_61d;
extern const int COLOR_ffi_base__FFILanguage__compile_extern_class;
void common_ffi__AModule__ensure_compile_ffi_wrapper(val* self);
extern const int COLOR_common_ffi__AModule__ensure_compile_ffi_wrapper;
extern const int COLOR_common_ffi__AModule__ffi_callbacks;
extern const int COLOR_abstract_collection__MapRead__keys;
extern const int COLOR_abstract_collection__Collection__has;
extern const int COLOR_abstract_collection__MapRead___91d_93d;
extern const int COLOR_ffi_base__FFILanguage__compile_callback;
extern const int COLOR_ffi_base__FFILanguage__compile_to_files;
extern const int COLOR_ffi_base__CCompilationUnit__write_as_impl;
extern const int COLOR_c_tools__CCompilationUnit__files;
extern const int COLOR_ffi_base__AModule__ffi_files;
val* NEW_c__ExternCFile(const struct type* type);
extern const struct type type_c__ExternCFile;
extern const int COLOR_c__AModule__c_compiler_options;
extern const int COLOR_c__ExternCFile__init;
void CHECK_NEW_c__ExternCFile(val*);
void common_ffi__AModule__finalize_ffi_wrapper(val* self, val* p0, val* p1);
extern const int COLOR_common_ffi__AExternPropdef___64dffi_has_been_compiled;
short int common_ffi__AExternPropdef__ffi_has_been_compiled(val* self);
void common_ffi__AExternPropdef__ffi_has_been_compiled_61d(val* self, short int p0);
extern const int COLOR_parser_nodes__AExternPropdef__n_extern_code_block;
extern const int COLOR_common_ffi__AExternPropdef__ffi_has_been_compiled;
extern const int COLOR_common_ffi__AExternPropdef__ffi_has_been_compiled_61d;
extern const int COLOR_ffi_base__FFILanguage__compile_extern_method;
void common_ffi__AExternPropdef__compile_ffi_method(val* self, val* p0);
extern const int COLOR_common_ffi__VerifyNitniCallbacksPhase__process_npropdef;
extern const struct type type_parser_nodes__AExternPropdef;
extern const int COLOR_nitni_callbacks__AExternPropdef__foreign_callbacks;
extern const int COLOR_nitni_callbacks__ForeignCallbackSet__all;
extern const int COLOR_parser_nodes__ANode__parent;
extern const struct type type_parser_nodes__AModule;
val* NEW_hash_collection__HashSet(const struct type* type);
extern const struct type type_hash_collection__HashSetnitni_callbacks__NitniCallback;
extern const int COLOR_hash_collection__HashSet__init;
void CHECK_NEW_hash_collection__HashSet(val*);
extern const int COLOR_abstract_collection__Map___91d_93d_61d;
void common_ffi__VerifyNitniCallbacksPhase__process_npropdef(val* self, val* p0);
