#include "nit.common.h"
#define COLOR_core__flat__FlatSubstringsIter___tgt 0
short int core__flat___core__flat__FlatSubstringsIter___core__abstract_collection__Iterator__is_ok(val* self);
extern const char FILE_core__flat[];
#define COLOR_core__kernel__Object___61d_61d 4
#define COLOR_core__flat___core__flat__FlatSubstringsIter___core__kernel__Object__init 20
#define COLOR_core__flat__FlatText__first_byte 86
#define COLOR_core__abstract_text__FlatText___bytelen 7
extern const struct type type_core__Int;
extern const char FILE_core__kernel[];
#define COLOR_core__flat__FlatText___position 3
#define COLOR_core__flat__FlatText___bytepos 4
#define COLOR_core__abstract_text__FlatText___items 5
long core___core__NativeString___length_of_char_at(char* self, long p0);
long core___core__NativeString___find_beginning_of_char_at(char* self, long p0);
#define COLOR_core__abstract_text__FlatText___length 6
long core___core__Int___abs(long self);
long core__flat___FlatText___last_byte(val* self);
long core___core__NativeString___char_to_byte_index_cached(char* self, long p0, long p1, long p2);
extern const struct type type_core__Byte;
long core__flat___FlatText___chars_to_escape_to_c(val* self);
#define COLOR_core__abstract_text__Object__to_s 3
val* core__flat___NativeString___to_s_unsafe(char* self, val* p0);
uint32_t core__flat___FlatText___fetch_char_at(val* self, long p0);
long core__flat___FlatText___char_to_byte_index(val* self, long p0);
uint32_t core___core__NativeString___char_at(char* self, long p0);
long core__abstract_text___Char___from_hex(uint32_t self);
long core___core__Int___Discrete__successor(long self, long p0);
#define COLOR_core__flat__FlatString___first_byte 1
#define COLOR_core__flat__FlatString___chars 2
val* NEW_core__flat__FlatStringCharView(const struct type* type);
extern const struct type type_core__flat__FlatStringCharView;
#define COLOR_core__abstract_text__StringCharView__target_61d 12
#define COLOR_core__kernel__Object__init 0
#define COLOR_core__flat__FlatString___bytes 9
val* NEW_core__flat__FlatStringByteView(const struct type* type);
extern const struct type type_core__flat__FlatStringByteView;
#define COLOR_core__abstract_text__StringByteView__target_61d 12
#define COLOR_core__flat__FlatString__lazy_32d_to_cstring 12
#define COLOR_core__flat__FlatString___to_cstring 11
val* core___core__FlatString___core__abstract_text__Text__empty(val* self);
val* NEW_core__FlatString(const struct type* type);
extern const struct type type_core__FlatString;
void core___core__FlatString___full(val* self, char* p0, long p1, long p2, long p3);
val* core__flat___NativeString___to_s_full(char* self, long p0, long p1);
val* core___core__FlatString___substring_impl(val* self, long p0, long p1, long p2);
val* NEW_core__FlatBuffer(const struct type* type);
extern const struct type type_core__FlatBuffer;
void core___core__FlatBuffer___with_capacity(val* self, long p0);
val* core___core__FlatString___core__abstract_text__Text__chars(val* self);
#define COLOR_core__abstract_collection__SequenceRead___91d_93d 29
uint32_t core___core__Char___to_upper(uint32_t self);
void core___core__FlatBuffer___core__abstract_text__Buffer__add(val* self, uint32_t p0);
val* core___core__FlatBuffer___core__abstract_text__Object__to_s(val* self);
uint32_t core___core__Char___to_lower(uint32_t self);
extern const struct type type_core__FlatText;
#define COLOR_core___core__FlatString___core__kernel__Object___61d_61d 105
#define COLOR_core__kernel__Comparable__OTHER 0
#define COLOR_core___core__FlatString___core__kernel__Comparable___60d 106
#define COLOR_core__abstract_text__Text___hash_cache 0
val* NEW_core__flat__FlatSubstringsIter(const struct type* type);
extern const struct type type_core__flat__FlatSubstringsIter;
#define COLOR_core__flat__FlatSubstringsIter__tgt_61d 18
#define COLOR_core__flat__FlatStringCharReverseIterator___target 0
#define COLOR_core__flat__FlatStringCharReverseIterator___curr_pos 1
uint32_t core__flat___FlatText___core__abstract_text__Text___91d_93d(val* self, long p0);
uint32_t core__flat___core__flat__FlatStringCharReverseIterator___core__abstract_collection__Iterator__item(val* self);
#define COLOR_core__flat___core__flat__FlatStringCharReverseIterator___core__kernel__Object__init 23
#define COLOR_core__flat__FlatStringCharIterator___target 0
#define COLOR_core__flat__FlatStringCharIterator___max 1
#define COLOR_core__flat__FlatStringCharIterator___curr_pos 2
#define COLOR_core__flat___core__flat__FlatStringCharIterator___core__kernel__Object__init 25
uint32_t core__flat___core__flat__FlatStringCharIterator___core__abstract_collection__Iterator__item(val* self);
#define COLOR_core__abstract_text__StringCharView___target 0
extern const char FILE_core__abstract_text[];
uint32_t core__flat___core__flat__FlatStringCharView___core__abstract_collection__SequenceRead___91d_93d(val* self, long p0);
val* NEW_core__flat__FlatStringCharIterator(const struct type* type);
extern const struct type type_core__flat__FlatStringCharIterator;
#define COLOR_core__flat__FlatStringCharIterator__target_61d 19
#define COLOR_core__flat__FlatStringCharIterator__curr_pos_61d 20
val* NEW_core__flat__FlatStringCharReverseIterator(const struct type* type);
extern const struct type type_core__flat__FlatStringCharReverseIterator;
#define COLOR_core__flat__FlatStringCharReverseIterator__target_61d 19
#define COLOR_core__flat__FlatStringCharReverseIterator__curr_pos_61d 20
#define COLOR_core__flat__FlatStringByteReverseIterator___target 0
#define COLOR_core__flat__FlatStringByteReverseIterator___target_items 1
#define COLOR_core__flat__FlatStringByteReverseIterator___curr_pos 2
#define COLOR_core__flat___core__flat__FlatStringByteReverseIterator___core__kernel__Object__init 25
unsigned char core__flat___core__flat__FlatStringByteReverseIterator___core__abstract_collection__Iterator__item(val* self);
val* BOX_core__Byte(unsigned char);
#define COLOR_core__flat__FlatStringByteIterator___target 0
#define COLOR_core__flat__FlatStringByteIterator___target_items 1
#define COLOR_core__flat__FlatStringByteIterator___curr_pos 2
#define COLOR_core__flat___core__flat__FlatStringByteIterator___core__kernel__Object__init 25
unsigned char core__flat___core__flat__FlatStringByteIterator___core__abstract_collection__Iterator__item(val* self);
#define COLOR_core__abstract_text__StringByteView___target 0
unsigned char core__flat___core__flat__FlatStringByteView___core__abstract_collection__SequenceRead___91d_93d(val* self, long p0);
val* NEW_core__flat__FlatStringByteIterator(const struct type* type);
extern const struct type type_core__flat__FlatStringByteIterator;
#define COLOR_core__flat__FlatStringByteIterator__target_61d 19
#define COLOR_core__flat__FlatStringByteIterator__curr_pos_61d 20
val* NEW_core__flat__FlatStringByteReverseIterator(const struct type* type);
extern const struct type type_core__flat__FlatStringByteReverseIterator;
#define COLOR_core__flat__FlatStringByteReverseIterator__target_61d 19
#define COLOR_core__flat__FlatStringByteReverseIterator__curr_pos_61d 20
#define COLOR_core___core__FlatBuffer___core__kernel__Object__init 102
#define COLOR_core__flat__FlatBuffer___chars 8
val* NEW_core__flat__FlatBufferCharView(const struct type* type);
extern const struct type type_core__flat__FlatBufferCharView;
#define COLOR_core__flat__FlatBuffer___bytes 10
val* NEW_core__flat__FlatBufferByteView(const struct type* type);
extern const struct type type_core__flat__FlatBufferByteView;
#define COLOR_core__flat__FlatBuffer___capacity 14
#define COLOR_core__flat__FlatBuffer___real_items 15
#define COLOR_core__abstract_text__Buffer___written 2
void core___core__FlatBuffer___reset(val* self);
#define COLOR_core__abstract_text__Buffer___is_dirty 1
long core___core__NativeString___char_to_byte_index(char* self, long p0);
long core__abstract_text___Char___u8char_len(uint32_t self);
void core___core__FlatBuffer___rshift_bytes(val* self, long p0, long p1);
void core___core__FlatBuffer___lshift_bytes(val* self, long p0, long p1);
void core__flat___NativeString___set_char_at(char* self, long p0, uint32_t p1);
void core___core__FlatBuffer___core__abstract_text__Buffer__enlarge(val* self, long p0);
val* NEW_core__Buffer(const struct type* type);
extern const struct type type_core__Buffer;
val* core__flat___Buffer___new(val* self);
#define COLOR_core__abstract_text__Text__bytelen 35
val* core___core__FlatBuffer___core__abstract_text__Text__substrings(val* self);
#define COLOR_core__abstract_collection__Iterator__iterator 16
#define COLOR_core__abstract_collection__Iterator__is_ok 12
#define COLOR_core__abstract_collection__Iterator__item 13
#define COLOR_core__abstract_collection__Iterator__next 14
#define COLOR_core__abstract_collection__Iterator__finish 15
#define COLOR_core__abstract_text__Text__length 22
#define COLOR_core__abstract_text__Text__is_empty 37
#define COLOR_core__abstract_text__Text__substrings 36
void core___core__FlatBuffer___core__abstract_text__Buffer__append(val* self, val* p0);
void core___core__FlatBuffer___with_infos(val* self, char* p0, long p1, long p2, long p3);
#define COLOR_core__flat__FlatBufferByteReverseIterator___target 0
#define COLOR_core__flat__FlatBufferByteReverseIterator___target_items 1
#define COLOR_core__flat__FlatBufferByteReverseIterator___curr_pos 2
#define COLOR_core__flat___core__flat__FlatBufferByteReverseIterator___core__kernel__Object__init 25
unsigned char core__flat___core__flat__FlatBufferByteReverseIterator___core__abstract_collection__Iterator__item(val* self);
unsigned char core__flat___core__flat__FlatBufferByteView___core__abstract_collection__SequenceRead___91d_93d(val* self, long p0);
val* NEW_core__flat__FlatBufferByteIterator(const struct type* type);
extern const struct type type_core__flat__FlatBufferByteIterator;
#define COLOR_core__flat__FlatBufferByteIterator__target_61d 19
#define COLOR_core__flat__FlatBufferByteIterator__curr_pos_61d 20
val* NEW_core__flat__FlatBufferByteReverseIterator(const struct type* type);
extern const struct type type_core__flat__FlatBufferByteReverseIterator;
#define COLOR_core__flat__FlatBufferByteReverseIterator__target_61d 19
#define COLOR_core__flat__FlatBufferByteReverseIterator__curr_pos_61d 20
#define COLOR_core__flat__FlatBufferByteIterator___target 0
#define COLOR_core__flat__FlatBufferByteIterator___target_items 1
#define COLOR_core__flat__FlatBufferByteIterator___curr_pos 2
#define COLOR_core__flat___core__flat__FlatBufferByteIterator___core__kernel__Object__init 25
unsigned char core__flat___core__flat__FlatBufferByteIterator___core__abstract_collection__Iterator__item(val* self);
#define COLOR_core__flat__FlatBufferCharReverseIterator___target 0
#define COLOR_core__flat__FlatBufferCharReverseIterator___curr_pos 1
uint32_t core__flat___core__flat__FlatBufferCharReverseIterator___core__abstract_collection__Iterator__item(val* self);
#define COLOR_core__flat___core__flat__FlatBufferCharReverseIterator___core__kernel__Object__init 23
uint32_t core__flat___core__flat__FlatBufferCharView___core__abstract_collection__SequenceRead___91d_93d(val* self, long p0);
extern const struct type type_core__Char;
long core__abstract_text___core__abstract_text__StringCharView___core__abstract_collection__Collection__length(val* self);
void core__flat___core__flat__FlatBufferCharView___core__abstract_collection__SimpleCollection__add(val* self, uint32_t p0);
void core___core__FlatBuffer___core__abstract_text__Buffer___91d_93d_61d(val* self, long p0, uint32_t p1);
void core__flat___core__flat__FlatBufferCharView___core__abstract_collection__Sequence___91d_93d_61d(val* self, long p0, uint32_t p1);
void core__flat___core__flat__FlatBufferCharView___core__abstract_collection__Sequence__push(val* self, uint32_t p0);
#define COLOR_core__abstract_collection__Collection__length 19
void core__flat___core__flat__FlatBufferCharView___enlarge(val* self, long p0);
#define COLOR_core__abstract_collection__Collection__iterator 21
val* NEW_core__flat__FlatBufferCharIterator(const struct type* type);
extern const struct type type_core__flat__FlatBufferCharIterator;
#define COLOR_core__flat__FlatBufferCharIterator__target_61d 19
#define COLOR_core__flat__FlatBufferCharIterator__curr_pos_61d 20
val* NEW_core__flat__FlatBufferCharReverseIterator(const struct type* type);
extern const struct type type_core__flat__FlatBufferCharReverseIterator;
#define COLOR_core__flat__FlatBufferCharReverseIterator__target_61d 19
#define COLOR_core__flat__FlatBufferCharReverseIterator__curr_pos_61d 20
#define COLOR_core__flat__FlatBufferCharIterator___target 0
#define COLOR_core__flat__FlatBufferCharIterator___max 1
#define COLOR_core__flat__FlatBufferCharIterator___curr_pos 2
#define COLOR_core__flat___core__flat__FlatBufferCharIterator___core__kernel__Object__init 25
uint32_t core__flat___core__flat__FlatBufferCharIterator___core__abstract_collection__Iterator__item(val* self);
long core___core__NativeString___cstring_length(char* self);
val* core__flat___NativeString___to_s_with_length(char* self, long p0);
val* core__flat___NativeString___core__abstract_text__Object__to_s(char* self);
val* core__flat___NativeString___clean_utf8(char* self, long p0);
void core___core__FlatString___with_infos(val* self, char* p0, long p1, long p2);
void core___core__FlatString___to_cstring_61d(val* self, char* p0);
short int core___core__Array___core__kernel__Object___61d_61d(val* self, val* p0);
val* NEW_core__Array(const struct type* type);
extern const struct type type_core__Array__core__Int;
void core___core__Array___core__kernel__Object__init(val* self);
void core___core__Array___core__abstract_collection__SimpleCollection__add(val* self, val* p0);
#define COLOR_core__array__Array___items 2
#define COLOR_core__array__AbstractArrayRead___length 0
void flat___NativeString_native_set_char___impl( char* self, long pos, uint32_t c, long ln );
long core___core__Int___digit_count(long self, long p0);
#define COLOR_core__abstract_text__String___42d 81
void core___core__FlatBuffer___from(val* self, val* p0);
void core__abstract_text___Int___fill_buffer(long self, val* p0, long p1, short int p2);
long abstract_text___Int_int_to_s_len___impl( long self );
void abstract_text___Int_native_int_to_s___impl( long self, char* nstr, long strlen );
val* core__flat___Int___core__abstract_text__Object__to_s(long self);
val* NEW_core__NativeArray(int length, const struct type* type);
extern const struct type type_core__NativeArray__core__String;
#define COLOR_core__NativeArray___35dE 0
extern const char FILE_core__array[];
#define COLOR_core__abstract_collection__MapRead__is_empty 16
#define COLOR_core__abstract_collection__MapRead__iterator 13
#define COLOR_core__abstract_collection__MapIterator__key 13
#define COLOR_core__abstract_collection__MapIterator__item 14
#define COLOR_core__abstract_text__NativeArray__native_to_s 12
#define COLOR_core__abstract_text__Buffer__append 76
#define COLOR_core__abstract_collection__MapIterator__next 15
#define COLOR_core__abstract_collection__MapIterator__is_ok 12
