#include "nit.common.h"
#define COLOR_core__abstract_collection__Collection__length 19
#define COLOR_core__abstract_collection__Collection__is_empty 20
#define COLOR_core__abstract_collection__Collection__iterator 21
#define COLOR_core__abstract_collection__Iterator__is_ok 12
#define COLOR_core__abstract_collection__Iterator__item 13
extern const struct type type_core__Int;
extern const char FILE_core__kernel[];
#define COLOR_core__abstract_collection__Iterator__next 14
#define COLOR_core__abstract_collection__Iterator__finish 15
#define COLOR_core__kernel__Object___61d_61d 4
extern const char FILE_core__abstract_collection[];
#define COLOR_core__abstract_collection__Collection__has 23
#define COLOR_core__abstract_collection__Ref___item 0
val* NEW_core__abstract_collection__RefIterator(const struct type* type);
#define COLOR_core__abstract_collection__RefIterator__core__Ref___35dE 2
#define COLOR_core__abstract_collection__RefIterator__container_61d 18
#define COLOR_core__kernel__Object__init 0
#define COLOR_core__Ref___35dE 3
#define COLOR_core___core__Ref___core__kernel__Object__init 14
#define COLOR_core__abstract_collection__RefIterator___container 1
#define COLOR_core__abstract_collection__RefIterator___is_ok 0
#define COLOR_core__Ref__core__abstract_collection__RefIterator___35dE 1
#define COLOR_core__abstract_collection___core__abstract_collection__RefIterator___core__kernel__Object__init 20
#define COLOR_core__Collection__core__SimpleCollection___35dE 10
#define COLOR_core__abstract_collection__SimpleCollection__add 45
extern const struct type type_core__Set__nullable__core__Object;
short int core___core__Collection___has_all(val* self, val* p0);
#define COLOR_core__kernel__Object__hash 11
#define COLOR_core__abstract_collection__MapRead__has_key 14
#define COLOR_core__abstract_collection__MapRead___91d_93d 15
extern const struct type type_core__MapRead__nullable__core__Object__nullable__core__Object;
#define COLOR_core__abstract_collection__MapRead__length 12
#define COLOR_core__abstract_collection__MapRead__iterator 13
#define COLOR_core__abstract_collection__MapIterator__is_ok 12
#define COLOR_core__abstract_collection__MapIterator__key 13
#define COLOR_core__abstract_collection__MapIterator__item 14
#define COLOR_core__kernel__Object___33d_61d 1
#define COLOR_core__abstract_collection__MapIterator__next 15
#define COLOR_core__abstract_collection__MapKeysIterator___original_iterator 0
#define COLOR_core__MapIterator__core__MapKeysIterator___35dK__core__MapKeysIterator___35dV 1
#define COLOR_core___core__MapKeysIterator___core__kernel__Object__init 20
#define COLOR_core__abstract_collection__MapValuesIterator___original_iterator 0
#define COLOR_core__MapIterator__core__MapValuesIterator___35dK__core__MapValuesIterator___35dV 1
#define COLOR_core___core__MapValuesIterator___core__kernel__Object__init 20
#define COLOR_core__abstract_collection__SequenceRead___91d_93d 29
#define COLOR_core__abstract_collection__SequenceRead__index_of_from 33
#define COLOR_core__abstract_collection__SequenceRead__last_index_of_from 35
#define COLOR_core__abstract_collection__IndexedIterator__index 18
extern const struct type type_core__SequenceRead__nullable__core__Object;
#define COLOR_core__abstract_collection__SequenceRead__reverse_iterator 36
#define COLOR_core__Sequence___35dE 8
#define COLOR_core__abstract_collection__Sequence___91d_93d_61d 48
#define COLOR_core__abstract_collection__Sequence__push 46
#define COLOR_core__Collection__core__Sequence___35dE 9
#define COLOR_core__abstract_collection__SimpleCollection__add_all 44
#define COLOR_core__abstract_collection__Sequence__insert_all 53
#define COLOR_core__abstract_collection__Sequence__insert 55
val* NEW_core__abstract_collection__CoupleMapIterator(const struct type* type);
#define COLOR_core__abstract_collection__CoupleMapIterator__core__CoupleMap___35dK__core__CoupleMap___35dV 6
val* core___core__ArrayMap___core__abstract_collection__CoupleMap__couple_iterator(val* self);
#define COLOR_core__abstract_collection__CoupleMapIterator__iter_61d 17
val* core___core__ArrayMap___core__abstract_collection__CoupleMap__couple_at(val* self, val* p0);
#define COLOR_core__abstract_collection__CoupleMapIterator___iter 0
#define COLOR_core__abstract_collection__Couple___second 1
#define COLOR_core__abstract_collection__Couple___first 0
#define COLOR_core__Iterator__core__Couple__core__abstract_collection__CoupleMapIterator___35dK__core__abstract_collection__CoupleMapIterator___35dV 0
#define COLOR_core__abstract_collection___core__abstract_collection__CoupleMapIterator___core__kernel__Object__init 18
#define COLOR_core__Couple___35dF 0
#define COLOR_core__Couple___35dS 1
#define COLOR_core___core__Couple___core__kernel__Object__init 16
