#include "nit.common.h"
extern const struct type type_core__Int8;
extern const char FILE_core__fixed_ints[];
int8_t core___core__Int8___core__kernel__Discrete__successor(int8_t self, long p0);
val* BOX_core__Int8(int8_t);
long core___core__Int8___core__kernel__Object__hash(int8_t self);
extern const struct class class_core__Int8;
#define COLOR_core__kernel__Comparable__OTHER 0
int8_t core___core__Int8___Numeric__to_i8(int8_t self);
long core___core__Int8___core__kernel__Discrete__distance(int8_t self, int8_t p0);
long core___core__Int8___core__kernel__Comparable___60d_61d_62d(int8_t self, int8_t p0);
int8_t core___core__Int8___core__kernel__Comparable__max(int8_t self, int8_t p0);
int8_t core___core__Int8___core__kernel__Comparable__min(int8_t self, int8_t p0);
extern const struct type type_core__Int16;
int16_t core___core__Int16___core__kernel__Discrete__successor(int16_t self, long p0);
val* BOX_core__Int16(int16_t);
long core___core__Int16___core__kernel__Object__hash(int16_t self);
extern const struct class class_core__Int16;
int16_t core___core__Int16___Numeric__to_i16(int16_t self);
long core___core__Int16___core__kernel__Discrete__distance(int16_t self, int16_t p0);
long core___core__Int16___core__kernel__Comparable___60d_61d_62d(int16_t self, int16_t p0);
int16_t core___core__Int16___core__kernel__Comparable__max(int16_t self, int16_t p0);
int16_t core___core__Int16___core__kernel__Comparable__min(int16_t self, int16_t p0);
extern const struct type type_core__UInt16;
uint16_t core___core__UInt16___core__kernel__Discrete__successor(uint16_t self, long p0);
val* BOX_core__UInt16(uint16_t);
long core___core__UInt16___core__kernel__Object__hash(uint16_t self);
extern const struct class class_core__UInt16;
uint16_t core___core__UInt16___Numeric__to_u16(uint16_t self);
long core___core__UInt16___core__kernel__Discrete__distance(uint16_t self, uint16_t p0);
long core___core__UInt16___core__kernel__Comparable___60d_61d_62d(uint16_t self, uint16_t p0);
uint16_t core___core__UInt16___core__kernel__Comparable__max(uint16_t self, uint16_t p0);
uint16_t core___core__UInt16___core__kernel__Comparable__min(uint16_t self, uint16_t p0);
extern const struct type type_core__Int32;
int32_t core___core__Int32___core__kernel__Discrete__successor(int32_t self, long p0);
val* BOX_core__Int32(int32_t);
long core___core__Int32___core__kernel__Object__hash(int32_t self);
extern const struct class class_core__Int32;
int32_t core___core__Int32___Numeric__to_i32(int32_t self);
long core___core__Int32___core__kernel__Discrete__distance(int32_t self, int32_t p0);
long core___core__Int32___core__kernel__Comparable___60d_61d_62d(int32_t self, int32_t p0);
int32_t core___core__Int32___core__kernel__Comparable__max(int32_t self, int32_t p0);
int32_t core___core__Int32___core__kernel__Comparable__min(int32_t self, int32_t p0);
extern const struct type type_core__UInt32;
uint32_t core___core__UInt32___core__kernel__Discrete__successor(uint32_t self, long p0);
val* BOX_core__UInt32(uint32_t);
long core___core__UInt32___core__kernel__Object__hash(uint32_t self);
extern const struct class class_core__UInt32;
uint32_t core___core__UInt32___Numeric__to_u32(uint32_t self);
long core___core__UInt32___core__kernel__Discrete__distance(uint32_t self, uint32_t p0);
long core___core__UInt32___core__kernel__Comparable___60d_61d_62d(uint32_t self, uint32_t p0);
uint32_t core___core__UInt32___core__kernel__Comparable__max(uint32_t self, uint32_t p0);
uint32_t core___core__UInt32___core__kernel__Comparable__min(uint32_t self, uint32_t p0);
