#include "nit.common.h"
extern const int COLOR_cpp__FFILanguageAssignationPhase___64dcpp_language;
val* cpp__FFILanguageAssignationPhase__cpp_language(val* self);
void cpp__FFILanguageAssignationPhase__cpp_language_61d(val* self, val* p0);
extern const int COLOR_cpp__AModule___64dcpp_file;
val* cpp__AModule__cpp_file(val* self);
void cpp__AModule__cpp_file_61d(val* self, val* p0);
extern const int COLOR_cpp__AModule___64dcpp_compiler_options;
val* cpp__AModule__cpp_compiler_options(val* self);
void cpp__AModule__cpp_compiler_options_61d(val* self, val* p0);
extern const int COLOR_cpp__AExternCodeBlock__is_cpp;
short int cpp__CPPLanguage__identify_language(val* self, val* p0);
extern const int COLOR_cpp__AModule__cpp_file;
val* NEW_cpp__CPPCompilationUnit(const struct type* type);
extern const struct type type_cpp__CPPCompilationUnit;
extern const int COLOR_cpp__CPPCompilationUnit__init;
extern const int COLOR_cpp__AModule__cpp_file_61d;
extern const int COLOR_cpp__AExternCodeBlock__is_cpp_header;
extern const int COLOR_c_tools__CCompilationUnit__header_custom;
extern const int COLOR_parser_nodes__ANode__location;
extern const int COLOR_c__Location__as_line_pragma;
extern const int COLOR_template__Template__add;
extern const int COLOR_ffi_base__AExternCodeBlock__code;
extern const int COLOR_cpp__AExternCodeBlock__is_cpp_body;
extern const int COLOR_c_tools__CCompilationUnit__body_custom;
void cpp__CPPLanguage__compile_module_block(val* self, val* p0, val* p1, val* p2);
extern const int COLOR_modelbuilder__AModule__mmodule;
extern const int COLOR_parser_nodes__ANode__parent;
extern const struct type type_parser_nodes__AClassdef;
extern const int COLOR_modelize_class__AClassdef__mclass;
extern const int COLOR_model__MClass__mclass_type;
extern const int COLOR_modelize_property__APropdef__mpropdef;
extern const int COLOR_model__MPropDef__mproperty;
val* string__NativeString__to_s_with_length(char* self, long p0);
extern const int COLOR_nitni_utilities__Object__long_signature;
extern const int COLOR_nitni_utilities__Object__internal_call_context;
extern const int COLOR_nitni_utilities__MMethod__build_csignature;
extern const int COLOR_c_tools__CCompilationUnit__body_decl;
val* NEW_array__Array(const struct type* type);
extern const struct type type_array__Arraykernel__Object;
val* NEW_array__NativeArray(int length, const struct type* type);
extern const struct type type_array__NativeArraykernel__Object;
extern const int COLOR_array__Array__with_native;
extern const int COLOR_string__Object__to_s;
val* NEW_c__ExternCFunction(const struct type* type);
extern const struct type type_c__ExternCFunction;
extern const int COLOR_c__ExternCFunction__init;
extern const int COLOR_c_tools__CFunction__exprs;
extern const int COLOR_cpp__Object__cpp_call_context;
extern const int COLOR_nitni_utilities__MMethod__build_ccall;
extern const int COLOR_c_tools__CCompilationUnit__add_exported_function;
extern const int COLOR_c_tools__CCompilationUnit__header_decl;
val* NEW_c_tools__CFunction(const struct type* type);
extern const struct type type_c_tools__CFunction;
extern const int COLOR_c_tools__CFunction__init;
extern const int COLOR_model__MMethod__is_init;
extern const int COLOR_cpp__Object__to_cpp_call_context;
extern const int COLOR_nitni_utilities__CallContext__name_mtype;
extern const int COLOR_model__MClassType__mclass;
extern const int COLOR_extern_classes__MClass__ftype;
extern const struct type type_cpp__ForeignCppType;
extern const int COLOR_model__MMethodDef__msignature;
extern const int COLOR_model__MSignature__mparameters;
extern const int COLOR_abstract_collection__Collection__iterator;
extern const int COLOR_abstract_collection__Iterator__is_ok;
extern const int COLOR_abstract_collection__Iterator__item;
extern const int COLOR_model__MParameter__name;
extern const int COLOR_model__MParameter__mtype;
extern const int COLOR_abstract_collection__Iterator__next;
extern const int COLOR_c_tools__CCompilationUnit__add_local_function;
extern const int COLOR_c_tools__CFunction__decls;
void cpp__CPPLanguage__compile_extern_method(val* self, val* p0, val* p1, val* p2, val* p3);
void cpp__CPPLanguage__compile_extern_class(val* self, val* p0, val* p1, val* p2, val* p3);
val* NEW_cpp__ForeignCppType(const struct type* type);
extern const int COLOR_cpp__ForeignCppType__init;
val* cpp__CPPLanguage__get_ftype(val* self, val* p0, val* p1);
extern const int COLOR_mmodule__MModule__name;
extern const int COLOR_cpp__CPPCompilationUnit__write_to_files;
extern const int COLOR_ffi_base__AModule__ffi_files;
extern const int COLOR_abstract_collection__SimpleCollection__add;
extern const int COLOR_c__AModule__c_linker_options;
extern const int COLOR_c__AModule__c_linker_options_61d;
void cpp__CPPLanguage__compile_to_files(val* self, val* p0, val* p1);
extern const int COLOR_cpp__NitniCallback__compile_callback_to_cpp;
void cpp__CPPLanguage__compile_callback(val* self, val* p0, val* p1, val* p2, val* p3);
extern const int COLOR_ffi_base__AExternCodeBlock__language_name;
extern const int COLOR_ffi_base__AExternCodeBlock__language_name_lowered;
extern const int COLOR_kernel__Object___61d_61d;
extern const int COLOR_string__AbstractString__has_prefix;
short int cpp__AExternCodeBlock__is_cpp(val* self);
short int cpp__AExternCodeBlock__is_cpp_body(val* self);
short int cpp__AExternCodeBlock__is_cpp_header(val* self);
extern const int COLOR_array__Array__with_capacity;
extern const int COLOR_nitni_base__AModule__cname;
extern const int COLOR_string__AbstractString__to_upper;
extern const struct type type_array__Arraystring__String;
extern const int COLOR_array__Array__init;
extern const int COLOR_ffi_base__CCompilationUnit__write_header_to_file;
extern const struct type type_array__NativeArraystring__String;
extern const int COLOR_ffi_base__CCompilationUnit__write_body_to_file;
extern const int COLOR_c_tools__CCompilationUnit__files;
val* NEW_cpp__ExternCppFile(const struct type* type);
extern const struct type type_cpp__ExternCppFile;
extern const int COLOR_cpp__ExternCppFile__init;
val* cpp__CPPCompilationUnit__write_to_files(val* self, val* p0, val* p1);
extern const int COLOR_c_tools__CCompilationUnit__init;
void cpp__CPPCompilationUnit__init(val* self);
extern const int COLOR_cpp__ExternCppFile___64damodule;
val* cpp__ExternCppFile__amodule(val* self);
void cpp__ExternCppFile__amodule_61d(val* self, val* p0);
extern const int COLOR_ffi_base__ExternFile__init;
extern const int COLOR_cpp__ExternCppFile__amodule_61d;
void cpp__ExternCppFile__init(val* self, val* p0, val* p1);
extern const int COLOR_ffi_base__ExternFile__filename;
extern const int COLOR_file__String__basename;
val* cpp__ExternCppFile__makefile_rule_name(val* self);
extern const int COLOR_cpp__ExternCppFile__amodule;
extern const int COLOR_cpp__AModule__cpp_compiler_options;
val* cpp__ExternCppFile__makefile_rule_content(val* self);
extern const int COLOR_cpp__ForeignCppType___64dcpp_type;
val* cpp__ForeignCppType__cpp_type(val* self);
void cpp__ForeignCppType__cpp_type_61d(val* self, val* p0);
extern const int COLOR_ffi_base__ForeignType__init;
extern const int COLOR_cpp__ForeignCppType__cpp_type_61d;
void cpp__ForeignCppType__init(val* self, val* p0);
void cpp__NitniCallback__compile_callback_to_cpp(val* self, val* p0, val* p1);
val* NEW_cpp__CppCallContext(const struct type* type);
extern const struct type type_cpp__CppCallContext;
extern const int COLOR_cpp__CppCallContext__init;
val* cpp__Object__cpp_call_context(val* self);
val* NEW_cpp__ToCppCallContext(const struct type* type);
extern const struct type type_cpp__ToCppCallContext;
extern const int COLOR_cpp__ToCppCallContext__init;
val* cpp__Object__to_cpp_call_context(val* self);
val* NEW_cpp__FromCppCallContext(const struct type* type);
extern const struct type type_cpp__FromCppCallContext;
extern const int COLOR_cpp__FromCppCallContext__init;
val* cpp__Object__from_cpp_call_context(val* self);
extern const int COLOR_nitni_callbacks__MExplicitCall__mproperty;
extern const struct type type_model__MMethod;
extern const int COLOR_nitni_callbacks__MExplicitCall__recv_mtype;
extern const int COLOR_nitni_utilities__Object__short_signature;
extern const int COLOR_cpp__Object__from_cpp_call_context;
void cpp__MExplicitCall__compile_callback_to_cpp(val* self, val* p0, val* p1);
extern const struct type type_model__MClassType;
extern const int COLOR_cpp__ForeignCppType__cpp_type;
extern const int COLOR_nitni_base__MType__cname;
val* cpp__CppCallContext__name_mtype(val* self, val* p0);
extern const int COLOR_nitni_utilities__CallContext__init;
void cpp__CppCallContext__init(val* self);
val* cpp__ToCppCallContext__cast_to(val* self, val* p0, val* p1);
void cpp__ToCppCallContext__init(val* self);
val* cpp__FromCppCallContext__cast_from(val* self, val* p0, val* p1);
void cpp__FromCppCallContext__init(val* self);
