#include "nit.common.h"
extern const int COLOR_csv__CSVDocument___64dheader;
val* csv__CSVDocument__header(val* self);
void csv__CSVDocument__header_61d(val* self, val* p0);
extern const int COLOR_csv__CSVDocument___64dlines;
val* csv__CSVDocument__lines(val* self);
void csv__CSVDocument__lines_61d(val* self, val* p0);
extern const int COLOR_csv__CSVDocument__header;
extern const int COLOR_abstract_collection__RemovableCollection__clear;
extern const int COLOR_abstract_collection__Collection__iterator;
extern const int COLOR_abstract_collection__Iterator__is_ok;
extern const int COLOR_abstract_collection__Iterator__item;
extern const int COLOR_string__Object__to_s;
extern const int COLOR_abstract_collection__SimpleCollection__add;
extern const int COLOR_abstract_collection__Iterator__next;
void csv__CSVDocument__set_header(val* self, val* p0);
extern const int COLOR_abstract_collection__Collection__length;
val* string__NativeString__to_s_with_length(char* self, long p0);
val* NEW_array__Array(const struct type* type);
extern const struct type type_array__Arraykernel__Object;
val* NEW_array__NativeArray(int length, const struct type* type);
extern const struct type type_array__NativeArraykernel__Object;
val* BOX_kernel__Int(long);
extern const int COLOR_array__Array__with_native;
extern const int COLOR_file__Object__print;
extern const struct type type_array__Arraystring__String;
extern const int COLOR_array__Array__init;
extern const int COLOR_csv__CSVDocument__lines;
void csv__CSVDocument__add_line(val* self, val* p0);
extern const int COLOR_string__Collection__join;
extern const int COLOR_string__String___43d;
val* csv__CSVDocument__to_s(val* self);
val* NEW_file__OFStream(const struct type* type);
extern const struct type type_file__OFStream;
extern const int COLOR_file__OFStream__open;
extern const int COLOR_stream__OStream__write;
extern const int COLOR_stream__IOS__close;
void csv__CSVDocument__save(val* self, val* p0);
void csv__CSVDocument__init(val* self);
