#include "nit.common.h"
extern const int COLOR_div_by_zero__ToolContext___64ddiv_by_zero_phase;
val* div_by_zero__ToolContext__div_by_zero_phase(val* self);
void div_by_zero__ToolContext__div_by_zero_phase_61d(val* self, val* p0);
extern const int COLOR_modelbuilder__AModule__mmodule;
val* NEW_div_by_zero__DivByZeroVisitor(const struct type* type);
extern const struct type type_div_by_zero__DivByZeroVisitor;
extern const int COLOR_phase__Phase__toolcontext;
extern const int COLOR_div_by_zero__DivByZeroVisitor__init;
extern const int COLOR_parser_nodes__Visitor__enter_visit;
void div_by_zero__DivByZeroPhase__process_nmodule(val* self, val* p0);
extern const int COLOR_div_by_zero__DivByZeroVisitor___64dtoolcontext;
val* div_by_zero__DivByZeroVisitor__toolcontext(val* self);
void div_by_zero__DivByZeroVisitor__toolcontext_61d(val* self, val* p0);
extern const int COLOR_div_by_zero__DivByZeroVisitor___64dmmodule;
val* div_by_zero__DivByZeroVisitor__mmodule(val* self);
void div_by_zero__DivByZeroVisitor__mmodule_61d(val* self, val* p0);
extern const int COLOR_parser_nodes__Visitor__init;
extern const int COLOR_div_by_zero__DivByZeroVisitor__toolcontext_61d;
extern const int COLOR_div_by_zero__DivByZeroVisitor__mmodule_61d;
void div_by_zero__DivByZeroVisitor__init(val* self, val* p0, val* p1);
extern const int COLOR_parser_nodes__ANode__visit_all;
extern const struct type type_parser_nodes__ASlashExpr;
extern const int COLOR_parser_nodes__ABinopExpr__n_expr2;
extern const struct type type_parser_nodes__AIntExpr;
extern const int COLOR_literal__AIntExpr__value;
extern const int COLOR_kernel__Object___33d_61d;
extern const int COLOR_parser_nodes__ASendExpr__n_expr;
extern const int COLOR_div_by_zero__DivByZeroVisitor__mmodule;
val* string__NativeString__to_s_with_length(char* self, long p0);
extern const int COLOR_model__MModule__get_primitive_class;
extern const int COLOR_model__MClass__mclass_type;
extern const int COLOR_typing__AExpr__mtype;
extern const int COLOR_model__MType__is_subtype;
extern const int COLOR_div_by_zero__DivByZeroVisitor__toolcontext;
extern const int COLOR_parser_nodes__ANode__location;
extern const int COLOR_toolcontext__ToolContext__error;
void div_by_zero__DivByZeroVisitor__visit(val* self, val* p0);
