#include "nit.common.h"
extern const int COLOR_lexer__Token___text;
extern const int COLOR_parser_nodes__ANode__location;
extern const int COLOR_location__Location__text;
val* lexer__Token__text(val* self);
void lexer__Token__text_61d(val* self, val* p0);
long lexer__Token__parser_index(val* self);
long lexer__TEol__parser_index(val* self);
extern const int COLOR_parser_nodes__ANode___location;
void lexer__TEol__init_tk(val* self, val* p0);
long lexer__TComment__parser_index(val* self);
void lexer__TComment__init_tk(val* self, val* p0);
long lexer__TKwpackage__parser_index(val* self);
void lexer__TKwpackage__init_tk(val* self, val* p0);
long lexer__TKwmodule__parser_index(val* self);
void lexer__TKwmodule__init_tk(val* self, val* p0);
long lexer__TKwimport__parser_index(val* self);
void lexer__TKwimport__init_tk(val* self, val* p0);
long lexer__TKwclass__parser_index(val* self);
void lexer__TKwclass__init_tk(val* self, val* p0);
long lexer__TKwabstract__parser_index(val* self);
void lexer__TKwabstract__init_tk(val* self, val* p0);
long lexer__TKwinterface__parser_index(val* self);
void lexer__TKwinterface__init_tk(val* self, val* p0);
long lexer__TKwenum__parser_index(val* self);
void lexer__TKwenum__init_tk(val* self, val* p0);
long lexer__TKwend__parser_index(val* self);
void lexer__TKwend__init_tk(val* self, val* p0);
long lexer__TKwmeth__parser_index(val* self);
void lexer__TKwmeth__init_tk(val* self, val* p0);
long lexer__TKwtype__parser_index(val* self);
void lexer__TKwtype__init_tk(val* self, val* p0);
long lexer__TKwinit__parser_index(val* self);
void lexer__TKwinit__init_tk(val* self, val* p0);
long lexer__TKwredef__parser_index(val* self);
void lexer__TKwredef__init_tk(val* self, val* p0);
long lexer__TKwis__parser_index(val* self);
void lexer__TKwis__init_tk(val* self, val* p0);
long lexer__TKwdo__parser_index(val* self);
void lexer__TKwdo__init_tk(val* self, val* p0);
long lexer__TKwreadable__parser_index(val* self);
void lexer__TKwreadable__init_tk(val* self, val* p0);
long lexer__TKwwritable__parser_index(val* self);
void lexer__TKwwritable__init_tk(val* self, val* p0);
long lexer__TKwvar__parser_index(val* self);
void lexer__TKwvar__init_tk(val* self, val* p0);
long lexer__TKwintern__parser_index(val* self);
void lexer__TKwintern__init_tk(val* self, val* p0);
long lexer__TKwextern__parser_index(val* self);
void lexer__TKwextern__init_tk(val* self, val* p0);
long lexer__TKwprotected__parser_index(val* self);
void lexer__TKwprotected__init_tk(val* self, val* p0);
long lexer__TKwprivate__parser_index(val* self);
void lexer__TKwprivate__init_tk(val* self, val* p0);
long lexer__TKwintrude__parser_index(val* self);
void lexer__TKwintrude__init_tk(val* self, val* p0);
long lexer__TKwif__parser_index(val* self);
void lexer__TKwif__init_tk(val* self, val* p0);
long lexer__TKwthen__parser_index(val* self);
void lexer__TKwthen__init_tk(val* self, val* p0);
long lexer__TKwelse__parser_index(val* self);
void lexer__TKwelse__init_tk(val* self, val* p0);
long lexer__TKwwhile__parser_index(val* self);
void lexer__TKwwhile__init_tk(val* self, val* p0);
long lexer__TKwloop__parser_index(val* self);
void lexer__TKwloop__init_tk(val* self, val* p0);
long lexer__TKwfor__parser_index(val* self);
void lexer__TKwfor__init_tk(val* self, val* p0);
long lexer__TKwin__parser_index(val* self);
void lexer__TKwin__init_tk(val* self, val* p0);
long lexer__TKwand__parser_index(val* self);
void lexer__TKwand__init_tk(val* self, val* p0);
long lexer__TKwor__parser_index(val* self);
void lexer__TKwor__init_tk(val* self, val* p0);
long lexer__TKwnot__parser_index(val* self);
void lexer__TKwnot__init_tk(val* self, val* p0);
long lexer__TKwimplies__parser_index(val* self);
void lexer__TKwimplies__init_tk(val* self, val* p0);
long lexer__TKwreturn__parser_index(val* self);
void lexer__TKwreturn__init_tk(val* self, val* p0);
long lexer__TKwcontinue__parser_index(val* self);
void lexer__TKwcontinue__init_tk(val* self, val* p0);
long lexer__TKwbreak__parser_index(val* self);
void lexer__TKwbreak__init_tk(val* self, val* p0);
long lexer__TKwabort__parser_index(val* self);
void lexer__TKwabort__init_tk(val* self, val* p0);
long lexer__TKwassert__parser_index(val* self);
void lexer__TKwassert__init_tk(val* self, val* p0);
long lexer__TKwnew__parser_index(val* self);
void lexer__TKwnew__init_tk(val* self, val* p0);
long lexer__TKwisa__parser_index(val* self);
void lexer__TKwisa__init_tk(val* self, val* p0);
long lexer__TKwonce__parser_index(val* self);
void lexer__TKwonce__init_tk(val* self, val* p0);
long lexer__TKwsuper__parser_index(val* self);
void lexer__TKwsuper__init_tk(val* self, val* p0);
long lexer__TKwself__parser_index(val* self);
void lexer__TKwself__init_tk(val* self, val* p0);
long lexer__TKwtrue__parser_index(val* self);
void lexer__TKwtrue__init_tk(val* self, val* p0);
long lexer__TKwfalse__parser_index(val* self);
void lexer__TKwfalse__init_tk(val* self, val* p0);
long lexer__TKwnull__parser_index(val* self);
void lexer__TKwnull__init_tk(val* self, val* p0);
long lexer__TKwas__parser_index(val* self);
void lexer__TKwas__init_tk(val* self, val* p0);
long lexer__TKwnullable__parser_index(val* self);
void lexer__TKwnullable__init_tk(val* self, val* p0);
long lexer__TKwisset__parser_index(val* self);
void lexer__TKwisset__init_tk(val* self, val* p0);
long lexer__TKwlabel__parser_index(val* self);
void lexer__TKwlabel__init_tk(val* self, val* p0);
long lexer__TKwdebug__parser_index(val* self);
void lexer__TKwdebug__init_tk(val* self, val* p0);
long lexer__TOpar__parser_index(val* self);
void lexer__TOpar__init_tk(val* self, val* p0);
long lexer__TCpar__parser_index(val* self);
void lexer__TCpar__init_tk(val* self, val* p0);
long lexer__TObra__parser_index(val* self);
void lexer__TObra__init_tk(val* self, val* p0);
long lexer__TCbra__parser_index(val* self);
void lexer__TCbra__init_tk(val* self, val* p0);
long lexer__TComma__parser_index(val* self);
void lexer__TComma__init_tk(val* self, val* p0);
long lexer__TColumn__parser_index(val* self);
void lexer__TColumn__init_tk(val* self, val* p0);
long lexer__TQuad__parser_index(val* self);
void lexer__TQuad__init_tk(val* self, val* p0);
long lexer__TAssign__parser_index(val* self);
void lexer__TAssign__init_tk(val* self, val* p0);
long lexer__TPluseq__parser_index(val* self);
void lexer__TPluseq__init_tk(val* self, val* p0);
long lexer__TMinuseq__parser_index(val* self);
void lexer__TMinuseq__init_tk(val* self, val* p0);
long lexer__TDotdotdot__parser_index(val* self);
void lexer__TDotdotdot__init_tk(val* self, val* p0);
long lexer__TDotdot__parser_index(val* self);
void lexer__TDotdot__init_tk(val* self, val* p0);
long lexer__TDot__parser_index(val* self);
void lexer__TDot__init_tk(val* self, val* p0);
long lexer__TPlus__parser_index(val* self);
void lexer__TPlus__init_tk(val* self, val* p0);
long lexer__TMinus__parser_index(val* self);
void lexer__TMinus__init_tk(val* self, val* p0);
long lexer__TStar__parser_index(val* self);
void lexer__TStar__init_tk(val* self, val* p0);
long lexer__TSlash__parser_index(val* self);
void lexer__TSlash__init_tk(val* self, val* p0);
long lexer__TPercent__parser_index(val* self);
void lexer__TPercent__init_tk(val* self, val* p0);
long lexer__TEq__parser_index(val* self);
void lexer__TEq__init_tk(val* self, val* p0);
long lexer__TNe__parser_index(val* self);
void lexer__TNe__init_tk(val* self, val* p0);
long lexer__TLt__parser_index(val* self);
void lexer__TLt__init_tk(val* self, val* p0);
long lexer__TLe__parser_index(val* self);
void lexer__TLe__init_tk(val* self, val* p0);
long lexer__TLl__parser_index(val* self);
void lexer__TLl__init_tk(val* self, val* p0);
long lexer__TGt__parser_index(val* self);
void lexer__TGt__init_tk(val* self, val* p0);
long lexer__TGe__parser_index(val* self);
void lexer__TGe__init_tk(val* self, val* p0);
long lexer__TGg__parser_index(val* self);
void lexer__TGg__init_tk(val* self, val* p0);
long lexer__TStarship__parser_index(val* self);
void lexer__TStarship__init_tk(val* self, val* p0);
long lexer__TBang__parser_index(val* self);
void lexer__TBang__init_tk(val* self, val* p0);
long lexer__TAt__parser_index(val* self);
void lexer__TAt__init_tk(val* self, val* p0);
long lexer__TClassid__parser_index(val* self);
void lexer__TClassid__init_tk(val* self, val* p0);
long lexer__TId__parser_index(val* self);
void lexer__TId__init_tk(val* self, val* p0);
long lexer__TAttrid__parser_index(val* self);
void lexer__TAttrid__init_tk(val* self, val* p0);
long lexer__TNumber__parser_index(val* self);
void lexer__TNumber__init_tk(val* self, val* p0);
long lexer__TFloat__parser_index(val* self);
void lexer__TFloat__init_tk(val* self, val* p0);
long lexer__TString__parser_index(val* self);
void lexer__TString__init_tk(val* self, val* p0);
long lexer__TStartString__parser_index(val* self);
void lexer__TStartString__init_tk(val* self, val* p0);
long lexer__TMidString__parser_index(val* self);
void lexer__TMidString__init_tk(val* self, val* p0);
long lexer__TEndString__parser_index(val* self);
void lexer__TEndString__init_tk(val* self, val* p0);
long lexer__TChar__parser_index(val* self);
void lexer__TChar__init_tk(val* self, val* p0);
long lexer__TBadString__parser_index(val* self);
void lexer__TBadString__init_tk(val* self, val* p0);
long lexer__TBadChar__parser_index(val* self);
void lexer__TBadChar__init_tk(val* self, val* p0);
long lexer__TExternCodeSegment__parser_index(val* self);
void lexer__TExternCodeSegment__init_tk(val* self, val* p0);
long lexer__EOF__parser_index(val* self);
val* string__NativeString__to_s_with_length(char* self, long p0);
void lexer__EOF__init_tk(val* self, val* p0);
extern const int COLOR_lexer__AError___message;
val* lexer__AError__message(val* self);
extern const int COLOR_lexer__EOF__init_tk;
void lexer__AError__init_error(val* self, val* p0, val* p1);
extern const int COLOR_lexer__ALexerError___string;
val* lexer__ALexerError__string(val* self);
extern const int COLOR_lexer__AError__init_error;
void lexer__ALexerError__init_lexer_error(val* self, val* p0, val* p1, val* p2);
extern const int COLOR_lexer__AParserError___token;
val* lexer__AParserError__token(val* self);
void lexer__AParserError__init_parser_error(val* self, val* p0, val* p1, val* p2);
extern const int COLOR_lexer__Lexer___file;
val* lexer__Lexer__file(val* self);
long lexer__Lexer__state_initial(val* self);
void lexer__Lexer__init(val* self, val* p0);
extern const int COLOR_lexer__Lexer___64dlast_token;
val* lexer__Lexer__last_token(val* self);
void lexer__Lexer__last_token_61d(val* self, val* p0);
extern const int COLOR_lexer__Lexer___token;
extern const int COLOR_lexer__Lexer__get_token;
extern const int COLOR_lexer__Lexer__last_token;
extern const int COLOR_parser_nodes__Token__next_token_61d;
extern const int COLOR_parser_nodes__Token__prev_token_61d;
extern const int COLOR_lexer__Lexer__last_token_61d;
val* lexer__Lexer__peek(val* self);
extern const int COLOR_lexer__Lexer__peek;
val* lexer__Lexer__next(val* self);
extern const int COLOR_lexer__Lexer___stream_pos;
extern const int COLOR_lexer__Lexer___pos;
extern const int COLOR_lexer__Lexer___line;
extern const int COLOR_location__SourceFile__string;
extern const int COLOR_abstract_collection__Collection__length;
extern const struct type type_kernel__Int;
extern const int COLOR_abstract_collection__SequenceRead___91d_93d;
extern const int COLOR_lexer__Lexer___cr;
extern const int COLOR_location__SourceFile__line_starts;
extern const int COLOR_abstract_collection__Sequence___91d_93d_61d;
extern const int COLOR_tables__TablesCapable__lexer_goto;
extern const int COLOR_tables__TablesCapable__lexer_accept;
val* NEW_location__Location(const struct type* type);
extern const struct type type_location__Location;
extern const int COLOR_location__Location__init;
val* NEW_parser_nodes__TEol(const struct type* type);
extern const struct type type_parser_nodes__TEol;
extern const int COLOR_lexer__TEol__init_tk;
val* NEW_parser_nodes__TComment(const struct type* type);
extern const struct type type_parser_nodes__TComment;
extern const int COLOR_lexer__TComment__init_tk;
val* NEW_parser_nodes__TKwpackage(const struct type* type);
extern const struct type type_parser_nodes__TKwpackage;
extern const int COLOR_lexer__TKwpackage__init_tk;
val* NEW_parser_nodes__TKwmodule(const struct type* type);
extern const struct type type_parser_nodes__TKwmodule;
extern const int COLOR_lexer__TKwmodule__init_tk;
val* NEW_parser_nodes__TKwimport(const struct type* type);
extern const struct type type_parser_nodes__TKwimport;
extern const int COLOR_lexer__TKwimport__init_tk;
val* NEW_parser_nodes__TKwclass(const struct type* type);
extern const struct type type_parser_nodes__TKwclass;
extern const int COLOR_lexer__TKwclass__init_tk;
val* NEW_parser_nodes__TKwabstract(const struct type* type);
extern const struct type type_parser_nodes__TKwabstract;
extern const int COLOR_lexer__TKwabstract__init_tk;
val* NEW_parser_nodes__TKwinterface(const struct type* type);
extern const struct type type_parser_nodes__TKwinterface;
extern const int COLOR_lexer__TKwinterface__init_tk;
val* NEW_parser_nodes__TKwenum(const struct type* type);
extern const struct type type_parser_nodes__TKwenum;
extern const int COLOR_lexer__TKwenum__init_tk;
val* NEW_parser_nodes__TKwend(const struct type* type);
extern const struct type type_parser_nodes__TKwend;
extern const int COLOR_lexer__TKwend__init_tk;
val* NEW_parser_nodes__TKwmeth(const struct type* type);
extern const struct type type_parser_nodes__TKwmeth;
extern const int COLOR_lexer__TKwmeth__init_tk;
val* NEW_parser_nodes__TKwtype(const struct type* type);
extern const struct type type_parser_nodes__TKwtype;
extern const int COLOR_lexer__TKwtype__init_tk;
val* NEW_parser_nodes__TKwinit(const struct type* type);
extern const struct type type_parser_nodes__TKwinit;
extern const int COLOR_lexer__TKwinit__init_tk;
val* NEW_parser_nodes__TKwredef(const struct type* type);
extern const struct type type_parser_nodes__TKwredef;
extern const int COLOR_lexer__TKwredef__init_tk;
val* NEW_parser_nodes__TKwis(const struct type* type);
extern const struct type type_parser_nodes__TKwis;
extern const int COLOR_lexer__TKwis__init_tk;
val* NEW_parser_nodes__TKwdo(const struct type* type);
extern const struct type type_parser_nodes__TKwdo;
extern const int COLOR_lexer__TKwdo__init_tk;
val* NEW_parser_nodes__TKwreadable(const struct type* type);
extern const struct type type_parser_nodes__TKwreadable;
extern const int COLOR_lexer__TKwreadable__init_tk;
val* NEW_parser_nodes__TKwwritable(const struct type* type);
extern const struct type type_parser_nodes__TKwwritable;
extern const int COLOR_lexer__TKwwritable__init_tk;
val* NEW_parser_nodes__TKwvar(const struct type* type);
extern const struct type type_parser_nodes__TKwvar;
extern const int COLOR_lexer__TKwvar__init_tk;
val* NEW_parser_nodes__TKwintern(const struct type* type);
extern const struct type type_parser_nodes__TKwintern;
extern const int COLOR_lexer__TKwintern__init_tk;
val* NEW_parser_nodes__TKwextern(const struct type* type);
extern const struct type type_parser_nodes__TKwextern;
extern const int COLOR_lexer__TKwextern__init_tk;
val* NEW_parser_nodes__TKwprotected(const struct type* type);
extern const struct type type_parser_nodes__TKwprotected;
extern const int COLOR_lexer__TKwprotected__init_tk;
val* NEW_parser_nodes__TKwprivate(const struct type* type);
extern const struct type type_parser_nodes__TKwprivate;
extern const int COLOR_lexer__TKwprivate__init_tk;
val* NEW_parser_nodes__TKwintrude(const struct type* type);
extern const struct type type_parser_nodes__TKwintrude;
extern const int COLOR_lexer__TKwintrude__init_tk;
val* NEW_parser_nodes__TKwif(const struct type* type);
extern const struct type type_parser_nodes__TKwif;
extern const int COLOR_lexer__TKwif__init_tk;
val* NEW_parser_nodes__TKwthen(const struct type* type);
extern const struct type type_parser_nodes__TKwthen;
extern const int COLOR_lexer__TKwthen__init_tk;
val* NEW_parser_nodes__TKwelse(const struct type* type);
extern const struct type type_parser_nodes__TKwelse;
extern const int COLOR_lexer__TKwelse__init_tk;
val* NEW_parser_nodes__TKwwhile(const struct type* type);
extern const struct type type_parser_nodes__TKwwhile;
extern const int COLOR_lexer__TKwwhile__init_tk;
val* NEW_parser_nodes__TKwloop(const struct type* type);
extern const struct type type_parser_nodes__TKwloop;
extern const int COLOR_lexer__TKwloop__init_tk;
val* NEW_parser_nodes__TKwfor(const struct type* type);
extern const struct type type_parser_nodes__TKwfor;
extern const int COLOR_lexer__TKwfor__init_tk;
val* NEW_parser_nodes__TKwin(const struct type* type);
extern const struct type type_parser_nodes__TKwin;
extern const int COLOR_lexer__TKwin__init_tk;
val* NEW_parser_nodes__TKwand(const struct type* type);
extern const struct type type_parser_nodes__TKwand;
extern const int COLOR_lexer__TKwand__init_tk;
val* NEW_parser_nodes__TKwor(const struct type* type);
extern const struct type type_parser_nodes__TKwor;
extern const int COLOR_lexer__TKwor__init_tk;
val* NEW_parser_nodes__TKwnot(const struct type* type);
extern const struct type type_parser_nodes__TKwnot;
extern const int COLOR_lexer__TKwnot__init_tk;
val* NEW_parser_nodes__TKwimplies(const struct type* type);
extern const struct type type_parser_nodes__TKwimplies;
extern const int COLOR_lexer__TKwimplies__init_tk;
val* NEW_parser_nodes__TKwreturn(const struct type* type);
extern const struct type type_parser_nodes__TKwreturn;
extern const int COLOR_lexer__TKwreturn__init_tk;
val* NEW_parser_nodes__TKwcontinue(const struct type* type);
extern const struct type type_parser_nodes__TKwcontinue;
extern const int COLOR_lexer__TKwcontinue__init_tk;
val* NEW_parser_nodes__TKwbreak(const struct type* type);
extern const struct type type_parser_nodes__TKwbreak;
extern const int COLOR_lexer__TKwbreak__init_tk;
val* NEW_parser_nodes__TKwabort(const struct type* type);
extern const struct type type_parser_nodes__TKwabort;
extern const int COLOR_lexer__TKwabort__init_tk;
val* NEW_parser_nodes__TKwassert(const struct type* type);
extern const struct type type_parser_nodes__TKwassert;
extern const int COLOR_lexer__TKwassert__init_tk;
val* NEW_parser_nodes__TKwnew(const struct type* type);
extern const struct type type_parser_nodes__TKwnew;
extern const int COLOR_lexer__TKwnew__init_tk;
val* NEW_parser_nodes__TKwisa(const struct type* type);
extern const struct type type_parser_nodes__TKwisa;
extern const int COLOR_lexer__TKwisa__init_tk;
val* NEW_parser_nodes__TKwonce(const struct type* type);
extern const struct type type_parser_nodes__TKwonce;
extern const int COLOR_lexer__TKwonce__init_tk;
val* NEW_parser_nodes__TKwsuper(const struct type* type);
extern const struct type type_parser_nodes__TKwsuper;
extern const int COLOR_lexer__TKwsuper__init_tk;
val* NEW_parser_nodes__TKwself(const struct type* type);
extern const struct type type_parser_nodes__TKwself;
extern const int COLOR_lexer__TKwself__init_tk;
val* NEW_parser_nodes__TKwtrue(const struct type* type);
extern const struct type type_parser_nodes__TKwtrue;
extern const int COLOR_lexer__TKwtrue__init_tk;
val* NEW_parser_nodes__TKwfalse(const struct type* type);
extern const struct type type_parser_nodes__TKwfalse;
extern const int COLOR_lexer__TKwfalse__init_tk;
val* NEW_parser_nodes__TKwnull(const struct type* type);
extern const struct type type_parser_nodes__TKwnull;
extern const int COLOR_lexer__TKwnull__init_tk;
val* NEW_parser_nodes__TKwas(const struct type* type);
extern const struct type type_parser_nodes__TKwas;
extern const int COLOR_lexer__TKwas__init_tk;
val* NEW_parser_nodes__TKwnullable(const struct type* type);
extern const struct type type_parser_nodes__TKwnullable;
extern const int COLOR_lexer__TKwnullable__init_tk;
val* NEW_parser_nodes__TKwisset(const struct type* type);
extern const struct type type_parser_nodes__TKwisset;
extern const int COLOR_lexer__TKwisset__init_tk;
val* NEW_parser_nodes__TKwlabel(const struct type* type);
extern const struct type type_parser_nodes__TKwlabel;
extern const int COLOR_lexer__TKwlabel__init_tk;
val* NEW_parser_nodes__TKwdebug(const struct type* type);
extern const struct type type_parser_nodes__TKwdebug;
extern const int COLOR_lexer__TKwdebug__init_tk;
val* NEW_parser_nodes__TOpar(const struct type* type);
extern const struct type type_parser_nodes__TOpar;
extern const int COLOR_lexer__TOpar__init_tk;
val* NEW_parser_nodes__TCpar(const struct type* type);
extern const struct type type_parser_nodes__TCpar;
extern const int COLOR_lexer__TCpar__init_tk;
val* NEW_parser_nodes__TObra(const struct type* type);
extern const struct type type_parser_nodes__TObra;
extern const int COLOR_lexer__TObra__init_tk;
val* NEW_parser_nodes__TCbra(const struct type* type);
extern const struct type type_parser_nodes__TCbra;
extern const int COLOR_lexer__TCbra__init_tk;
val* NEW_parser_nodes__TComma(const struct type* type);
extern const struct type type_parser_nodes__TComma;
extern const int COLOR_lexer__TComma__init_tk;
val* NEW_parser_nodes__TColumn(const struct type* type);
extern const struct type type_parser_nodes__TColumn;
extern const int COLOR_lexer__TColumn__init_tk;
val* NEW_parser_nodes__TQuad(const struct type* type);
extern const struct type type_parser_nodes__TQuad;
extern const int COLOR_lexer__TQuad__init_tk;
val* NEW_parser_nodes__TAssign(const struct type* type);
extern const struct type type_parser_nodes__TAssign;
extern const int COLOR_lexer__TAssign__init_tk;
val* NEW_parser_nodes__TPluseq(const struct type* type);
extern const struct type type_parser_nodes__TPluseq;
extern const int COLOR_lexer__TPluseq__init_tk;
val* NEW_parser_nodes__TMinuseq(const struct type* type);
extern const struct type type_parser_nodes__TMinuseq;
extern const int COLOR_lexer__TMinuseq__init_tk;
val* NEW_parser_nodes__TDotdotdot(const struct type* type);
extern const struct type type_parser_nodes__TDotdotdot;
extern const int COLOR_lexer__TDotdotdot__init_tk;
val* NEW_parser_nodes__TDotdot(const struct type* type);
extern const struct type type_parser_nodes__TDotdot;
extern const int COLOR_lexer__TDotdot__init_tk;
val* NEW_parser_nodes__TDot(const struct type* type);
extern const struct type type_parser_nodes__TDot;
extern const int COLOR_lexer__TDot__init_tk;
val* NEW_parser_nodes__TPlus(const struct type* type);
extern const struct type type_parser_nodes__TPlus;
extern const int COLOR_lexer__TPlus__init_tk;
val* NEW_parser_nodes__TMinus(const struct type* type);
extern const struct type type_parser_nodes__TMinus;
extern const int COLOR_lexer__TMinus__init_tk;
val* NEW_parser_nodes__TStar(const struct type* type);
extern const struct type type_parser_nodes__TStar;
extern const int COLOR_lexer__TStar__init_tk;
val* NEW_parser_nodes__TSlash(const struct type* type);
extern const struct type type_parser_nodes__TSlash;
extern const int COLOR_lexer__TSlash__init_tk;
val* NEW_parser_nodes__TPercent(const struct type* type);
extern const struct type type_parser_nodes__TPercent;
extern const int COLOR_lexer__TPercent__init_tk;
val* NEW_parser_nodes__TEq(const struct type* type);
extern const struct type type_parser_nodes__TEq;
extern const int COLOR_lexer__TEq__init_tk;
val* NEW_parser_nodes__TNe(const struct type* type);
extern const struct type type_parser_nodes__TNe;
extern const int COLOR_lexer__TNe__init_tk;
val* NEW_parser_nodes__TLt(const struct type* type);
extern const struct type type_parser_nodes__TLt;
extern const int COLOR_lexer__TLt__init_tk;
val* NEW_parser_nodes__TLe(const struct type* type);
extern const struct type type_parser_nodes__TLe;
extern const int COLOR_lexer__TLe__init_tk;
val* NEW_parser_nodes__TLl(const struct type* type);
extern const struct type type_parser_nodes__TLl;
extern const int COLOR_lexer__TLl__init_tk;
val* NEW_parser_nodes__TGt(const struct type* type);
extern const struct type type_parser_nodes__TGt;
extern const int COLOR_lexer__TGt__init_tk;
val* NEW_parser_nodes__TGe(const struct type* type);
extern const struct type type_parser_nodes__TGe;
extern const int COLOR_lexer__TGe__init_tk;
val* NEW_parser_nodes__TGg(const struct type* type);
extern const struct type type_parser_nodes__TGg;
extern const int COLOR_lexer__TGg__init_tk;
val* NEW_parser_nodes__TStarship(const struct type* type);
extern const struct type type_parser_nodes__TStarship;
extern const int COLOR_lexer__TStarship__init_tk;
val* NEW_parser_nodes__TBang(const struct type* type);
extern const struct type type_parser_nodes__TBang;
extern const int COLOR_lexer__TBang__init_tk;
val* NEW_parser_nodes__TAt(const struct type* type);
extern const struct type type_parser_nodes__TAt;
extern const int COLOR_lexer__TAt__init_tk;
val* NEW_parser_nodes__TClassid(const struct type* type);
extern const struct type type_parser_nodes__TClassid;
extern const int COLOR_lexer__TClassid__init_tk;
val* NEW_parser_nodes__TId(const struct type* type);
extern const struct type type_parser_nodes__TId;
extern const int COLOR_lexer__TId__init_tk;
val* NEW_parser_nodes__TAttrid(const struct type* type);
extern const struct type type_parser_nodes__TAttrid;
extern const int COLOR_lexer__TAttrid__init_tk;
val* NEW_parser_nodes__TNumber(const struct type* type);
extern const struct type type_parser_nodes__TNumber;
extern const int COLOR_lexer__TNumber__init_tk;
val* NEW_parser_nodes__TFloat(const struct type* type);
extern const struct type type_parser_nodes__TFloat;
extern const int COLOR_lexer__TFloat__init_tk;
val* NEW_parser_nodes__TString(const struct type* type);
extern const struct type type_parser_nodes__TString;
extern const int COLOR_lexer__TString__init_tk;
val* NEW_parser_nodes__TStartString(const struct type* type);
extern const struct type type_parser_nodes__TStartString;
extern const int COLOR_lexer__TStartString__init_tk;
val* NEW_parser_nodes__TMidString(const struct type* type);
extern const struct type type_parser_nodes__TMidString;
extern const int COLOR_lexer__TMidString__init_tk;
val* NEW_parser_nodes__TEndString(const struct type* type);
extern const struct type type_parser_nodes__TEndString;
extern const int COLOR_lexer__TEndString__init_tk;
val* NEW_parser_nodes__TChar(const struct type* type);
extern const struct type type_parser_nodes__TChar;
extern const int COLOR_lexer__TChar__init_tk;
val* NEW_parser_nodes__TBadString(const struct type* type);
extern const struct type type_parser_nodes__TBadString;
extern const int COLOR_lexer__TBadString__init_tk;
val* NEW_parser_nodes__TBadChar(const struct type* type);
extern const struct type type_parser_nodes__TBadChar;
extern const int COLOR_lexer__TBadChar__init_tk;
val* NEW_parser_nodes__TExternCodeSegment(const struct type* type);
extern const struct type type_parser_nodes__TExternCodeSegment;
extern const int COLOR_lexer__TExternCodeSegment__init_tk;
extern const int COLOR_string__AbstractString__substring;
val* NEW_parser_nodes__ALexerError(const struct type* type);
extern const struct type type_parser_nodes__ALexerError;
val* NEW_array__Array(const struct type* type);
extern const struct type type_array__Arraykernel__Object;
extern const int COLOR_array__Array__with_capacity;
extern const int COLOR_abstract_collection__SimpleCollection__add;
extern const int COLOR_string__Object__to_s;
extern const int COLOR_lexer__ALexerError__init_lexer_error;
val* NEW_parser_nodes__EOF(const struct type* type);
extern const struct type type_parser_nodes__EOF;
val* lexer__Lexer__get_token(val* self);
