#include "nit.common.h"
extern const int COLOR_literal__ToolContext___64dliteral_phase;
val* literal__ToolContext__literal_phase(val* self);
void literal__ToolContext__literal_phase_61d(val* self, val* p0);
extern const int COLOR_phase__Phase__toolcontext;
extern const int COLOR_literal__AModule__do_literal;
void literal__LiteralPhase__process_nmodule(val* self, val* p0);
val* NEW_literal__LiteralVisitor(const struct type* type);
extern const struct type type_literal__LiteralVisitor;
extern const int COLOR_literal__LiteralVisitor__init;
extern const int COLOR_parser_nodes__Visitor__enter_visit;
void literal__AModule__do_literal(val* self, val* p0);
extern const int COLOR_literal__LiteralVisitor___64dtoolcontext;
val* literal__LiteralVisitor__toolcontext(val* self);
void literal__LiteralVisitor__toolcontext_61d(val* self, val* p0);
extern const int COLOR_parser_nodes__Visitor__init;
extern const int COLOR_literal__LiteralVisitor__toolcontext_61d;
void literal__LiteralVisitor__init(val* self, val* p0);
extern const int COLOR_literal__ANode__accept_literal;
extern const int COLOR_parser_nodes__ANode__visit_all;
void literal__LiteralVisitor__visit(val* self, val* p0);
void literal__ANode__accept_literal(val* self, val* p0);
extern const int COLOR_literal__AIntExpr___64dvalue;
val* literal__AIntExpr__value(val* self);
void literal__AIntExpr__value_61d(val* self, val* p0);
extern const int COLOR_parser_nodes__AIntExpr__n_number;
extern const int COLOR_parser_nodes__Token__text;
extern const int COLOR_string__AbstractString__to_i;
extern const int COLOR_literal__AIntExpr__value_61d;
void literal__AIntExpr__accept_literal(val* self, val* p0);
extern const int COLOR_literal__AFloatExpr___64dvalue;
val* literal__AFloatExpr__value(val* self);
void literal__AFloatExpr__value_61d(val* self, val* p0);
extern const int COLOR_parser_nodes__AFloatExpr__n_float;
extern const int COLOR_string__AbstractString__to_f;
extern const int COLOR_literal__AFloatExpr__value_61d;
void literal__AFloatExpr__accept_literal(val* self, val* p0);
extern const int COLOR_literal__ACharExpr___64dvalue;
val* literal__ACharExpr__value(val* self);
void literal__ACharExpr__value_61d(val* self, val* p0);
extern const int COLOR_parser_nodes__ACharExpr__n_char;
extern const int COLOR_string__AbstractString__unescape_nit;
extern const int COLOR_abstract_collection__Collection__length;
extern const int COLOR_literal__LiteralVisitor__toolcontext;
extern const int COLOR_parser_nodes__ANode__hot_location;
val* string__NativeString__to_s_with_length(char* self, long p0);
val* NEW_array__Array(const struct type* type);
extern const struct type type_array__Arraykernel__Object;
val* NEW_array__NativeArray(int length, const struct type* type);
extern const struct type type_array__NativeArraykernel__Object;
extern const int COLOR_array__Array__with_native;
extern const int COLOR_string__Object__to_s;
extern const int COLOR_toolcontext__ToolContext__error;
extern const int COLOR_abstract_collection__SequenceRead___91d_93d;
extern const int COLOR_literal__ACharExpr__value_61d;
void literal__ACharExpr__accept_literal(val* self, val* p0);
extern const int COLOR_literal__AStringFormExpr___64dvalue;
val* literal__AStringFormExpr__value(val* self);
void literal__AStringFormExpr__value_61d(val* self, val* p0);
extern const int COLOR_parser_nodes__AStringFormExpr__n_string;
extern const struct type type_kernel__Int;
extern const int COLOR_string__AbstractString__substring;
extern const int COLOR_literal__AStringFormExpr__value_61d;
void literal__AStringFormExpr__accept_literal(val* self, val* p0);
