#include "nit.common.h"
extern const int COLOR_location__SourceFile___64dfilename;
val* location__SourceFile__filename(val* self);
void location__SourceFile__filename_61d(val* self, val* p0);
extern const int COLOR_location__SourceFile___64dstring;
val* location__SourceFile__string(val* self);
void location__SourceFile__string_61d(val* self, val* p0);
extern const int COLOR_location__SourceFile__filename_61d;
extern const int COLOR_stream__IStream__read_all;
extern const int COLOR_location__SourceFile__string_61d;
extern const int COLOR_location__SourceFile__line_starts;
extern const int COLOR_abstract_collection__Sequence___91d_93d_61d;
void location__SourceFile__init(val* self, val* p0, val* p1);
void location__SourceFile__from_string(val* self, val* p0, val* p1);
extern const int COLOR_location__SourceFile___64dline_starts;
val* location__SourceFile__line_starts(val* self);
void location__SourceFile__line_starts_61d(val* self, val* p0);
extern const int COLOR_location__Location___64dfile;
val* location__Location__file(val* self);
void location__Location__file_61d(val* self, val* p0);
extern const int COLOR_location__Location___64dline_start;
long location__Location__line_start(val* self);
void location__Location__line_start_61d(val* self, long p0);
extern const int COLOR_location__Location___64dline_end;
long location__Location__line_end(val* self);
void location__Location__line_end_61d(val* self, long p0);
extern const int COLOR_location__Location___64dcolumn_start;
long location__Location__column_start(val* self);
void location__Location__column_start_61d(val* self, long p0);
extern const int COLOR_location__Location___64dcolumn_end;
long location__Location__column_end(val* self);
void location__Location__column_end_61d(val* self, long p0);
extern const int COLOR_location__Location__file_61d;
extern const int COLOR_location__Location__line_start_61d;
extern const int COLOR_location__Location__line_end_61d;
extern const int COLOR_location__Location__column_start_61d;
extern const int COLOR_location__Location__column_end_61d;
void location__Location__init(val* self, val* p0, long p1, long p2, long p3, long p4);
extern const int COLOR_location__Location__file;
extern const int COLOR_location__Location__line_start;
extern const int COLOR_abstract_collection__SequenceRead___91d_93d;
extern const int COLOR_location__Location__column_start;
long location__Location__pstart(val* self);
extern const int COLOR_location__Location__line_end;
extern const int COLOR_location__Location__column_end;
long location__Location__pend(val* self);
extern const int COLOR_location__Location__text_cache;
extern const int COLOR_location__Location__pstart;
extern const int COLOR_location__Location__pend;
extern const int COLOR_location__SourceFile__string;
extern const int COLOR_string__AbstractString__substring;
extern const int COLOR_location__Location__text_cache_61d;
val* location__Location__text(val* self);
extern const int COLOR_location__Location___64dtext_cache;
val* location__Location__text_cache(val* self);
void location__Location__text_cache_61d(val* self, val* p0);
extern const int COLOR_location__Location__init;
void location__Location__with_file(val* self, val* p0);
extern const struct type type_location__Location;
extern const int COLOR_kernel__Object___33d_61d;
short int location__Location___61d_61d(val* self, val* p0);
extern const struct type type_kernel__Int;
short int location__Location__located_in(val* self, val* p0);
val* string__NativeString__to_s_with_length(char* self, long p0);
extern const int COLOR_location__SourceFile__filename;
extern const int COLOR_abstract_collection__Collection__length;
extern const int COLOR_string__String___43d;
val* NEW_array__Array(const struct type* type);
extern const struct type type_array__Arraykernel__Object;
extern const int COLOR_array__Array__with_capacity;
extern const int COLOR_abstract_collection__SimpleCollection__add;
extern const int COLOR_string__Object__to_s;
val* location__Location__to_s(val* self);
extern const int COLOR_kernel__Object___61d_61d;
val* NEW_location__Location(const struct type* type);
val* location__Location__relative_to(val* self, val* p0);
extern const int COLOR_kernel__Comparable_VTOTHER;
extern const int COLOR_location__Location__located_in;
short int location__Location___60d(val* self, val* p0);
extern const struct class class_kernel__Char;
val* NEW_string__Buffer(const struct type* type);
extern const struct type type_string__Buffer;
extern const int COLOR_string__Buffer__init;
val* NEW_range__Range(const struct type* type);
extern const struct type type_range__Rangekernel__Int;
extern const int COLOR_range__Range__without_last;
extern const int COLOR_abstract_collection__Collection__iterator;
extern const int COLOR_abstract_collection__Iterator__is_ok;
extern const int COLOR_abstract_collection__Iterator__item;
extern const int COLOR_abstract_collection__Iterator__next;
val* location__Location__colored_line(val* self, val* p0);
