/* This C header file is generated by NIT to compile modules and programs that requires metamodel. */
#ifndef metamodel_2_sep
#define metamodel_2_sep
#include "vararg._sep.h"
#include "virtualtype._sep.h"
#include <nit_common.h>
#define LOCATE_metamodel "./metamodel//metamodel.nit"
extern const int SFT_metamodel[];
#endif
