#include "nit.common.h"
extern const int COLOR_modelize_class__ToolContext___64dmodelize_class_phase;
val* modelize_class__ToolContext__modelize_class_phase(val* self);
void modelize_class__ToolContext__modelize_class_phase_61d(val* self, val* p0);
extern const int COLOR_phase__Phase__toolcontext;
extern const int COLOR_modelbuilder__ToolContext__modelbuilder;
extern const int COLOR_modelize_class__ModelBuilder__build_classes;
void modelize_class__ModelizeClassPhase__process_nmodule(val* self, val* p0);
extern const int COLOR_modelbuilder__AModule__mmodule;
extern const struct type type_parser_nodes__AStdClassdef;
extern const int COLOR_parser_nodes__AStdClassdef__n_id;
extern const int COLOR_parser_nodes__Token__text;
extern const int COLOR_parser_nodes__AStdClassdef__n_classkind;
extern const int COLOR_modelize_class__AClasskind__mkind;
extern const int COLOR_parser_nodes__AStdClassdef__n_visibility;
extern const int COLOR_modelbuilder__AVisibility__mvisibility;
extern const int COLOR_parser_nodes__AStdClassdef__n_formaldefs;
extern const int COLOR_abstract_collection__Collection__length;
extern const int COLOR_model_base__Object__protected_visibility;
extern const int COLOR_kernel__Object___61d_61d;
val* string__NativeString__to_s_with_length(char* self, long p0);
extern const int COLOR_modelbuilder__ModelBuilder__error;
extern const int COLOR_model_base__Object__intrude_visibility;
extern const struct type type_parser_nodes__ATopClassdef;
extern const int COLOR_model__Object__interface_kind;
extern const int COLOR_model_base__Object__public_visibility;
extern const struct type type_parser_nodes__AMainClassdef;
extern const int COLOR_model__Object__concrete_kind;
extern const int COLOR_modelbuilder__ModelBuilder__try_get_mclass_by_name;
extern const int COLOR_parser_nodes__AStdClassdef__n_kwredef;
val* NEW_array__Array(const struct type* type);
extern const struct type type_array__Arraykernel__Object;
val* NEW_array__NativeArray(int length, const struct type* type);
extern const struct type type_array__NativeArraykernel__Object;
extern const int COLOR_array__Array__with_native;
extern const int COLOR_string__Object__to_s;
val* NEW_model__MClass(const struct type* type);
extern const struct type type_model__MClass;
extern const int COLOR_model__MClass__init;
extern const int COLOR_modelize_class__AModule__mclass2nclassdef;
extern const int COLOR_abstract_collection__MapRead__has_key;
extern const int COLOR_abstract_collection__MapRead___91d_93d;
extern const int COLOR_parser_nodes__ANode__location;
extern const int COLOR_location__Location__line_start;
extern const int COLOR_model__MClass__arity;
extern const int COLOR_kernel__Object___33d_61d;
extern const int COLOR_model__MClass__kind;
extern const int COLOR_model__MClass__visibility;
extern const int COLOR_modelize_class__AClassdef__mclass_61d;
extern const int COLOR_abstract_collection__Map___91d_93d_61d;
void modelize_class__ModelBuilder__build_a_mclass(val* self, val* p0, val* p1);
extern const int COLOR_modelize_class__AClassdef__mclass;
extern const struct type type_array__Arraystring__String;
extern const int COLOR_array__Array__init;
extern const struct type type_array__Arraymodel__MType;
extern const struct type type_kernel__Int;
val* NEW_range__Range(const struct type* type);
extern const struct type type_range__Rangekernel__Int;
extern const int COLOR_range__Range__without_last;
extern const int COLOR_abstract_collection__Collection__iterator;
extern const int COLOR_abstract_collection__Iterator__is_ok;
extern const int COLOR_abstract_collection__Iterator__item;
extern const int COLOR_abstract_collection__SequenceRead___91d_93d;
extern const int COLOR_parser_nodes__AFormaldef__n_id;
extern const int COLOR_abstract_collection__Collection__has;
extern const struct type type_kernel__Char;
extern const int COLOR_modelbuilder__ModelBuilder__warning;
extern const int COLOR_abstract_collection__Iterator__next;
extern const int COLOR_abstract_collection__SimpleCollection__add;
extern const int COLOR_model__MClass__mclass_type;
extern const int COLOR_model__MClassType__arguments;
extern const struct type type_model__MParameterType;
extern const int COLOR_modelize_class__AFormaldef__mtype_61d;
extern const int COLOR_parser_nodes__AFormaldef__n_type;
extern const int COLOR_modelize_class__ModelBuilder__resolve_mtype_unchecked;
extern const int COLOR_model__MType__need_anchor;
extern const int COLOR_modelize_class__AFormaldef__bound_61d;
extern const int COLOR_model__MClass__mclassdefs;
extern const int COLOR_abstract_collection__Collection__is_empty;
extern const int COLOR_model__MType__as_nullable;
extern const int COLOR_model__MClass__intro;
extern const int COLOR_model__MClassDef__bound_mtype;
extern const int COLOR_model__MClass__get_mtype;
val* NEW_model__MClassDef(const struct type* type);
extern const struct type type_model__MClassDef;
extern const int COLOR_model__MClassDef__init;
extern const int COLOR_modelize_class__AClassdef__mclassdef_61d;
extern const int COLOR_modelize_class__ModelBuilder__mclassdef2nclassdef;
extern const int COLOR_model__MClassDef__is_intro;
extern const int COLOR_modelbuilder__ModelBuilder__toolcontext;
extern const int COLOR_model__MClass__full_name;
extern const int COLOR_toolcontext__ToolContext__info;
void modelize_class__ModelBuilder__build_a_mclassdef(val* self, val* p0, val* p1);
extern const int COLOR_modelize_class__AClassdef__mclassdef;
extern const struct type type_array__Arraymodel__MClassType;
extern const int COLOR_parser_nodes__AStdClassdef__n_superclasses;
extern const int COLOR_parser_nodes__ASuperclass__n_type;
extern const struct type type_model__MClassType;
extern const int COLOR_model__Object__extern_kind;
extern const int COLOR_model__MClass__name;
extern const int COLOR_model__MClassDef__set_supertypes;
extern const int COLOR_string__Collection__join;
void modelize_class__ModelBuilder__collect_a_mclassdef_inheritance(val* self, val* p0, val* p1);
extern const int COLOR_model__MClassDef__supertypes;
extern const int COLOR_model__MType__is_subtype;
void modelize_class__ModelBuilder__check_supertypes(val* self, val* p0, val* p1);
extern const int COLOR_toolcontext__ToolContext__error_count;
extern const int COLOR_modelize_class__AModule__build_classes_is_done;
extern const int COLOR_modelize_class__AModule__build_classes_is_done_61d;
extern const int COLOR_mmodule__MModule__in_importation;
extern const int COLOR_poset__POSetElement__direct_greaters;
extern const int COLOR_modelbuilder__ModelBuilder__mmodule2nmodule;
extern const int COLOR_parser_nodes__AModule__n_classdefs;
extern const int COLOR_modelize_class__ModelBuilder__build_a_mclass;
extern const int COLOR_modelize_class__ModelBuilder__build_a_mclassdef;
extern const int COLOR_modelize_class__ModelBuilder__collect_a_mclassdef_inheritance;
extern const int COLOR_model__MClassDef__add_in_hierarchy;
extern const int COLOR_modelize_class__ModelBuilder__check_supertypes;
extern const int COLOR_modelize_class__AType__mtype;
extern const int COLOR_modelize_class__ModelBuilder__resolve_mtype;
val* NEW_hash_collection__HashMap(const struct type* type);
extern const struct type type_hash_collection__HashMapmodel__MClassmodel__MClassType;
extern const int COLOR_hash_collection__HashMap__init;
extern const int COLOR_model__MClassDef__in_hierarchy;
extern const int COLOR_poset__POSetElement__greaters;
extern const int COLOR_model__MClassType__mclass;
extern const int COLOR_model__MClassDef__mclass;
extern const int COLOR_model__MType__resolve_for;
extern const struct type type_array__Arraymodel__MClass;
val* NEW_array__ArrayMap(const struct type* type);
extern const struct type type_array__ArrayMapmodel__MClassparser_nodes__AType;
extern const int COLOR_array__ArrayMap__init;
void modelize_class__ModelBuilder__build_classes(val* self, val* p0);
extern const int COLOR_modelize_class__ModelBuilder___64dmclassdef2nclassdef;
val* modelize_class__ModelBuilder__mclassdef2nclassdef(val* self);
void modelize_class__ModelBuilder__mclassdef2nclassdef_61d(val* self, val* p0);
extern const int COLOR_parser_nodes__AType__n_id;
extern const int COLOR_parser_nodes__ANode__parent;
extern const struct type type_parser_nodes__AModule;
extern const int COLOR_modelbuilder__ModelBuilder__try_get_mproperty_by_name;
extern const struct type type_nullable_model__MVirtualTypeProp;
extern const int COLOR_parser_nodes__AType__n_types;
extern const int COLOR_model__MVirtualTypeProp__mvirtualtype;
extern const int COLOR_parser_nodes__AType__n_kwnullable;
extern const int COLOR_modelize_class__AType__mtype_61d;
extern const int COLOR_model__MClassDef__parameter_names;
val* modelize_class__ModelBuilder__resolve_mtype_unchecked(val* self, val* p0, val* p1, short int p2);
extern const int COLOR_modelize_class__AType__checked_mtype;
extern const struct type type_model__MGenericType;
extern const int COLOR_modelize_class__AType__checked_mtype_61d;
val* modelize_class__ModelBuilder__resolve_mtype(val* self, val* p0, val* p1);
extern const int COLOR_modelize_class__AModule___64dbuild_classes_is_done;
short int modelize_class__AModule__build_classes_is_done(val* self);
void modelize_class__AModule__build_classes_is_done_61d(val* self, short int p0);
extern const int COLOR_modelize_class__AModule___64dmclass2nclassdef;
val* modelize_class__AModule__mclass2nclassdef(val* self);
void modelize_class__AModule__mclass2nclassdef_61d(val* self, val* p0);
extern const int COLOR_modelize_class__AClassdef___64dmclass;
val* modelize_class__AClassdef__mclass(val* self);
void modelize_class__AClassdef__mclass_61d(val* self, val* p0);
extern const int COLOR_modelize_class__AClassdef___64dmclassdef;
val* modelize_class__AClassdef__mclassdef(val* self);
void modelize_class__AClassdef__mclassdef_61d(val* self, val* p0);
val* modelize_class__AClasskind__mkind(val* self);
val* modelize_class__AConcreteClasskind__mkind(val* self);
extern const int COLOR_model__Object__abstract_kind;
val* modelize_class__AAbstractClasskind__mkind(val* self);
val* modelize_class__AInterfaceClasskind__mkind(val* self);
extern const int COLOR_model__Object__enum_kind;
val* modelize_class__AEnumClasskind__mkind(val* self);
val* modelize_class__AExternClasskind__mkind(val* self);
extern const int COLOR_modelize_class__AFormaldef___64dmtype;
val* modelize_class__AFormaldef__mtype(val* self);
void modelize_class__AFormaldef__mtype_61d(val* self, val* p0);
extern const int COLOR_modelize_class__AFormaldef___64dbound;
val* modelize_class__AFormaldef__bound(val* self);
void modelize_class__AFormaldef__bound_61d(val* self, val* p0);
extern const int COLOR_modelize_class__AType___64dmtype;
val* modelize_class__AType__mtype(val* self);
void modelize_class__AType__mtype_61d(val* self, val* p0);
extern const int COLOR_modelize_class__AType___64dchecked_mtype;
short int modelize_class__AType__checked_mtype(val* self);
void modelize_class__AType__checked_mtype_61d(val* self, short int p0);
