#include "nit.common.h"
extern const int COLOR_modelize_property__ToolContext___64dmodelize_property_phase;
val* modelize_property__ToolContext__modelize_property_phase(val* self);
void modelize_property__ToolContext__modelize_property_phase_61d(val* self, val* p0);
extern const int COLOR_parser_nodes__AModule__n_classdefs;
extern const int COLOR_abstract_collection__Collection__iterator;
extern const int COLOR_abstract_collection__Iterator__is_ok;
extern const int COLOR_abstract_collection__Iterator__item;
extern const int COLOR_phase__Phase__toolcontext;
extern const int COLOR_modelbuilder__ToolContext__modelbuilder;
extern const int COLOR_modelize_property__ModelBuilder__build_properties;
extern const int COLOR_abstract_collection__Iterator__next;
void modelize_property__ModelizePropertyPhase__process_nmodule(val* self, val* p0);
extern const int COLOR_modelize_property__ModelBuilder___64dmpropdef2npropdef;
val* modelize_property__ModelBuilder__mpropdef2npropdef(val* self);
void modelize_property__ModelBuilder__mpropdef2npropdef_61d(val* self, val* p0);
extern const int COLOR_modelize_property__AClassdef__build_properties_is_done;
extern const int COLOR_modelize_property__AClassdef__build_properties_is_done_61d;
extern const int COLOR_modelize_class__AClassdef__mclassdef;
extern const int COLOR_model__MClassDef__in_hierarchy;
extern const int COLOR_poset__POSetElement__direct_greaters;
extern const int COLOR_modelize_class__ModelBuilder__mclassdef2nclassdef;
extern const int COLOR_abstract_collection__MapRead___91d_93d;
extern const int COLOR_parser_nodes__AClassdef__n_propdefs;
extern const int COLOR_modelize_property__APropdef__build_property;
extern const int COLOR_modelize_property__APropdef__build_signature;
extern const int COLOR_modelize_property__APropdef__check_signature;
extern const int COLOR_modelize_property__ModelBuilder__process_default_constructors;
void modelize_property__ModelBuilder__build_properties(val* self, val* p0);
extern const int COLOR_model__MClassDef__is_intro;
extern const int COLOR_model__MClassDef__mclass;
extern const int COLOR_model__MClass__kind;
extern const int COLOR_model__MClassKind__need_init;
extern const int COLOR_model__MClassDef__mpropdefs;
extern const struct type type_model__MMethodDef;
extern const int COLOR_model__MPropDef__mproperty;
extern const int COLOR_model__MMethod__is_init;
extern const struct type type_parser_nodes__AStdClassdef;
extern const int COLOR_model__MClassDef__mmodule;
val* NEW_array__Array(const struct type* type);
extern const struct type type_array__Arraymodel__MMethod;
extern const int COLOR_array__Array__init;
extern const int COLOR_model__MClassDef__supertypes;
extern const int COLOR_model__MClassType__mclass;
extern const int COLOR_model__MClassDef__bound_mtype;
extern const int COLOR_model__MType__anchor_to;
val* string__NativeString__to_s_with_length(char* self, long p0);
extern const int COLOR_modelbuilder__ModelBuilder__try_get_mproperty_by_name2;
extern const struct type type_nullable_model__MMethod;
extern const int COLOR_model__MProperty__intro;
extern const int COLOR_model__MMethodDef__msignature;
extern const int COLOR_model__MSignature__arity;
extern const int COLOR_abstract_collection__SimpleCollection__add;
extern const int COLOR_modelize_property__MClass__inherit_init_from;
extern const int COLOR_kernel__Object___61d_61d;
extern const struct type type_array__Arraykernel__Object;
val* NEW_array__NativeArray(int length, const struct type* type);
extern const struct type type_array__NativeArraykernel__Object;
extern const int COLOR_array__Array__with_native;
extern const int COLOR_string__Object__to_s;
extern const int COLOR_modelbuilder__ModelBuilder__error;
extern const int COLOR_abstract_collection__Collection__is_empty;
extern const int COLOR_modelbuilder__ModelBuilder__toolcontext;
extern const int COLOR_toolcontext__ToolContext__info;
extern const int COLOR_modelize_property__MClass__inherit_init_from_61d;
extern const int COLOR_string__Collection__join;
extern const int COLOR_modelize_property__AClassdef__super_inits_61d;
val* NEW_model__MMethod(const struct type* type);
extern const struct type type_model__MMethod;
extern const int COLOR_model__MClass__visibility;
extern const int COLOR_model__MMethod__init;
val* NEW_model__MMethodDef(const struct type* type);
extern const int COLOR_parser_nodes__ANode__location;
extern const int COLOR_model__MMethodDef__init;
extern const struct type type_array__Arraymodel__MParameter;
val* NEW_model__MSignature(const struct type* type);
extern const struct type type_model__MSignature;
extern const int COLOR_model__MSignature__init;
extern const int COLOR_model__MMethodDef__msignature_61d;
extern const int COLOR_model__MMethod__is_init_61d;
extern const int COLOR_modelize_property__AClassdef__mfree_init_61d;
extern const struct type type_parser_nodes__AAttrPropdef;
extern const int COLOR_parser_nodes__AAttrPropdef__n_expr;
extern const int COLOR_modelize_property__APropdef__mpropdef;
extern const int COLOR_model__MProperty__name;
extern const int COLOR_string__AbstractString__substring_from;
extern const int COLOR_model__MAttributeDef__static_mtype;
val* NEW_model__MParameter(const struct type* type);
extern const struct type type_model__MParameter;
extern const int COLOR_model__MParameter__init;
void modelize_property__ModelBuilder__process_default_constructors(val* self, val* p0);
extern const int COLOR_modelize_property__MClass___64dinherit_init_from;
val* modelize_property__MClass__inherit_init_from(val* self);
void modelize_property__MClass__inherit_init_from_61d(val* self, val* p0);
extern const int COLOR_modelize_property__AClassdef___64dbuild_properties_is_done;
short int modelize_property__AClassdef__build_properties_is_done(val* self);
void modelize_property__AClassdef__build_properties_is_done_61d(val* self, short int p0);
extern const int COLOR_modelize_property__AClassdef___64dsuper_inits;
val* modelize_property__AClassdef__super_inits(val* self);
void modelize_property__AClassdef__super_inits_61d(val* self, val* p0);
extern const int COLOR_modelize_property__AClassdef___64dmfree_init;
val* modelize_property__AClassdef__mfree_init(val* self);
void modelize_property__AClassdef__mfree_init_61d(val* self, val* p0);
extern const int COLOR_modelize_property__AClassdef___64dmprop2npropdef;
val* modelize_property__AClassdef__mprop2npropdef(val* self);
void modelize_property__AClassdef__mprop2npropdef_61d(val* self, val* p0);
val* NEW_modelize_property__TextCollectorVisitor(const struct type* type);
extern const struct type type_modelize_property__TextCollectorVisitor;
extern const int COLOR_modelize_property__TextCollectorVisitor__init;
extern const int COLOR_parser_nodes__Visitor__enter_visit;
extern const int COLOR_modelize_property__TextCollectorVisitor__text;
extern const int COLOR_kernel__Object___33d_61d;
val* modelize_property__Prod__collect_text(val* self);
extern const int COLOR_modelize_property__TextCollectorVisitor___64dtext;
val* modelize_property__TextCollectorVisitor__text(val* self);
void modelize_property__TextCollectorVisitor__text_61d(val* self, val* p0);
extern const struct type type_parser_nodes__Token;
extern const int COLOR_parser_nodes__Token__text;
extern const int COLOR_string__String___43d;
extern const int COLOR_modelize_property__TextCollectorVisitor__text_61d;
extern const int COLOR_parser_nodes__ANode__visit_all;
void modelize_property__TextCollectorVisitor__visit(val* self, val* p0);
extern const int COLOR_parser_nodes__Visitor__init;
void modelize_property__TextCollectorVisitor__init(val* self);
extern const int COLOR_modelize_property__APropdef___64dmpropdef;
val* modelize_property__APropdef__mpropdef(val* self);
extern const int COLOR_parser_nodes__APropdef_VTMPROPDEF;
void modelize_property__APropdef__mpropdef_61d(val* self, val* p0);
void modelize_property__APropdef__build_property(val* self, val* p0, val* p1);
void modelize_property__APropdef__build_signature(val* self, val* p0, val* p1);
void modelize_property__APropdef__check_signature(val* self, val* p0, val* p1);
extern const int COLOR_model_base__Object__public_visibility;
extern const int COLOR_modelbuilder__AVisibility__mvisibility;
extern const int COLOR_model_base__Object__intrude_visibility;
extern const int COLOR_model_base__Object__private_visibility;
extern const int COLOR_model_base__Object__protected_visibility;
val* modelize_property__APropdef__new_property_visibility(val* self, val* p0, val* p1, val* p2);
extern const int COLOR_model__MProperty__visibility;
void modelize_property__APropdef__check_redef_property_visibility(val* self, val* p0, val* p1, val* p2, val* p3);
extern const int COLOR_modelize_property__AClassdef__mprop2npropdef;
extern const int COLOR_abstract_collection__MapRead__has_key;
short int modelize_property__APropdef__check_redef_keyword(val* self, val* p0, val* p1, val* p2, short int p3, val* p4);
extern const int COLOR_modelize_property__ASignature___64dis_visited;
short int modelize_property__ASignature__is_visited(val* self);
void modelize_property__ASignature__is_visited_61d(val* self, short int p0);
extern const int COLOR_modelize_property__ASignature___64dparam_names;
val* modelize_property__ASignature__param_names(val* self);
void modelize_property__ASignature__param_names_61d(val* self, val* p0);
extern const int COLOR_modelize_property__ASignature___64dparam_types;
val* modelize_property__ASignature__param_types(val* self);
void modelize_property__ASignature__param_types_61d(val* self, val* p0);
extern const int COLOR_modelize_property__ASignature___64dvararg_rank;
long modelize_property__ASignature__vararg_rank(val* self);
void modelize_property__ASignature__vararg_rank_61d(val* self, long p0);
extern const int COLOR_modelize_property__ASignature___64dret_type;
val* modelize_property__ASignature__ret_type(val* self);
void modelize_property__ASignature__ret_type_61d(val* self, val* p0);
extern const int COLOR_modelize_property__ASignature__param_names;
extern const int COLOR_modelize_property__ASignature__param_types;
extern const int COLOR_parser_nodes__ASignature__n_params;
extern const int COLOR_parser_nodes__AParam__n_id;
extern const int COLOR_parser_nodes__AParam__n_type;
extern const int COLOR_modelize_class__ModelBuilder__resolve_mtype;
val* NEW_range__Range(const struct type* type);
extern const struct type type_range__Rangekernel__Int;
extern const int COLOR_abstract_collection__Collection__length;
extern const int COLOR_range__Range__without_last;
extern const int COLOR_parser_nodes__AParam__n_dotdotdot;
extern const int COLOR_modelize_property__ASignature__vararg_rank;
extern const int COLOR_abstract_collection__SequenceRead___91d_93d;
extern const int COLOR_modelize_property__ASignature__vararg_rank_61d;
extern const int COLOR_parser_nodes__ASignature__n_type;
extern const int COLOR_modelize_property__ASignature__ret_type_61d;
extern const int COLOR_modelize_property__ASignature__ret_type;
extern const int COLOR_modelize_property__ASignature__is_visited_61d;
short int modelize_property__ASignature__visit_signature(val* self, val* p0, val* p1);
extern const int COLOR_modelize_property__AParam__mparameter_61d;
val* modelize_property__ASignature__build_signature(val* self, val* p0, val* p1);
extern const int COLOR_modelize_property__AParam___64dmparameter;
val* modelize_property__AParam__mparameter(val* self);
void modelize_property__AParam__mparameter_61d(val* self, val* p0);
extern const struct type type_parser_nodes__AInitPropdef;
extern const int COLOR_parser_nodes__AMethPropdef__n_methid;
extern const struct type type_parser_nodes__AMainMethPropdef;
extern const struct type type_parser_nodes__AConcreteInitPropdef;
extern const int COLOR_parser_nodes__AConcreteInitPropdef__n_kwinit;
extern const struct type type_parser_nodes__AExternInitPropdef;
extern const int COLOR_parser_nodes__AExternInitPropdef__n_kwnew;
extern const struct type type_parser_nodes__AIdMethid;
extern const int COLOR_parser_nodes__AIdMethid__n_id;
extern const int COLOR_modelize_property__Prod__collect_text;
extern const int COLOR_parser_nodes__AMethPropdef__n_signature;
extern const int COLOR_parser_nodes__AMethPropdef__n_kwredef;
extern const int COLOR_modelbuilder__ModelBuilder__try_get_mproperty_by_name;
extern const int COLOR_parser_nodes__AMethPropdef__n_visibility;
extern const int COLOR_modelize_property__APropdef__new_property_visibility;
extern const int COLOR_model__MMethod__is_new_61d;
extern const int COLOR_modelize_property__APropdef__check_redef_keyword;
extern const int COLOR_modelize_property__APropdef__check_redef_property_visibility;
extern const int COLOR_abstract_collection__Map___91d_93d_61d;
extern const int COLOR_modelize_property__APropdef__mpropdef_61d;
extern const int COLOR_modelize_property__ModelBuilder__mpropdef2npropdef;
extern const int COLOR_model__MPropDef__is_intro;
extern const int COLOR_model__MProperty__full_name;
void modelize_property__AMethPropdef__build_property(val* self, val* p0, val* p1);
extern const int COLOR_model__MPropDef__mclassdef;
extern const struct type type_array__Arraystring__String;
extern const struct type type_array__Arraymodel__MType;
extern const int COLOR_modelize_property__ASignature__visit_signature;
extern const int COLOR_model__MSignature__mparameters;
extern const int COLOR_model__MParameter__mtype;
extern const int COLOR_model__MSignature__vararg_rank;
extern const int COLOR_model__MSignature__return_mtype;
extern const struct type type_parser_nodes__ADeferredMethPropdef;
extern const int COLOR_model__MMethodDef__is_abstract_61d;
void modelize_property__AMethPropdef__build_signature(val* self, val* p0, val* p1);
extern const struct type type_kernel__Int;
extern const int COLOR_model__MType__is_subtype;
extern const int COLOR_model__MParameter__name;
void modelize_property__AMethPropdef__check_signature(val* self, val* p0, val* p1);
extern const int COLOR_modelize_property__AAttrPropdef___64dmreadpropdef;
val* modelize_property__AAttrPropdef__mreadpropdef(val* self);
void modelize_property__AAttrPropdef__mreadpropdef_61d(val* self, val* p0);
extern const int COLOR_modelize_property__AAttrPropdef___64dmwritepropdef;
val* modelize_property__AAttrPropdef__mwritepropdef(val* self);
void modelize_property__AAttrPropdef__mwritepropdef_61d(val* self, val* p0);
extern const int COLOR_parser_nodes__AAttrPropdef__n_id;
extern const int COLOR_parser_nodes__AAttrPropdef__n_id2;
extern const int COLOR_model__Object__interface_kind;
extern const int COLOR_model__Object__enum_kind;
extern const int COLOR_model__Object__extern_kind;
extern const int COLOR_parser_nodes__AAttrPropdef__n_visibility;
val* NEW_model__MAttribute(const struct type* type);
extern const struct type type_model__MAttribute;
extern const int COLOR_model__MAttribute__init;
extern const int COLOR_parser_nodes__AAttrPropdef__n_kwredef;
val* NEW_model__MAttributeDef(const struct type* type);
extern const struct type type_model__MAttributeDef;
extern const int COLOR_model__MAttributeDef__init;
extern const int COLOR_parser_nodes__AAttrPropdef__n_readable;
extern const int COLOR_parser_nodes__AAble__n_visibility;
extern const int COLOR_parser_nodes__AAble__n_kwredef;
extern const int COLOR_modelize_property__AAttrPropdef__mreadpropdef_61d;
extern const int COLOR_parser_nodes__AAttrPropdef__n_writable;
extern const int COLOR_modelize_property__AAttrPropdef__mwritepropdef_61d;
extern const int COLOR_model_base__Object__none_visibility;
void modelize_property__AAttrPropdef__build_property(val* self, val* p0, val* p1);
extern const int COLOR_parser_nodes__AAttrPropdef__n_type;
extern const struct type type_parser_nodes__ANewExpr;
extern const int COLOR_parser_nodes__ANewExpr__n_type;
extern const struct type type_parser_nodes__AIntExpr;
extern const int COLOR_modelbuilder__ModelBuilder__try_get_mclass_by_name;
extern const int COLOR_model__MClass__mclass_type;
extern const struct type type_parser_nodes__AFloatExpr;
extern const struct type type_parser_nodes__ACharExpr;
extern const struct type type_parser_nodes__ABoolExpr;
extern const struct type type_parser_nodes__ASuperstringExpr;
extern const struct type type_parser_nodes__AStringFormExpr;
extern const int COLOR_toolcontext__ToolContext__opt_warn;
extern const int COLOR_opts__Option__value;
extern const int COLOR_modelbuilder__ModelBuilder__warning;
extern const int COLOR_model__MAttributeDef__static_mtype_61d;
extern const int COLOR_modelize_property__AAttrPropdef__mreadpropdef;
extern const int COLOR_modelize_property__AAttrPropdef__mwritepropdef;
extern const int COLOR_array__Array__with_capacity;
extern const int COLOR_abstract_collection__Sequence__push;
void modelize_property__AAttrPropdef__build_signature(val* self, val* p0, val* p1);
extern const int COLOR_modelize_property__AAttrPropdef__check_method_signature;
void modelize_property__AAttrPropdef__check_signature(val* self, val* p0, val* p1);
void modelize_property__AAttrPropdef__check_method_signature(val* self, val* p0, val* p1, val* p2);
extern const int COLOR_parser_nodes__ATypePropdef__n_id;
extern const int COLOR_parser_nodes__ATypePropdef__n_visibility;
val* NEW_model__MVirtualTypeProp(const struct type* type);
extern const struct type type_model__MVirtualTypeProp;
extern const int COLOR_model__MVirtualTypeProp__init;
extern const struct type type_kernel__Char;
extern const int COLOR_parser_nodes__ATypePropdef__n_kwredef;
val* NEW_model__MVirtualTypeDef(const struct type* type);
extern const struct type type_model__MVirtualTypeDef;
extern const int COLOR_model__MVirtualTypeDef__init;
void modelize_property__ATypePropdef__build_property(val* self, val* p0, val* p1);
extern const int COLOR_parser_nodes__ATypePropdef__n_type;
extern const int COLOR_model__MVirtualTypeDef__bound_61d;
void modelize_property__ATypePropdef__build_signature(val* self, val* p0, val* p1);
extern const int COLOR_model__MVirtualTypeDef__bound;
extern const struct type type_model__MVirtualType;
extern const struct type type_array__Arraymodel__MVirtualType;
extern const int COLOR_model__MVirtualTypeProp__mvirtualtype;
extern const int COLOR_abstract_collection__Collection__has;
extern const int COLOR_model__MVirtualType__lookup_bound;
void modelize_property__ATypePropdef__check_signature(val* self, val* p0, val* p1);
