/* This C header file is generated by NIT to compile modules and programs that requires ./native_interface/ni_metamodel. */
#ifndef native_interface___ni_metamodel_sep
#define native_interface___ni_metamodel_sep
#include "compiling._sep.h"
#include <nit_common.h>
extern const char LOCATE_native_interface___ni_metamodel[];
extern const int SFT_native_interface___ni_metamodel[];
#define CALL_native_interface___ni_metamodel___MMType___friendly_extern_name(recv) ((native_interface___ni_metamodel___MMType___friendly_extern_name_t)CALL((recv), (SFT_native_interface___ni_metamodel[0] + 0)))
#define CALL_native_interface___ni_metamodel___MMType___mangled_name(recv) ((native_interface___ni_metamodel___MMType___mangled_name_t)CALL((recv), (SFT_native_interface___ni_metamodel[0] + 1)))
#define CALL_native_interface___ni_metamodel___MMType___from_native(recv) ((native_interface___ni_metamodel___MMType___from_native_t)CALL((recv), (SFT_native_interface___ni_metamodel[0] + 2)))
#define CALL_native_interface___ni_metamodel___MMType___assign_to_friendly(recv) ((native_interface___ni_metamodel___MMType___assign_to_friendly_t)CALL((recv), (SFT_native_interface___ni_metamodel[0] + 3)))
#define CALL_native_interface___ni_metamodel___MMType___assign_from_friendly(recv) ((native_interface___ni_metamodel___MMType___assign_from_friendly_t)CALL((recv), (SFT_native_interface___ni_metamodel[0] + 4)))
#define CALL_native_interface___ni_metamodel___MMType___uses_nitni_ref(recv) ((native_interface___ni_metamodel___MMType___uses_nitni_ref_t)CALL((recv), (SFT_native_interface___ni_metamodel[0] + 5)))
#define CALL_native_interface___ni_metamodel___MMType___friendly_null_getter(recv) ((native_interface___ni_metamodel___MMType___friendly_null_getter_t)CALL((recv), (SFT_native_interface___ni_metamodel[0] + 6)))
#define CALL_native_interface___ni_metamodel___MMType___local_friendly_null_getter_from(recv) ((native_interface___ni_metamodel___MMType___local_friendly_null_getter_from_t)CALL((recv), (SFT_native_interface___ni_metamodel[0] + 7)))
#define CALL_native_interface___ni_metamodel___MMMethod___local_friendly_name_from(recv) ((native_interface___ni_metamodel___MMMethod___local_friendly_name_from_t)CALL((recv), (SFT_native_interface___ni_metamodel[1] + 0)))
#define CALL_native_interface___ni_metamodel___MMMethod___friendly_super_cname(recv) ((native_interface___ni_metamodel___MMMethod___friendly_super_cname_t)CALL((recv), (SFT_native_interface___ni_metamodel[1] + 1)))
#define CALL_native_interface___ni_metamodel___MMMethod___local_friendly_super_name_from(recv) ((native_interface___ni_metamodel___MMMethod___local_friendly_super_name_from_t)CALL((recv), (SFT_native_interface___ni_metamodel[1] + 2)))
#define CALL_native_interface___ni_metamodel___MMMethod___friendly_cparams(recv) ((native_interface___ni_metamodel___MMMethod___friendly_cparams_t)CALL((recv), (SFT_native_interface___ni_metamodel[1] + 3)))
#define CALL_native_interface___ni_metamodel___MMMethod___csignature_with_suffix(recv) ((native_interface___ni_metamodel___MMMethod___csignature_with_suffix_t)CALL((recv), (SFT_native_interface___ni_metamodel[1] + 4)))
#define CALL_native_interface___ni_metamodel___MMMethod___csignature_with_name(recv) ((native_interface___ni_metamodel___MMMethod___csignature_with_name_t)CALL((recv), (SFT_native_interface___ni_metamodel[1] + 5)))
#define CALL_native_interface___ni_metamodel___MMMethod___friendly_csignature(recv) ((native_interface___ni_metamodel___MMMethod___friendly_csignature_t)CALL((recv), (SFT_native_interface___ni_metamodel[1] + 6)))
#define CALL_native_interface___ni_metamodel___MMMethod___frontier_csignature_from(recv) ((native_interface___ni_metamodel___MMMethod___frontier_csignature_from_t)CALL((recv), (SFT_native_interface___ni_metamodel[1] + 7)))
#define CALL_native_interface___ni_metamodel___MMMethod___friendly_super_csignature(recv) ((native_interface___ni_metamodel___MMMethod___friendly_super_csignature_t)CALL((recv), (SFT_native_interface___ni_metamodel[1] + 8)))
#define CALL_native_interface___ni_metamodel___MMMethod___frontier_super_csignature_from(recv) ((native_interface___ni_metamodel___MMMethod___frontier_super_csignature_from_t)CALL((recv), (SFT_native_interface___ni_metamodel[1] + 9)))
#define CALL_native_interface___ni_metamodel___MMMethod___impl_csignature(recv) ((native_interface___ni_metamodel___MMMethod___impl_csignature_t)CALL((recv), (SFT_native_interface___ni_metamodel[1] + 10)))
#define CALL_native_interface___ni_metamodel___MMMethod___cparams(recv) ((native_interface___ni_metamodel___MMMethod___cparams_t)CALL((recv), (SFT_native_interface___ni_metamodel[1] + 11)))
#define CALL_native_interface___ni_metamodel___MMMethod___out_csignature(recv) ((native_interface___ni_metamodel___MMMethod___out_csignature_t)CALL((recv), (SFT_native_interface___ni_metamodel[1] + 12)))
#define ATTR_native_interface___ni_metamodel___MMImportedCast_____atin_name(recv) ATTR(recv, (SFT_native_interface___ni_metamodel[2] + 0))
#define CALL_native_interface___ni_metamodel___MMImportedCast___in_name(recv) ((native_interface___ni_metamodel___MMImportedCast___in_name_t)CALL((recv), (SFT_native_interface___ni_metamodel[3] + 0)))
#define CALL_native_interface___ni_metamodel___MMImportedCast___in_name__eq(recv) ((native_interface___ni_metamodel___MMImportedCast___in_name__eq_t)CALL((recv), (SFT_native_interface___ni_metamodel[3] + 1)))
#define CALL_native_interface___ni_metamodel___MMImportedCast___as_friendly_extern_name(recv) ((native_interface___ni_metamodel___MMImportedCast___as_friendly_extern_name_t)CALL((recv), (SFT_native_interface___ni_metamodel[3] + 2)))
#define CALL_native_interface___ni_metamodel___MMImportedCast___as_local_cname(recv) ((native_interface___ni_metamodel___MMImportedCast___as_local_cname_t)CALL((recv), (SFT_native_interface___ni_metamodel[3] + 3)))
#define CALL_native_interface___ni_metamodel___MMImportedCast___as_local_csignature(recv) ((native_interface___ni_metamodel___MMImportedCast___as_local_csignature_t)CALL((recv), (SFT_native_interface___ni_metamodel[3] + 4)))
#define CALL_native_interface___ni_metamodel___MMImportedCast___as_friendly_csignature(recv) ((native_interface___ni_metamodel___MMImportedCast___as_friendly_csignature_t)CALL((recv), (SFT_native_interface___ni_metamodel[3] + 5)))
#define CALL_native_interface___ni_metamodel___MMImportedCast___is_a_friendly_extern_name(recv) ((native_interface___ni_metamodel___MMImportedCast___is_a_friendly_extern_name_t)CALL((recv), (SFT_native_interface___ni_metamodel[3] + 6)))
#define CALL_native_interface___ni_metamodel___MMImportedCast___is_a_local_cname(recv) ((native_interface___ni_metamodel___MMImportedCast___is_a_local_cname_t)CALL((recv), (SFT_native_interface___ni_metamodel[3] + 7)))
#define CALL_native_interface___ni_metamodel___MMImportedCast___is_a_local_csignature(recv) ((native_interface___ni_metamodel___MMImportedCast___is_a_local_csignature_t)CALL((recv), (SFT_native_interface___ni_metamodel[3] + 8)))
#define CALL_native_interface___ni_metamodel___MMImportedCast___is_a_friendly_csignature(recv) ((native_interface___ni_metamodel___MMImportedCast___is_a_friendly_csignature_t)CALL((recv), (SFT_native_interface___ni_metamodel[3] + 9)))
val_t native_interface___ni_metamodel___MMType___friendly_extern_name(val_t p0);
typedef val_t (*native_interface___ni_metamodel___MMType___friendly_extern_name_t)(val_t p0);
val_t native_interface___ni_metamodel___MMType___mangled_name(val_t p0);
typedef val_t (*native_interface___ni_metamodel___MMType___mangled_name_t)(val_t p0);
val_t native_interface___ni_metamodel___MMType___from_native(val_t p0, val_t p1);
typedef val_t (*native_interface___ni_metamodel___MMType___from_native_t)(val_t p0, val_t p1);
val_t native_interface___ni_metamodel___MMType___assign_to_friendly(val_t p0, val_t p1, val_t p2);
typedef val_t (*native_interface___ni_metamodel___MMType___assign_to_friendly_t)(val_t p0, val_t p1, val_t p2);
val_t native_interface___ni_metamodel___MMType___assign_from_friendly(val_t p0, val_t p1, val_t p2);
typedef val_t (*native_interface___ni_metamodel___MMType___assign_from_friendly_t)(val_t p0, val_t p1, val_t p2);
val_t native_interface___ni_metamodel___MMType___uses_nitni_ref(val_t p0);
typedef val_t (*native_interface___ni_metamodel___MMType___uses_nitni_ref_t)(val_t p0);
val_t native_interface___ni_metamodel___MMType___friendly_null_getter(val_t p0);
typedef val_t (*native_interface___ni_metamodel___MMType___friendly_null_getter_t)(val_t p0);
val_t native_interface___ni_metamodel___MMType___local_friendly_null_getter_from(val_t p0, val_t p1);
typedef val_t (*native_interface___ni_metamodel___MMType___local_friendly_null_getter_from_t)(val_t p0, val_t p1);
val_t NEW_MMType_metamodel___static_type___MMType___init();
val_t native_interface___ni_metamodel___MMMethod___local_friendly_name_from(val_t p0, val_t p1, val_t p2);
typedef val_t (*native_interface___ni_metamodel___MMMethod___local_friendly_name_from_t)(val_t p0, val_t p1, val_t p2);
val_t native_interface___ni_metamodel___MMMethod___friendly_super_cname(val_t p0);
typedef val_t (*native_interface___ni_metamodel___MMMethod___friendly_super_cname_t)(val_t p0);
val_t native_interface___ni_metamodel___MMMethod___local_friendly_super_name_from(val_t p0, val_t p1);
typedef val_t (*native_interface___ni_metamodel___MMMethod___local_friendly_super_name_from_t)(val_t p0, val_t p1);
val_t native_interface___ni_metamodel___MMMethod___friendly_cparams(val_t p0, val_t p1);
typedef val_t (*native_interface___ni_metamodel___MMMethod___friendly_cparams_t)(val_t p0, val_t p1);
val_t native_interface___ni_metamodel___MMMethod___csignature_with_suffix(val_t p0, val_t p1, val_t p2);
typedef val_t (*native_interface___ni_metamodel___MMMethod___csignature_with_suffix_t)(val_t p0, val_t p1, val_t p2);
val_t native_interface___ni_metamodel___MMMethod___csignature_with_name(val_t p0, val_t p1, val_t p2);
typedef val_t (*native_interface___ni_metamodel___MMMethod___csignature_with_name_t)(val_t p0, val_t p1, val_t p2);
val_t native_interface___ni_metamodel___MMMethod___friendly_csignature(val_t p0, val_t p1);
typedef val_t (*native_interface___ni_metamodel___MMMethod___friendly_csignature_t)(val_t p0, val_t p1);
val_t native_interface___ni_metamodel___MMMethod___frontier_csignature_from(val_t p0, val_t p1, val_t p2);
typedef val_t (*native_interface___ni_metamodel___MMMethod___frontier_csignature_from_t)(val_t p0, val_t p1, val_t p2);
val_t native_interface___ni_metamodel___MMMethod___friendly_super_csignature(val_t p0);
typedef val_t (*native_interface___ni_metamodel___MMMethod___friendly_super_csignature_t)(val_t p0);
val_t native_interface___ni_metamodel___MMMethod___frontier_super_csignature_from(val_t p0, val_t p1);
typedef val_t (*native_interface___ni_metamodel___MMMethod___frontier_super_csignature_from_t)(val_t p0, val_t p1);
val_t native_interface___ni_metamodel___MMMethod___impl_csignature(val_t p0);
typedef val_t (*native_interface___ni_metamodel___MMMethod___impl_csignature_t)(val_t p0);
val_t native_interface___ni_metamodel___MMMethod___cparams(val_t p0);
typedef val_t (*native_interface___ni_metamodel___MMMethod___cparams_t)(val_t p0);
val_t native_interface___ni_metamodel___MMMethod___out_csignature(val_t p0);
typedef val_t (*native_interface___ni_metamodel___MMMethod___out_csignature_t)(val_t p0);
val_t NEW_MMMethod_metamodel___abstractmetamodel___MMLocalProperty___init(val_t p0, val_t p1);
val_t native_interface___ni_metamodel___MMImportedCast___in_name(val_t p0);
typedef val_t (*native_interface___ni_metamodel___MMImportedCast___in_name_t)(val_t p0);
void native_interface___ni_metamodel___MMImportedCast___in_name__eq(val_t p0, val_t p1);
typedef void (*native_interface___ni_metamodel___MMImportedCast___in_name__eq_t)(val_t p0, val_t p1);
val_t native_interface___ni_metamodel___MMImportedCast___as_friendly_extern_name(val_t p0);
typedef val_t (*native_interface___ni_metamodel___MMImportedCast___as_friendly_extern_name_t)(val_t p0);
val_t native_interface___ni_metamodel___MMImportedCast___as_local_cname(val_t p0, val_t p1);
typedef val_t (*native_interface___ni_metamodel___MMImportedCast___as_local_cname_t)(val_t p0, val_t p1);
val_t native_interface___ni_metamodel___MMImportedCast___as_local_csignature(val_t p0, val_t p1);
typedef val_t (*native_interface___ni_metamodel___MMImportedCast___as_local_csignature_t)(val_t p0, val_t p1);
val_t native_interface___ni_metamodel___MMImportedCast___as_friendly_csignature(val_t p0);
typedef val_t (*native_interface___ni_metamodel___MMImportedCast___as_friendly_csignature_t)(val_t p0);
val_t native_interface___ni_metamodel___MMImportedCast___is_a_friendly_extern_name(val_t p0);
typedef val_t (*native_interface___ni_metamodel___MMImportedCast___is_a_friendly_extern_name_t)(val_t p0);
val_t native_interface___ni_metamodel___MMImportedCast___is_a_local_cname(val_t p0, val_t p1);
typedef val_t (*native_interface___ni_metamodel___MMImportedCast___is_a_local_cname_t)(val_t p0, val_t p1);
val_t native_interface___ni_metamodel___MMImportedCast___is_a_local_csignature(val_t p0, val_t p1);
typedef val_t (*native_interface___ni_metamodel___MMImportedCast___is_a_local_csignature_t)(val_t p0, val_t p1);
val_t native_interface___ni_metamodel___MMImportedCast___is_a_friendly_csignature(val_t p0);
typedef val_t (*native_interface___ni_metamodel___MMImportedCast___is_a_friendly_csignature_t)(val_t p0);
val_t native_interface___ni_metamodel___MMImportedCast___hash(val_t p0);
typedef val_t (*native_interface___ni_metamodel___MMImportedCast___hash_t)(val_t p0);
val_t NEW_MMImportedCast_metamodel___static_type___MMImportedCast___init(val_t p0, val_t p1);
#endif
