#include "nit.common.h"
#define COLOR_nit__local_var_init__ToolContext___local_var_init_phase 36
extern const char FILE_nit__local_var_init[];
#define COLOR_nit__phase__Phase___toolcontext 0
extern const char FILE_nit__phase[];
void nit__local_var_init___APropdef___do_local_var_init(val* self, val* p0);
val* NEW_nit__local_var_init__LocalVarInitVisitor(const struct type* type);
extern const struct type type_nit__local_var_init__LocalVarInitVisitor;
#define COLOR_nit__local_var_init__LocalVarInitVisitor__toolcontext_61d 36
#define COLOR_standard__kernel__Object__init 7
void nit___nit__Visitor___enter_visit(val* self, val* p0);
#define COLOR_nit__local_var_init__LocalVarInitVisitor___toolcontext 1
#define COLOR_nit__local_var_init__LocalVarInitVisitor___maybe_unset_vars 2
#define COLOR_standard__kernel__Object___61d_61d 2
#define COLOR_standard__abstract_collection__SimpleCollection__add 57
#define COLOR_standard__abstract_collection__Collection__has 40
#define COLOR_nit__flow__AExpr___after_flow_context 4
#define COLOR_nit__local_var_init__FlowContext___set_vars 9
short int nit__local_var_init___FlowContext___is_variable_set(val* self, val* p0);
val* nit___nit__ANode___hot_location(val* self);
val* standard___standard__NativeString___to_s_with_length(char* self, long p0);
val* NEW_standard__Array(const struct type* type);
extern const struct type type_standard__Array__standard__Object;
val* NEW_standard__NativeArray(int length, const struct type* type);
extern const struct type type_standard__NativeArray__standard__Object;
#define COLOR_standard__array__Array__with_native 73
#define COLOR_standard__string__Object__to_s 9
void nit___nit__ToolContext___error(val* self, val* p0, val* p1);
#define COLOR_standard__abstract_collection__RemovableCollection__remove 53
#define COLOR_nit__local_var_init__ANode__accept_local_var_visitor 44
#define COLOR_nit__local_var_init___nit__local_var_init__LocalVarInitVisitor___standard__kernel__Object__init 41
#define COLOR_nit__flow__FlowContext___previous 0
extern const char FILE_nit__flow[];
#define COLOR_standard__array__AbstractArrayRead___length 0
val* standard___standard__SequenceRead___Collection__first(val* self);
val* standard___standard__AbstractArrayRead___standard__abstract_collection__Collection__iterator(val* self);
short int standard__array___standard__array__ArrayIterator___standard__abstract_collection__Iterator__is_ok(val* self);
val* standard__array___standard__array__ArrayIterator___standard__abstract_collection__Iterator__item(val* self);
void standard__array___standard__array__ArrayIterator___standard__abstract_collection__Iterator__next(val* self);
#define COLOR_nit__parser_nodes__ANode__visit_all 40
#define COLOR_nit__local_var_init___AVardeclExpr___ANode__accept_local_var_visitor 91
#define COLOR_nit__parser_nodes__AVardeclExpr___n_expr 14
#define COLOR_nit__scope__AVardeclExpr___variable 15
void nit__local_var_init___nit__local_var_init__LocalVarInitVisitor___mark_is_unset(val* self, val* p0, val* p1);
#define COLOR_nit__local_var_init___AVarExpr___ANode__accept_local_var_visitor 84
#define COLOR_nit__scope__AVarFormExpr___variable 11
void nit__local_var_init___nit__local_var_init__LocalVarInitVisitor___check_is_set(val* self, val* p0, val* p1);
#define COLOR_nit__local_var_init___AVarAssignExpr___ANode__accept_local_var_visitor 93
void nit__local_var_init___nit__local_var_init__LocalVarInitVisitor___mark_is_set(val* self, val* p0, val* p1);
#define COLOR_nit__local_var_init___AVarReassignExpr___ANode__accept_local_var_visitor 97
