#include "nit.common.h"
#define COLOR_nit__local_var_init__ToolContext___local_var_init_phase 46
extern const char FILE_nit__local_var_init[];
#define COLOR_nit__phase__Phase___toolcontext 0
extern const char FILE_nit__phase[];
void nit__local_var_init___APropdef___do_local_var_init(val* self, val* p0);
val* NEW_nit__local_var_init__LocalVarInitVisitor(const struct type* type);
extern const struct type type_nit__local_var_init__LocalVarInitVisitor;
#define COLOR_nit__local_var_init__LocalVarInitVisitor__toolcontext_61d 19
#define COLOR_standard__kernel__Object__init 0
void nit___nit__Visitor___enter_visit(val* self, val* p0);
#define COLOR_nit__local_var_init__LocalVarInitVisitor___toolcontext 1
#define COLOR_nit__local_var_init__LocalVarInitVisitor___maybe_unset_vars 2
#define COLOR_standard__kernel__Object___61d_61d 4
#define COLOR_standard__abstract_collection__SimpleCollection__add 45
#define COLOR_standard__abstract_collection__Collection__has 28
#define COLOR_nit__flow__AExpr___after_flow_context 9
#define COLOR_nit__local_var_init__FlowContext___set_vars 1
short int nit__local_var_init___FlowContext___is_variable_set(val* self, val* p0);
val* nit___nit__ANode___hot_location(val* self);
val* NEW_standard__NativeArray(int length, const struct type* type);
extern const struct type type_standard__NativeArray__standard__String;
val* standard___standard__NativeString___to_s_with_length(char* self, long p0);
#define COLOR_standard__string__Object__to_s 3
#define COLOR_standard__string__NativeArray__native_to_s 16
val* nit___nit__ToolContext___error(val* self, val* p0, val* p1);
#define COLOR_standard__abstract_collection__RemovableCollection__remove 38
#define COLOR_nit__local_var_init__ANode__accept_local_var_visitor 28
#define COLOR_nit__local_var_init___nit__local_var_init__LocalVarInitVisitor___standard__kernel__Object__init 25
#define COLOR_nit__flow__FlowContext___previous 2
extern const char FILE_nit__flow[];
#define COLOR_standard__array__AbstractArrayRead___length 0
val* standard___standard__SequenceRead___Collection__first(val* self);
val* standard___standard__AbstractArrayRead___standard__abstract_collection__Collection__iterator(val* self);
short int standard__array___standard__array__ArrayIterator___standard__abstract_collection__Iterator__is_ok(val* self);
val* standard__array___standard__array__ArrayIterator___standard__abstract_collection__Iterator__item(val* self);
void standard__array___standard__array__ArrayIterator___standard__abstract_collection__Iterator__next(val* self);
void standard__array___standard__array__ArrayIterator___standard__abstract_collection__Iterator__finish(val* self);
#define COLOR_nit__parser_nodes__ANode__visit_all 20
#define COLOR_nit__local_var_init___AVardeclExpr___ANode__accept_local_var_visitor 75
#define COLOR_nit__parser_nodes__AVardeclExpr___n_expr 14
#define COLOR_nit__scope__AVardeclExpr___variable 15
void nit__local_var_init___nit__local_var_init__LocalVarInitVisitor___mark_is_unset(val* self, val* p0, val* p1);
#define COLOR_nit__local_var_init___AVarExpr___ANode__accept_local_var_visitor 68
#define COLOR_nit__scope__AVarFormExpr___variable 11
void nit__local_var_init___nit__local_var_init__LocalVarInitVisitor___check_is_set(val* self, val* p0, val* p1);
#define COLOR_nit__local_var_init___AVarAssignExpr___ANode__accept_local_var_visitor 69
void nit__local_var_init___nit__local_var_init__LocalVarInitVisitor___mark_is_set(val* self, val* p0, val* p1);
#define COLOR_nit__local_var_init___AVarReassignExpr___ANode__accept_local_var_visitor 67
