#include "nit.common.h"
#define COLOR_nit__parser_nodes__ANode___location 0
extern const char FILE_nit__parser_nodes[];
val* standard__file___Sys___stderr(val* self);
val* NEW_standard__NativeArray(int length, const struct type* type);
extern const struct type type_standard__NativeArray__standard__String;
val* standard___standard__NativeString___to_s_with_length(char* self, long p0);
#define COLOR_nit__parser_nodes__ANode__hot_location 18
#define COLOR_standard__string__Object__to_s 3
val* standard__string___Object___class_name(val* self);
val* nit___nit__Location___colored_line(val* self, val* p0);
#define COLOR_standard__string__NativeArray__native_to_s 16
void standard___standard__FileWriter___standard__stream__Writer__write(val* self, val* p0);
#define COLOR_nit__parser_nodes__ANode___parent 1
#define COLOR_standard__kernel__Object___61d_61d 4
#define COLOR_nit__parser_nodes__ANode__replace_child 33
#define COLOR_nit__parser_nodes__ANodes___parent 0
#define COLOR_nit__parser_nodes__ANodes___items 1
val* standard___standard__AbstractArrayRead___standard__abstract_collection__Collection__iterator(val* self);
#define COLOR_standard__array__AbstractArrayRead___length 0
short int standard___standard__AbstractArrayRead___standard__abstract_collection__Collection__is_empty(val* self);
#define COLOR_nit__ANodes___35dE 2
void nit___nit__ANodes___hook_add(val* self, val* p0);
void standard___standard__AbstractArray___standard__abstract_collection__Sequence__push(val* self, val* p0);
val* standard___standard__AbstractArray___standard__abstract_collection__Sequence__pop(val* self);
void nit___nit__ANodes___hook_remove(val* self, val* p0);
void standard___standard__AbstractArray___standard__abstract_collection__Sequence__unshift(val* self, val* p0);
val* standard___standard__AbstractArray___standard__abstract_collection__Sequence__shift(val* self);
short int standard___standard__AbstractArrayRead___standard__abstract_collection__Collection__has(val* self, val* p0);
val* standard___standard__Array___standard__abstract_collection__SequenceRead___91d_93d(val* self, long p0);
val* nit___nit__ANodes___standard__abstract_collection__SequenceRead___91d_93d(val* self, long p0);
void standard___standard__Array___standard__abstract_collection__Sequence___91d_93d_61d(val* self, long p0, val* p1);
void standard___standard__AbstractArray___standard__abstract_collection__Sequence__remove_at(val* self, long p0);
#define COLOR_standard__abstract_collection__Collection__iterator 25
#define COLOR_standard__abstract_collection__Iterator__is_ok 16
#define COLOR_standard__abstract_collection__Iterator__item 17
void standard___standard__Sequence___SimpleCollection__add(val* self, val* p0);
#define COLOR_standard__abstract_collection__Iterator__next 18
#define COLOR_standard__abstract_collection__Iterator__finish 19
long nit___nit__ANodes___standard__abstract_collection__Collection__length(val* self);
extern const struct type type_standard__Int;
extern const char FILE_standard__kernel[];
void nit___nit__ANodes___standard__abstract_collection__Sequence___91d_93d_61d(val* self, long p0, val* p1);
void nit___nit__ANodes___standard__abstract_collection__Sequence__remove_at(val* self, long p0);
long standard___standard__Int___Discrete__successor(long self, long p0);
val* nit___nit__ANodes___standard__abstract_collection__Collection__iterator(val* self);
void nit___nit__Visitor___enter_visit(val* self, val* p0);
#define COLOR_nit___nit__ANodes___standard__kernel__Object__init 43
#define COLOR_nit__parser_nodes__Token___prev_token 2
#define COLOR_nit__parser_nodes__Token___next_token 3
#define COLOR_nit__parser_nodes__Token___is_loose 4
#define COLOR_nit__parser_nodes__Token___prev_looses 5
val* NEW_standard__Array(const struct type* type);
extern const struct type type_standard__Array__nit__Token;
void standard___standard__Array___standard__kernel__Object__init(val* self);
#define COLOR_nit__parser_nodes__Token___next_looses 7
val* nit__lexer_work___Token___text(val* self);
#define COLOR_nit__parser_nodes__SourceFile___first_token 5
#define COLOR_nit__parser_nodes__SourceFile___last_token 6
#define COLOR_nit__parser_nodes__Prod___n_annotations 2
extern const struct type type_standard__Array__nit__AAnnotation;
#define COLOR_nit__parser_nodes__AAnnotations___n_items 7
val* nit___nit__AAnnotation___name(val* self);
void standard___standard__Array___standard__abstract_collection__SimpleCollection__add(val* self, val* p0);
extern const struct type type_nit__AClassdef;
#define COLOR_nit__parser_nodes__AClassdef___n_propdefs 9
extern const struct type type_nit__AAnnotPropdef;
#define COLOR_nit___nit__Prod___ANode__replace_with 39
extern const struct type type_nit__Prod;
#define COLOR_nit__parser_nodes__Visitor___current_node 0
#define COLOR_nit__parser_nodes__Visitor__visit 17
#define COLOR_nit__parser_nodes__AModule___n_moduledecl 8
#define COLOR_nit__parser_nodes__AModule___n_imports 9
#define COLOR_nit__parser_nodes__AModule___n_extern_code_blocks 10
#define COLOR_nit__parser_nodes__AModule___n_classdefs 11
#define COLOR_nit__parser_nodes__ADefinition___n_doc 10
#define COLOR_nit__parser_nodes__ADefinition___n_kwredef 11
#define COLOR_nit__parser_nodes__ADefinition___n_visibility 12
#define COLOR_nit__parser_nodes__AModuledecl___n_name 5
#define COLOR_nit__parser_nodes__AImport___n_visibility 4
#define COLOR_nit__parser_nodes__AStdImport___n_name 7
#define COLOR_nit___nit__APublicVisibility___standard__kernel__Object__init 43
#define COLOR_nit__parser_nodes__AStdClassdef___n_classkind 13
#define COLOR_nit__parser_nodes__AStdClassdef___n_id 14
#define COLOR_nit__parser_nodes__AStdClassdef___n_formaldefs 16
#define COLOR_nit__parser_nodes__AStdClassdef___n_extern_code_block 18
extern const struct type type_standard__Array__nit__ASuperPropdef;
void standard___standard__Array___with_capacity(val* self, long p0);
extern const struct type type_nit__ASuperPropdef;
#define COLOR_nit__parser_nodes__AFormaldef___n_id 6
#define COLOR_nit__parser_nodes__AFormaldef___n_type 7
#define COLOR_nit__parser_nodes__AAttrPropdef___n_id2 20
#define COLOR_nit__parser_nodes__AAttrPropdef___n_type 21
#define COLOR_nit__parser_nodes__AAttrPropdef___n_expr 23
#define COLOR_nit__parser_nodes__AAttrPropdef___n_block 25
#define COLOR_nit__parser_nodes__AMethPropdef___n_kwinit 14
#define COLOR_nit__parser_nodes__AMethPropdef___n_kwnew 15
#define COLOR_nit__parser_nodes__AMethPropdef___n_methid 16
#define COLOR_nit__parser_nodes__AMethPropdef___n_signature 17
#define COLOR_nit__parser_nodes__AMethPropdef___n_block 19
#define COLOR_nit__parser_nodes__AMethPropdef___n_extern_calls 21
#define COLOR_nit__parser_nodes__AMethPropdef___n_extern_code_block 22
#define COLOR_nit__parser_nodes__ASuperPropdef___n_type 13
#define COLOR_nit__parser_nodes__AExternCalls___n_extern_calls 5
#define COLOR_nit__parser_nodes__ATypePropdef___n_id 13
#define COLOR_nit__parser_nodes__ATypePropdef___n_type 14
#define COLOR_nit__parser_nodes__AIdMethid___n_id 4
#define COLOR_nit__parser_nodes__ASignature___n_params 10
#define COLOR_nit__parser_nodes__ASignature___n_type 12
#define COLOR_nit__parser_nodes__AParam___n_id 5
#define COLOR_nit__parser_nodes__AParam___n_type 6
#define COLOR_nit__parser_nodes__AParam___n_dotdotdot 7
#define COLOR_nit__parser_nodes__AType___n_kwnullable 6
#define COLOR_nit__parser_nodes__AType___n_id 7
#define COLOR_nit__parser_nodes__AType___n_types 9
#define COLOR_nit__parser_nodes__ALabel___n_id 5
#define COLOR_nit__parser_nodes__ABlockExpr___n_expr 10
#define COLOR_nit__parser_nodes__AVardeclExpr___n_id 11
#define COLOR_nit__parser_nodes__AVardeclExpr___n_type 12
#define COLOR_nit__parser_nodes__AVardeclExpr___n_expr 14
#define COLOR_nit__parser_nodes__AReturnExpr___n_expr 11
#define COLOR_nit__parser_nodes__ALabelable___n_label 10
#define COLOR_nit__parser_nodes__AEscapeExpr___n_expr 11
#define COLOR_nit__parser_nodes__ADoExpr___n_block 12
#define COLOR_nit__parser_nodes__AIfExpr___n_expr 11
#define COLOR_nit__parser_nodes__AIfExpr___n_then 13
#define COLOR_nit__parser_nodes__AIfExpr___n_else 15
#define COLOR_nit__parser_nodes__AIfexprExpr___n_expr 11
#define COLOR_nit__parser_nodes__AIfexprExpr___n_then 13
#define COLOR_nit__parser_nodes__AIfexprExpr___n_else 15
#define COLOR_nit__parser_nodes__AWhileExpr___n_expr 12
#define COLOR_nit__parser_nodes__AWhileExpr___n_block 14
#define COLOR_nit__parser_nodes__ALoopExpr___n_block 12
#define COLOR_nit__parser_nodes__AForExpr___n_ids 12
#define COLOR_nit__parser_nodes__AForExpr___n_expr 14
#define COLOR_nit__parser_nodes__AForExpr___n_block 16
#define COLOR_nit__parser_nodes__AWithExpr___n_expr 12
#define COLOR_nit__parser_nodes__AWithExpr___n_block 14
#define COLOR_nit__parser_nodes__AAssertExpr___n_id 11
#define COLOR_nit__parser_nodes__AAssertExpr___n_expr 12
#define COLOR_nit__parser_nodes__AAssertExpr___n_else 14
#define COLOR_nit__parser_nodes__AAssignFormExpr___n_assign 12
#define COLOR_nit__parser_nodes__AAssignFormExpr___n_value 13
#define COLOR_nit__parser_nodes__AReassignFormExpr___n_assign_op 12
#define COLOR_nit__parser_nodes__AReassignFormExpr___n_value 13
#define COLOR_nit__parser_nodes__AOnceExpr___n_expr 11
#define COLOR_nit__parser_nodes__ASendExpr___n_expr 10
#define COLOR_nit__parser_nodes__ABinopExpr___n_op 12
#define COLOR_nit__parser_nodes__ABinopExpr___n_expr2 13
#define COLOR_nit__parser_nodes__ABinBoolExpr___n_expr 10
#define COLOR_nit__parser_nodes__ABinBoolExpr___n_expr2 12
#define COLOR_nit__parser_nodes__ANotExpr___n_expr 11
#define COLOR_nit__parser_nodes__AIsaExpr___n_expr 10
#define COLOR_nit__parser_nodes__AIsaExpr___n_type 12
#define COLOR_nit__parser_nodes__ANewExpr___n_kwnew 10
#define COLOR_nit__parser_nodes__ANewExpr___n_type 11
#define COLOR_nit__parser_nodes__ANewExpr___n_id 12
#define COLOR_nit__parser_nodes__ANewExpr___n_args 13
#define COLOR_nit__parser_nodes__AAttrFormExpr___n_expr 10
#define COLOR_nit__parser_nodes__AAttrFormExpr___n_id 11
#define COLOR_nit__parser_nodes__ACallFormExpr___n_id 16
#define COLOR_nit__parser_nodes__ACallFormExpr___n_args 17
#define COLOR_nit__parser_nodes__ASuperExpr___n_args 12
#define COLOR_nit__parser_nodes__AInitExpr___n_kwinit 12
#define COLOR_nit__parser_nodes__AInitExpr___n_args 13
#define COLOR_nit__parser_nodes__ABraFormExpr___n_args 16
#define COLOR_nit__parser_nodes__ARangeExpr___n_expr 10
#define COLOR_nit__parser_nodes__ARangeExpr___n_expr2 12
#define COLOR_nit__parser_nodes__AArrayExpr___n_exprs 11
#define COLOR_nit__parser_nodes__AArrayExpr___n_type 12
#define COLOR_nit__parser_nodes__ADecIntExpr___n_number 11
#define COLOR_nit__parser_nodes__AHexIntExpr___n_hex_number 11
#define COLOR_nit__parser_nodes__ABinIntExpr___n_bin_number 11
#define COLOR_nit__parser_nodes__AOctIntExpr___n_oct_number 11
#define COLOR_nit__parser_nodes__ADecByteExpr___n_bytenum 11
#define COLOR_nit__parser_nodes__AHexByteExpr___n_hex_bytenum 11
#define COLOR_nit__parser_nodes__ABinByteExpr___n_bin_bytenum 11
#define COLOR_nit__parser_nodes__AOctByteExpr___n_oct_bytenum 11
#define COLOR_nit__parser_nodes__AFloatExpr___n_float 10
#define COLOR_nit__parser_nodes__ACharExpr___n_char 10
#define COLOR_nit__parser_nodes__AStringFormExpr___n_string 10
#define COLOR_nit__parser_nodes__ASuperstringExpr___n_exprs 10
#define COLOR_nit__parser_nodes__AParExpr___n_expr 11
#define COLOR_nit__parser_nodes__AAsCastForm___n_expr 10
#define COLOR_nit__parser_nodes__AAsCastExpr___n_type 14
#define COLOR_nit__parser_nodes__AVarargExpr___n_expr 10
#define COLOR_nit__parser_nodes__ANamedargExpr___n_id 10
#define COLOR_nit__parser_nodes__ANamedargExpr___n_expr 12
#define COLOR_nit__parser_nodes__AManyExpr___n_exprs 10
#define COLOR_nit__parser_nodes__ADebugTypeExpr___n_expr 12
#define COLOR_nit__parser_nodes__ADebugTypeExpr___n_type 13
#define COLOR_nit__parser_nodes__AExprs___n_exprs 4
#define COLOR_nit__parser_nodes__AModuleName___n_quad 4
#define COLOR_nit__parser_nodes__AModuleName___n_path 5
#define COLOR_nit__parser_nodes__AModuleName___n_id 6
#define COLOR_nit__parser_nodes__AInLanguage___n_string 5
#define COLOR_nit__parser_nodes__AExternCodeBlock___n_in_language 4
#define COLOR_nit__parser_nodes__AExternCodeBlock___n_extern_code_segment 5
#define COLOR_nit__parser_nodes__AQualified___n_id 5
#define COLOR_nit__parser_nodes__ADoc___n_comment 5
#define COLOR_nit__parser_nodes__AAnnotation___n_atid 9
#define COLOR_nit__parser_nodes__AAnnotation___n_args 14
#define COLOR_nit__parser_nodes__AAtid___n_id 4
#define COLOR_nit__parser_nodes__Start___n_base 4
#define COLOR_nit__parser_nodes__Start___n_eof 5
#define COLOR_nit___nit__Start___standard__kernel__Object__init 44
