#include "nit.common.h"
#define COLOR_nitc__parser_nodes__ANode___location 1
extern const char FILE_nitc__parser_nodes[];
val* core__file___Sys___stderr(val* self);
val* NEW_core__NativeArray(int length, const struct type* type);
extern const struct type type_core__NativeArray__core__String;
val* core__flat___CString___to_s_unsafe(char* self, val* p0, val* p1, val* p2, val* p3);
#define COLOR_nitc__parser_nodes__ANode__hot_location 16
#define COLOR_core__abstract_text__Object__to_s 3
val* core__abstract_text___Object___class_name(val* self);
val* nitc___nitc__Location___colored_line(val* self, val* p0);
#define COLOR_core__abstract_text__NativeArray__native_to_s 12
void core___core__FileWriter___core__stream__Writer__write(val* self, val* p0);
#define COLOR_nitc__parser_nodes__ANode___parent 2
#define COLOR_core__kernel__Object___61d_61d 4
#define COLOR_nitc__parser_nodes__ANode__replace_child 32
#define COLOR_nitc__parser_nodes__ANodes___parent 0
#define COLOR_nitc__parser_nodes__ANodes___items 1
val* core___core__AbstractArrayRead___core__abstract_collection__Collection__iterator(val* self);
val* core___core__AbstractArrayRead___core__abstract_collection__SequenceRead__reverse_iterator(val* self);
#define COLOR_core__array__AbstractArrayRead___length 0
short int core___core__AbstractArrayRead___core__abstract_collection__Collection__is_empty(val* self);
#define COLOR_nitc__ANodes___35dE 1
void nitc___nitc__ANodes___hook_add(val* self, val* p0);
void core___core__AbstractArray___core__abstract_collection__Sequence__push(val* self, val* p0);
val* core___core__AbstractArray___core__abstract_collection__Sequence__pop(val* self);
void nitc___nitc__ANodes___hook_remove(val* self, val* p0);
void core___core__AbstractArray___core__abstract_collection__Sequence__unshift(val* self, val* p0);
val* core___core__AbstractArray___core__abstract_collection__Sequence__shift(val* self);
short int core___core__AbstractArrayRead___core__abstract_collection__Collection__has(val* self, val* p0);
val* core___core__Array___core__abstract_collection__SequenceRead___91d_93d(val* self, long p0);
val* nitc___nitc__ANodes___core__abstract_collection__SequenceRead___91d_93d(val* self, long p0);
void core___core__Array___core__abstract_collection__Sequence___91d_93d_61d(val* self, long p0, val* p1);
void core___core__AbstractArray___core__abstract_collection__Sequence__remove_at(val* self, long p0);
#define COLOR_core__abstract_collection__Collection__iterator 24
#define COLOR_core__abstract_collection__Iterator__is_ok 12
#define COLOR_core__abstract_collection__Iterator__item 13
void core___core__Sequence___SimpleCollection__add(val* self, val* p0);
#define COLOR_core__abstract_collection__Iterator__next 14
#define COLOR_core__abstract_collection__Iterator__finish 15
long nitc___nitc__ANodes___core__abstract_collection__Collection__length(val* self);
extern const struct type type_core__Int;
extern const char FILE_core__kernel[];
void nitc___nitc__ANodes___core__abstract_collection__Sequence___91d_93d_61d(val* self, long p0, val* p1);
void nitc___nitc__ANodes___core__abstract_collection__Sequence__remove_at(val* self, long p0);
long core___core__Int___Discrete__successor(long self, long p0);
val* nitc___nitc__ANodes___core__abstract_collection__Collection__iterator(val* self);
void nitc___nitc__Visitor___enter_visit(val* self, val* p0);
#define COLOR_nitc___nitc__ANodes___core__kernel__Object__init 32
#define COLOR_nitc__parser_nodes__Token___prev_token 3
#define COLOR_nitc__parser_nodes__Token___next_token 4
#define COLOR_nitc__parser_nodes__Token___is_loose 5
#define COLOR_nitc__parser_nodes__Token___prev_looses 6
val* NEW_core__Array(const struct type* type);
extern const struct type type_core__Array__nitc__Token;
void core___core__Array___core__kernel__Object__init(val* self);
#define COLOR_nitc__parser_nodes__Token___next_looses 8
val* nitc__lexer_work___Token___text(val* self);
#define COLOR_nitc__parser_nodes__SourceFile___first_token 6
#define COLOR_nitc__parser_nodes__SourceFile___last_token 7
#define COLOR_nitc__parser_nodes__Prod___n_annotations 9
extern const struct type type_core__Array__nitc__AAnnotation;
#define COLOR_nitc__parser_nodes__AAnnotations___n_items 6
val* nitc___nitc__AAnnotation___name(val* self);
void core___core__Array___core__abstract_collection__SimpleCollection__add(val* self, val* p0);
extern const struct type type_nitc__AClassdef;
#define COLOR_nitc__parser_nodes__AClassdef___n_propdefs 7
extern const struct type type_nitc__AAnnotPropdef;
#define COLOR_nitc___nitc__Prod___ANode__replace_with 46
extern const struct type type_nitc__Prod;
#define COLOR_nitc__parser_nodes__Visitor___current_node 0
#define COLOR_nitc__parser_nodes__Visitor__visit 13
#define COLOR_nitc__parser_nodes__AModule___n_moduledecl 7
#define COLOR_nitc__parser_nodes__AModule___n_imports 8
#define COLOR_nitc__parser_nodes__AModule___n_extern_code_blocks 11
#define COLOR_nitc__parser_nodes__AModule___n_classdefs 12
#define COLOR_nitc__parser_nodes__ADefinition___n_doc 8
#define COLOR_nitc__parser_nodes__ADefinition___n_kwredef 11
#define COLOR_nitc__parser_nodes__ADefinition___n_visibility 12
#define COLOR_nitc__parser_nodes__AModuledecl___n_name 4
#define COLOR_nitc__parser_nodes__AImport___n_visibility 3
#define COLOR_nitc__parser_nodes__AStdImport___n_name 6
#define COLOR_nitc__parser_nodes__AStdClassdef___n_classkind 13
#define COLOR_nitc__parser_nodes__AStdClassdef___n_qid 14
#define COLOR_nitc__parser_nodes__AStdClassdef___n_formaldefs 16
#define COLOR_nitc__parser_nodes__AStdClassdef___n_extern_code_block 18
extern const struct type type_core__Array__nitc__ASuperPropdef;
void core___core__Array___with_capacity(val* self, long p0);
extern const struct type type_nitc__ASuperPropdef;
#define COLOR_nitc__parser_nodes__AFormaldef___n_id 5
#define COLOR_nitc__parser_nodes__AFormaldef___n_type 6
#define COLOR_nitc__parser_nodes__AAttrPropdef___n_id2 23
#define COLOR_nitc__parser_nodes__AAttrPropdef___n_type 24
#define COLOR_nitc__parser_nodes__AAttrPropdef___n_expr 26
#define COLOR_nitc__parser_nodes__AAttrPropdef___n_block 28
#define COLOR_nitc__parser_nodes__AMethPropdef___n_kwinit 16
#define COLOR_nitc__parser_nodes__AMethPropdef___n_kwnew 17
#define COLOR_nitc__parser_nodes__AMethPropdef___n_methid 18
#define COLOR_nitc__parser_nodes__AMethPropdef___n_signature 19
#define COLOR_nitc__parser_nodes__AMethPropdef___n_block 21
#define COLOR_nitc__parser_nodes__AMethPropdef___n_extern_calls 23
#define COLOR_nitc__parser_nodes__AMethPropdef___n_extern_code_block 24
#define COLOR_nitc__parser_nodes__ASuperPropdef___n_type 15
#define COLOR_nitc__parser_nodes__AExternCalls___n_extern_calls 4
#define COLOR_nitc__parser_nodes__ATypePropdef___n_qid 15
#define COLOR_nitc__parser_nodes__ATypePropdef___n_type 16
#define COLOR_nitc__parser_nodes__AIdMethid___n_id 3
#define COLOR_nitc__parser_nodes__AQid___n_id 4
#define COLOR_nitc__parser_nodes__AQclassid___n_qualified 3
#define COLOR_nitc__parser_nodes__AQclassid___n_id 4
#define COLOR_nitc__parser_nodes__ASignature___n_params 11
#define COLOR_nitc__parser_nodes__ASignature___n_type 13
#define COLOR_nitc__parser_nodes__AParam___n_id 4
#define COLOR_nitc__parser_nodes__AParam___n_type 5
#define COLOR_nitc__parser_nodes__AParam___n_dotdotdot 6
#define COLOR_nitc__parser_nodes__AType___n_kwnullable 5
#define COLOR_nitc__parser_nodes__AType___n_qid 6
#define COLOR_nitc__parser_nodes__AType___n_types 8
#define COLOR_nitc__parser_nodes__ALabel___n_id 4
#define COLOR_nitc__parser_nodes__ABlockExpr___n_expr 3
#define COLOR_nitc__parser_nodes__AVardeclExpr___n_id 4
#define COLOR_nitc__parser_nodes__AVardeclExpr___n_type 5
#define COLOR_nitc__parser_nodes__AVardeclExpr___n_expr 7
#define COLOR_nitc__parser_nodes__ALabelable___n_label 3
#define COLOR_nitc__parser_nodes__AEscapeExpr___n_expr 4
#define COLOR_nitc__parser_nodes__ADoExpr___n_block 5
#define COLOR_nitc__parser_nodes__ADoExpr___n_catch 7
#define COLOR_nitc__parser_nodes__AIfExpr___n_expr 4
#define COLOR_nitc__parser_nodes__AIfExpr___n_then 6
#define COLOR_nitc__parser_nodes__AIfExpr___n_else 8
#define COLOR_nitc__parser_nodes__AIfexprExpr___n_expr 4
#define COLOR_nitc__parser_nodes__AIfexprExpr___n_then 6
#define COLOR_nitc__parser_nodes__AIfexprExpr___n_else 8
#define COLOR_nitc__parser_nodes__AWhileExpr___n_expr 5
#define COLOR_nitc__parser_nodes__AWhileExpr___n_block 7
#define COLOR_nitc__parser_nodes__ALoopExpr___n_block 5
#define COLOR_nitc__parser_nodes__AForExpr___n_groups 5
#define COLOR_nitc__parser_nodes__AForExpr___n_block 7
#define COLOR_nitc__parser_nodes__AForGroup___n_ids 3
#define COLOR_nitc__parser_nodes__AForGroup___n_expr 5
#define COLOR_nitc__parser_nodes__AWithExpr___n_expr 5
#define COLOR_nitc__parser_nodes__AWithExpr___n_block 7
#define COLOR_nitc__parser_nodes__AAssertExpr___n_id 4
#define COLOR_nitc__parser_nodes__AAssertExpr___n_expr 5
#define COLOR_nitc__parser_nodes__AAssertExpr___n_else 7
#define COLOR_nitc__parser_nodes__AAssignFormExpr___n_assign 5
#define COLOR_nitc__parser_nodes__AAssignFormExpr___n_value 6
#define COLOR_nitc__parser_nodes__AReassignFormExpr___n_assign_op 5
#define COLOR_nitc__parser_nodes__AReassignFormExpr___n_value 6
#define COLOR_nitc__parser_nodes__AOnceExpr___n_expr 4
#define COLOR_nitc__parser_nodes__ASendExpr___n_expr 3
#define COLOR_nitc__parser_nodes__ABinopExpr___n_op 5
#define COLOR_nitc__parser_nodes__ABinopExpr___n_expr2 6
#define COLOR_nitc__parser_nodes__ABinBoolExpr___n_expr 3
#define COLOR_nitc__parser_nodes__ABinBoolExpr___n_expr2 5
#define COLOR_nitc__parser_nodes__ANotExpr___n_expr 4
#define COLOR_nitc__parser_nodes__AIsaExpr___n_expr 3
#define COLOR_nitc__parser_nodes__AIsaExpr___n_type 5
#define COLOR_nitc__parser_nodes__ANewExpr___n_kwnew 3
#define COLOR_nitc__parser_nodes__ANewExpr___n_type 4
#define COLOR_nitc__parser_nodes__ANewExpr___n_qid 5
#define COLOR_nitc__parser_nodes__ANewExpr___n_args 6
#define COLOR_nitc__parser_nodes__AAttrFormExpr___n_expr 3
#define COLOR_nitc__parser_nodes__AAttrFormExpr___n_id 4
#define COLOR_nitc__parser_nodes__ACallFormExpr___n_qid 18
#define COLOR_nitc__parser_nodes__ACallFormExpr___n_args 19
#define COLOR_nitc__parser_nodes__ASuperExpr___n_args 5
#define COLOR_nitc__parser_nodes__AInitExpr___n_kwinit 5
#define COLOR_nitc__parser_nodes__AInitExpr___n_args 6
#define COLOR_nitc__parser_nodes__ABraFormExpr___n_args 18
#define COLOR_nitc__parser_nodes__ARangeExpr___n_expr 3
#define COLOR_nitc__parser_nodes__ARangeExpr___n_expr2 5
#define COLOR_nitc__parser_nodes__AArrayExpr___n_exprs 4
#define COLOR_nitc__parser_nodes__AArrayExpr___n_type 5
#define COLOR_nitc__parser_nodes__AIntegerExpr___n_integer 3
#define COLOR_nitc__parser_nodes__AFloatExpr___n_float 3
#define COLOR_nitc__parser_nodes__ACharExpr___n_char 18
#define COLOR_nitc__parser_nodes__AStringFormExpr___n_string 25
#define COLOR_nitc__parser_nodes__ASuperstringExpr___n_exprs 25
#define COLOR_nitc__parser_nodes__AParExpr___n_expr 4
#define COLOR_nitc__parser_nodes__AAsCastForm___n_expr 3
#define COLOR_nitc__parser_nodes__AAsCastExpr___n_type 7
#define COLOR_nitc__parser_nodes__AVarargExpr___n_expr 3
#define COLOR_nitc__parser_nodes__ANamedargExpr___n_id 3
#define COLOR_nitc__parser_nodes__ANamedargExpr___n_expr 5
#define COLOR_nitc__parser_nodes__AManyExpr___n_exprs 3
#define COLOR_nitc__parser_nodes__ADebugTypeExpr___n_expr 5
#define COLOR_nitc__parser_nodes__ADebugTypeExpr___n_type 6
#define COLOR_nitc__parser_nodes__AExprs___n_exprs 3
#define COLOR_nitc__parser_nodes__AModuleName___n_quad 3
#define COLOR_nitc__parser_nodes__AModuleName___n_path 4
#define COLOR_nitc__parser_nodes__AModuleName___n_id 5
#define COLOR_nitc__parser_nodes__AInLanguage___n_string 4
#define COLOR_nitc__parser_nodes__AExternCodeBlock___n_in_language 3
#define COLOR_nitc__parser_nodes__AExternCodeBlock___n_extern_code_segment 4
#define COLOR_nitc__parser_nodes__AQualified___n_id 4
#define COLOR_nitc__parser_nodes__AQualified___n_classid 5
#define COLOR_nitc__parser_nodes__ADoc___n_comment 4
#define COLOR_nitc__parser_nodes__AAnnotation___n_atid 14
#define COLOR_nitc__parser_nodes__AAnnotation___n_args 16
#define COLOR_nitc__parser_nodes__AAtid___n_id 3
#define COLOR_nitc__parser_nodes__Start___n_base 3
#define COLOR_nitc__parser_nodes__Start___n_eof 4
#define COLOR_nitc___nitc__Start___core__kernel__Object__init 38
