#include "nit.common.h"
val* NEW_toolcontext__ToolContext(const struct type* type);
extern const struct type type_toolcontext__ToolContext;
extern const int COLOR_toolcontext__ToolContext__init;
void CHECK_NEW_toolcontext__ToolContext(val*);
val* NEW_opts__OptionBool(const struct type* type);
extern const struct type type_opts__OptionBool;
val* string__NativeString__to_s_with_length(char* self, long p0);
val* NEW_array__Array(const struct type* type);
extern const struct type type_array__Arraystring__String;
val* NEW_array__NativeArray(int length, const struct type* type);
extern const struct type type_array__NativeArraystring__String;
extern const int COLOR_array__Array__with_native;
void CHECK_NEW_array__Array(val*);
extern const int COLOR_opts__OptionBool__init;
void CHECK_NEW_opts__OptionBool(val*);
extern const int COLOR_toolcontext__ToolContext__option_context;
extern const struct type type_array__Arrayopts__Option;
extern const struct type type_array__NativeArrayopts__Option;
extern const int COLOR_opts__OptionContext__add_option;
val* NEW_opts__OptionArray(const struct type* type);
extern const struct type type_opts__OptionArray;
extern const int COLOR_opts__OptionArray__init;
void CHECK_NEW_opts__OptionArray(val*);
extern const int COLOR_toolcontext__ToolContext__process_options;
val* NEW_model_base__Model(const struct type* type);
extern const struct type type_model_base__Model;
extern const int COLOR_model_base__Model__init;
void CHECK_NEW_model_base__Model(val*);
val* NEW_modelbuilder__ModelBuilder(const struct type* type);
extern const struct type type_modelbuilder__ModelBuilder;
extern const int COLOR_modelbuilder__ModelBuilder__init;
void CHECK_NEW_modelbuilder__ModelBuilder(val*);
extern const int COLOR_opts__OptionContext__rest;
extern const int COLOR_abstract_collection__Collection__is_empty;
extern const int COLOR_opts__OptionContext__usage;
extern const int COLOR_abstract_collection__Collection__length;
extern const struct type type_kernel__Int;
extern const int COLOR_string__Collection__join;
extern const struct type type_array__Arraykernel__Object;
extern const struct type type_array__NativeArraykernel__Object;
extern const int COLOR_string__Object__to_s;
extern const int COLOR_file__Object__print;
extern const int COLOR_abstract_collection__Collection__first;
extern const int COLOR_modelbuilder__ModelBuilder__parse;
extern const int COLOR_opts__Option__value;
extern const int COLOR_abstract_collection__SimpleCollection__add_all;
extern const int COLOR_modelbuilder__ModelBuilder__run_phases;
val* NEW_model_base__MModule(const struct type* type);
extern const struct type type_model_base__MModule;
extern const int COLOR_model_base__MModule__name;
extern const int COLOR_model_base__MModule__location;
extern const int COLOR_model_base__MModule__init;
void CHECK_NEW_model_base__MModule(val*);
extern const int COLOR_model_base__MModule__set_imported_mmodules;
extern const int COLOR_rapid_type_analysis__ModelBuilder__do_rapid_type_analysis;
extern const int COLOR_separate_erasure_compiler__ToolContext__opt_erasure;
extern const int COLOR_separate_erasure_compiler__ModelBuilder__run_separate_erasure_compiler;
extern const int COLOR_global_compiler__ModelBuilder__run_global_compiler;
extern const int COLOR_separate_compiler__ModelBuilder__run_separate_compiler;
void nitg__Sys__main(val* self);
