#include "nit.common.h"
extern const int COLOR_model__MMethod__is_init;
extern const int COLOR_model__MProperty__name;
val* string__NativeString__to_s_with_length(char* self, long p0);
extern const int COLOR_kernel__Object___61d_61d;
extern const int COLOR_nitni_base__MType__mangled_cname;
val* NEW_array__Array(const struct type* type);
extern const struct type type_array__Arraykernel__Object;
val* NEW_array__NativeArray(int length, const struct type* type);
extern const struct type type_array__NativeArraykernel__Object;
extern const int COLOR_array__Array__with_native;
extern const int COLOR_string__Object__to_s;
extern const int COLOR_nitni_base__MMethod__short_cname;
extern const int COLOR_array__Array__with_capacity;
extern const int COLOR_abstract_collection__SimpleCollection__add;
extern const int COLOR_nitni_utilities__SignatureLength__long;
extern const int COLOR_mmodule__MModule__name;
val* nitni_utilities__MMethod__build_cname(val* self, val* p0, val* p1, val* p2, val* p3);
extern const int COLOR_model__MProperty__lookup_first_definition;
extern const int COLOR_model__MMethodDef__msignature;
extern const int COLOR_nitni_utilities__CallContext__name_mtype;
extern const int COLOR_model__MSignature__return_mtype;
extern const int COLOR_model__MType__resolve_for;
extern const int COLOR_nitni_utilities__MMethod__build_cname;
val* NEW_list__List(const struct type* type);
extern const struct type type_list__Liststring__String;
extern const int COLOR_list__List__init;
extern const int COLOR_model__MSignature__mparameters;
extern const int COLOR_abstract_collection__Collection__iterator;
extern const int COLOR_abstract_collection__Iterator__is_ok;
extern const int COLOR_abstract_collection__Iterator__item;
extern const int COLOR_model__MParameter__mtype;
extern const int COLOR_model__MParameter__name;
extern const int COLOR_abstract_collection__Iterator__next;
extern const int COLOR_string__Collection__join;
val* nitni_utilities__MMethod__build_csignature(val* self, val* p0, val* p1, val* p2, val* p3, val* p4);
extern const int COLOR_nitni_utilities__CallContext__cast_to;
extern const int COLOR_nitni_utilities__CallContext__cast_from;
val* nitni_utilities__MMethod__build_ccall(val* self, val* p0, val* p1, val* p2, val* p3, val* p4, val* p5);
extern const int COLOR_nitni_base__MType__cname_blind;
val* nitni_utilities__CallContext__name_mtype(val* self, val* p0);
val* nitni_utilities__CallContext__cast_from(val* self, val* p0, val* p1);
val* nitni_utilities__CallContext__cast_to(val* self, val* p0, val* p1);
void nitni_utilities__CallContext__init(val* self);
val* NEW_nitni_utilities__CallContext(const struct type* type);
extern const struct type type_nitni_utilities__CallContext;
extern const int COLOR_nitni_utilities__CallContext__init;
val* nitni_utilities__Object__internal_call_context(val* self);
val* NEW_nitni_utilities__SignatureLength(const struct type* type);
extern const struct type type_nitni_utilities__SignatureLength;
extern const int COLOR_nitni_utilities__SignatureLength__init;
val* nitni_utilities__Object__long_signature(val* self);
val* nitni_utilities__Object__short_signature(val* self);
extern const int COLOR_nitni_utilities__SignatureLength___64dlong;
short int nitni_utilities__SignatureLength__long(val* self);
void nitni_utilities__SignatureLength__long_61d(val* self, short int p0);
extern const int COLOR_nitni_utilities__SignatureLength__long_61d;
void nitni_utilities__SignatureLength__init(val* self, short int p0);
