#include "nit.common.h"
extern const int COLOR_nitni_callbacks__ToolContext___64dverify_nitni_callback_phase;
val* nitni_callbacks__ToolContext__verify_nitni_callback_phase(val* self);
void nitni_callbacks__ToolContext__verify_nitni_callback_phase_61d(val* self, val* p0);
extern const struct type type_parser_nodes__AExternPropdef;
extern const int COLOR_phase__Phase__toolcontext;
extern const int COLOR_nitni_callbacks__AExternPropdef__verify_nitni_callbacks;
void nitni_callbacks__VerifyNitniCallbacksPhase__process_npropdef(val* self, val* p0);
extern const int COLOR_nitni_callbacks__ForeignCallbackSet___64dcallbacks;
val* nitni_callbacks__ForeignCallbackSet__callbacks(val* self);
void nitni_callbacks__ForeignCallbackSet__callbacks_61d(val* self, val* p0);
extern const int COLOR_nitni_callbacks__ForeignCallbackSet___64dsupers;
val* nitni_callbacks__ForeignCallbackSet__supers(val* self);
void nitni_callbacks__ForeignCallbackSet__supers_61d(val* self, val* p0);
extern const int COLOR_nitni_callbacks__ForeignCallbackSet___64dtypes;
val* nitni_callbacks__ForeignCallbackSet__types(val* self);
void nitni_callbacks__ForeignCallbackSet__types_61d(val* self, val* p0);
extern const int COLOR_nitni_callbacks__ForeignCallbackSet___64dcasts;
val* nitni_callbacks__ForeignCallbackSet__casts(val* self);
void nitni_callbacks__ForeignCallbackSet__casts_61d(val* self, val* p0);
extern const int COLOR_nitni_callbacks__ForeignCallbackSet___64dall_cached;
val* nitni_callbacks__ForeignCallbackSet__all_cached(val* self);
void nitni_callbacks__ForeignCallbackSet__all_cached_61d(val* self, val* p0);
extern const int COLOR_nitni_callbacks__ForeignCallbackSet__all_cached;
val* NEW_hash_collection__HashSet(const struct type* type);
extern const struct type type_hash_collection__HashSetnitni_callbacks__NitniCallback;
extern const int COLOR_hash_collection__HashSet__init;
void CHECK_NEW_hash_collection__HashSet(val*);
extern const int COLOR_nitni_callbacks__ForeignCallbackSet__callbacks;
extern const int COLOR_abstract_collection__SimpleCollection__add_all;
extern const int COLOR_nitni_callbacks__ForeignCallbackSet__supers;
extern const int COLOR_nitni_callbacks__ForeignCallbackSet__types;
extern const int COLOR_nitni_callbacks__ForeignCallbackSet__casts;
extern const int COLOR_nitni_callbacks__ForeignCallbackSet__all_cached_61d;
val* nitni_callbacks__ForeignCallbackSet__all(val* self);
void nitni_callbacks__ForeignCallbackSet__join(val* self, val* p0);
void nitni_callbacks__ForeignCallbackSet__init(val* self);
extern const int COLOR_nitni_callbacks__AExternPropdef___64dforeign_callbacks_cache;
val* nitni_callbacks__AExternPropdef__foreign_callbacks_cache(val* self);
void nitni_callbacks__AExternPropdef__foreign_callbacks_cache_61d(val* self, val* p0);
extern const int COLOR_nitni_callbacks__AExternPropdef__foreign_callbacks_cache;
val* string__NativeString__to_s_with_length(char* self, long p0);
extern const int COLOR_file__Object__print;
val* nitni_callbacks__AExternPropdef__foreign_callbacks(val* self);
val* NEW_nitni_callbacks__ForeignCallbackSet(const struct type* type);
extern const struct type type_nitni_callbacks__ForeignCallbackSet;
extern const int COLOR_nitni_callbacks__ForeignCallbackSet__init;
void CHECK_NEW_nitni_callbacks__ForeignCallbackSet(val*);
extern const int COLOR_modelize_property__APropdef__mpropdef;
extern const int COLOR_model__MPropDef__mclassdef;
extern const int COLOR_model__MClassDef__mmodule;
extern const int COLOR_model__MClassDef__bound_mtype;
extern const int COLOR_abstract_collection__SimpleCollection__add;
extern const int COLOR_model__MMethodDef__msignature;
extern const int COLOR_model__MSignature__return_mtype;
extern const struct type type_model__MParameterType;
extern const struct type type_model__MVirtualType;
extern const int COLOR_model__MType__anchor_to;
extern const int COLOR_model__MType__resolve_for;
extern const int COLOR_model__MSignature__mparameters;
extern const int COLOR_abstract_collection__Collection__iterator;
extern const int COLOR_abstract_collection__Iterator__is_ok;
extern const int COLOR_abstract_collection__Iterator__item;
extern const int COLOR_model__MParameter__mtype;
extern const int COLOR_abstract_collection__Iterator__next;
extern const int COLOR_parser_nodes__AExternPropdef__n_extern_calls;
extern const int COLOR_parser_nodes__AExternCalls__n_extern_calls;
extern const int COLOR_nitni_callbacks__AExternCall__verify_and_collect;
extern const int COLOR_nitni_callbacks__AExternPropdef__foreign_callbacks_cache_61d;
void nitni_callbacks__AExternPropdef__verify_nitni_callbacks(val* self, val* p0);
extern const int COLOR_nitni_callbacks__AExternPropdef__foreign_callbacks;
extern const int COLOR_nitni_callbacks__MExplicitCall__recv_mtype;
extern const int COLOR_nitni_callbacks__MExplicitCall__mproperty;
extern const struct type type_model__MMethod;
extern const int COLOR_rapid_type_analysis__RapidTypeVisitor__add_send;
extern const int COLOR_nitni_callbacks__MExplicitCast__to;
extern const int COLOR_rapid_type_analysis__RapidTypeVisitor__add_cast_type;
extern const int COLOR_rapid_type_analysis__RapidTypeVisitor__analysis;
extern const int COLOR_nitni_callbacks__MExplicitSuper__from;
extern const int COLOR_model__MClassDef__mclass;
extern const int COLOR_model__MClass__mclass_type;
extern const struct type type_model__MMethodDef;
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis__add_super_send;
extern const struct type type_model__MClassType;
extern const int COLOR_rapid_type_analysis__RapidTypeVisitor__add_type;
void nitni_callbacks__AExternPropdef__accept_rapid_type_visitor(val* self, val* p0);
extern const int COLOR_nitni_callbacks__MExplicitCall___64drecv_mtype;
val* nitni_callbacks__MExplicitCall__recv_mtype(val* self);
void nitni_callbacks__MExplicitCall__recv_mtype_61d(val* self, val* p0);
extern const int COLOR_nitni_callbacks__MExplicitCall___64dmproperty;
val* nitni_callbacks__MExplicitCall__mproperty(val* self);
void nitni_callbacks__MExplicitCall__mproperty_61d(val* self, val* p0);
extern const int COLOR_nitni_callbacks__MExplicitCall___64dfrom_mmodule;
val* nitni_callbacks__MExplicitCall__from_mmodule(val* self);
void nitni_callbacks__MExplicitCall__from_mmodule_61d(val* self, val* p0);
extern const int COLOR_model__MProperty__lookup_first_definition;
extern const int COLOR_nitni_callbacks__MExplicitCall__recv_mtype_61d;
void nitni_callbacks__MExplicitCall__fill_type_for(val* self, val* p0, val* p1);
extern const int COLOR_model__MProperty__intro;
extern const int COLOR_model__MMethod__is_init;
extern const int COLOR_nitni_base__MType__cname;
extern const int COLOR_nitni_callbacks__MExplicitCall__from_mmodule;
extern const int COLOR_model__MProperty__name;
extern const int COLOR_kernel__Object___61d_61d;
extern const int COLOR_nitni_base__MType__mangled_cname;
val* NEW_array__Array(const struct type* type);
extern const struct type type_array__Arraykernel__Object;
val* NEW_array__NativeArray(int length, const struct type* type);
extern const struct type type_array__NativeArraykernel__Object;
extern const int COLOR_array__Array__with_native;
void CHECK_NEW_array__Array(val*);
extern const int COLOR_string__Object__to_s;
extern const int COLOR_nitni_base__MMethod__short_cname;
val* NEW_list__List(const struct type* type);
extern const struct type type_list__Liststring__String;
extern const int COLOR_list__List__init;
void CHECK_NEW_list__List(val*);
extern const int COLOR_model__MParameter__name;
extern const int COLOR_array__Array__with_capacity;
extern const int COLOR_string__Collection__join;
val* nitni_callbacks__MExplicitCall__csignature(val* self);
extern const int COLOR_nitni_base__MType__cname_blind;
val* nitni_callbacks__MExplicitCall__csignature_blind(val* self);
extern const int COLOR_kernel__Object__hash;
long nitni_callbacks__MExplicitCall__hash(val* self);
extern const struct type type_nitni_callbacks__MExplicitCall;
short int nitni_callbacks__MExplicitCall___61d_61d(val* self, val* p0);
void nitni_callbacks__MExplicitCall__init(val* self, val* p0, val* p1, val* p2);
extern const int COLOR_nitni_callbacks__MExplicitSuper___64dfrom;
val* nitni_callbacks__MExplicitSuper__from(val* self);
void nitni_callbacks__MExplicitSuper__from_61d(val* self, val* p0);
extern const int COLOR_model__MPropDef__mproperty;
extern const int COLOR_model__MClass__name;
val* nitni_callbacks__MExplicitSuper__csignature(val* self);
long nitni_callbacks__MExplicitSuper__hash(val* self);
extern const struct type type_nitni_callbacks__MExplicitSuper;
short int nitni_callbacks__MExplicitSuper___61d_61d(val* self, val* p0);
void nitni_callbacks__MExplicitSuper__init(val* self, val* p0);
extern const int COLOR_nitni_callbacks__MExplicitCast___64dfrom;
val* nitni_callbacks__MExplicitCast__from(val* self);
void nitni_callbacks__MExplicitCast__from_61d(val* self, val* p0);
extern const int COLOR_nitni_callbacks__MExplicitCast___64dto;
val* nitni_callbacks__MExplicitCast__to(val* self);
void nitni_callbacks__MExplicitCast__to_61d(val* self, val* p0);
extern const int COLOR_nitni_callbacks__MExplicitCast__from;
val* nitni_callbacks__MExplicitCast__check_cname(val* self);
extern const int COLOR_nitni_callbacks__MExplicitCast__check_cname;
val* nitni_callbacks__MExplicitCast__check_csignature(val* self);
val* nitni_callbacks__MExplicitCast__check_csignature_blind(val* self);
val* nitni_callbacks__MExplicitCast__cast_cname(val* self);
extern const int COLOR_nitni_callbacks__MExplicitCast__cast_cname;
val* nitni_callbacks__MExplicitCast__cast_csignature(val* self);
val* nitni_callbacks__MExplicitCast__cast_csignature_blind(val* self);
long nitni_callbacks__MExplicitCast__hash(val* self);
extern const struct type type_nitni_callbacks__MExplicitCast;
short int nitni_callbacks__MExplicitCast___61d_61d(val* self, val* p0);
void nitni_callbacks__MExplicitCast__init(val* self, val* p0, val* p1);
void nitni_callbacks__AExternCall__verify_and_collect(val* self, val* p0, val* p1, val* p2);
extern const int COLOR_parser_nodes__ALocalPropExternCall__n_methid;
extern const int COLOR_modelize_property__Prod__collect_text;
extern const int COLOR_modelbuilder__ToolContext__modelbuilder;
extern const int COLOR_modelbuilder__ModelBuilder__try_get_mproperty_by_name2;
extern const int COLOR_parser_nodes__ANode__location;
extern const int COLOR_toolcontext__ToolContext__error;
val* NEW_nitni_callbacks__MExplicitCall(const struct type* type);
extern const int COLOR_nitni_callbacks__MExplicitCall__init;
void CHECK_NEW_nitni_callbacks__MExplicitCall(val*);
extern const int COLOR_nitni_callbacks__MExplicitCall__fill_type_for;
void nitni_callbacks__ALocalPropExternCall__verify_and_collect(val* self, val* p0, val* p1, val* p2);
extern const int COLOR_modelize_class__ModelBuilder__mclassdef2nclassdef;
extern const int COLOR_abstract_collection__MapRead___91d_93d;
extern const int COLOR_parser_nodes__AFullPropExternCall__n_type;
extern const int COLOR_modelize_class__ModelBuilder__resolve_mtype;
extern const struct type type_model__MNullableType;
extern const int COLOR_parser_nodes__AFullPropExternCall__n_methid;
void nitni_callbacks__AFullPropExternCall__verify_and_collect(val* self, val* p0, val* p1, val* p2);
extern const int COLOR_parser_nodes__AInitPropExternCall__n_type;
void nitni_callbacks__AInitPropExternCall__verify_and_collect(val* self, val* p0, val* p1, val* p2);
val* NEW_nitni_callbacks__MExplicitSuper(const struct type* type);
extern const int COLOR_nitni_callbacks__MExplicitSuper__init;
void CHECK_NEW_nitni_callbacks__MExplicitSuper(val*);
void nitni_callbacks__ASuperExternCall__verify_and_collect(val* self, val* p0, val* p1, val* p2);
val* nitni_callbacks__ACastExternCall__from_mtype(val* self);
val* nitni_callbacks__ACastExternCall__to_mtype(val* self);
extern const int COLOR_nitni_callbacks__ACastExternCall__from_mtype;
extern const int COLOR_nitni_callbacks__ACastExternCall__to_mtype;
val* NEW_nitni_callbacks__MExplicitCast(const struct type* type);
extern const int COLOR_nitni_callbacks__MExplicitCast__init;
void CHECK_NEW_nitni_callbacks__MExplicitCast(val*);
void nitni_callbacks__ACastExternCall__verify_and_collect(val* self, val* p0, val* p1, val* p2);
extern const int COLOR_parser_nodes__ACastAsExternCall__n_from_type;
extern const int COLOR_modelize_class__AType__mtype;
val* nitni_callbacks__ACastAsExternCall__from_mtype(val* self);
extern const int COLOR_parser_nodes__ACastAsExternCall__n_to_type;
val* nitni_callbacks__ACastAsExternCall__to_mtype(val* self);
extern const int COLOR_parser_nodes__ANode__parent;
extern const struct type type_parser_nodes__AClassdef;
extern const int COLOR_modelize_class__ModelBuilder__resolve_mtype_unchecked;
extern const int COLOR_nitni_callbacks__ACastAsExternCall__verify_and_collect;
void nitni_callbacks__ACastAsExternCall__verify_and_collect(val* self, val* p0, val* p1, val* p2);
extern const int COLOR_parser_nodes__AAsNullableExternCall__n_type;
val* nitni_callbacks__AAsNullableExternCall__from_mtype(val* self);
extern const int COLOR_model__MType__as_nullable;
val* nitni_callbacks__AAsNullableExternCall__to_mtype(val* self);
extern const int COLOR_nitni_callbacks__AAsNullableExternCall__verify_and_collect;
void nitni_callbacks__AAsNullableExternCall__verify_and_collect(val* self, val* p0, val* p1, val* p2);
extern const int COLOR_parser_nodes__AAsNotNullableExternCall__n_type;
val* nitni_callbacks__AAsNotNullableExternCall__from_mtype(val* self);
extern const int COLOR_model__MNullableType__mtype;
val* nitni_callbacks__AAsNotNullableExternCall__to_mtype(val* self);
extern const int COLOR_nitni_callbacks__AAsNotNullableExternCall__verify_and_collect;
void nitni_callbacks__AAsNotNullableExternCall__verify_and_collect(val* self, val* p0, val* p1, val* p2);
