#include "nit.common.h"
extern const int COLOR_model__MProperty__name;
val* string__NativeString__to_s_with_length(char* self, long p0);
extern const int COLOR_kernel__Object___61d_61d;
extern const int COLOR_abstract_collection__SequenceRead__last;
extern const struct class class_kernel__Char;
val* NEW_array__Array(const struct type* type);
extern const struct type type_array__Arraykernel__Object;
extern const int COLOR_array__Array__with_capacity;
void CHECK_NEW_array__Array(val*);
extern const int COLOR_abstract_collection__SimpleCollection__add;
extern const int COLOR_abstract_collection__Collection__length;
extern const int COLOR_string__AbstractString__substring;
extern const int COLOR_string__Object__to_s;
val* nitni_base__MMethod__short_cname(val* self);
extern const int COLOR_modelbuilder__AModule__mmodule;
extern const int COLOR_model_base__MModule__name;
val* nitni_base__AModule__cname(val* self);
extern const int COLOR_model__MPropDef__mclassdef;
extern const int COLOR_model__MClassDef__mclass;
extern const int COLOR_model__MClass__name;
extern const int COLOR_model__MPropDef__mproperty;
extern const int COLOR_nitni_base__MMethod__short_cname;
val* nitni_base__MMethodDef__cname(val* self);
extern const int COLOR_nitni_base__MMethodDef__cname;
val* nitni_base__MMethodDef__impl_cname(val* self, val* p0);
val* nitni_base__MMethodDef__super_cname(val* self, val* p0);
extern const int COLOR_string__Object__class_name;
extern const int COLOR_file__Object__print;
val* nitni_base__MType__cname(val* self);
val* nitni_base__MType__cname_blind(val* self);
val* nitni_base__MType__mangled_cname(val* self);
short int nitni_base__MType__is_cprimitive(val* self);
extern const int COLOR_model__MClassType__mclass;
extern const int COLOR_model__MClass__kind;
extern const int COLOR_model__Object__extern_kind;
extern const int COLOR_nitni_base__MClass__ctype;
extern const int COLOR_nitni_base__MType__mangled_cname;
val* nitni_base__MClassType__cname(val* self);
val* nitni_base__MClassType__cname_blind(val* self);
val* nitni_base__MClassType__mangled_cname(val* self);
extern const struct type type_array__Arraystring__String;
extern const int COLOR_abstract_collection__Sequence__push;
extern const int COLOR_abstract_collection__Collection__has;
short int nitni_base__MClassType__is_cprimitive(val* self);
val* nitni_base__MNullableType__cname(val* self);
val* nitni_base__MNullableType__cname_blind(val* self);
extern const int COLOR_model__MNullableType__mtype;
val* nitni_base__MNullableType__mangled_cname(val* self);
short int nitni_base__MNullableType__is_cprimitive(val* self);
val* nitni_base__MVirtualType__mangled_cname(val* self);
val* nitni_base__MGenericType__cname(val* self);
extern const int COLOR_nitni_base__MGenericType__mangled_cname;
extern const int COLOR_array__Array__init;
extern const int COLOR_model__MClassType__arguments;
extern const int COLOR_abstract_collection__Collection__iterator;
extern const int COLOR_abstract_collection__Iterator__is_ok;
extern const int COLOR_abstract_collection__Iterator__item;
extern const int COLOR_abstract_collection__Iterator__next;
extern const int COLOR_string__Collection__join;
val* nitni_base__MGenericType__mangled_cname(val* self);
val* nitni_base__MClass__ctype(val* self);
