/* This C file is generated by NIT to compile module opts. */
#include "opts._sep.h"
val_t opts___Option___names(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 16;
  fra.me.meth = LOCATE_opts___Option___names;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/opts.nit:16 */
  REGB0 = TAG_Bool(ATTR_opts___Option____names(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_names", LOCATE_opts, 16);
  }
  fra.me.REG[0] = ATTR_opts___Option____names(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t opts___Option___helptext(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 22;
  fra.me.meth = LOCATE_opts___Option___helptext;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/opts.nit:22 */
  REGB0 = TAG_Bool(ATTR_opts___Option____helptext(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_helptext", LOCATE_opts, 22);
  }
  fra.me.REG[0] = ATTR_opts___Option____helptext(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t opts___Option___mandatory(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 25;
  fra.me.meth = LOCATE_opts___Option___mandatory;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/opts.nit:25 */
  REGB0 = TAG_Bool(ATTR_opts___Option____mandatory(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_mandatory", LOCATE_opts, 25);
  }
  REGB0 = ATTR_opts___Option____mandatory(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return REGB0;
}
void opts___Option___mandatory__eq(val_t p0, val_t p1){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 25;
  fra.me.meth = LOCATE_opts___Option___mandatory__eq;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  REGB0 = p1;
  /* ./../lib/opts.nit:25 */
  ATTR_opts___Option____mandatory(fra.me.REG[0]) = REGB0;
  stack_frame_head = fra.me.prev;
  return;
}
void opts___Option___value__eq(val_t p0, val_t p1){
  struct {struct stack_frame_t me; val_t MORE_REG[1];} fra;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 28;
  fra.me.meth = LOCATE_opts___Option___value__eq;
  fra.me.has_broke = 0;
  fra.me.REG_size = 2;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  /* ./../lib/opts.nit:28 */
  ATTR_opts___Option____value(fra.me.REG[0]) = fra.me.REG[1];
  stack_frame_head = fra.me.prev;
  return;
}
val_t opts___Option___value(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 31;
  fra.me.meth = LOCATE_opts___Option___value;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/opts.nit:32 */
  fra.me.REG[0] = ATTR_opts___Option____value(fra.me.REG[0]);
  REGB0 = TAG_Bool((fra.me.REG[0]==NIT_NULL) || VAL_ISA(fra.me.REG[0], COLOR_standard___kernel___Object, ID_standard___kernel___Object)) /*cast VALUE*/;
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Cast failed", NULL, LOCATE_opts, 32);
  }
  goto label1;
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t opts___Option___default_value(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 34;
  fra.me.meth = LOCATE_opts___Option___default_value;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/opts.nit:34 */
  fra.me.REG[0] = ATTR_opts___Option____default_value(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
void opts___Option___default_value__eq(val_t p0, val_t p1){
  struct {struct stack_frame_t me; val_t MORE_REG[1];} fra;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 34;
  fra.me.meth = LOCATE_opts___Option___default_value__eq;
  fra.me.has_broke = 0;
  fra.me.REG_size = 2;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  /* ./../lib/opts.nit:34 */
  ATTR_opts___Option____default_value(fra.me.REG[0]) = fra.me.REG[1];
  stack_frame_head = fra.me.prev;
  return;
}
void opts___Option___init_opt(val_t p0, val_t p1, val_t p2, val_t p3, int* init_table){
  int itpos0 = VAL2OBJ(p0)->vft[INIT_TABLE_POS_opts___Option].i;
  struct {struct stack_frame_t me; val_t MORE_REG[4];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t tmp;
  if (init_table[itpos0]) return;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 37;
  fra.me.meth = LOCATE_opts___Option___init_opt;
  fra.me.has_broke = 0;
  fra.me.REG_size = 5;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[3] = NIT_NULL;
  fra.me.REG[4] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  fra.me.REG[2] = p2;
  fra.me.REG[3] = p3;
  /* ./../lib/opts.nit:40 */
  REGB0 = TAG_Bool(fra.me.REG[3]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    REGB1 = TAG_Bool(fra.me.REG[3]==NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
      REGB1 = TAG_Bool(false);
      REGB0 = REGB1;
    } else {
      REGB1 = CALL_standard___kernel___Object_____eqeq(fra.me.REG[3])(fra.me.REG[3], NIT_NULL);
      REGB0 = REGB1;
    }
  }
  if (UNTAG_Bool(REGB0)) {
    /* ./../lib/opts.nit:41 */
    fra.me.REG[4] = NEW_Array_standard___collection___array___Array___init();
    ATTR_opts___Option____names(fra.me.REG[0]) = fra.me.REG[4];
  } else {
    /* ./../lib/opts.nit:43 */
    REGB0 = TAG_Bool(fra.me.REG[3]==NIT_NULL);
    if (UNTAG_Bool(REGB0)) {
      nit_abort("Reciever is null", NULL, LOCATE_opts, 43);
    }
    fra.me.REG[3] = CALL_standard___collection___array___Collection___to_a(fra.me.REG[3])(fra.me.REG[3]);
    ATTR_opts___Option____names(fra.me.REG[0]) = fra.me.REG[3];
  }
  /* ./../lib/opts.nit:45 */
  ATTR_opts___Option____helptext(fra.me.REG[0]) = fra.me.REG[1];
  /* ./../lib/opts.nit:46 */
  REGB0 = TAG_Bool(false);
  ATTR_opts___Option____mandatory(fra.me.REG[0]) = REGB0;
  /* ./../lib/opts.nit:47 */
  ATTR_opts___Option____default_value(fra.me.REG[0]) = fra.me.REG[2];
  /* ./../lib/opts.nit:48 */
  ATTR_opts___Option____value(fra.me.REG[0]) = fra.me.REG[2];
  stack_frame_head = fra.me.prev;
  init_table[itpos0] = 1;
  return;
}
void opts___Option___add_aliases(val_t p0, val_t p1){
  struct {struct stack_frame_t me; val_t MORE_REG[1];} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 51;
  fra.me.meth = LOCATE_opts___Option___add_aliases;
  fra.me.has_broke = 0;
  fra.me.REG_size = 2;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  /* ./../lib/opts.nit:51 */
  REGB0 = TAG_Bool(VAL_ISA(fra.me.REG[1], COLOR_standard___collection___array___Array, ID_standard___collection___array___Array)) /*cast Array[String]*/;
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Cast failed", NULL, LOCATE_opts, 51);
  }
  /* ./../lib/opts.nit:52 */
  REGB0 = TAG_Bool(ATTR_opts___Option____names(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_names", LOCATE_opts, 52);
  }
  fra.me.REG[0] = ATTR_opts___Option____names(fra.me.REG[0]);
  CALL_standard___collection___abstract_collection___SimpleCollection___add_all(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[1]);
  stack_frame_head = fra.me.prev;
  return;
}
val_t opts___Option___to_s(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 54;
  fra.me.meth = LOCATE_opts___Option___to_s;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/opts.nit:55 */
  REGB0 = TAG_Int(2);
  fra.me.REG[0] = CALL_opts___Option___pretty(fra.me.REG[0])(fra.me.REG[0], REGB0);
  goto label1;
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t opts___Option___pretty(val_t p0, val_t p1){
  struct {struct stack_frame_t me; val_t MORE_REG[3];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t tmp;
  static val_t once_value_1; /* Once value */
  static val_t once_value_2; /* Once value */
  static val_t once_value_3; /* Once value */
    static val_t once_value_4; /* Once value */
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 57;
  fra.me.meth = LOCATE_opts___Option___pretty;
  fra.me.has_broke = 0;
  fra.me.REG_size = 4;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[3] = NIT_NULL;
  fra.me.REG[0] = p0;
  REGB0 = p1;
  /* ./../lib/opts.nit:60 */
  if (!once_value_1) {
    fra.me.REG[1] = BOX_NativeString("  ");
    REGB1 = TAG_Int(2);
    fra.me.REG[1] = NEW_String_standard___string___String___with_native(fra.me.REG[1], REGB1);
    once_value_1 = fra.me.REG[1];
    register_static_object(&once_value_1);
  } else fra.me.REG[1] = once_value_1;
  fra.me.REG[1] = fra.me.REG[1];
  fra.me.REG[1] = NEW_Buffer_standard___string___Buffer___from(fra.me.REG[1]);
  /* ./../lib/opts.nit:61 */
  REGB1 = TAG_Bool(ATTR_opts___Option____names(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_names", LOCATE_opts, 61);
  }
  fra.me.REG[2] = ATTR_opts___Option____names(fra.me.REG[0]);
  if (!once_value_2) {
    fra.me.REG[3] = BOX_NativeString(", ");
    REGB1 = TAG_Int(2);
    fra.me.REG[3] = NEW_String_standard___string___String___with_native(fra.me.REG[3], REGB1);
    once_value_2 = fra.me.REG[3];
    register_static_object(&once_value_2);
  } else fra.me.REG[3] = once_value_2;
  fra.me.REG[3] = fra.me.REG[3];
  fra.me.REG[3] = CALL_standard___string___Collection___join(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[3]);
  CALL_standard___collection___abstract_collection___Sequence___append(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[3]);
  /* ./../lib/opts.nit:62 */
  if (!once_value_3) {
    fra.me.REG[3] = BOX_NativeString("  ");
    REGB1 = TAG_Int(2);
    fra.me.REG[3] = NEW_String_standard___string___String___with_native(fra.me.REG[3], REGB1);
    once_value_3 = fra.me.REG[3];
    register_static_object(&once_value_3);
  } else fra.me.REG[3] = once_value_3;
  fra.me.REG[3] = fra.me.REG[3];
  CALL_standard___collection___abstract_collection___Sequence___append(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[3]);
  /* ./../lib/standard//collection//array.nit:23 */
  REGB1 = TAG_Bool(ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[1])!=NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_length", LOCATE_standard___collection___array, 23);
  }
  REGB1 = ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[1]);
  /* ./../lib/standard//kernel.nit:220 */
  REGB1 = TAG_Int(UNTAG_Int(REGB0)-UNTAG_Int(REGB1));
  /* ./../lib/opts.nit:64 */
  REGB0 = TAG_Int(0);
  /* ./../lib/standard//kernel.nit:217 */
  REGB0 = TAG_Bool(UNTAG_Int(REGB1)>UNTAG_Int(REGB0));
  /* ./../lib/opts.nit:64 */
  if (UNTAG_Bool(REGB0)) {
    if (!once_value_4) {
      fra.me.REG[3] = BOX_NativeString(" ");
      REGB0 = TAG_Int(1);
      fra.me.REG[3] = NEW_String_standard___string___String___with_native(fra.me.REG[3], REGB0);
      once_value_4 = fra.me.REG[3];
      register_static_object(&once_value_4);
    } else fra.me.REG[3] = once_value_4;
    fra.me.REG[3] = fra.me.REG[3];
    fra.me.REG[3] = CALL_standard___string___String_____star(fra.me.REG[3])(fra.me.REG[3], REGB1);
    CALL_standard___collection___abstract_collection___Sequence___append(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[3]);
  }
  /* ./../lib/opts.nit:65 */
  fra.me.REG[0] = CALL_opts___Option___helptext(fra.me.REG[0])(fra.me.REG[0]);
  CALL_standard___collection___abstract_collection___Sequence___append(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[0]);
  /* ./../lib/opts.nit:67 */
  fra.me.REG[1] = CALL_standard___string___Object___to_s(fra.me.REG[1])(fra.me.REG[1]);
  goto label5;
  label5: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[1];
}
val_t opts___Option___pretty_default(val_t p0){
  struct {struct stack_frame_t me; val_t MORE_REG[2];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t tmp;
    static val_t once_value_1; /* Once value */
    static val_t once_value_2; /* Once value */
  static val_t once_value_4; /* Once value */
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 70;
  fra.me.meth = LOCATE_opts___Option___pretty_default;
  fra.me.has_broke = 0;
  fra.me.REG_size = 3;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/opts.nit:72 */
  fra.me.REG[0] = CALL_opts___Option___default_value(fra.me.REG[0])(fra.me.REG[0]);
  /* ./../lib/opts.nit:73 */
  REGB0 = TAG_Bool(fra.me.REG[0]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    REGB1 = TAG_Bool(fra.me.REG[0]==NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
      REGB1 = TAG_Bool(false);
      REGB0 = REGB1;
    } else {
      REGB1 = CALL_standard___kernel___Object_____eqeq(fra.me.REG[0])(fra.me.REG[0], NIT_NULL);
      REGB0 = REGB1;
    }
  }
  REGB0 = TAG_Bool(!UNTAG_Bool(REGB0));
  if (UNTAG_Bool(REGB0)) {
    REGB0 = TAG_Int(3);
    fra.me.REG[1] = NEW_Array_standard___collection___array___Array___with_capacity(REGB0);
    if (!once_value_1) {
      fra.me.REG[2] = BOX_NativeString(" (");
      REGB0 = TAG_Int(2);
      fra.me.REG[2] = NEW_String_standard___string___String___with_native(fra.me.REG[2], REGB0);
      once_value_1 = fra.me.REG[2];
      register_static_object(&once_value_1);
    } else fra.me.REG[2] = once_value_1;
    fra.me.REG[2] = fra.me.REG[2];
    CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
    fra.me.REG[0] = CALL_standard___string___Object___to_s(fra.me.REG[0])(fra.me.REG[0]);
    CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[0]);
    if (!once_value_2) {
      fra.me.REG[0] = BOX_NativeString(")");
      REGB0 = TAG_Int(1);
      fra.me.REG[0] = NEW_String_standard___string___String___with_native(fra.me.REG[0], REGB0);
      once_value_2 = fra.me.REG[0];
      register_static_object(&once_value_2);
    } else fra.me.REG[0] = once_value_2;
    fra.me.REG[0] = fra.me.REG[0];
    CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[0]);
    fra.me.REG[1] = CALL_standard___string___Object___to_s(fra.me.REG[1])(fra.me.REG[1]);
    goto label3;
  }
  /* ./../lib/opts.nit:74 */
  if (!once_value_4) {
    fra.me.REG[0] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[0] = NEW_String_standard___string___String___with_native(fra.me.REG[0], REGB0);
    once_value_4 = fra.me.REG[0];
    register_static_object(&once_value_4);
  } else fra.me.REG[0] = once_value_4;
  fra.me.REG[0] = fra.me.REG[0];
  fra.me.REG[1] = fra.me.REG[0];
  goto label3;
  label3: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[1];
}
void opts___Option___read_param(val_t p0, val_t p1){
  struct {struct stack_frame_t me;} fra;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 77;
  fra.me.meth = LOCATE_opts___Option___read_param;
  fra.me.has_broke = 0;
  fra.me.REG_size = 0;
  /* ./../lib/opts.nit:77 */
  nit_abort("Deferred method called", NULL, LOCATE_opts, 77);
  stack_frame_head = fra.me.prev;
  return;
}
void opts___OptionText___init(val_t p0, val_t p1, int* init_table){
  int itpos1 = VAL2OBJ(p0)->vft[INIT_TABLE_POS_opts___OptionText].i;
  struct {struct stack_frame_t me; val_t MORE_REG[1];} fra;
  val_t tmp;
  if (init_table[itpos1]) return;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 83;
  fra.me.meth = LOCATE_opts___OptionText___init;
  fra.me.has_broke = 0;
  fra.me.REG_size = 2;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  /* ./../lib/opts.nit:83 */
  CALL_opts___Option___init_opt(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[1], NIT_NULL, NIT_NULL, init_table);
  stack_frame_head = fra.me.prev;
  init_table[itpos1] = 1;
  return;
}
val_t opts___OptionText___pretty(val_t p0, val_t p1){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 85;
  fra.me.meth = LOCATE_opts___OptionText___pretty;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  REGB0 = p1;
  /* ./../lib/opts.nit:85 */
  fra.me.REG[0] = CALL_standard___string___Object___to_s(fra.me.REG[0])(fra.me.REG[0]);
  goto label1;
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t opts___OptionText___to_s(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 87;
  fra.me.meth = LOCATE_opts___OptionText___to_s;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/opts.nit:87 */
  fra.me.REG[0] = CALL_opts___Option___helptext(fra.me.REG[0])(fra.me.REG[0]);
  goto label1;
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
void opts___OptionBool___init(val_t p0, val_t p1, val_t p2, int* init_table){
  int itpos2 = VAL2OBJ(p0)->vft[INIT_TABLE_POS_opts___OptionBool].i;
  struct {struct stack_frame_t me; val_t MORE_REG[2];} fra;
  val_t REGB0;
  val_t tmp;
  if (init_table[itpos2]) return;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 94;
  fra.me.meth = LOCATE_opts___OptionBool___init;
  fra.me.has_broke = 0;
  fra.me.REG_size = 3;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  fra.me.REG[2] = p2;
  /* ./../lib/opts.nit:94 */
  REGB0 = TAG_Bool(VAL_ISA(fra.me.REG[2], COLOR_standard___collection___array___Array, ID_standard___collection___array___Array)) /*cast Array[String]*/;
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Cast failed", NULL, LOCATE_opts, 94);
  }
  REGB0 = TAG_Bool(false);
  CALL_opts___Option___init_opt(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[1], REGB0, fra.me.REG[2], init_table);
  stack_frame_head = fra.me.prev;
  init_table[itpos2] = 1;
  return;
}
void opts___OptionBool___read_param(val_t p0, val_t p1){
  struct {struct stack_frame_t me; val_t MORE_REG[1];} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 96;
  fra.me.meth = LOCATE_opts___OptionBool___read_param;
  fra.me.has_broke = 0;
  fra.me.REG_size = 2;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  /* ./../lib/opts.nit:96 */
  REGB0 = TAG_Bool(true);
  CALL_opts___Option___value__eq(fra.me.REG[0])(fra.me.REG[0], REGB0);
  stack_frame_head = fra.me.prev;
  return;
}
void opts___OptionCount___init(val_t p0, val_t p1, val_t p2, int* init_table){
  int itpos3 = VAL2OBJ(p0)->vft[INIT_TABLE_POS_opts___OptionCount].i;
  struct {struct stack_frame_t me; val_t MORE_REG[2];} fra;
  val_t REGB0;
  val_t tmp;
  if (init_table[itpos3]) return;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 103;
  fra.me.meth = LOCATE_opts___OptionCount___init;
  fra.me.has_broke = 0;
  fra.me.REG_size = 3;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  fra.me.REG[2] = p2;
  /* ./../lib/opts.nit:103 */
  REGB0 = TAG_Bool(VAL_ISA(fra.me.REG[2], COLOR_standard___collection___array___Array, ID_standard___collection___array___Array)) /*cast Array[String]*/;
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Cast failed", NULL, LOCATE_opts, 103);
  }
  REGB0 = TAG_Int(0);
  CALL_opts___Option___init_opt(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[1], REGB0, fra.me.REG[2], init_table);
  stack_frame_head = fra.me.prev;
  init_table[itpos3] = 1;
  return;
}
void opts___OptionCount___read_param(val_t p0, val_t p1){
  struct {struct stack_frame_t me; val_t MORE_REG[1];} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 105;
  fra.me.meth = LOCATE_opts___OptionCount___read_param;
  fra.me.has_broke = 0;
  fra.me.REG_size = 2;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  /* ./../lib/opts.nit:105 */
  fra.me.REG[1] = CALL_opts___Option___value(fra.me.REG[0])(fra.me.REG[0]);
  REGB0 = TAG_Int(1);
  /* ./../lib/standard//kernel.nit:218 */
  REGB0 = TAG_Int(UNTAG_Int(fra.me.REG[1])+UNTAG_Int(REGB0));
  /* ./../lib/opts.nit:105 */
  CALL_opts___Option___value__eq(fra.me.REG[0])(fra.me.REG[0], REGB0);
  stack_frame_head = fra.me.prev;
  return;
}
val_t opts___OptionParameter___convert(val_t p0, val_t p1){
  struct {struct stack_frame_t me;} fra;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 111;
  fra.me.meth = LOCATE_opts___OptionParameter___convert;
  fra.me.has_broke = 0;
  fra.me.REG_size = 0;
  /* ./../lib/opts.nit:111 */
  nit_abort("Deferred method called", NULL, LOCATE_opts, 111);
  stack_frame_head = fra.me.prev;
  return NIT_NULL;
}
void opts___OptionParameter___read_param(val_t p0, val_t p1){
  struct {struct stack_frame_t me; val_t MORE_REG[2];} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 113;
  fra.me.meth = LOCATE_opts___OptionParameter___read_param;
  fra.me.has_broke = 0;
  fra.me.REG_size = 3;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  /* ./../lib/opts.nit:115 */
  REGB0 = CALL_standard___collection___abstract_collection___Iterator___is_ok(fra.me.REG[1])(fra.me.REG[1]);
  if (UNTAG_Bool(REGB0)) {
    /* ./../lib/opts.nit:116 */
    fra.me.REG[2] = CALL_standard___collection___abstract_collection___Iterator___item(fra.me.REG[1])(fra.me.REG[1]);
    fra.me.REG[2] = CALL_opts___OptionParameter___convert(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[2]);
    CALL_opts___Option___value__eq(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[2]);
    /* ./../lib/opts.nit:117 */
    CALL_standard___collection___abstract_collection___Iterator___next(fra.me.REG[1])(fra.me.REG[1]);
  }
  stack_frame_head = fra.me.prev;
  return;
}
void opts___OptionParameter___init_opt(val_t p0, val_t p1, val_t p2, val_t p3, int* init_table){
  int itpos4 = VAL2OBJ(p0)->vft[INIT_TABLE_POS_opts___OptionParameter].i;
  struct {struct stack_frame_t me; val_t MORE_REG[3];} fra;
  val_t tmp;
  if (init_table[itpos4]) return;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 123;
  fra.me.meth = LOCATE_opts___OptionParameter___init_opt;
  fra.me.has_broke = 0;
  fra.me.REG_size = 4;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[3] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  fra.me.REG[2] = p2;
  fra.me.REG[3] = p3;
  /* ./../lib/opts.nit:123 */
  CALL_opts___Option___init_opt(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[1], fra.me.REG[2], fra.me.REG[3], init_table);
  stack_frame_head = fra.me.prev;
  init_table[itpos4] = 1;
  return;
}
void opts___OptionString___init(val_t p0, val_t p1, val_t p2, int* init_table){
  int itpos5 = VAL2OBJ(p0)->vft[INIT_TABLE_POS_opts___OptionString].i;
  struct {struct stack_frame_t me; val_t MORE_REG[2];} fra;
  val_t REGB0;
  val_t tmp;
  if (init_table[itpos5]) return;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 130;
  fra.me.meth = LOCATE_opts___OptionString___init;
  fra.me.has_broke = 0;
  fra.me.REG_size = 3;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  fra.me.REG[2] = p2;
  /* ./../lib/opts.nit:130 */
  REGB0 = TAG_Bool(VAL_ISA(fra.me.REG[2], COLOR_standard___collection___array___Array, ID_standard___collection___array___Array)) /*cast Array[String]*/;
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Cast failed", NULL, LOCATE_opts, 130);
  }
  CALL_opts___OptionParameter___init_opt(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[1], NIT_NULL, fra.me.REG[2], init_table);
  stack_frame_head = fra.me.prev;
  init_table[itpos5] = 1;
  return;
}
val_t opts___OptionString___convert(val_t p0, val_t p1){
  struct {struct stack_frame_t me; val_t MORE_REG[1];} fra;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 132;
  fra.me.meth = LOCATE_opts___OptionString___convert;
  fra.me.has_broke = 0;
  fra.me.REG_size = 2;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  /* ./../lib/opts.nit:132 */
  goto label1;
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[1];
}
void opts___OptionEnum___init(val_t p0, val_t p1, val_t p2, val_t p3, val_t p4, int* init_table){
  int itpos6 = VAL2OBJ(p0)->vft[INIT_TABLE_POS_opts___OptionEnum].i;
  struct {struct stack_frame_t me; val_t MORE_REG[5];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t REGB2;
  val_t tmp;
  static val_t once_value_1; /* Once value */
  static val_t once_value_2; /* Once value */
  static val_t once_value_3; /* Once value */
  static val_t once_value_4; /* Once value */
  if (init_table[itpos6]) return;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 140;
  fra.me.meth = LOCATE_opts___OptionEnum___init;
  fra.me.has_broke = 0;
  fra.me.REG_size = 6;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[3] = NIT_NULL;
  fra.me.REG[4] = NIT_NULL;
  fra.me.REG[5] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  fra.me.REG[2] = p2;
  REGB0 = p3;
  fra.me.REG[3] = p4;
  /* ./../lib/opts.nit:140 */
  REGB1 = TAG_Bool(VAL_ISA(fra.me.REG[3], COLOR_standard___collection___array___Array, ID_standard___collection___array___Array)) /*cast Array[String]*/;
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Cast failed", NULL, LOCATE_opts, 140);
  }
  /* ./../lib/standard//collection//array.nit:23 */
  REGB1 = TAG_Bool(ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[1])!=NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_length", LOCATE_standard___collection___array, 23);
  }
  REGB1 = ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[1]);
  /* ./../lib/opts.nit:142 */
  REGB2 = TAG_Int(0);
  /* ./../lib/standard//kernel.nit:217 */
  REGB2 = TAG_Bool(UNTAG_Int(REGB1)>UNTAG_Int(REGB2));
  /* ./../lib/opts.nit:142 */
  if (UNTAG_Bool(REGB2)) {
  } else {
    nit_abort("Assert failed", NULL, LOCATE_opts, 142);
  }
  /* ./../lib/opts.nit:143 */
  fra.me.REG[4] = CALL_standard___collection___array___Collection___to_a(fra.me.REG[1])(fra.me.REG[1]);
  ATTR_opts___OptionEnum____values(fra.me.REG[0]) = fra.me.REG[4];
  /* ./../lib/opts.nit:144 */
  REGB2 = TAG_Int(5);
  fra.me.REG[4] = NEW_Array_standard___collection___array___Array___with_capacity(REGB2);
  if (!once_value_1) {
    fra.me.REG[5] = BOX_NativeString("");
    REGB2 = TAG_Int(0);
    fra.me.REG[5] = NEW_String_standard___string___String___with_native(fra.me.REG[5], REGB2);
    once_value_1 = fra.me.REG[5];
    register_static_object(&once_value_1);
  } else fra.me.REG[5] = once_value_1;
  fra.me.REG[5] = fra.me.REG[5];
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[4])(fra.me.REG[4], fra.me.REG[5]);
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[4])(fra.me.REG[4], fra.me.REG[2]);
  if (!once_value_2) {
    fra.me.REG[2] = BOX_NativeString(" <");
    REGB2 = TAG_Int(2);
    fra.me.REG[2] = NEW_String_standard___string___String___with_native(fra.me.REG[2], REGB2);
    once_value_2 = fra.me.REG[2];
    register_static_object(&once_value_2);
  } else fra.me.REG[2] = once_value_2;
  fra.me.REG[2] = fra.me.REG[2];
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[4])(fra.me.REG[4], fra.me.REG[2]);
  if (!once_value_3) {
    fra.me.REG[2] = BOX_NativeString(", ");
    REGB2 = TAG_Int(2);
    fra.me.REG[2] = NEW_String_standard___string___String___with_native(fra.me.REG[2], REGB2);
    once_value_3 = fra.me.REG[2];
    register_static_object(&once_value_3);
  } else fra.me.REG[2] = once_value_3;
  fra.me.REG[2] = fra.me.REG[2];
  fra.me.REG[2] = CALL_standard___string___Collection___join(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[4])(fra.me.REG[4], fra.me.REG[2]);
  if (!once_value_4) {
    fra.me.REG[2] = BOX_NativeString(">");
    REGB2 = TAG_Int(1);
    fra.me.REG[2] = NEW_String_standard___string___String___with_native(fra.me.REG[2], REGB2);
    once_value_4 = fra.me.REG[2];
    register_static_object(&once_value_4);
  } else fra.me.REG[2] = once_value_4;
  fra.me.REG[2] = fra.me.REG[2];
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[4])(fra.me.REG[4], fra.me.REG[2]);
  fra.me.REG[4] = CALL_standard___string___Object___to_s(fra.me.REG[4])(fra.me.REG[4]);
  CALL_opts___OptionParameter___init_opt(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[4], REGB0, fra.me.REG[3], init_table);
  stack_frame_head = fra.me.prev;
  init_table[itpos6] = 1;
  return;
}
val_t opts___OptionEnum___convert(val_t p0, val_t p1){
  struct {struct stack_frame_t me; val_t MORE_REG[1];} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 147;
  fra.me.meth = LOCATE_opts___OptionEnum___convert;
  fra.me.has_broke = 0;
  fra.me.REG_size = 2;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  /* ./../lib/opts.nit:149 */
  REGB0 = TAG_Bool(ATTR_opts___OptionEnum____values(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_values", LOCATE_opts, 149);
  }
  fra.me.REG[0] = ATTR_opts___OptionEnum____values(fra.me.REG[0]);
  REGB0 = CALL_standard___collection___abstract_collection___SequenceRead___index_of(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[1]);
  /* ./../lib/opts.nit:150 */
  goto label1;
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return REGB0;
}
val_t opts___OptionEnum___value_name(val_t p0){
  struct {struct stack_frame_t me; val_t MORE_REG[1];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t REGB2;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 153;
  fra.me.meth = LOCATE_opts___OptionEnum___value_name;
  fra.me.has_broke = 0;
  fra.me.REG_size = 2;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/opts.nit:153 */
  REGB0 = TAG_Bool(ATTR_opts___OptionEnum____values(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_values", LOCATE_opts, 153);
  }
  fra.me.REG[1] = ATTR_opts___OptionEnum____values(fra.me.REG[0]);
  fra.me.REG[0] = CALL_opts___Option___value(fra.me.REG[0])(fra.me.REG[0]);
  /* ./../lib/standard//collection//array.nit:243 */
  REGB0 = fra.me.REG[0];
  /* ./../lib/standard//collection//array.nit:245 */
  REGB1 = TAG_Int(0);
  /* ./../lib/standard//kernel.nit:216 */
  REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
  /* ./../lib/standard//collection//array.nit:245 */
  if (UNTAG_Bool(REGB1)) {
    REGB1 = TAG_Bool(ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[1])!=NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_length", LOCATE_standard___collection___array, 245);
    }
    REGB1 = ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[1]);
    /* ./../lib/standard//kernel.nit:215 */
    REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
  } else {
    /* ./../lib/standard//collection//array.nit:245 */
    REGB2 = TAG_Bool(false);
    REGB1 = REGB2;
  }
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Assert %s  failed", "'index'", LOCATE_standard___collection___array, 245);
  }
  /* ./../lib/standard//collection//array.nit:246 */
  fra.me.REG[1] = ATTR_standard___collection___array___Array____items(fra.me.REG[1]);
  REGB1 = TAG_Bool(fra.me.REG[1]==NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
    nit_abort("Reciever is null", NULL, LOCATE_standard___collection___array, 246);
  }
  /* ./../lib/standard//collection//array.nit:654 */
  fra.me.REG[1] = ((Nit_NativeArray)fra.me.REG[1])->val[UNTAG_Int(REGB0)];
  /* ./../lib/standard//collection//array.nit:246 */
  goto label1;
  label1: while(0);
  /* ./../lib/opts.nit:153 */
  goto label2;
  label2: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[1];
}
val_t opts___OptionEnum___pretty_default(val_t p0){
  struct {struct stack_frame_t me; val_t MORE_REG[2];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t REGB2;
  val_t tmp;
    static val_t once_value_1; /* Once value */
    static val_t once_value_3; /* Once value */
    static val_t once_value_5; /* Once value */
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 155;
  fra.me.meth = LOCATE_opts___OptionEnum___pretty_default;
  fra.me.has_broke = 0;
  fra.me.REG_size = 3;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/opts.nit:157 */
  fra.me.REG[1] = CALL_opts___Option___default_value(fra.me.REG[0])(fra.me.REG[0]);
  REGB0 = TAG_Bool(fra.me.REG[1]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    REGB1 = TAG_Bool(fra.me.REG[1]==NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
      REGB1 = TAG_Bool(false);
      REGB0 = REGB1;
    } else {
      /* ./../lib/standard//kernel.nit:210 */
      REGB1 = TAG_Bool((fra.me.REG[1])==(NIT_NULL));
      /* ./../lib/opts.nit:157 */
      REGB0 = REGB1;
    }
  }
  REGB0 = TAG_Bool(!UNTAG_Bool(REGB0));
  if (UNTAG_Bool(REGB0)) {
    /* ./../lib/opts.nit:158 */
    REGB0 = TAG_Int(3);
    fra.me.REG[1] = NEW_Array_standard___collection___array___Array___with_capacity(REGB0);
    if (!once_value_1) {
      fra.me.REG[2] = BOX_NativeString(" (");
      REGB0 = TAG_Int(2);
      fra.me.REG[2] = NEW_String_standard___string___String___with_native(fra.me.REG[2], REGB0);
      once_value_1 = fra.me.REG[2];
      register_static_object(&once_value_1);
    } else fra.me.REG[2] = once_value_1;
    fra.me.REG[2] = fra.me.REG[2];
    CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
    REGB0 = TAG_Bool(ATTR_opts___OptionEnum____values(fra.me.REG[0])!=NIT_NULL);
    if (UNTAG_Bool(REGB0)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_values", LOCATE_opts, 158);
    }
    fra.me.REG[2] = ATTR_opts___OptionEnum____values(fra.me.REG[0]);
    fra.me.REG[0] = CALL_opts___Option___default_value(fra.me.REG[0])(fra.me.REG[0]);
    REGB0 = TAG_Bool((fra.me.REG[0]!=NIT_NULL) && VAL_ISA(fra.me.REG[0], COLOR_standard___kernel___Int, ID_standard___kernel___Int)) /*cast VALUE*/;
    if (UNTAG_Bool(REGB0)) {
    } else {
      nit_abort("Cast failed", NULL, LOCATE_opts, 158);
    }
    /* ./../lib/standard//collection//array.nit:243 */
    REGB0 = fra.me.REG[0];
    /* ./../lib/standard//collection//array.nit:245 */
    REGB1 = TAG_Int(0);
    /* ./../lib/standard//kernel.nit:216 */
    REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
    /* ./../lib/standard//collection//array.nit:245 */
    if (UNTAG_Bool(REGB1)) {
      REGB1 = TAG_Bool(ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[2])!=NIT_NULL);
      if (UNTAG_Bool(REGB1)) {
      } else {
        nit_abort("Uninitialized attribute %s", "_length", LOCATE_standard___collection___array, 245);
      }
      REGB1 = ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[2]);
      /* ./../lib/standard//kernel.nit:215 */
      REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
    } else {
      /* ./../lib/standard//collection//array.nit:245 */
      REGB2 = TAG_Bool(false);
      REGB1 = REGB2;
    }
    if (UNTAG_Bool(REGB1)) {
    } else {
      nit_abort("Assert %s  failed", "'index'", LOCATE_standard___collection___array, 245);
    }
    /* ./../lib/standard//collection//array.nit:246 */
    fra.me.REG[2] = ATTR_standard___collection___array___Array____items(fra.me.REG[2]);
    REGB1 = TAG_Bool(fra.me.REG[2]==NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
      nit_abort("Reciever is null", NULL, LOCATE_standard___collection___array, 246);
    }
    /* ./../lib/standard//collection//array.nit:654 */
    fra.me.REG[2] = ((Nit_NativeArray)fra.me.REG[2])->val[UNTAG_Int(REGB0)];
    /* ./../lib/standard//collection//array.nit:246 */
    goto label2;
    label2: while(0);
    /* ./../lib/opts.nit:158 */
    CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
    if (!once_value_3) {
      fra.me.REG[2] = BOX_NativeString(")");
      REGB0 = TAG_Int(1);
      fra.me.REG[2] = NEW_String_standard___string___String___with_native(fra.me.REG[2], REGB0);
      once_value_3 = fra.me.REG[2];
      register_static_object(&once_value_3);
    } else fra.me.REG[2] = once_value_3;
    fra.me.REG[2] = fra.me.REG[2];
    CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
    fra.me.REG[1] = CALL_standard___string___Object___to_s(fra.me.REG[1])(fra.me.REG[1]);
    goto label4;
  } else {
    /* ./../lib/opts.nit:160 */
    if (!once_value_5) {
      fra.me.REG[2] = BOX_NativeString("");
      REGB0 = TAG_Int(0);
      fra.me.REG[2] = NEW_String_standard___string___String___with_native(fra.me.REG[2], REGB0);
      once_value_5 = fra.me.REG[2];
      register_static_object(&once_value_5);
    } else fra.me.REG[2] = once_value_5;
    fra.me.REG[2] = fra.me.REG[2];
    fra.me.REG[1] = fra.me.REG[2];
    goto label4;
  }
  label4: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[1];
}
void opts___OptionInt___init(val_t p0, val_t p1, val_t p2, val_t p3, int* init_table){
  int itpos7 = VAL2OBJ(p0)->vft[INIT_TABLE_POS_opts___OptionInt].i;
  struct {struct stack_frame_t me; val_t MORE_REG[2];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t tmp;
  if (init_table[itpos7]) return;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 169;
  fra.me.meth = LOCATE_opts___OptionInt___init;
  fra.me.has_broke = 0;
  fra.me.REG_size = 3;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  REGB0 = p2;
  fra.me.REG[2] = p3;
  /* ./../lib/opts.nit:169 */
  REGB1 = TAG_Bool(VAL_ISA(fra.me.REG[2], COLOR_standard___collection___array___Array, ID_standard___collection___array___Array)) /*cast Array[String]*/;
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Cast failed", NULL, LOCATE_opts, 169);
  }
  CALL_opts___OptionParameter___init_opt(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[1], REGB0, fra.me.REG[2], init_table);
  stack_frame_head = fra.me.prev;
  init_table[itpos7] = 1;
  return;
}
val_t opts___OptionInt___convert(val_t p0, val_t p1){
  struct {struct stack_frame_t me; val_t MORE_REG[1];} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 171;
  fra.me.meth = LOCATE_opts___OptionInt___convert;
  fra.me.has_broke = 0;
  fra.me.REG_size = 2;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  /* ./../lib/opts.nit:171 */
  REGB0 = CALL_standard___string___AbstractString___to_i(fra.me.REG[1])(fra.me.REG[1]);
  goto label1;
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return REGB0;
}
void opts___OptionArray___init(val_t p0, val_t p1, val_t p2, int* init_table){
  int itpos8 = VAL2OBJ(p0)->vft[INIT_TABLE_POS_opts___OptionArray].i;
  struct {struct stack_frame_t me; val_t MORE_REG[3];} fra;
  val_t REGB0;
  val_t tmp;
  if (init_table[itpos8]) return;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 178;
  fra.me.meth = LOCATE_opts___OptionArray___init;
  fra.me.has_broke = 0;
  fra.me.REG_size = 4;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[3] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  fra.me.REG[2] = p2;
  /* ./../lib/opts.nit:178 */
  REGB0 = TAG_Bool(VAL_ISA(fra.me.REG[2], COLOR_standard___collection___array___Array, ID_standard___collection___array___Array)) /*cast Array[String]*/;
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Cast failed", NULL, LOCATE_opts, 178);
  }
  /* ./../lib/opts.nit:180 */
  fra.me.REG[3] = NEW_Array_standard___collection___array___Array___init();
  ATTR_opts___OptionArray____values(fra.me.REG[0]) = fra.me.REG[3];
  /* ./../lib/opts.nit:181 */
  REGB0 = TAG_Bool(ATTR_opts___OptionArray____values(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_values", LOCATE_opts, 181);
  }
  fra.me.REG[3] = ATTR_opts___OptionArray____values(fra.me.REG[0]);
  CALL_opts___OptionParameter___init_opt(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[1], fra.me.REG[3], fra.me.REG[2], init_table);
  stack_frame_head = fra.me.prev;
  init_table[itpos8] = 1;
  return;
}
val_t opts___OptionArray___convert(val_t p0, val_t p1){
  struct {struct stack_frame_t me; val_t MORE_REG[2];} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 185;
  fra.me.meth = LOCATE_opts___OptionArray___convert;
  fra.me.has_broke = 0;
  fra.me.REG_size = 3;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  /* ./../lib/opts.nit:187 */
  REGB0 = TAG_Bool(ATTR_opts___OptionArray____values(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_values", LOCATE_opts, 187);
  }
  fra.me.REG[2] = ATTR_opts___OptionArray____values(fra.me.REG[0]);
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[1]);
  /* ./../lib/opts.nit:188 */
  REGB0 = TAG_Bool(ATTR_opts___OptionArray____values(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_values", LOCATE_opts, 188);
  }
  fra.me.REG[0] = ATTR_opts___OptionArray____values(fra.me.REG[0]);
  goto label1;
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t opts___OptionContext___options(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 193;
  fra.me.meth = LOCATE_opts___OptionContext___options;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/opts.nit:193 */
  REGB0 = TAG_Bool(ATTR_opts___OptionContext____options(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_options", LOCATE_opts, 193);
  }
  fra.me.REG[0] = ATTR_opts___OptionContext____options(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t opts___OptionContext___rest(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 194;
  fra.me.meth = LOCATE_opts___OptionContext___rest;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/opts.nit:194 */
  REGB0 = TAG_Bool(ATTR_opts___OptionContext____rest(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_rest", LOCATE_opts, 194);
  }
  fra.me.REG[0] = ATTR_opts___OptionContext____rest(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
void opts___OptionContext___usage(val_t p0){
  struct {struct stack_frame_t me; val_t MORE_REG[5];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t REGB2;
  val_t REGB3;
  val_t REGB4;
  val_t REGB5;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 198;
  fra.me.meth = LOCATE_opts___OptionContext___usage;
  fra.me.has_broke = 0;
  fra.me.REG_size = 6;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[3] = NIT_NULL;
  fra.me.REG[4] = NIT_NULL;
  fra.me.REG[5] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/opts.nit:200 */
  REGB0 = TAG_Int(1);
  /* ./../lib/opts.nit:201 */
  REGB1 = TAG_Bool(ATTR_opts___OptionContext____options(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_options", LOCATE_opts, 201);
  }
  fra.me.REG[1] = ATTR_opts___OptionContext____options(fra.me.REG[0]);
  /* ./../lib/standard//collection//array.nit:234 */
  REGB1 = TAG_Int(0);
  /* ./../lib/standard//collection//array.nit:235 */
  REGB2 = TAG_Bool(ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[1])!=NIT_NULL);
  if (UNTAG_Bool(REGB2)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_length", LOCATE_standard___collection___array, 235);
  }
  REGB2 = ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[1]);
  /* ./../lib/standard//collection//array.nit:236 */
  fra.me.REG[2] = ATTR_standard___collection___array___Array____items(fra.me.REG[1]);
  /* ./../lib/standard//collection//array.nit:237 */
  while(1) {
    /* ./../lib/standard//collection//array.nit:23 */
    REGB2 = TAG_Bool(ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[1])!=NIT_NULL);
    if (UNTAG_Bool(REGB2)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_length", LOCATE_standard___collection___array, 23);
    }
    REGB2 = ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[1]);
    /* ./../lib/standard//kernel.nit:215 */
    REGB2 = TAG_Bool(UNTAG_Int(REGB1)<UNTAG_Int(REGB2));
    /* ./../lib/standard//collection//array.nit:237 */
    if (UNTAG_Bool(REGB2)) {
      /* ./../lib/standard//collection//array.nit:238 */
      REGB2 = TAG_Bool(fra.me.REG[2]==NIT_NULL);
      if (UNTAG_Bool(REGB2)) {
        nit_abort("Reciever is null", NULL, LOCATE_standard___collection___array, 238);
      }
      /* ./../lib/standard//collection//array.nit:654 */
      fra.me.REG[3] = ((Nit_NativeArray)fra.me.REG[2])->val[UNTAG_Int(REGB1)];
      /* ./../lib/opts.nit:202 */
      REGB2 = TAG_Int(3);
      /* ./../lib/opts.nit:203 */
      fra.me.REG[3] = CALL_opts___Option___names(fra.me.REG[3])(fra.me.REG[3]);
      /* ./../lib/standard//collection//array.nit:234 */
      REGB3 = TAG_Int(0);
      /* ./../lib/standard//collection//array.nit:235 */
      REGB4 = TAG_Bool(ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[3])!=NIT_NULL);
      if (UNTAG_Bool(REGB4)) {
      } else {
        nit_abort("Uninitialized attribute %s", "_length", LOCATE_standard___collection___array, 235);
      }
      REGB4 = ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[3]);
      /* ./../lib/standard//collection//array.nit:236 */
      fra.me.REG[4] = ATTR_standard___collection___array___Array____items(fra.me.REG[3]);
      /* ./../lib/standard//collection//array.nit:237 */
      while(1) {
        /* ./../lib/standard//collection//array.nit:23 */
        REGB4 = TAG_Bool(ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[3])!=NIT_NULL);
        if (UNTAG_Bool(REGB4)) {
        } else {
          nit_abort("Uninitialized attribute %s", "_length", LOCATE_standard___collection___array, 23);
        }
        REGB4 = ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[3]);
        /* ./../lib/standard//kernel.nit:215 */
        REGB4 = TAG_Bool(UNTAG_Int(REGB3)<UNTAG_Int(REGB4));
        /* ./../lib/standard//collection//array.nit:237 */
        if (UNTAG_Bool(REGB4)) {
          /* ./../lib/standard//collection//array.nit:238 */
          REGB4 = TAG_Bool(fra.me.REG[4]==NIT_NULL);
          if (UNTAG_Bool(REGB4)) {
            nit_abort("Reciever is null", NULL, LOCATE_standard___collection___array, 238);
          }
          /* ./../lib/standard//collection//array.nit:654 */
          fra.me.REG[5] = ((Nit_NativeArray)fra.me.REG[4])->val[UNTAG_Int(REGB3)];
          /* ./../lib/standard//collection//array.nit:23 */
          REGB4 = TAG_Bool(ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[5])!=NIT_NULL);
          if (UNTAG_Bool(REGB4)) {
          } else {
            nit_abort("Uninitialized attribute %s", "_length", LOCATE_standard___collection___array, 23);
          }
          REGB4 = ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[5]);
          /* ./../lib/opts.nit:204 */
          REGB5 = TAG_Int(2);
          /* ./../lib/standard//kernel.nit:218 */
          REGB5 = TAG_Int(UNTAG_Int(REGB4)+UNTAG_Int(REGB5));
          REGB5 = TAG_Int(UNTAG_Int(REGB2)+UNTAG_Int(REGB5));
          /* ./../lib/opts.nit:204 */
          REGB2 = REGB5;
          /* ./../lib/standard//collection//array.nit:239 */
          REGB5 = TAG_Int(1);
          /* ./../lib/standard//kernel.nit:218 */
          REGB5 = TAG_Int(UNTAG_Int(REGB3)+UNTAG_Int(REGB5));
          /* ./../lib/standard//collection//array.nit:239 */
          REGB3 = REGB5;
        } else {
          /* ./../lib/standard//collection//array.nit:237 */
          goto label1;
        }
      }
      label1: while(0);
      /* ./../lib/standard//kernel.nit:215 */
      REGB3 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB2));
      /* ./../lib/opts.nit:206 */
      if (UNTAG_Bool(REGB3)) {
        REGB0 = REGB2;
      }
      /* ./../lib/standard//collection//array.nit:239 */
      REGB2 = TAG_Int(1);
      /* ./../lib/standard//kernel.nit:218 */
      REGB2 = TAG_Int(UNTAG_Int(REGB1)+UNTAG_Int(REGB2));
      /* ./../lib/standard//collection//array.nit:239 */
      REGB1 = REGB2;
    } else {
      /* ./../lib/standard//collection//array.nit:237 */
      goto label2;
    }
  }
  label2: while(0);
  /* ./../lib/opts.nit:209 */
  REGB1 = TAG_Bool(ATTR_opts___OptionContext____options(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_options", LOCATE_opts, 209);
  }
  fra.me.REG[2] = ATTR_opts___OptionContext____options(fra.me.REG[0]);
  /* ./../lib/standard//collection//array.nit:234 */
  REGB1 = TAG_Int(0);
  /* ./../lib/standard//collection//array.nit:235 */
  REGB2 = TAG_Bool(ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[2])!=NIT_NULL);
  if (UNTAG_Bool(REGB2)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_length", LOCATE_standard___collection___array, 235);
  }
  REGB2 = ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[2]);
  /* ./../lib/standard//collection//array.nit:236 */
  fra.me.REG[1] = ATTR_standard___collection___array___Array____items(fra.me.REG[2]);
  /* ./../lib/standard//collection//array.nit:237 */
  while(1) {
    /* ./../lib/standard//collection//array.nit:23 */
    REGB2 = TAG_Bool(ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[2])!=NIT_NULL);
    if (UNTAG_Bool(REGB2)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_length", LOCATE_standard___collection___array, 23);
    }
    REGB2 = ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[2]);
    /* ./../lib/standard//kernel.nit:215 */
    REGB2 = TAG_Bool(UNTAG_Int(REGB1)<UNTAG_Int(REGB2));
    /* ./../lib/standard//collection//array.nit:237 */
    if (UNTAG_Bool(REGB2)) {
      /* ./../lib/standard//collection//array.nit:238 */
      REGB2 = TAG_Bool(fra.me.REG[1]==NIT_NULL);
      if (UNTAG_Bool(REGB2)) {
        nit_abort("Reciever is null", NULL, LOCATE_standard___collection___array, 238);
      }
      /* ./../lib/standard//collection//array.nit:654 */
      fra.me.REG[4] = ((Nit_NativeArray)fra.me.REG[1])->val[UNTAG_Int(REGB1)];
      /* ./../lib/opts.nit:210 */
      fra.me.REG[4] = CALL_opts___Option___pretty(fra.me.REG[4])(fra.me.REG[4], REGB0);
      CALL_standard___file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[4]);
      /* ./../lib/standard//collection//array.nit:239 */
      REGB2 = TAG_Int(1);
      /* ./../lib/standard//kernel.nit:218 */
      REGB2 = TAG_Int(UNTAG_Int(REGB1)+UNTAG_Int(REGB2));
      /* ./../lib/standard//collection//array.nit:239 */
      REGB1 = REGB2;
    } else {
      /* ./../lib/standard//collection//array.nit:237 */
      goto label3;
    }
  }
  label3: while(0);
  stack_frame_head = fra.me.prev;
  return;
}
void opts___OptionContext___parse(val_t p0, val_t p1){
  struct {struct stack_frame_t me; val_t MORE_REG[1];} fra;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 214;
  fra.me.meth = LOCATE_opts___OptionContext___parse;
  fra.me.has_broke = 0;
  fra.me.REG_size = 2;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  /* ./../lib/opts.nit:217 */
  fra.me.REG[1] = CALL_standard___collection___abstract_collection___Collection___iterator(fra.me.REG[1])(fra.me.REG[1]);
  /* ./../lib/opts.nit:218 */
  CALL_opts___OptionContext___parse_intern(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[1]);
  stack_frame_head = fra.me.prev;
  return;
}
void opts___OptionContext___parse_intern(val_t p0, val_t p1){
  struct {struct stack_frame_t me; val_t MORE_REG[4];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t REGB2;
  val_t tmp;
      static val_t once_value_1; /* Once value */
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 221;
  fra.me.meth = LOCATE_opts___OptionContext___parse_intern;
  fra.me.has_broke = 0;
  fra.me.REG_size = 5;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[3] = NIT_NULL;
  fra.me.REG[4] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  /* ./../lib/opts.nit:223 */
  REGB0 = TAG_Bool(true);
  /* ./../lib/opts.nit:224 */
  CALL_opts___OptionContext___build(fra.me.REG[0])(fra.me.REG[0]);
  /* ./../lib/opts.nit:225 */
  REGB1 = TAG_Bool(ATTR_opts___OptionContext____rest(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_rest", LOCATE_opts, 225);
  }
  fra.me.REG[2] = ATTR_opts___OptionContext____rest(fra.me.REG[0]);
  /* ./../lib/opts.nit:227 */
  while(1) {
    if (UNTAG_Bool(REGB0)) {
      REGB1 = CALL_standard___collection___abstract_collection___Iterator___is_ok(fra.me.REG[1])(fra.me.REG[1]);
    } else {
      REGB2 = TAG_Bool(false);
      REGB1 = REGB2;
    }
    if (UNTAG_Bool(REGB1)) {
      /* ./../lib/opts.nit:228 */
      fra.me.REG[3] = CALL_standard___collection___abstract_collection___Iterator___item(fra.me.REG[1])(fra.me.REG[1]);
      /* ./../lib/opts.nit:229 */
      if (!once_value_1) {
        fra.me.REG[4] = BOX_NativeString("--");
        REGB1 = TAG_Int(2);
        fra.me.REG[4] = NEW_String_standard___string___String___with_native(fra.me.REG[4], REGB1);
        once_value_1 = fra.me.REG[4];
        register_static_object(&once_value_1);
      } else fra.me.REG[4] = once_value_1;
      fra.me.REG[4] = fra.me.REG[4];
      REGB1 = TAG_Bool(IS_EQUAL_OO(fra.me.REG[3],fra.me.REG[4]));
      if (UNTAG_Bool(REGB1)) {
      } else {
        REGB2 = CALL_standard___kernel___Object_____eqeq(fra.me.REG[3])(fra.me.REG[3], fra.me.REG[4]);
        REGB1 = REGB2;
      }
      if (UNTAG_Bool(REGB1)) {
        /* ./../lib/opts.nit:230 */
        CALL_standard___collection___abstract_collection___Iterator___next(fra.me.REG[1])(fra.me.REG[1]);
        /* ./../lib/opts.nit:231 */
        fra.me.REG[4] = CALL_standard___collection___array___Iterator___to_a(fra.me.REG[1])(fra.me.REG[1]);
        CALL_standard___collection___abstract_collection___SimpleCollection___add_all(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[4]);
        /* ./../lib/opts.nit:232 */
        REGB1 = TAG_Bool(false);
        REGB0 = REGB1;
      } else {
        /* ./../lib/opts.nit:234 */
        REGB1 = TAG_Bool(ATTR_opts___OptionContext____optmap(fra.me.REG[0])!=NIT_NULL);
        if (UNTAG_Bool(REGB1)) {
        } else {
          nit_abort("Uninitialized attribute %s", "_optmap", LOCATE_opts, 234);
        }
        fra.me.REG[4] = ATTR_opts___OptionContext____optmap(fra.me.REG[0]);
        REGB1 = CALL_standard___collection___abstract_collection___MapRead___has_key(fra.me.REG[4])(fra.me.REG[4], fra.me.REG[3]);
        if (UNTAG_Bool(REGB1)) {
          /* ./../lib/opts.nit:235 */
          REGB1 = TAG_Bool(ATTR_opts___OptionContext____optmap(fra.me.REG[0])!=NIT_NULL);
          if (UNTAG_Bool(REGB1)) {
          } else {
            nit_abort("Uninitialized attribute %s", "_optmap", LOCATE_opts, 235);
          }
          fra.me.REG[4] = ATTR_opts___OptionContext____optmap(fra.me.REG[0]);
          fra.me.REG[3] = CALL_standard___collection___abstract_collection___MapRead_____bra(fra.me.REG[4])(fra.me.REG[4], fra.me.REG[3]);
          /* ./../lib/opts.nit:236 */
          CALL_standard___collection___abstract_collection___Iterator___next(fra.me.REG[1])(fra.me.REG[1]);
          /* ./../lib/opts.nit:237 */
          CALL_opts___Option___read_param(fra.me.REG[3])(fra.me.REG[3], fra.me.REG[1]);
        } else {
          /* ./../lib/opts.nit:239 */
          fra.me.REG[3] = CALL_standard___collection___abstract_collection___Iterator___item(fra.me.REG[1])(fra.me.REG[1]);
          CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[3]);
          /* ./../lib/opts.nit:240 */
          CALL_standard___collection___abstract_collection___Iterator___next(fra.me.REG[1])(fra.me.REG[1]);
        }
      }
    } else {
      /* ./../lib/opts.nit:227 */
      goto label2;
    }
  }
  label2: while(0);
  stack_frame_head = fra.me.prev;
  return;
}
void opts___OptionContext___add_option(val_t p0, val_t p1){
  struct {struct stack_frame_t me; val_t MORE_REG[4];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 246;
  fra.me.meth = LOCATE_opts___OptionContext___add_option;
  fra.me.has_broke = 0;
  fra.me.REG_size = 5;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[3] = NIT_NULL;
  fra.me.REG[4] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  /* ./../lib/opts.nit:246 */
  REGB0 = TAG_Bool(VAL_ISA(fra.me.REG[1], COLOR_standard___collection___array___Array, ID_standard___collection___array___Array)) /*cast Array[Option]*/;
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Cast failed", NULL, LOCATE_opts, 246);
  }
  /* ./../lib/standard//collection//array.nit:234 */
  REGB0 = TAG_Int(0);
  /* ./../lib/standard//collection//array.nit:235 */
  REGB1 = TAG_Bool(ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[1])!=NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_length", LOCATE_standard___collection___array, 235);
  }
  REGB1 = ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[1]);
  /* ./../lib/standard//collection//array.nit:236 */
  fra.me.REG[2] = ATTR_standard___collection___array___Array____items(fra.me.REG[1]);
  /* ./../lib/standard//collection//array.nit:237 */
  while(1) {
    /* ./../lib/standard//collection//array.nit:23 */
    REGB1 = TAG_Bool(ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[1])!=NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_length", LOCATE_standard___collection___array, 23);
    }
    REGB1 = ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[1]);
    /* ./../lib/standard//kernel.nit:215 */
    REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
    /* ./../lib/standard//collection//array.nit:237 */
    if (UNTAG_Bool(REGB1)) {
      /* ./../lib/standard//collection//array.nit:238 */
      REGB1 = TAG_Bool(fra.me.REG[2]==NIT_NULL);
      if (UNTAG_Bool(REGB1)) {
        nit_abort("Reciever is null", NULL, LOCATE_standard___collection___array, 238);
      }
      /* ./../lib/standard//collection//array.nit:654 */
      fra.me.REG[3] = ((Nit_NativeArray)fra.me.REG[2])->val[UNTAG_Int(REGB0)];
      /* ./../lib/opts.nit:249 */
      REGB1 = TAG_Bool(ATTR_opts___OptionContext____options(fra.me.REG[0])!=NIT_NULL);
      if (UNTAG_Bool(REGB1)) {
      } else {
        nit_abort("Uninitialized attribute %s", "_options", LOCATE_opts, 249);
      }
      fra.me.REG[4] = ATTR_opts___OptionContext____options(fra.me.REG[0]);
      CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[4])(fra.me.REG[4], fra.me.REG[3]);
      /* ./../lib/standard//collection//array.nit:239 */
      REGB1 = TAG_Int(1);
      /* ./../lib/standard//kernel.nit:218 */
      REGB1 = TAG_Int(UNTAG_Int(REGB0)+UNTAG_Int(REGB1));
      /* ./../lib/standard//collection//array.nit:239 */
      REGB0 = REGB1;
    } else {
      /* ./../lib/standard//collection//array.nit:237 */
      goto label1;
    }
  }
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return;
}
void opts___OptionContext___init(val_t p0, int* init_table){
  int itpos9 = VAL2OBJ(p0)->vft[INIT_TABLE_POS_opts___OptionContext].i;
  struct {struct stack_frame_t me; val_t MORE_REG[1];} fra;
  val_t tmp;
  if (init_table[itpos9]) return;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 253;
  fra.me.meth = LOCATE_opts___OptionContext___init;
  fra.me.has_broke = 0;
  fra.me.REG_size = 2;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/opts.nit:255 */
  fra.me.REG[1] = NEW_Array_standard___collection___array___Array___init();
  ATTR_opts___OptionContext____options(fra.me.REG[0]) = fra.me.REG[1];
  /* ./../lib/opts.nit:256 */
  fra.me.REG[1] = NEW_HashMap_standard___collection___hash_collection___HashMap___init();
  ATTR_opts___OptionContext____optmap(fra.me.REG[0]) = fra.me.REG[1];
  /* ./../lib/opts.nit:257 */
  fra.me.REG[1] = NEW_Array_standard___collection___array___Array___init();
  ATTR_opts___OptionContext____rest(fra.me.REG[0]) = fra.me.REG[1];
  stack_frame_head = fra.me.prev;
  init_table[itpos9] = 1;
  return;
}
void opts___OptionContext___build(val_t p0){
  struct {struct stack_frame_t me; val_t MORE_REG[7];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t REGB2;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_opts;
  fra.me.line = 260;
  fra.me.meth = LOCATE_opts___OptionContext___build;
  fra.me.has_broke = 0;
  fra.me.REG_size = 8;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[3] = NIT_NULL;
  fra.me.REG[4] = NIT_NULL;
  fra.me.REG[5] = NIT_NULL;
  fra.me.REG[6] = NIT_NULL;
  fra.me.REG[7] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/opts.nit:262 */
  REGB0 = TAG_Bool(ATTR_opts___OptionContext____options(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_options", LOCATE_opts, 262);
  }
  fra.me.REG[1] = ATTR_opts___OptionContext____options(fra.me.REG[0]);
  /* ./../lib/standard//collection//array.nit:234 */
  REGB0 = TAG_Int(0);
  /* ./../lib/standard//collection//array.nit:235 */
  REGB1 = TAG_Bool(ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[1])!=NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_length", LOCATE_standard___collection___array, 235);
  }
  REGB1 = ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[1]);
  /* ./../lib/standard//collection//array.nit:236 */
  fra.me.REG[2] = ATTR_standard___collection___array___Array____items(fra.me.REG[1]);
  /* ./../lib/standard//collection//array.nit:237 */
  while(1) {
    /* ./../lib/standard//collection//array.nit:23 */
    REGB1 = TAG_Bool(ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[1])!=NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_length", LOCATE_standard___collection___array, 23);
    }
    REGB1 = ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[1]);
    /* ./../lib/standard//kernel.nit:215 */
    REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
    /* ./../lib/standard//collection//array.nit:237 */
    if (UNTAG_Bool(REGB1)) {
      /* ./../lib/standard//collection//array.nit:238 */
      REGB1 = TAG_Bool(fra.me.REG[2]==NIT_NULL);
      if (UNTAG_Bool(REGB1)) {
        nit_abort("Reciever is null", NULL, LOCATE_standard___collection___array, 238);
      }
      /* ./../lib/standard//collection//array.nit:654 */
      fra.me.REG[3] = ((Nit_NativeArray)fra.me.REG[2])->val[UNTAG_Int(REGB0)];
      /* ./../lib/opts.nit:263 */
      fra.me.REG[4] = CALL_opts___Option___names(fra.me.REG[3])(fra.me.REG[3]);
      /* ./../lib/standard//collection//array.nit:234 */
      REGB1 = TAG_Int(0);
      /* ./../lib/standard//collection//array.nit:235 */
      REGB2 = TAG_Bool(ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[4])!=NIT_NULL);
      if (UNTAG_Bool(REGB2)) {
      } else {
        nit_abort("Uninitialized attribute %s", "_length", LOCATE_standard___collection___array, 235);
      }
      REGB2 = ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[4]);
      /* ./../lib/standard//collection//array.nit:236 */
      fra.me.REG[5] = ATTR_standard___collection___array___Array____items(fra.me.REG[4]);
      /* ./../lib/standard//collection//array.nit:237 */
      while(1) {
        /* ./../lib/standard//collection//array.nit:23 */
        REGB2 = TAG_Bool(ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[4])!=NIT_NULL);
        if (UNTAG_Bool(REGB2)) {
        } else {
          nit_abort("Uninitialized attribute %s", "_length", LOCATE_standard___collection___array, 23);
        }
        REGB2 = ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[4]);
        /* ./../lib/standard//kernel.nit:215 */
        REGB2 = TAG_Bool(UNTAG_Int(REGB1)<UNTAG_Int(REGB2));
        /* ./../lib/standard//collection//array.nit:237 */
        if (UNTAG_Bool(REGB2)) {
          /* ./../lib/standard//collection//array.nit:238 */
          REGB2 = TAG_Bool(fra.me.REG[5]==NIT_NULL);
          if (UNTAG_Bool(REGB2)) {
            nit_abort("Reciever is null", NULL, LOCATE_standard___collection___array, 238);
          }
          /* ./../lib/standard//collection//array.nit:654 */
          fra.me.REG[6] = ((Nit_NativeArray)fra.me.REG[5])->val[UNTAG_Int(REGB1)];
          /* ./../lib/opts.nit:264 */
          REGB2 = TAG_Bool(ATTR_opts___OptionContext____optmap(fra.me.REG[0])!=NIT_NULL);
          if (UNTAG_Bool(REGB2)) {
          } else {
            nit_abort("Uninitialized attribute %s", "_optmap", LOCATE_opts, 264);
          }
          fra.me.REG[7] = ATTR_opts___OptionContext____optmap(fra.me.REG[0]);
          CALL_standard___collection___abstract_collection___Map_____braeq(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[6], fra.me.REG[3]);
          /* ./../lib/standard//collection//array.nit:239 */
          REGB2 = TAG_Int(1);
          /* ./../lib/standard//kernel.nit:218 */
          REGB2 = TAG_Int(UNTAG_Int(REGB1)+UNTAG_Int(REGB2));
          /* ./../lib/standard//collection//array.nit:239 */
          REGB1 = REGB2;
        } else {
          /* ./../lib/standard//collection//array.nit:237 */
          goto label1;
        }
      }
      label1: while(0);
      /* ./../lib/standard//collection//array.nit:239 */
      REGB1 = TAG_Int(1);
      /* ./../lib/standard//kernel.nit:218 */
      REGB1 = TAG_Int(UNTAG_Int(REGB0)+UNTAG_Int(REGB1));
      /* ./../lib/standard//collection//array.nit:239 */
      REGB0 = REGB1;
    } else {
      /* ./../lib/standard//collection//array.nit:237 */
      goto label2;
    }
  }
  label2: while(0);
  stack_frame_head = fra.me.prev;
  return;
}
