#include "nit.common.h"
extern const int COLOR_opts__Option___names;
val* opts__Option__names(val* self);
extern const int COLOR_opts__Option___helptext;
val* opts__Option__helptext(val* self);
extern const int COLOR_opts__Option___errors;
val* opts__Option__errors(val* self);
extern const int COLOR_opts__Option___mandatory;
short int opts__Option__mandatory(val* self);
void opts__Option__mandatory_61d(val* self, short int p0);
extern const int COLOR_opts__Option___read;
short int opts__Option__read(val* self);
extern const int COLOR_opts__Option_VTVALUE;
extern const int COLOR_opts__Option___value;
void opts__Option__value_61d(val* self, val* p0);
val* opts__Option__value(val* self);
extern const int COLOR_opts__Option___default_value;
val* opts__Option__default_value(val* self);
void opts__Option__default_value_61d(val* self, val* p0);
val* NEW_array__Array(const struct type* type);
extern const struct type type_array__Arraystring__String;
extern const int COLOR_array__Array__init;
extern const int COLOR_array__Collection__to_a;
void opts__Option__init_opt(val* self, val* p0, val* p1, val* p2);
extern const int COLOR_abstract_collection__SimpleCollection__add_all;
void opts__Option__add_aliases(val* self, val* p0);
extern const int COLOR_opts__Option__pretty;
val* opts__Option__to_s(val* self);
val* NEW_string__Buffer(const struct type* type);
extern const struct type type_string__Buffer;
val* string__NativeString__to_s_with_length(char* self, long p0);
extern const int COLOR_string__Buffer__from;
extern const int COLOR_string__Collection__join;
extern const int COLOR_abstract_collection__Sequence__append;
extern const int COLOR_abstract_collection__Collection__length;
extern const struct type type_kernel__Int;
extern const int COLOR_string__String___42d;
extern const int COLOR_opts__Option__helptext;
extern const int COLOR_string__Object__to_s;
val* opts__Option__pretty(val* self, long p0);
extern const int COLOR_opts__Option__default_value;
extern const struct type type_array__Arraykernel__Object;
extern const int COLOR_array__Array__with_capacity;
extern const int COLOR_abstract_collection__SimpleCollection__add;
val* opts__Option__pretty_default(val* self);
void opts__Option__read_param(val* self, val* p0);
extern const int COLOR_opts__Option__init_opt;
void opts__OptionText__init(val* self, val* p0);
val* opts__OptionText__pretty(val* self, long p0);
val* opts__OptionText__to_s(val* self);
void opts__OptionBool__init(val* self, val* p0, val* p1);
extern const int COLOR_opts__OptionBool__read_param;
extern const int COLOR_opts__Option__value_61d;
void opts__OptionBool__read_param(val* self, val* p0);
void opts__OptionCount__init(val* self, val* p0, val* p1);
extern const int COLOR_opts__OptionCount__read_param;
extern const int COLOR_opts__Option__value;
void opts__OptionCount__read_param(val* self, val* p0);
val* opts__OptionParameter__convert(val* self, val* p0);
extern const int COLOR_opts__OptionParameter___parameter_mandatory;
short int opts__OptionParameter__parameter_mandatory(val* self);
void opts__OptionParameter__parameter_mandatory_61d(val* self, short int p0);
extern const int COLOR_opts__OptionParameter__read_param;
extern const int COLOR_abstract_collection__Iterator__is_ok;
extern const int COLOR_abstract_collection__Iterator__item;
extern const int COLOR_abstract_collection__Collection__first;
extern const struct class class_kernel__Char;
extern const int COLOR_opts__OptionParameter__convert;
extern const int COLOR_abstract_collection__Iterator__next;
extern const int COLOR_opts__Option__names;
val* NEW_array__NativeArray(int length, const struct type* type);
extern const struct type type_array__NativeArraykernel__Object;
extern const int COLOR_array__Array__with_native;
void opts__OptionParameter__read_param(val* self, val* p0);
void opts__OptionParameter__init_opt(val* self, val* p0, val* p1, val* p2);
extern const int COLOR_opts__OptionParameter__init_opt;
void opts__OptionString__init(val* self, val* p0, val* p1);
val* opts__OptionString__convert(val* self, val* p0);
extern const int COLOR_opts__OptionEnum___values;
void opts__OptionEnum__init(val* self, val* p0, val* p1, long p2, val* p3);
extern const int COLOR_abstract_collection__SequenceRead__index_of;
extern const int COLOR_string__String___43d;
long opts__OptionEnum__convert(val* self, val* p0);
extern const int COLOR_abstract_collection__SequenceRead___91d_93d;
val* opts__OptionEnum__value_name(val* self);
val* opts__OptionEnum__pretty_default(val* self);
void opts__OptionInt__init(val* self, val* p0, long p1, val* p2);
extern const int COLOR_string__AbstractString__to_i;
long opts__OptionInt__convert(val* self, val* p0);
extern const int COLOR_opts__OptionArray___values;
void opts__OptionArray__init(val* self, val* p0, val* p1);
val* opts__OptionArray__convert(val* self, val* p0);
extern const int COLOR_opts__OptionContext___options;
val* opts__OptionContext__options(val* self);
extern const int COLOR_opts__OptionContext___rest;
val* opts__OptionContext__rest(val* self);
extern const int COLOR_opts__OptionContext___errors;
val* opts__OptionContext__errors(val* self);
extern const int COLOR_abstract_collection__Collection__iterator;
extern const int COLOR_file__Object__print;
void opts__OptionContext__usage(val* self);
extern const int COLOR_opts__OptionContext__parse_intern;
void opts__OptionContext__parse(val* self, val* p0);
extern const int COLOR_opts__OptionContext__build;
extern const int COLOR_kernel__Object___61d_61d;
extern const int COLOR_array__Iterator__to_a;
extern const int COLOR_array__AbstractArrayRead__last_index_of;
val* NEW_range__Range(const struct type* type);
extern const struct type type_range__Rangekernel__Int;
extern const int COLOR_range__Range__init;
val* string__Char__to_s(char self);
extern const int COLOR_opts__OptionContext___optmap;
extern const int COLOR_abstract_collection__MapRead__has_key;
extern const int COLOR_abstract_collection__MapRead___91d_93d;
extern const struct type type_opts__OptionParameter;
extern const int COLOR_opts__Option__read_param;
extern const int COLOR_opts__Option__mandatory;
extern const int COLOR_opts__Option__read;
void opts__OptionContext__parse_intern(val* self, val* p0);
void opts__OptionContext__add_option(val* self, val* p0);
extern const struct type type_array__Arrayopts__Option;
val* NEW_hash_collection__HashMap(const struct type* type);
extern const struct type type_hash_collection__HashMapstring__Stringopts__Option;
extern const int COLOR_hash_collection__HashMap__init;
void opts__OptionContext__init(val* self);
extern const int COLOR_abstract_collection__Map___91d_93d_61d;
void opts__OptionContext__build(val* self);
extern const int COLOR_opts__Option__errors;
val* opts__OptionContext__get_errors(val* self);
