#include "nit.common.h"
extern const int COLOR_ordered_tree__OrderedTree___64droots;
val* ordered_tree__OrderedTree__roots(val* self);
extern const int COLOR_array__Arrayordered_tree__OrderedTree_FT0;
void ordered_tree__OrderedTree__roots_61d(val* self, val* p0);
extern const int COLOR_ordered_tree__OrderedTree___64dsub;
val* ordered_tree__OrderedTree__sub(val* self);
extern const int COLOR_hash_collection__HashMapordered_tree__OrderedTree_FT0array__Arrayordered_tree__OrderedTree_FT0;
void ordered_tree__OrderedTree__sub_61d(val* self, val* p0);
extern const int COLOR_nullable_ordered_tree__OrderedTree_FT0;
extern const int COLOR_ordered_tree__OrderedTree_FT0;
extern const int COLOR_ordered_tree__OrderedTree__roots;
extern const int COLOR_abstract_collection__SimpleCollection__add;
extern const int COLOR_ordered_tree__OrderedTree__sub;
extern const int COLOR_abstract_collection__MapRead__has_key;
extern const int COLOR_abstract_collection__MapRead___91d_93d;
val* NEW_array__Array(const struct type* type);
val* NEW_array__NativeArray(int length, const struct type* type);
extern const int COLOR_array__NativeArrayordered_tree__OrderedTree_FT0;
extern const int COLOR_array__Array__with_native;
extern const int COLOR_abstract_collection__Map___91d_93d_61d;
void ordered_tree__OrderedTree__add(val* self, val* p0, val* p1);
extern const int COLOR_abstract_collection__SequenceRead__last;
extern const int COLOR_abstract_collection__Collection__iterator;
extern const int COLOR_abstract_collection__Iterator__is_ok;
extern const int COLOR_abstract_collection__Iterator__item;
extern const int COLOR_ordered_tree__OrderedTree__display;
extern const int COLOR_stream__OStream__write;
val* string__NativeString__to_s_with_length(char* self, long p0);
extern const int COLOR_ordered_tree__OrderedTree__sub_pretty;
extern const int COLOR_abstract_collection__Iterator__next;
void ordered_tree__OrderedTree__pretty(val* self, val* p0);
extern const int COLOR_kernel__Object___33d_61d;
extern const struct type type_array__Arraykernel__Object;
extern const struct type type_array__NativeArraykernel__Object;
extern const int COLOR_string__Object__to_s;
extern const int COLOR_string__String___43d;
void ordered_tree__OrderedTree__sub_pretty(val* self, val* p0, val* p1, val* p2);
extern const int COLOR_sorter__AbstractSorterordered_tree__OrderedTree_FT0;
extern const int COLOR_sorter__AbstractSorter__sort;
extern const int COLOR_abstract_collection__MapRead__values;
void ordered_tree__OrderedTree__sort_with(val* self, val* p0);
val* ordered_tree__OrderedTree__display(val* self, val* p0);
void ordered_tree__OrderedTree__init(val* self);
