#include "nit.common.h"
val* NEW_location__SourceFile(const struct type* type);
extern const struct type type_location__SourceFile;
val* string__NativeString__to_s_with_length(char* self, long p0);
extern const int COLOR_location__SourceFile__from_string;
val* NEW_lexer__Lexer(const struct type* type);
extern const struct type type_lexer__Lexer;
extern const int COLOR_lexer__Lexer__init;
val* NEW_parser__Parser(const struct type* type);
extern const struct type type_parser__Parser;
extern const int COLOR_parser__Parser__init;
extern const int COLOR_parser__Parser__parse;
extern const int COLOR_parser_nodes__Start__n_eof;
extern const struct type type_parser_nodes__AError;
extern const int COLOR_lexer__AError__message;
val* NEW_array__Array(const struct type* type);
extern const struct type type_array__Arraykernel__Object;
val* NEW_array__NativeArray(int length, const struct type* type);
extern const struct type type_array__NativeArraykernel__Object;
extern const int COLOR_array__Array__with_native;
extern const int COLOR_string__Object__to_s;
extern const int COLOR_toolcontext__ToolContext__fatal_error;
extern const int COLOR_parser_nodes__Start__n_base;
val* parser_util__ToolContext__parse_module(val* self, val* p0);
extern const int COLOR_parser_util__ToolContext__parse_module;
extern const int COLOR_parser_nodes__AModule__n_classdefs;
extern const int COLOR_abstract_collection__Collection__length;
extern const int COLOR_abstract_collection__Collection__first;
val* parser_util__ToolContext__parse_classdef(val* self, val* p0);
extern const int COLOR_array__Array__with_capacity;
extern const int COLOR_abstract_collection__SimpleCollection__add;
extern const int COLOR_parser_util__ToolContext__parse_classdef;
extern const int COLOR_parser_nodes__AClassdef__n_propdefs;
val* parser_util__ToolContext__parse_propdef(val* self, val* p0);
extern const struct type type_parser_nodes__AMainMethPropdef;
extern const int COLOR_parser_nodes__AConcreteMethPropdef__n_block;
extern const struct type type_parser_nodes__ABlockExpr;
extern const int COLOR_parser_nodes__ABlockExpr__n_expr;
extern const struct type type_parser_nodes__ADoExpr;
extern const int COLOR_parser_nodes__ADoExpr__n_block;
val* parser_util__ToolContext__parse_stmts(val* self, val* p0);
extern const struct type type_parser_nodes__AVardeclExpr;
extern const int COLOR_parser_nodes__AVardeclExpr__n_expr;
val* parser_util__ToolContext__parse_expr(val* self, val* p0);
val* NEW_parser_util__InjectedLexer(const struct type* type);
extern const struct type type_parser_util__InjectedLexer;
extern const int COLOR_parser_util__InjectedLexer__injected_before;
val* NEW_parser_nodes__TKwvar(const struct type* type);
extern const struct type type_parser_nodes__TKwvar;
extern const int COLOR_parser_nodes__TKwvar__init;
val* NEW_parser_nodes__TId(const struct type* type);
extern const struct type type_parser_nodes__TId;
extern const int COLOR_parser_nodes__TId__init;
val* NEW_parser_nodes__TColumn(const struct type* type);
extern const struct type type_parser_nodes__TColumn;
extern const int COLOR_parser_nodes__TColumn__init;
val* NEW_parser_nodes__TClassid(const struct type* type);
extern const struct type type_parser_nodes__TClassid;
extern const int COLOR_parser_nodes__TClassid__init;
val* NEW_parser_nodes__TObra(const struct type* type);
extern const struct type type_parser_nodes__TObra;
extern const int COLOR_parser_nodes__TObra__init;
extern const int COLOR_parser_util__InjectedLexer__injected_after;
val* NEW_parser_nodes__TCbra(const struct type* type);
extern const struct type type_parser_nodes__TCbra;
extern const int COLOR_parser_nodes__TCbra__init;
extern const int COLOR_parser_nodes__AVardeclExpr__n_type;
extern const int COLOR_parser_nodes__AType__n_types;
extern const int COLOR_lexer__Lexer__next;
extern const struct type type_parser_nodes__EOF;
val* NEW_parser_nodes__TAssign(const struct type* type);
extern const struct type type_parser_nodes__TAssign;
extern const int COLOR_parser_nodes__TAssign__init;
val* NEW_parser_nodes__TOpar(const struct type* type);
extern const struct type type_parser_nodes__TOpar;
extern const int COLOR_parser_nodes__TOpar__init;
val* NEW_parser_nodes__TCpar(const struct type* type);
extern const struct type type_parser_nodes__TCpar;
extern const int COLOR_parser_nodes__TCpar__init;
extern const struct type type_parser_nodes__AParExpr;
extern const int COLOR_parser_nodes__AProxyExpr__n_expr;
extern const int COLOR_parser_nodes__ANode__location;
extern const int COLOR_kernel__Comparable___62d;
val* NEW_parser_nodes__TKwdo(const struct type* type);
extern const struct type type_parser_nodes__TKwdo;
extern const int COLOR_parser_nodes__TKwdo__init;
val* NEW_parser_nodes__TKwend(const struct type* type);
extern const struct type type_parser_nodes__TKwend;
extern const int COLOR_parser_nodes__TKwend__init;
val* parser_util__ToolContext__parse_something(val* self, val* p0);
extern const int COLOR_parser_util__InjectedLexer___64dinjected_before;
val* parser_util__InjectedLexer__injected_before(val* self);
void parser_util__InjectedLexer__injected_before_61d(val* self, val* p0);
extern const int COLOR_parser_util__InjectedLexer___64dinjected_after;
val* parser_util__InjectedLexer__injected_after(val* self);
void parser_util__InjectedLexer__injected_after_61d(val* self, val* p0);
extern const int COLOR_parser_util__InjectedLexer___64dis_finished;
short int parser_util__InjectedLexer__is_finished(val* self);
void parser_util__InjectedLexer__is_finished_61d(val* self, short int p0);
extern const int COLOR_abstract_collection__Collection__is_empty;
extern const int COLOR_abstract_collection__Sequence__shift;
extern const int COLOR_parser_nodes__ANode___location;
val* NEW_location__Location(const struct type* type);
extern const struct type type_location__Location;
extern const int COLOR_lexer__Lexer__file;
extern const int COLOR_location__Location__init;
extern const int COLOR_parser_util__InjectedLexer__is_finished;
extern const int COLOR_parser_util__InjectedLexer__get_token;
extern const int COLOR_abstract_collection__Sequence__push;
extern const int COLOR_parser_util__InjectedLexer__is_finished_61d;
val* parser_util__InjectedLexer__get_token(val* self);
val* NEW_parser_util__CollectTokensByTextVisitor(const struct type* type);
extern const struct type type_parser_util__CollectTokensByTextVisitor;
extern const int COLOR_parser_util__CollectTokensByTextVisitor__init;
extern const int COLOR_parser_nodes__Visitor__enter_visit;
extern const int COLOR_parser_util__CollectTokensByTextVisitor__result;
val* parser_util__ANode__collect_tokens_by_text(val* self, val* p0);
val* NEW_parser_util__CollectAnnotationsByNameVisitor(const struct type* type);
extern const struct type type_parser_util__CollectAnnotationsByNameVisitor;
extern const int COLOR_parser_util__CollectAnnotationsByNameVisitor__init;
extern const int COLOR_parser_util__CollectAnnotationsByNameVisitor__result;
val* parser_util__ANode__collect_annotations_by_name(val* self, val* p0);
extern const int COLOR_parser_util__CollectTokensByTextVisitor___64dtext;
val* parser_util__CollectTokensByTextVisitor__text(val* self);
void parser_util__CollectTokensByTextVisitor__text_61d(val* self, val* p0);
extern const int COLOR_parser_nodes__Visitor__init;
extern const int COLOR_parser_util__CollectTokensByTextVisitor__text_61d;
void parser_util__CollectTokensByTextVisitor__init(val* self, val* p0);
extern const int COLOR_parser_util__CollectTokensByTextVisitor___64dresult;
val* parser_util__CollectTokensByTextVisitor__result(val* self);
void parser_util__CollectTokensByTextVisitor__result_61d(val* self, val* p0);
extern const int COLOR_parser_nodes__ANode__visit_all;
extern const struct type type_parser_nodes__Token;
extern const int COLOR_parser_nodes__Token__text;
extern const int COLOR_parser_util__CollectTokensByTextVisitor__text;
extern const int COLOR_kernel__Object___61d_61d;
void parser_util__CollectTokensByTextVisitor__visit(val* self, val* p0);
extern const int COLOR_parser_util__CollectAnnotationsByNameVisitor___64dname;
val* parser_util__CollectAnnotationsByNameVisitor__name(val* self);
void parser_util__CollectAnnotationsByNameVisitor__name_61d(val* self, val* p0);
extern const int COLOR_parser_util__CollectAnnotationsByNameVisitor__name_61d;
void parser_util__CollectAnnotationsByNameVisitor__init(val* self, val* p0);
extern const int COLOR_parser_util__CollectAnnotationsByNameVisitor___64dresult;
val* parser_util__CollectAnnotationsByNameVisitor__result(val* self);
void parser_util__CollectAnnotationsByNameVisitor__result_61d(val* self, val* p0);
extern const struct type type_parser_nodes__AAnnotation;
extern const int COLOR_parser_nodes__AAnnotation__n_atid;
extern const int COLOR_parser_nodes__AAtid__n_id;
extern const int COLOR_parser_util__CollectAnnotationsByNameVisitor__name;
void parser_util__CollectAnnotationsByNameVisitor__visit(val* self, val* p0);
