#include "nit.common.h"
extern const int COLOR_phase__ToolContext___64dphases;
val* phase__ToolContext__phases(val* self);
void phase__ToolContext__phases_61d(val* self, val* p0);
extern const int COLOR_phase__ToolContext__phases;
extern const int COLOR_array__Collection__to_a;
extern const int COLOR_sorter__AbstractSorter__sort;
val* phase__ToolContext__phases_list(val* self);
extern const int COLOR_time__Object__get_time;
val* string__NativeString__to_s_with_length(char* self, long p0);
extern const int COLOR_toolcontext__ToolContext__info;
extern const int COLOR_phase__ToolContext__phases_list;
extern const int COLOR_abstract_collection__Collection__iterator;
extern const int COLOR_abstract_collection__Iterator__is_ok;
extern const int COLOR_abstract_collection__Iterator__item;
extern const int COLOR_string__Object__class_name;
val* NEW_array__Array(const struct type* type);
extern const struct type type_array__Arraykernel__Object;
val* NEW_array__NativeArray(int length, const struct type* type);
extern const struct type type_array__NativeArraykernel__Object;
extern const int COLOR_array__Array__with_native;
extern const int COLOR_string__Object__to_s;
extern const int COLOR_abstract_collection__Iterator__next;
extern const int COLOR_parser_nodes__ANode__location;
extern const int COLOR_location__Location__file;
extern const int COLOR_location__SourceFile__filename;
extern const int COLOR_phase__Phase__toolcontext;
extern const int COLOR_kernel__Object___61d_61d;
extern const int COLOR_toolcontext__ToolContext__error_count;
extern const int COLOR_phase__Phase__process_nmodule;
extern const int COLOR_toolcontext__ToolContext__check_errors;
extern const int COLOR_parser_nodes__AModule__n_classdefs;
extern const int COLOR_phase__Phase__process_nclassdef;
extern const int COLOR_parser_nodes__AClassdef__n_propdefs;
extern const int COLOR_phase__Phase__process_npropdef;
val* NEW_phase__AnnotationPhaseVisitor(const struct type* type);
extern const struct type type_phase__AnnotationPhaseVisitor;
extern const int COLOR_phase__AnnotationPhaseVisitor__init;
extern const int COLOR_parser_nodes__Visitor__enter_visit;
void phase__ToolContext__run_phases(val* self, val* p0);
extern const int COLOR_phase__AnnotationPhaseVisitor___64dphase;
val* phase__AnnotationPhaseVisitor__phase(val* self);
void phase__AnnotationPhaseVisitor__phase_61d(val* self, val* p0);
extern const int COLOR_parser_nodes__Visitor__init;
extern const int COLOR_phase__AnnotationPhaseVisitor__phase_61d;
void phase__AnnotationPhaseVisitor__init(val* self, val* p0);
extern const int COLOR_parser_nodes__ANode__visit_all;
extern const struct type type_parser_nodes__AAnnotation;
extern const int COLOR_phase__AnnotationPhaseVisitor__phase;
extern const int COLOR_parser_nodes__ANode__parent;
extern const int COLOR_phase__Phase__process_annotated_node;
void phase__AnnotationPhaseVisitor__visit(val* self, val* p0);
extern const int COLOR_phase__Phase___64dtoolcontext;
val* phase__Phase__toolcontext(val* self);
void phase__Phase__toolcontext_61d(val* self, val* p0);
extern const int COLOR_phase__Phase___64din_hierarchy;
val* phase__Phase__in_hierarchy(val* self);
void phase__Phase__in_hierarchy_61d(val* self, val* p0);
extern const int COLOR_phase__Phase__toolcontext_61d;
extern const int COLOR_poset__POSet__add_node;
extern const int COLOR_phase__Phase__in_hierarchy_61d;
extern const int COLOR_poset__POSet__add_edge;
void phase__Phase__init(val* self, val* p0, val* p1);
void phase__Phase__process_nmodule(val* self, val* p0);
void phase__Phase__process_nclassdef(val* self, val* p0);
void phase__Phase__process_npropdef(val* self, val* p0);
void phase__Phase__process_annotated_node(val* self, val* p0, val* p1);
