#include "nit.common.h"
extern const int COLOR_pkgconfig__ToolContext___64dpkgconfig_phase;
val* pkgconfig__ToolContext__pkgconfig_phase(val* self);
void pkgconfig__ToolContext__pkgconfig_phase_61d(val* self, val* p0);
extern const int COLOR_parser_nodes__AAnnotation__n_atid;
extern const int COLOR_parser_nodes__AAtid__n_id;
extern const int COLOR_parser_nodes__Token__text;
val* string__NativeString__to_s_with_length(char* self, long p0);
extern const int COLOR_kernel__Object___33d_61d;
extern const int COLOR_phase__Phase__toolcontext;
extern const int COLOR_modelbuilder__ToolContext__modelbuilder;
extern const struct type type_parser_nodes__AModuledecl;
extern const int COLOR_modelbuilder__ModelBuilder__error;
extern const int COLOR_parser_nodes__AAnnotation__n_args;
extern const int COLOR_abstract_collection__Collection__is_empty;
val* NEW_array__Array(const struct type* type);
extern const struct type type_array__Arraystring__String;
extern const int COLOR_array__Array__init;
void CHECK_NEW_array__Array(val*);
extern const int COLOR_abstract_collection__Collection__iterator;
extern const int COLOR_abstract_collection__Iterator__is_ok;
extern const int COLOR_abstract_collection__Iterator__item;
extern const struct type type_parser_nodes__AExprAtArg;
extern const int COLOR_parser_nodes__AExprAtArg__n_expr;
extern const struct type type_parser_nodes__AStringFormExpr;
extern const int COLOR_modelize_property__Prod__collect_text;
extern const int COLOR_abstract_collection__Collection__length;
extern const int COLOR_string__AbstractString__substring;
extern const int COLOR_abstract_collection__SimpleCollection__add;
extern const int COLOR_abstract_collection__Iterator__next;
extern const int COLOR_parser_nodes__ANode__parent;
extern const struct type type_parser_nodes__AModule;
val* NEW_exec__IProcess(const struct type* type);
extern const struct type type_exec__IProcess;
val* NEW_array__NativeArray(int length, const struct type* type);
extern const struct type type_array__NativeArraystring__String;
extern const int COLOR_array__Array__with_native;
extern const int COLOR_exec__IProcess__init;
void CHECK_NEW_exec__IProcess(val*);
extern const int COLOR_exec__Process__wait;
extern const int COLOR_exec__Process__status;
val* NEW_exec__Process(const struct type* type);
extern const struct type type_exec__Process;
extern const int COLOR_exec__Process__init;
void CHECK_NEW_exec__Process(val*);
extern const struct type type_array__Arraykernel__Object;
extern const struct type type_array__NativeArraykernel__Object;
extern const int COLOR_string__Object__to_s;
extern const int COLOR_stream__IStream__read_all;
extern const int COLOR_c__AModule__c_compiler_options;
extern const int COLOR_string_search__String__replace;
extern const int COLOR_c__AModule__c_compiler_options_61d;
extern const int COLOR_c__AModule__c_linker_options;
extern const int COLOR_c__AModule__c_linker_options_61d;
void pkgconfig__PkgconfigPhase__process_annotated_node(val* self, val* p0, val* p1);
