#include "nit.common.h"
extern const int COLOR_platform__ToolContext___64dplatform_phase;
val* platform__ToolContext__platform_phase(val* self);
void platform__ToolContext__platform_phase_61d(val* self, val* p0);
val* platform__ToolContext__platform_from_name(val* self, val* p0);
val* string__NativeString__to_s_with_length(char* self, long p0);
extern const int COLOR_parser_nodes__AAnnotation__n_atid;
extern const int COLOR_parser_nodes__AAtid__n_id;
extern const int COLOR_parser_nodes__Token__text;
extern const int COLOR_kernel__Object___33d_61d;
extern const int COLOR_phase__Phase__toolcontext;
extern const int COLOR_modelbuilder__ToolContext__modelbuilder;
extern const struct type type_parser_nodes__AModuledecl;
val* NEW_array__Array(const struct type* type);
extern const struct type type_array__Arraykernel__Object;
val* NEW_array__NativeArray(int length, const struct type* type);
extern const struct type type_array__NativeArraykernel__Object;
extern const int COLOR_array__Array__with_native;
extern const int COLOR_string__Object__to_s;
extern const int COLOR_modelbuilder__ModelBuilder__error;
extern const int COLOR_parser_nodes__AAnnotation__n_args;
extern const int COLOR_abstract_collection__Collection__length;
extern const struct type type_kernel__Int;
extern const int COLOR_abstract_collection__Collection__is_empty;
extern const int COLOR_parser_nodes__AModuledecl__n_name;
extern const int COLOR_modelize_property__Prod__collect_text;
extern const int COLOR_abstract_collection__Collection__first;
extern const struct type type_parser_nodes__AExprAtArg;
extern const int COLOR_parser_nodes__AExprAtArg__n_expr;
extern const struct type type_parser_nodes__AStringFormExpr;
extern const int COLOR_string__AbstractString__substring;
extern const int COLOR_parser_nodes__ANode__parent;
extern const struct type type_parser_nodes__AModule;
extern const int COLOR_modelbuilder__AModule__mmodule;
extern const int COLOR_platform__ToolContext__platform_from_name;
extern const int COLOR_parser_nodes__ANode__location;
extern const int COLOR_toolcontext__ToolContext__error;
extern const int COLOR_platform__MModule__target_platform;
extern const int COLOR_platform__MModule__local_target_platform_61d;
void platform__PlatformPhase__process_annotated_node(val* self, val* p0, val* p1);
extern const int COLOR_platform__MModule___64dlocal_target_platform;
val* platform__MModule__local_target_platform(val* self);
void platform__MModule__local_target_platform_61d(val* self, val* p0);
extern const int COLOR_platform__MModule__local_target_platform;
extern const int COLOR_mmodule__MModule__in_importation;
extern const int COLOR_poset__POSetElement__greaters;
extern const int COLOR_abstract_collection__Collection__iterator;
extern const int COLOR_abstract_collection__Iterator__is_ok;
extern const int COLOR_abstract_collection__Iterator__item;
extern const int COLOR_abstract_collection__Iterator__next;
val* platform__MModule__target_platform(val* self);
short int platform__Platform__supports_libunwind(val* self);
void platform__Platform__init(val* self);
