#include "nit.common.h"
val* NEW_rapid_type_analysis__RapidTypeAnalysis(const struct type* type);
extern const struct type type_rapid_type_analysis__RapidTypeAnalysis;
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis__init;
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis__run_analysis;
val* rapid_type_analysis__ModelBuilder__do_rapid_type_analysis(val* self, val* p0);
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis___64dmodelbuilder;
val* rapid_type_analysis__RapidTypeAnalysis__modelbuilder(val* self);
void rapid_type_analysis__RapidTypeAnalysis__modelbuilder_61d(val* self, val* p0);
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis___64dmainmodule;
val* rapid_type_analysis__RapidTypeAnalysis__mainmodule(val* self);
void rapid_type_analysis__RapidTypeAnalysis__mainmodule_61d(val* self, val* p0);
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis___64dlive_types;
val* rapid_type_analysis__RapidTypeAnalysis__live_types(val* self);
void rapid_type_analysis__RapidTypeAnalysis__live_types_61d(val* self, val* p0);
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis___64dlive_open_types;
val* rapid_type_analysis__RapidTypeAnalysis__live_open_types(val* self);
void rapid_type_analysis__RapidTypeAnalysis__live_open_types_61d(val* self, val* p0);
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis___64dlive_classes;
val* rapid_type_analysis__RapidTypeAnalysis__live_classes(val* self);
void rapid_type_analysis__RapidTypeAnalysis__live_classes_61d(val* self, val* p0);
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis___64dlive_cast_types;
val* rapid_type_analysis__RapidTypeAnalysis__live_cast_types(val* self);
void rapid_type_analysis__RapidTypeAnalysis__live_cast_types_61d(val* self, val* p0);
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis___64dlive_open_cast_types;
val* rapid_type_analysis__RapidTypeAnalysis__live_open_cast_types(val* self);
void rapid_type_analysis__RapidTypeAnalysis__live_open_cast_types_61d(val* self, val* p0);
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis___64dlive_methoddefs;
val* rapid_type_analysis__RapidTypeAnalysis__live_methoddefs(val* self);
void rapid_type_analysis__RapidTypeAnalysis__live_methoddefs_61d(val* self, val* p0);
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis___64dlive_methods;
val* rapid_type_analysis__RapidTypeAnalysis__live_methods(val* self);
void rapid_type_analysis__RapidTypeAnalysis__live_methods_61d(val* self, val* p0);
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis___64dlive_super_sends;
val* rapid_type_analysis__RapidTypeAnalysis__live_super_sends(val* self);
void rapid_type_analysis__RapidTypeAnalysis__live_super_sends_61d(val* self, val* p0);
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis___64dtotry_methods;
val* rapid_type_analysis__RapidTypeAnalysis__totry_methods(val* self);
void rapid_type_analysis__RapidTypeAnalysis__totry_methods_61d(val* self, val* p0);
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis___64dtodo;
val* rapid_type_analysis__RapidTypeAnalysis__todo(val* self);
void rapid_type_analysis__RapidTypeAnalysis__todo_61d(val* self, val* p0);
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis__mainmodule;
extern const int COLOR_model__MModule__sys_type;
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis__add_new;
val* string__NativeString__to_s_with_length(char* self, long p0);
extern const int COLOR_model__MClassType__mclass;
extern const int COLOR_model__MModule__try_get_primitive_method;
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis__add_send;
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis__modelbuilder;
extern const int COLOR_modelbuilder__ModelBuilder__model;
extern const int COLOR_model__Model__get_mclasses_by_name;
extern const int COLOR_abstract_collection__Collection__iterator;
extern const int COLOR_abstract_collection__Iterator__is_ok;
extern const int COLOR_abstract_collection__Iterator__item;
extern const int COLOR_model__MClass__mclass_type;
extern const int COLOR_abstract_collection__Iterator__next;
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis__todo;
extern const int COLOR_abstract_collection__Collection__is_empty;
extern const int COLOR_abstract_collection__Sequence__shift;
val* NEW_rapid_type_analysis__RapidTypeVisitor(const struct type* type);
extern const struct type type_rapid_type_analysis__RapidTypeVisitor;
extern const int COLOR_model__MPropDef__mclassdef;
extern const int COLOR_model__MClassDef__bound_mtype;
extern const int COLOR_rapid_type_analysis__RapidTypeVisitor__init;
extern const int COLOR_model__MMethodDef__msignature;
extern const int COLOR_model__MSignature__vararg_rank;
extern const struct type type_kernel__Int;
extern const int COLOR_modelize_property__ModelBuilder__mpropdef2npropdef;
extern const int COLOR_abstract_collection__MapRead___91d_93d;
extern const int COLOR_model__MSignature__mparameters;
extern const int COLOR_abstract_collection__SequenceRead___91d_93d;
extern const int COLOR_model__MParameter__mtype;
extern const int COLOR_model__MModule__get_primitive_class;
val* NEW_array__Array(const struct type* type);
extern const struct type type_array__Arraymodel__MType;
val* NEW_array__NativeArray(int length, const struct type* type);
extern const struct type type_array__NativeArraymodel__MType;
extern const int COLOR_array__Array__with_native;
extern const int COLOR_model__MClass__get_mtype;
extern const int COLOR_rapid_type_analysis__RapidTypeVisitor__add_type;
extern const int COLOR_modelbuilder__ModelBuilder__force_get_primitive_method;
extern const int COLOR_rapid_type_analysis__RapidTypeVisitor__add_monomorphic_send;
val* NEW_range__Range(const struct type* type);
extern const struct type type_range__Rangekernel__Int;
extern const int COLOR_model__MSignature__arity;
extern const int COLOR_range__Range__without_last;
extern const int COLOR_model__MPropDef__mproperty;
extern const int COLOR_model__MProperty__intro;
extern const int COLOR_model__MType__need_anchor;
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis__add_cast;
extern const int COLOR_abstract_collection__MapRead__has_key;
extern const int COLOR_model__MProperty__name;
extern const int COLOR_kernel__Object___61d_61d;
extern const int COLOR_modelize_class__ModelBuilder__mclassdef2nclassdef;
extern const int COLOR_modelize_property__AClassdef__super_inits;
extern const int COLOR_rapid_type_analysis__RapidTypeVisitor__receiver;
extern const struct type type_parser_nodes__AConcreteMethPropdef;
extern const int COLOR_auto_super_init__AConcreteMethPropdef__auto_super_inits;
extern const struct type type_parser_nodes__AInternMethPropdef;
extern const struct type type_parser_nodes__AExternMethPropdef;
extern const int COLOR_parser_nodes__AExternPropdef__n_extern;
extern const int COLOR_model__MSignature__return_mtype;
extern const struct type type_model__MClassType;
extern const int COLOR_model__MClass__kind;
extern const int COLOR_model__Object__abstract_kind;
extern const int COLOR_kernel__Object___33d_61d;
extern const int COLOR_model__Object__interface_kind;
extern const int COLOR_parser_nodes__ANode__parent;
extern const struct type type_parser_nodes__AClassdef;
extern const int COLOR_parser_nodes__Visitor__enter_visit;
extern const struct type type_parser_nodes__AExternInitPropdef;
val* NEW_list__List(const struct type* type);
extern const struct type type_list__Listmodel__MClassType;
extern const int COLOR_list__List__init;
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis__live_types;
extern const int COLOR_abstract_collection__SimpleCollection__add_all;
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis__live_open_types;
extern const int COLOR_model__MType__can_resolve_for;
extern const int COLOR_model__MType__anchor_to;
extern const int COLOR_abstract_collection__Collection__has;
extern const int COLOR_abstract_collection__SimpleCollection__add;
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis__check_depth;
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis__live_open_cast_types;
extern const struct type type_model__MNullableType;
extern const int COLOR_model__MNullableType__mtype;
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis__live_cast_types;
void rapid_type_analysis__RapidTypeAnalysis__run_analysis(val* self);
extern const int COLOR_model__MType__length;
extern const int COLOR_modelbuilder__ModelBuilder__toolcontext;
extern const struct type type_array__Arraykernel__Object;
extern const struct type type_array__NativeArraykernel__Object;
extern const int COLOR_string__Object__to_s;
extern const int COLOR_toolcontext__ToolContext__fatal_error;
void rapid_type_analysis__RapidTypeAnalysis__check_depth(val* self, val* p0);
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis__live_classes;
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis__totry_methods;
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis__try_send;
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis__live_super_sends;
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis__try_super_send;
extern const int COLOR_model__MType__collect_mclassdefs;
extern const int COLOR_parser_nodes__AClassdef__n_propdefs;
extern const struct type type_parser_nodes__AAttrPropdef;
extern const int COLOR_parser_nodes__AAttrPropdef__n_expr;
extern const int COLOR_modelize_property__APropdef__mpropdef;
void rapid_type_analysis__RapidTypeAnalysis__add_new(val* self, val* p0, val* p1);
void rapid_type_analysis__RapidTypeAnalysis__add_cast(val* self, val* p0);
extern const int COLOR_model__MClass__intro;
extern const int COLOR_model__MType__has_mproperty;
extern const int COLOR_model__MProperty__lookup_first_definition;
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis__add_call;
void rapid_type_analysis__RapidTypeAnalysis__try_send(val* self, val* p0, val* p1);
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis__live_methoddefs;
extern const int COLOR_model__MProperty__mpropdefs;
extern const int COLOR_abstract_collection__Collection__length;
extern const int COLOR_model__MMethodDef__is_abstract;
extern const int COLOR_abstract_collection__RemovableCollection__remove;
void rapid_type_analysis__RapidTypeAnalysis__add_call(val* self, val* p0);
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis__live_methods;
extern const int COLOR_abstract_collection__Collection__first;
void rapid_type_analysis__RapidTypeAnalysis__add_send(val* self, val* p0, val* p1);
extern const int COLOR_model__MPropDef__lookup_next_definition;
void rapid_type_analysis__RapidTypeAnalysis__try_super_send(val* self, val* p0, val* p1);
void rapid_type_analysis__RapidTypeAnalysis__add_super_send(val* self, val* p0, val* p1);
void rapid_type_analysis__RapidTypeAnalysis__init(val* self, val* p0, val* p1);
extern const int COLOR_rapid_type_analysis__RapidTypeVisitor___64danalysis;
val* rapid_type_analysis__RapidTypeVisitor__analysis(val* self);
void rapid_type_analysis__RapidTypeVisitor__analysis_61d(val* self, val* p0);
extern const int COLOR_rapid_type_analysis__RapidTypeVisitor___64dreceiver;
val* rapid_type_analysis__RapidTypeVisitor__receiver(val* self);
void rapid_type_analysis__RapidTypeVisitor__receiver_61d(val* self, val* p0);
extern const int COLOR_rapid_type_analysis__RapidTypeVisitor___64dmpropdef;
val* rapid_type_analysis__RapidTypeVisitor__mpropdef(val* self);
void rapid_type_analysis__RapidTypeVisitor__mpropdef_61d(val* self, val* p0);
extern const int COLOR_parser_nodes__Visitor__init;
extern const int COLOR_rapid_type_analysis__RapidTypeVisitor__analysis_61d;
extern const int COLOR_rapid_type_analysis__RapidTypeVisitor__receiver_61d;
extern const int COLOR_rapid_type_analysis__RapidTypeVisitor__mpropdef_61d;
void rapid_type_analysis__RapidTypeVisitor__init(val* self, val* p0, val* p1, val* p2);
extern const int COLOR_rapid_type_analysis__ANode__accept_rapid_type_visitor;
extern const struct type type_parser_nodes__AExpr;
extern const int COLOR_typing__AExpr__implicit_cast_to;
extern const int COLOR_rapid_type_analysis__RapidTypeVisitor__add_cast_type;
extern const struct type type_parser_nodes__AAnnotations;
extern const int COLOR_parser_nodes__ANode__visit_all;
void rapid_type_analysis__RapidTypeVisitor__visit(val* self, val* p0);
extern const int COLOR_rapid_type_analysis__RapidTypeVisitor__analysis;
extern const struct type type_model__MNullType;
val* rapid_type_analysis__RapidTypeVisitor__cleanup_type(val* self, val* p0);
val* rapid_type_analysis__RapidTypeVisitor__get_class(val* self, val* p0);
extern const int COLOR_rapid_type_analysis__RapidTypeVisitor__cleanup_type;
extern const int COLOR_parser_nodes__Visitor__current_node;
val* rapid_type_analysis__RapidTypeVisitor__get_method(val* self, val* p0, val* p1);
void rapid_type_analysis__RapidTypeVisitor__add_type(val* self, val* p0);
void rapid_type_analysis__RapidTypeVisitor__add_monomorphic_send(val* self, val* p0, val* p1);
void rapid_type_analysis__RapidTypeVisitor__add_send(val* self, val* p0, val* p1);
void rapid_type_analysis__RapidTypeVisitor__add_cast_type(val* self, val* p0);
void rapid_type_analysis__ANode__accept_rapid_type_visitor(val* self, val* p0);
extern const int COLOR_typing__AExpr__mtype;
void rapid_type_analysis__AIntExpr__accept_rapid_type_visitor(val* self, val* p0);
void rapid_type_analysis__AFloatExpr__accept_rapid_type_visitor(val* self, val* p0);
void rapid_type_analysis__ACharExpr__accept_rapid_type_visitor(val* self, val* p0);
extern const int COLOR_model__MClassType__arguments;
extern const int COLOR_rapid_type_analysis__RapidTypeVisitor__get_method;
void rapid_type_analysis__AArrayExpr__accept_rapid_type_visitor(val* self, val* p0);
extern const int COLOR_rapid_type_analysis__RapidTypeVisitor__get_class;
void rapid_type_analysis__AStringFormExpr__accept_rapid_type_visitor(val* self, val* p0);
extern const struct type type_array__Arraymodel__MClassType;
extern const struct type type_array__NativeArraymodel__MClassType;
void rapid_type_analysis__ASuperstringExpr__accept_rapid_type_visitor(val* self, val* p0);
void rapid_type_analysis__ACrangeExpr__accept_rapid_type_visitor(val* self, val* p0);
void rapid_type_analysis__AOrangeExpr__accept_rapid_type_visitor(val* self, val* p0);
void rapid_type_analysis__ATrueExpr__accept_rapid_type_visitor(val* self, val* p0);
void rapid_type_analysis__AFalseExpr__accept_rapid_type_visitor(val* self, val* p0);
extern const int COLOR_typing__AIsaExpr__cast_type;
void rapid_type_analysis__AIsaExpr__accept_rapid_type_visitor(val* self, val* p0);
void rapid_type_analysis__AAsCastExpr__accept_rapid_type_visitor(val* self, val* p0);
extern const int COLOR_typing__ASendExpr__mproperty;
extern const int COLOR_parser_nodes__ASendExpr__n_expr;
extern const int COLOR_rapid_type_analysis__RapidTypeVisitor__add_send;
void rapid_type_analysis__ASendExpr__accept_rapid_type_visitor(val* self, val* p0);
extern const int COLOR_typing__AReassignFormExpr__read_type;
extern const int COLOR_typing__AReassignFormExpr__reassign_property;
extern const int COLOR_typing__ASendReassignFormExpr__write_mproperty;
extern const struct type type_parser_nodes__ASelfExpr;
void rapid_type_analysis__ASendReassignFormExpr__accept_rapid_type_visitor(val* self, val* p0);
void rapid_type_analysis__AVarReassignExpr__accept_rapid_type_visitor(val* self, val* p0);
void rapid_type_analysis__AAttrReassignExpr__accept_rapid_type_visitor(val* self, val* p0);
extern const int COLOR_typing__ASuperExpr__mproperty;
extern const int COLOR_rapid_type_analysis__RapidTypeVisitor__mpropdef;
extern const struct type type_model__MMethodDef;
extern const int COLOR_rapid_type_analysis__RapidTypeAnalysis__add_super_send;
void rapid_type_analysis__ASuperExpr__accept_rapid_type_visitor(val* self, val* p0);
extern const int COLOR_parser_nodes__AForExpr__n_expr;
extern const int COLOR_typing__AForExpr__coltype;
extern const int COLOR_scope__AForExpr__variables;
void rapid_type_analysis__AForExpr__accept_rapid_type_visitor(val* self, val* p0);
extern const int COLOR_typing__ANewExpr__mproperty;
void rapid_type_analysis__ANewExpr__accept_rapid_type_visitor(val* self, val* p0);
