#include "nit.common.h"
extern const int COLOR_ropes__TupleLeafNodePos___64dcurr_node;
val* ropes__TupleLeafNodePos__curr_node(val* self);
void ropes__TupleLeafNodePos__curr_node_61d(val* self, val* p0);
extern const int COLOR_ropes__TupleLeafNodePos___64dcorrected_pos;
long ropes__TupleLeafNodePos__corrected_pos(val* self);
void ropes__TupleLeafNodePos__corrected_pos_61d(val* self, long p0);
extern const int COLOR_ropes__TupleLeafNodePos___64dvisit_stack;
val* ropes__TupleLeafNodePos__visit_stack(val* self);
void ropes__TupleLeafNodePos__visit_stack_61d(val* self, val* p0);
void ropes__TupleLeafNodePos__init(val* self, val* p0, long p1, val* p2);
extern const int COLOR_ropes__Rope___64dstr_representation;
val* ropes__Rope__str_representation(val* self);
void ropes__Rope__str_representation_61d(val* self, val* p0);
extern const int COLOR_ropes__Rope___64dparent_node;
val* ropes__Rope__parent_node(val* self);
void ropes__Rope__parent_node_61d(val* self, val* p0);
val* NEW_ropes__ConcatNode(const struct type* type);
extern const struct type type_ropes__ConcatNode;
extern const int COLOR_ropes__ConcatNode__init;
extern const int COLOR_ropes__Rope__parent_node_61d;
void ropes__Rope__init(val* self);
extern const int COLOR_ropes__Rope__parent_node;
val* NEW_ropes__LeafNode(const struct type* type);
extern const struct type type_ropes__LeafNode;
extern const int COLOR_ropes__LeafNode__init;
extern const int COLOR_ropes__ConcatNode__right_child_61d;
extern const int COLOR_ropes__ConcatNode__update_data;
void ropes__Rope__with_string(val* self, val* p0);
val* NEW_ropes__CharRopeView(const struct type* type);
extern const struct type type_ropes__CharRopeView;
extern const int COLOR_ropes__CharRopeView__init;
val* ropes__Rope__chars(val* self);
extern const int COLOR_ropes__RopeNode__length;
long ropes__Rope__length(val* self);
extern const int COLOR_ropes__Rope__str_representation;
extern const int COLOR_ropes__Rope__flatten;
val* ropes__Rope__to_s(val* self);
extern const int COLOR_ropes__Rope__length;
extern const int COLOR_string__StringCapable__calloc_string;
val* NEW_ropes__DFSRopeLeafIterator(const struct type* type);
extern const struct type type_ropes__DFSRopeLeafIterator;
extern const int COLOR_ropes__DFSRopeLeafIterator__init;
extern const int COLOR_abstract_collection__Iterator__is_ok;
extern const int COLOR_abstract_collection__Iterator__item;
extern const int COLOR_ropes__LeafNode__value;
extern const int COLOR_string__AbstractString___items;
extern const int COLOR_abstract_collection__Collection__length;
extern const int COLOR_abstract_collection__Iterator__next;
val* string__NativeString__to_s_with_length(char* self, long p0);
val* ropes__Rope__flatten(val* self);
extern const struct type type_kernel__Int;
val* NEW_list__List(const struct type* type);
extern const struct type type_list__Listropes__TupleVisitNode;
extern const int COLOR_list__List__init;
val* NEW_ropes__TupleVisitNode(const struct type* type);
extern const struct type type_ropes__TupleVisitNode;
extern const int COLOR_ropes__TupleVisitNode__init;
extern const int COLOR_ropes__ConcatNode__left_child;
extern const int COLOR_ropes__TupleVisitNode__left_visited_61d;
extern const int COLOR_ropes__ConcatNode__right_child;
extern const int COLOR_ropes__TupleVisitNode__right_visited_61d;
extern const int COLOR_file__Object__print;
extern const int COLOR_abstract_collection__Sequence__push;
val* NEW_ropes__TupleLeafNodePos(const struct type* type);
extern const struct type type_ropes__TupleLeafNodePos;
extern const int COLOR_ropes__TupleLeafNodePos__init;
val* ropes__Rope__get_node_for_pos(val* self, long p0);
val* NEW_ropes__BufferRope(const struct type* type);
extern const struct type type_ropes__BufferRope;
extern const int COLOR_ropes__BufferRope__init;
extern const int COLOR_ropes__BufferRope__append;
val* ropes__Rope___43d(val* self, val* p0);
extern const int COLOR_ropes__Rope__iterator;
extern const int COLOR_abstract_collection__Collection__iterator;
val* ropes__Rope__multi_concat(val* self, val* p0);
extern const int COLOR_string__Object__to_s;
val* NEW_range__Range(const struct type* type);
extern const struct type type_range__Rangekernel__Int;
extern const int COLOR_range__Range__init;
val* ropes__Rope___42d(val* self, long p0);
val* ropes__Rope__iterator(val* self);
extern const int COLOR_ropes__DFSRopeLeafIterator__with_index;
extern const int COLOR_ropes__RopeIterator__pos;
extern const int COLOR_string__AbstractString__substring;
val* ropes__Rope__subrope(val* self, long p0, long p1);
extern const int COLOR_string__AbstractString__to_upper;
val* ropes__Rope__to_upper(val* self);
extern const int COLOR_string__AbstractString__to_lower;
val* ropes__Rope__to_lower(val* self);
extern const struct type type_ropes__Rope;
extern const struct type type_string__AbstractString;
val* NEW_ropes__RopeCharIterator(const struct type* type);
extern const struct type type_ropes__RopeCharIterator;
extern const int COLOR_ropes__RopeCharIterator__init;
extern const int COLOR_abstract_collection__SequenceRead___91d_93d;
short int ropes__Rope___61d_61d(val* self, val* p0);
extern const int COLOR_kernel__Comparable_VTOTHER;
extern const int COLOR_ropes__Rope__chars;
extern const struct type type_kernel__Char;
short int ropes__Rope___60d(val* self, val* p0);
extern const int COLOR_ropes__BufferRope___64dis_dirty;
short int ropes__BufferRope__is_dirty(val* self);
void ropes__BufferRope__is_dirty_61d(val* self, short int p0);
extern const int COLOR_ropes__Rope__init;
void ropes__BufferRope__init(val* self);
extern const int COLOR_ropes__Rope__with_string;
void ropes__BufferRope__with_string(val* self, val* p0);
extern const int COLOR_ropes__RopeNode__parent;
extern const int COLOR_ropes__ConcatNode__left_child_61d;
extern const int COLOR_ropes__RopeNode__parent_61d;
extern const int COLOR_kernel__Object___61d_61d;
void ropes__BufferRope__rotate_right(val* self, val* p0);
void ropes__BufferRope__rotate_left(val* self, val* p0);
extern const int COLOR_ropes__RopeNode__balance_factor;
extern const int COLOR_ropes__BufferRope__balance_node;
void ropes__BufferRope__balance_from_node(val* self, val* p0);
extern const int COLOR_ropes__BufferRope__rotate_left;
extern const int COLOR_ropes__BufferRope__rotate_right;
void ropes__BufferRope__balance_node(val* self, val* p0);
extern const int COLOR_ropes__BufferRope__balance_from_node;
val* NEW_string__Buffer(const struct type* type);
extern const struct type type_string__Buffer;
extern const int COLOR_string__Buffer__with_capacity;
extern const int COLOR_abstract_collection__SimpleCollection__add;
extern const int COLOR_ropes__BufferRope__is_dirty;
extern const int COLOR_ropes__BufferRope__is_dirty_61d;
val* ropes__BufferRope__append(val* self, val* p0);
val* ropes__BufferRope__append_multi(val* self, val* p0);
extern const int COLOR_ropes__BufferRope__prepend;
val* ropes__BufferRope__prepend(val* self, val* p0);
val* ropes__BufferRope__prepend_multi(val* self, val* p0);
extern const struct type type_list__Liststring__String;
extern const int COLOR_abstract_collection__Sequence__shift;
val* ropes__BufferRope__concat(val* self, val* p0);
val* NEW_ropes__ImmutableRope(const struct type* type);
extern const struct type type_ropes__ImmutableRope;
extern const int COLOR_ropes__ImmutableRope__init;
extern const int COLOR_ropes__Rope__str_representation_61d;
val* ropes__BufferRope__freeze(val* self);
val* ropes__BufferRope__to_immutable(val* self);
extern const int COLOR_ropes__BufferRope__subrope;
val* ropes__BufferRope__subrope(val* self, long p0, long p1);
extern const int COLOR_ropes__BufferRope___42d;
val* ropes__BufferRope___42d(val* self, long p0);
extern const int COLOR_ropes__BufferRope___43d;
val* ropes__BufferRope___43d(val* self, val* p0);
extern const int COLOR_ropes__BufferRope__multi_concat;
val* ropes__BufferRope__multi_concat(val* self, val* p0);
val* ropes__BufferRope__to_s(val* self);
void ropes__ImmutableRope__init(val* self);
void ropes__ImmutableRope__with_string(val* self, val* p0);
extern const int COLOR_ropes__ImmutableRope__subrope;
extern const int COLOR_ropes__BufferRope__to_immutable;
val* ropes__ImmutableRope__subrope(val* self, long p0, long p1);
extern const int COLOR_ropes__ImmutableRope___42d;
val* ropes__ImmutableRope___42d(val* self, long p0);
extern const int COLOR_ropes__ImmutableRope___43d;
val* ropes__ImmutableRope___43d(val* self, val* p0);
extern const int COLOR_ropes__ImmutableRope__multi_concat;
val* ropes__ImmutableRope__multi_concat(val* self, val* p0);
extern const int COLOR_ropes__CharRopeView___64dtarget;
val* ropes__CharRopeView__target(val* self);
void ropes__CharRopeView__target_61d(val* self, val* p0);
extern const int COLOR_ropes__CharRopeView__target_61d;
void ropes__CharRopeView__init(val* self, val* p0);
extern const int COLOR_ropes__CharRopeView__target;
extern const int COLOR_ropes__Rope__get_node_for_pos;
extern const int COLOR_ropes__TupleLeafNodePos__curr_node;
extern const int COLOR_ropes__TupleLeafNodePos__corrected_pos;
char ropes__CharRopeView___91d_93d(val* self, long p0);
char ropes__CharRopeView__first(val* self);
extern const struct class class_kernel__Char;
extern const int COLOR_abstract_collection__IndexedIterator__index;
long ropes__CharRopeView__index_of(val* self, char p0);
val* ropes__CharRopeView__iterator(val* self);
char ropes__CharRopeView__last(val* self);
long ropes__CharRopeView__length(val* self);
long ropes__CharRopeView__count(val* self, char p0);
short int ropes__CharRopeView__has_only(val* self, char p0);
short int ropes__CharRopeView__is_empty(val* self);
extern const int COLOR_array__Collection__to_a;
val* ropes__CharRopeView__to_a(val* self);
val* ropes__CharRopeView__to_s(val* self);
extern const struct type type_abstract_collection__SequenceReadkernel__Char;
extern const struct class class_kernel__Int;
short int ropes__CharRopeView___61d_61d(val* self, val* p0);
extern const int COLOR_ropes__TupleVisitNode__node_61d;
void ropes__TupleVisitNode__init(val* self, val* p0);
extern const int COLOR_ropes__TupleVisitNode___64dnode;
val* ropes__TupleVisitNode__node(val* self);
void ropes__TupleVisitNode__node_61d(val* self, val* p0);
extern const int COLOR_ropes__TupleVisitNode___64dleft_visited;
short int ropes__TupleVisitNode__left_visited(val* self);
void ropes__TupleVisitNode__left_visited_61d(val* self, short int p0);
extern const int COLOR_ropes__TupleVisitNode___64dright_visited;
short int ropes__TupleVisitNode__right_visited(val* self);
void ropes__TupleVisitNode__right_visited_61d(val* self, short int p0);
extern const int COLOR_ropes__RopeIterator___target;
val* ropes__RopeIterator__target(val* self);
extern const int COLOR_ropes__RopeIterator___64dpos;
long ropes__RopeIterator__pos(val* self);
void ropes__RopeIterator__pos_61d(val* self, long p0);
void ropes__RopeIterator__init(val* self, val* p0);
void ropes__RopeIterator__with_index(val* self, val* p0, long p1);
extern const int COLOR_ropes__RopeCharIterator___64dsub_str_iter;
val* ropes__RopeCharIterator__sub_str_iter(val* self);
void ropes__RopeCharIterator__sub_str_iter_61d(val* self, val* p0);
extern const int COLOR_ropes__RopeCharIterator___64dabs_pos;
long ropes__RopeCharIterator__abs_pos(val* self);
void ropes__RopeCharIterator__abs_pos_61d(val* self, long p0);
extern const int COLOR_ropes__RopeCharIterator___64dsub_pos;
long ropes__RopeCharIterator__sub_pos(val* self);
void ropes__RopeCharIterator__sub_pos_61d(val* self, long p0);
extern const int COLOR_ropes__RopeCharIterator___64dcurr_substring;
val* ropes__RopeCharIterator__curr_substring(val* self);
void ropes__RopeCharIterator__curr_substring_61d(val* self, val* p0);
extern const int COLOR_ropes__RopeCharIterator__sub_str_iter_61d;
extern const int COLOR_ropes__RopeCharIterator__sub_str_iter;
extern const int COLOR_ropes__RopeCharIterator__curr_substring_61d;
void ropes__RopeCharIterator__init(val* self, val* p0);
extern const int COLOR_ropes__RopeCharIterator__curr_substring;
extern const int COLOR_ropes__RopeCharIterator__sub_pos;
char ropes__RopeCharIterator__item(val* self);
short int ropes__RopeCharIterator__is_ok(val* self);
extern const int COLOR_ropes__RopeCharIterator__sub_pos_61d;
extern const int COLOR_ropes__RopeCharIterator__abs_pos;
extern const int COLOR_ropes__RopeCharIterator__abs_pos_61d;
void ropes__RopeCharIterator__next(val* self);
long ropes__RopeCharIterator__index(val* self);
extern const int COLOR_ropes__DFSRopeLeafIterator___64dvisit_stack;
val* ropes__DFSRopeLeafIterator__visit_stack(val* self);
void ropes__DFSRopeLeafIterator__visit_stack_61d(val* self, val* p0);
extern const int COLOR_ropes__DFSRopeLeafIterator___64dcurr_leaf;
val* ropes__DFSRopeLeafIterator__curr_leaf(val* self);
void ropes__DFSRopeLeafIterator__curr_leaf_61d(val* self, val* p0);
extern const int COLOR_ropes__RopeIterator__init;
extern const int COLOR_ropes__RopeIterator__target;
extern const int COLOR_ropes__DFSRopeLeafIterator__visit_stack;
extern const int COLOR_ropes__DFSRopeLeafIterator__curr_leaf_61d;
extern const int COLOR_ropes__DFSRopeLeafIterator__next_body;
void ropes__DFSRopeLeafIterator__init(val* self, val* p0);
extern const int COLOR_ropes__RopeIterator__with_index;
extern const int COLOR_ropes__TupleLeafNodePos__visit_stack;
extern const int COLOR_ropes__DFSRopeLeafIterator__visit_stack_61d;
extern const int COLOR_ropes__RopeIterator__pos_61d;
void ropes__DFSRopeLeafIterator__with_index(val* self, val* p0, long p1);
extern const int COLOR_ropes__DFSRopeLeafIterator__curr_leaf;
short int ropes__DFSRopeLeafIterator__is_ok(val* self);
void ropes__DFSRopeLeafIterator__next(val* self);
extern const int COLOR_abstract_collection__Collection__is_empty;
extern const int COLOR_abstract_collection__SequenceRead__last;
extern const int COLOR_ropes__TupleVisitNode__left_visited;
extern const int COLOR_ropes__TupleVisitNode__node;
extern const int COLOR_ropes__TupleVisitNode__right_visited;
extern const int COLOR_abstract_collection__Sequence__pop;
void ropes__DFSRopeLeafIterator__next_body(val* self);
val* ropes__DFSRopeLeafIterator__item(val* self);
extern const int COLOR_ropes__RopeNode___64dparent;
val* ropes__RopeNode__parent(val* self);
void ropes__RopeNode__parent_61d(val* self, val* p0);
extern const int COLOR_ropes__RopeNode___64dheight;
long ropes__RopeNode__height(val* self);
void ropes__RopeNode__height_61d(val* self, long p0);
extern const int COLOR_ropes__RopeNode__height;
long ropes__RopeNode__balance_factor(val* self);
extern const int COLOR_ropes__RopeNode___length;
long ropes__RopeNode__length(val* self);
void ropes__RopeNode__length_61d(val* self, long p0);
void ropes__RopeNode__init(val* self);
extern const int COLOR_ropes__ConcatNode___left_child;
val* ropes__ConcatNode__left_child(val* self);
extern const int COLOR_ropes__ConcatNode___right_child;
val* ropes__ConcatNode__right_child(val* self);
void ropes__ConcatNode__left_child_61d(val* self, val* p0);
void ropes__ConcatNode__right_child_61d(val* self, val* p0);
extern const int COLOR_ropes__RopeNode__length_61d;
extern const int COLOR_ropes__RopeNode__height_61d;
void ropes__ConcatNode__update_data(val* self);
long ropes__ConcatNode__balance_factor(val* self);
extern const int COLOR_ropes__RopeNode__init;
void ropes__ConcatNode__init(val* self);
extern const int COLOR_ropes__LeafNode___value;
void ropes__LeafNode__init(val* self, val* p0);
val* ropes__LeafNode__value(val* self);
void ropes__LeafNode__value_61d(val* self, val* p0);
extern const int COLOR_ropes__String___61d_61d;
short int ropes__String___61d_61d(val* self, val* p0);
extern const int COLOR_ropes__Buffer___61d_61d;
short int ropes__Buffer___61d_61d(val* self, val* p0);
