#include "nit.common.h"
extern const int COLOR_serialization_phase__ToolContext___64dserialization_phase;
val* serialization_phase__ToolContext__serialization_phase(val* self);
void serialization_phase__ToolContext__serialization_phase_61d(val* self, val* p0);
extern const int COLOR_parser_nodes__AAnnotation__n_atid;
extern const int COLOR_parser_nodes__AAtid__n_id;
extern const int COLOR_parser_nodes__Token__text;
val* string__NativeString__to_s_with_length(char* self, long p0);
extern const int COLOR_kernel__Object___33d_61d;
extern const struct type type_parser_nodes__AStdClassdef;
extern const int COLOR_phase__Phase__toolcontext;
extern const int COLOR_parser_nodes__ANode__location;
extern const int COLOR_toolcontext__ToolContext__error;
extern const int COLOR_serialization_phase__SerializationPhase__generate_serialization_method;
void serialization_phase__SerializationPhase__process_annotated_node(val* self, val* p0, val* p1);
extern const int COLOR_parser_nodes__AClassdef__n_propdefs;
val* NEW_array__Array(const struct type* type);
extern const struct type type_array__Arraystring__String;
extern const int COLOR_array__Array__init;
extern const int COLOR_abstract_collection__SimpleCollection__add;
extern const int COLOR_abstract_collection__Collection__iterator;
extern const int COLOR_abstract_collection__Iterator__is_ok;
extern const int COLOR_abstract_collection__Iterator__item;
extern const struct type type_parser_nodes__AAttrPropdef;
extern const int COLOR_parser_nodes__AAttrPropdef__n_id;
extern const int COLOR_parser_nodes__AAttrPropdef__n_id2;
extern const struct type type_array__Arraykernel__Object;
val* NEW_array__NativeArray(int length, const struct type* type);
extern const struct type type_array__NativeArraykernel__Object;
extern const int COLOR_array__Array__with_native;
extern const int COLOR_string__Object__to_s;
extern const int COLOR_abstract_collection__Iterator__next;
extern const int COLOR_string__Collection__join;
extern const int COLOR_parser_util__ToolContext__parse_propdef;
extern const int COLOR_abstract_collection__Sequence__push;
void serialization_phase__SerializationPhase__generate_serialization_method(val* self, val* p0);
