#include "nit.common.h"
extern const int COLOR_simple_misc_analysis__ToolContext___64dsimple_misc_analysis_phase;
val* simple_misc_analysis__ToolContext__simple_misc_analysis_phase(val* self);
void simple_misc_analysis__ToolContext__simple_misc_analysis_phase_61d(val* self, val* p0);
extern const int COLOR_phase__Phase__toolcontext;
extern const int COLOR_simple_misc_analysis__AModule__do_simple_misc_analysis;
void simple_misc_analysis__SimpleMiscAnalysisPhase__process_nmodule(val* self, val* p0);
val* NEW_simple_misc_analysis__SimpleMiscVisitor(const struct type* type);
extern const struct type type_simple_misc_analysis__SimpleMiscVisitor;
extern const int COLOR_simple_misc_analysis__SimpleMiscVisitor__init;
extern const int COLOR_parser_nodes__Visitor__enter_visit;
void simple_misc_analysis__AModule__do_simple_misc_analysis(val* self, val* p0);
extern const int COLOR_simple_misc_analysis__ANode__accept_simple_misc;
void simple_misc_analysis__SimpleMiscVisitor__visit(val* self, val* p0);
extern const int COLOR_simple_misc_analysis__SimpleMiscVisitor___64donce_count;
long simple_misc_analysis__SimpleMiscVisitor__once_count(val* self);
void simple_misc_analysis__SimpleMiscVisitor__once_count_61d(val* self, long p0);
extern const int COLOR_simple_misc_analysis__SimpleMiscVisitor___64dtoolcontext;
val* simple_misc_analysis__SimpleMiscVisitor__toolcontext(val* self);
void simple_misc_analysis__SimpleMiscVisitor__toolcontext_61d(val* self, val* p0);
extern const int COLOR_simple_misc_analysis__SimpleMiscVisitor__toolcontext;
extern const int COLOR_parser_nodes__ANode__hot_location;
extern const int COLOR_toolcontext__ToolContext__warning;
void simple_misc_analysis__SimpleMiscVisitor__warning(val* self, val* p0, val* p1);
extern const int COLOR_parser_nodes__Visitor__init;
extern const int COLOR_simple_misc_analysis__SimpleMiscVisitor__toolcontext_61d;
void simple_misc_analysis__SimpleMiscVisitor__init(val* self, val* p0);
extern const int COLOR_parser_nodes__ANode__visit_all;
extern const int COLOR_simple_misc_analysis__ANode__after_simple_misc;
void simple_misc_analysis__ANode__accept_simple_misc(val* self, val* p0);
void simple_misc_analysis__ANode__after_simple_misc(val* self, val* p0);
extern const int COLOR_parser_nodes__ASignature__n_opar;
extern const int COLOR_parser_nodes__ASignature__n_params;
extern const int COLOR_abstract_collection__Collection__is_empty;
val* string__NativeString__to_s_with_length(char* self, long p0);
extern const int COLOR_simple_misc_analysis__SimpleMiscVisitor__warning;
void simple_misc_analysis__ASignature__after_simple_misc(val* self, val* p0);
void simple_misc_analysis__AExpr__warn_parentheses(val* self, val* p0);
void simple_misc_analysis__AParExpr__warn_parentheses(val* self, val* p0);
extern const int COLOR_parser_nodes__AExprs__n_exprs;
void simple_misc_analysis__AParExprs__after_simple_misc(val* self, val* p0);
extern const int COLOR_parser_nodes__AReturnExpr__n_expr;
extern const int COLOR_simple_misc_analysis__AExpr__warn_parentheses;
void simple_misc_analysis__AReturnExpr__after_simple_misc(val* self, val* p0);
extern const int COLOR_parser_nodes__AContinueExpr__n_expr;
void simple_misc_analysis__AContinueExpr__after_simple_misc(val* self, val* p0);
extern const int COLOR_parser_nodes__ABreakExpr__n_expr;
void simple_misc_analysis__ABreakExpr__after_simple_misc(val* self, val* p0);
extern const int COLOR_parser_nodes__AWhileExpr__n_expr;
extern const struct type type_parser_nodes__ATrueExpr;
void simple_misc_analysis__AWhileExpr__after_simple_misc(val* self, val* p0);
extern const int COLOR_parser_nodes__AForExpr__n_expr;
void simple_misc_analysis__AForExpr__after_simple_misc(val* self, val* p0);
extern const int COLOR_parser_nodes__AIfExpr__n_expr;
void simple_misc_analysis__AIfExpr__after_simple_misc(val* self, val* p0);
extern const int COLOR_parser_nodes__AIfexprExpr__n_expr;
void simple_misc_analysis__AIfexprExpr__after_simple_misc(val* self, val* p0);
extern const int COLOR_simple_misc_analysis__SimpleMiscVisitor__once_count;
extern const struct type type_kernel__Int;
extern const int COLOR_simple_misc_analysis__SimpleMiscVisitor__once_count_61d;
extern const int COLOR_simple_misc_analysis__AOnceExpr__accept_simple_misc;
void simple_misc_analysis__AOnceExpr__accept_simple_misc(val* self, val* p0);
