#include "nit.common.h"
#define COLOR_standard__hash_collection__HashCollection___35dK 13
extern const char FILE_standard__hash_collection[];
#define COLOR_standard__kernel__Object___61d_61d 2
#define COLOR_standard__kernel__Object__hash 4
#define COLOR_standard__hash_collection__HashCollection___capacity 1
extern const struct type type_standard__Int;
extern const char FILE_standard__kernel[];
#define COLOR_standard__hash_collection__HashCollection___last_accessed_key 5
#define COLOR_standard__hash_collection__HashCollection___last_accessed_node 6
long standard__hash_collection___standard__hash_collection__HashCollection___index_at(val* self, val* p0);
val* standard__hash_collection___standard__hash_collection__HashCollection___node_at_idx(val* self, long p0, val* p1);
#define COLOR_standard__hash_collection__HashCollection___array 0
#define COLOR_standard__hash_collection__HashNode___key 0
#define COLOR_standard__hash_collection__HashNode___next_in_bucklet 4
#define COLOR_nullable__standard__hash_collection__HashCollection__N 14
#define COLOR_standard__hash_collection__HashCollection__N 15
#define COLOR_standard__hash_collection__HashCollection___first_item 3
#define COLOR_standard__hash_collection__HashCollection___last_item 4
#define COLOR_standard__hash_collection__HashNode___next_item 1
#define COLOR_standard__hash_collection__HashNode___prev_item 2
#define COLOR_standard__NativeArray___35dE 0
extern const char FILE_standard__array[];
#define COLOR_standard__hash_collection__HashNode___prev_in_bucklet 3
#define COLOR_standard__hash_collection__HashCollection___the_length 2
void standard__hash_collection___standard__hash_collection__HashCollection___enlarge(val* self, long p0);
val* NEW_standard__NativeArray(int length, const struct type* type);
#define COLOR_standard__NativeArray__nullable__standard__hash_collection__HashCollection__N 16
#define COLOR_standard__hash_collection__HashNode___35dK 1
#define COLOR_standard__hash_collection___standard__hash_collection__HashNode___standard__kernel__Object__init 33
#define COLOR_standard__HashMap___35dK 5
val* standard__hash_collection___standard__hash_collection__HashCollection___node_at(val* self, val* p0);
#define COLOR_standard__abstract_collection__MapRead__provide_default_value 40
#define COLOR_standard__hash_collection__HashMapNode___value 5
val* NEW_standard__HashMapIterator(const struct type* type);
#define COLOR_standard__HashMapIterator__standard__HashMap___35dK__standard__HashMap___35dV 6
#define COLOR_standard__hash_collection__HashMapIterator__map_61d 38
#define COLOR_standard__kernel__Object__init 7
#define COLOR_standard__HashMap___35dV 7
val* NEW_standard__hash_collection__HashMapNode(const struct type* type);
#define COLOR_standard__hash_collection__HashMapNode__standard__HashMap___35dK__standard__HashMap___35dV 8
#define COLOR_standard__hash_collection__HashNode__key_61d 32
#define COLOR_standard__hash_collection__HashMapNode__value_61d 34
void standard__hash_collection___standard__hash_collection__HashCollection___store(val* self, long p0, val* p1);
void standard__hash_collection___standard__hash_collection__HashCollection___raz(val* self);
#define COLOR_standard___standard__HashMap___standard__kernel__Object__init 52
#define COLOR_standard__hash_collection__HashMap___keys 7
#define COLOR_standard__hash_collection__HashMap___values 8
#define COLOR_standard__hash_collection__HashMapKeys___map 0
#define COLOR_standard__HashMap__standard__hash_collection__HashMapKeys___35dK__standard__hash_collection__HashMapKeys___35dV 0
#define COLOR_standard__hash_collection__HashMapKeys___35dK 1
short int standard___standard__HashMap___standard__abstract_collection__MapRead__is_empty(val* self);
long standard___standard__HashMap___standard__abstract_collection__MapRead__length(val* self);
val* NEW_standard__MapKeysIterator(const struct type* type);
#define COLOR_standard__MapKeysIterator__standard__hash_collection__HashMapKeys___35dK__standard__hash_collection__HashMapKeys___35dV 2
val* standard___standard__HashMap___standard__abstract_collection__MapRead__iterator(val* self);
#define COLOR_standard__abstract_collection__MapKeysIterator__original_iterator_61d 39
void standard___standard__HashMap___standard__abstract_collection__Map__clear(val* self);
void standard__hash_collection___standard__hash_collection__HashCollection___remove_node(val* self, val* p0);
#define COLOR_standard__hash_collection___standard__hash_collection__HashMapKeys___standard__kernel__Object__init 56
#define COLOR_standard__hash_collection__HashMapValues___map 0
#define COLOR_standard__HashMap__standard__hash_collection__HashMapValues___35dK__standard__hash_collection__HashMapValues___35dV 0
#define COLOR_standard__hash_collection__HashMapValues___35dV 1
val* NEW_standard__MapValuesIterator(const struct type* type);
#define COLOR_standard__MapValuesIterator__standard__hash_collection__HashMapValues___35dK__standard__hash_collection__HashMapValues___35dV 2
#define COLOR_standard__abstract_collection__MapValuesIterator__original_iterator_61d 39
#define COLOR_standard__hash_collection___standard__hash_collection__HashMapValues___standard__kernel__Object__init 56
#define COLOR_standard__hash_collection__HashMapNode___35dV 0
#define COLOR_standard__hash_collection___standard__hash_collection__HashMapNode___standard__kernel__Object__init 35
#define COLOR_standard__hash_collection__HashMapIterator___node 1
short int standard___standard__HashMapIterator___standard__abstract_collection__MapIterator__is_ok(val* self);
#define COLOR_standard__hash_collection__HashMapIterator___map 0
#define COLOR_standard__HashMap__standard__HashMapIterator___35dK__standard__HashMapIterator___35dV 0
#define COLOR_standard__HashSet___35dE 0
val* NEW_standard__hash_collection__HashSetNode(const struct type* type);
#define COLOR_standard__hash_collection__HashSetNode__standard__HashSet___35dE 1
val* NEW_standard__hash_collection__HashSetIterator(const struct type* type);
#define COLOR_standard__hash_collection__HashSetIterator__standard__HashSet___35dE 2
#define COLOR_standard__hash_collection__HashSetIterator__set_61d 38
#define COLOR_standard___standard__HashSet___standard__kernel__Object__init 60
#define COLOR_standard__Collection__standard__HashSet___35dE 3
void standard___standard__HashSet___standard__kernel__Object__init(val* self);
void standard___standard__SimpleCollection___add_all(val* self, val* p0);
#define COLOR_standard__hash_collection__HashSetIterator___node 1
short int standard__hash_collection___standard__hash_collection__HashSetIterator___standard__abstract_collection__Iterator__is_ok(val* self);
#define COLOR_standard__HashSet__standard__hash_collection__HashSetIterator___35dE 1
#define COLOR_standard__hash_collection__HashSetIterator___set 0
