#include "nit.common.h"
#define COLOR_standard__abstract_collection__Collection__length 39
#define COLOR_standard__abstract_collection__Collection__iterator 37
#define COLOR_standard__abstract_collection__Iterator__is_ok 34
#define COLOR_standard__abstract_collection__Iterator__item 32
extern const struct type type_standard__Int;
extern const char FILE_standard__kernel[];
#define COLOR_standard__abstract_collection__Iterator__next 33
#define COLOR_standard__Collection___35dE 10
extern const char FILE_standard__abstract_collection[];
#define COLOR_standard__kernel__Object___61d_61d 2
#define COLOR_standard__Collection__standard__Collection___35dE 11
#define COLOR_standard__abstract_collection__Collection__has 40
#define COLOR_standard__abstract_collection__Container___item 0
#define COLOR_standard__Container___35dE 1
val* NEW_standard__abstract_collection__ContainerIterator(const struct type* type);
#define COLOR_standard__abstract_collection__ContainerIterator__standard__Container___35dE 2
#define COLOR_standard__abstract_collection__ContainerIterator__container_61d 39
#define COLOR_standard__kernel__Object__init 7
#define COLOR_standard___standard__Container___standard__kernel__Object__init 47
#define COLOR_standard__abstract_collection__ContainerIterator___container 1
#define COLOR_standard__abstract_collection__ContainerIterator___is_ok 0
#define COLOR_standard__Container__standard__abstract_collection__ContainerIterator___35dE 1
#define COLOR_standard__abstract_collection___standard__abstract_collection__ContainerIterator___standard__kernel__Object__init 40
#define COLOR_standard__RemovableCollection___35dE 9
#define COLOR_standard__Collection__standard__SimpleCollection___35dE 8
#define COLOR_standard__abstract_collection__SimpleCollection__add 57
extern const struct type type_standard__Set__standard__Object;
#define COLOR_standard__Collection__standard__Set___35dE 4
short int standard___standard__Collection___has_all(val* self, val* p0);
#define COLOR_standard__kernel__Object__hash 4
#define COLOR_standard__MapRead___35dK 9
short int standard___standard__MapRead___has_key(val* self, val* p0);
#define COLOR_standard__abstract_collection__MapRead___91d_93d 32
#define COLOR_standard__abstract_collection__MapRead__keys 37
#define COLOR_standard__abstract_collection__MapKeysIterator___original_iterator 0
#define COLOR_standard__MapIterator__standard__MapKeysIterator___35dK__standard__MapKeysIterator___35dV 1
#define COLOR_standard__abstract_collection__MapIterator__is_ok 35
#define COLOR_standard__abstract_collection__MapIterator__next 34
#define COLOR_standard__abstract_collection__MapIterator__key 33
#define COLOR_standard___standard__MapKeysIterator___standard__kernel__Object__init 40
#define COLOR_standard__abstract_collection__MapValuesIterator___original_iterator 0
#define COLOR_standard__MapIterator__standard__MapValuesIterator___35dK__standard__MapValuesIterator___35dV 1
#define COLOR_standard__abstract_collection__MapIterator__item 32
#define COLOR_standard___standard__MapValuesIterator___standard__kernel__Object__init 40
#define COLOR_standard__abstract_collection__Collection__is_empty 38
#define COLOR_standard__abstract_collection__SequenceRead___91d_93d 45
#define COLOR_standard__SequenceRead___35dE 13
#define COLOR_standard__abstract_collection__SequenceRead__index_of_from 49
#define COLOR_standard__abstract_collection__SequenceRead__last_index_of_from 50
#define COLOR_standard__abstract_collection__IndexedIterator__index 38
extern const struct type type_standard__SequenceRead__nullable__standard__Object;
#define COLOR_standard__kernel__Object___33d_61d 3
#define COLOR_standard__Sequence___35dE 6
#define COLOR_standard__abstract_collection__Sequence___91d_93d_61d 66
#define COLOR_standard__abstract_collection__Sequence__push 60
#define COLOR_standard__Collection__standard__Sequence___35dE 7
#define COLOR_standard__abstract_collection__SimpleCollection__add_all 58
#define COLOR_standard__abstract_collection__Sequence__insert_all 68
#define COLOR_standard__abstract_collection__Sequence__insert 67
val* NEW_standard__abstract_collection__CoupleMapIterator(const struct type* type);
#define COLOR_standard__abstract_collection__CoupleMapIterator__standard__CoupleMap___35dK__standard__CoupleMap___35dV 6
val* standard___standard__ArrayMap___standard__abstract_collection__CoupleMap__couple_iterator(val* self);
#define COLOR_standard__abstract_collection__CoupleMapIterator__iter_61d 37
#define COLOR_standard__abstract_collection__CoupleMapIterator___iter 0
#define COLOR_standard__abstract_collection__Couple___second 1
#define COLOR_standard__abstract_collection__Couple___first 0
#define COLOR_standard__Iterator__standard__Couple__standard__abstract_collection__CoupleMapIterator___35dK__standard__abstract_collection__CoupleMapIterator___35dV 0
#define COLOR_standard__abstract_collection___standard__abstract_collection__CoupleMapIterator___standard__kernel__Object__init 38
#define COLOR_standard__Couple___35dF 0
#define COLOR_standard__Couple___35dS 1
#define COLOR_standard___standard__Couple___standard__kernel__Object__init 36
