/* This C file is generated by NIT to compile module standard___file. */
#include "standard___file._sep.h"
void standard___file___Object___printn(val_t p0, val_t p1){
  struct {struct stack_frame_t me; val_t MORE_REG[1];} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 25;
  fra.me.meth = LOCATE_standard___file___Object___printn;
  fra.me.has_broke = 0;
  fra.me.REG_size = 2;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  /* ./../lib/standard//file.nit:25 */
  REGB0 = TAG_Bool(VAL_ISA(fra.me.REG[1], COLOR_standard___collection___array___Array, ID_standard___collection___array___Array)) /*cast Array[Object]*/;
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Cast failed", NULL, LOCATE_standard___file, 25);
  }
  /* ./../lib/standard//file.nit:28 */
  fra.me.REG[0] = CALL_standard___file___Object___stdout(fra.me.REG[0])(fra.me.REG[0]);
  fra.me.REG[1] = CALL_standard___string___Object___to_s(fra.me.REG[1])(fra.me.REG[1]);
  CALL_standard___stream___OStream___write(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[1]);
  stack_frame_head = fra.me.prev;
  return;
}
void standard___file___Object___print(val_t p0, val_t p1){
  struct {struct stack_frame_t me; val_t MORE_REG[2];} fra;
  val_t REGB0;
  val_t tmp;
  static val_t once_value_1; /* Once value */
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 31;
  fra.me.meth = LOCATE_standard___file___Object___print;
  fra.me.has_broke = 0;
  fra.me.REG_size = 3;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  /* ./../lib/standard//file.nit:34 */
  fra.me.REG[2] = CALL_standard___file___Object___stdout(fra.me.REG[0])(fra.me.REG[0]);
  fra.me.REG[1] = CALL_standard___string___Object___to_s(fra.me.REG[1])(fra.me.REG[1]);
  CALL_standard___stream___OStream___write(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[1]);
  /* ./../lib/standard//file.nit:35 */
  fra.me.REG[0] = CALL_standard___file___Object___stdout(fra.me.REG[0])(fra.me.REG[0]);
  if (!once_value_1) {
    fra.me.REG[1] = BOX_NativeString("\n");
    REGB0 = TAG_Int(1);
    fra.me.REG[1] = NEW_String_standard___string___String___with_native(fra.me.REG[1], REGB0);
    once_value_1 = fra.me.REG[1];
    register_static_object(&once_value_1);
  } else fra.me.REG[1] = once_value_1;
  fra.me.REG[1] = fra.me.REG[1];
  CALL_standard___stream___OStream___write(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[1]);
  stack_frame_head = fra.me.prev;
  return;
}
val_t standard___file___Object___getc(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 38;
  fra.me.meth = LOCATE_standard___file___Object___getc;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:41 */
  fra.me.REG[0] = CALL_standard___file___Object___stdin(fra.me.REG[0])(fra.me.REG[0]);
  REGB0 = CALL_standard___stream___IStream___read_char(fra.me.REG[0])(fra.me.REG[0]);
  /* ./../lib/standard//kernel.nit:280 */
  REGB0 = TAG_Char(UNTAG_Int(REGB0));
  /* ./../lib/standard//file.nit:41 */
  goto label1;
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return REGB0;
}
val_t standard___file___Object___gets(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 44;
  fra.me.meth = LOCATE_standard___file___Object___gets;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:47 */
  fra.me.REG[0] = CALL_standard___file___Object___stdin(fra.me.REG[0])(fra.me.REG[0]);
  fra.me.REG[0] = CALL_standard___stream___IStream___read_line(fra.me.REG[0])(fra.me.REG[0]);
  goto label1;
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t standard___file___Object___stdin(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t tmp;
  static val_t once_value_1; /* Once value */
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 291;
  fra.me.meth = LOCATE_standard___file___Object___stdin;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:292 */
  if (!once_value_1) {
    fra.me.REG[0] = NEW_Stdin_standard___file___Stdin___init();
    once_value_1 = fra.me.REG[0];
    register_static_object(&once_value_1);
  } else fra.me.REG[0] = once_value_1;
  fra.me.REG[0] = fra.me.REG[0];
  goto label2;
  label2: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t standard___file___Object___stdout(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t tmp;
  static val_t once_value_1; /* Once value */
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 294;
  fra.me.meth = LOCATE_standard___file___Object___stdout;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:295 */
  if (!once_value_1) {
    fra.me.REG[0] = NEW_Stdout_standard___file___Stdout___init();
    once_value_1 = fra.me.REG[0];
    register_static_object(&once_value_1);
  } else fra.me.REG[0] = once_value_1;
  fra.me.REG[0] = fra.me.REG[0];
  goto label2;
  label2: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t standard___file___Object___stderr(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t tmp;
  static val_t once_value_1; /* Once value */
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 297;
  fra.me.meth = LOCATE_standard___file___Object___stderr;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:298 */
  if (!once_value_1) {
    fra.me.REG[0] = NEW_Stderr_standard___file___Stderr___init();
    once_value_1 = fra.me.REG[0];
    register_static_object(&once_value_1);
  } else fra.me.REG[0] = once_value_1;
  fra.me.REG[0] = fra.me.REG[0];
  goto label2;
  label2: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t standard___file___FStream___path(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 55;
  fra.me.meth = LOCATE_standard___file___FStream___path;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:55 */
  fra.me.REG[0] = ATTR_standard___file___FStream____path(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t standard___file___FStream___file_stat(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 61;
  fra.me.meth = LOCATE_standard___file___FStream___file_stat;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:62 */
  fra.me.REG[0] = ATTR_standard___file___FStream____file(fra.me.REG[0]);
  REGB0 = TAG_Bool(fra.me.REG[0]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
    nit_abort("Reciever is null", NULL, LOCATE_standard___file, 62);
  }
  fra.me.REG[0] = CALL_standard___file___NativeFile___file_stat(fra.me.REG[0])(fra.me.REG[0]);
  goto label1;
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
void standard___file___IFStream___reopen(val_t p0){
  struct {struct stack_frame_t me; val_t MORE_REG[1];} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 71;
  fra.me.meth = LOCATE_standard___file___IFStream___reopen;
  fra.me.has_broke = 0;
  fra.me.REG_size = 2;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:73 */
  REGB0 = CALL_standard___stream___IStream___eof(fra.me.REG[0])(fra.me.REG[0]);
  REGB0 = TAG_Bool(!UNTAG_Bool(REGB0));
  if (UNTAG_Bool(REGB0)) {
    CALL_standard___stream___IOS___close(fra.me.REG[0])(fra.me.REG[0]);
  }
  /* ./../lib/standard//file.nit:74 */
  fra.me.REG[1] = ATTR_standard___file___FStream____path(fra.me.REG[0]);
  REGB0 = TAG_Bool(fra.me.REG[1]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
    nit_abort("Reciever is null", NULL, LOCATE_standard___file, 74);
  }
  fra.me.REG[1] = CALL_standard___string___String___to_cstring(fra.me.REG[1])(fra.me.REG[1]);
  fra.me.REG[1] = CALL_standard___file___NativeFileCapable___io_open_read(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[1]);
  ATTR_standard___file___FStream____file(fra.me.REG[0]) = fra.me.REG[1];
  /* ./../lib/standard//file.nit:75 */
  REGB0 = TAG_Bool(false);
  ATTR_standard___file___IFStream____end_reached(fra.me.REG[0]) = REGB0;
  /* ./../lib/standard//file.nit:76 */
  REGB0 = TAG_Int(0);
  ATTR_standard___stream___BufferedIStream____buffer_pos(fra.me.REG[0]) = REGB0;
  /* ./../lib/standard//file.nit:77 */
  fra.me.REG[0] = ATTR_standard___stream___BufferedIStream____buffer(fra.me.REG[0]);
  REGB0 = TAG_Bool(fra.me.REG[0]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
    nit_abort("Reciever is null", NULL, LOCATE_standard___file, 77);
  }
  CALL_standard___collection___abstract_collection___RemovableCollection___clear(fra.me.REG[0])(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return;
}
void standard___file___IFStream___close(val_t p0){
  struct {struct stack_frame_t me; val_t MORE_REG[1];} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 80;
  fra.me.meth = LOCATE_standard___file___IFStream___close;
  fra.me.has_broke = 0;
  fra.me.REG_size = 2;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:82 */
  fra.me.REG[1] = ATTR_standard___file___FStream____file(fra.me.REG[0]);
  REGB0 = TAG_Bool(fra.me.REG[1]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
    nit_abort("Reciever is null", NULL, LOCATE_standard___file, 82);
  }
  REGB0 = CALL_standard___file___NativeFile___io_close(fra.me.REG[1])(fra.me.REG[1]);
  /* ./../lib/standard//file.nit:83 */
  REGB0 = TAG_Bool(true);
  ATTR_standard___file___IFStream____end_reached(fra.me.REG[0]) = REGB0;
  stack_frame_head = fra.me.prev;
  return;
}
void standard___file___IFStream___fill_buffer(val_t p0){
  struct {struct stack_frame_t me; val_t MORE_REG[3];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 86;
  fra.me.meth = LOCATE_standard___file___IFStream___fill_buffer;
  fra.me.has_broke = 0;
  fra.me.REG_size = 4;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[3] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:89 */
  fra.me.REG[1] = ATTR_standard___file___FStream____file(fra.me.REG[0]);
  fra.me.REG[2] = ATTR_standard___stream___BufferedIStream____buffer(fra.me.REG[0]);
  REGB0 = TAG_Bool(fra.me.REG[2]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
    nit_abort("Reciever is null", NULL, LOCATE_standard___file, 89);
  }
  REGB0 = TAG_Bool(ATTR_standard___string___AbstractString____items(fra.me.REG[2])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_items", LOCATE_standard___file, 89);
  }
  fra.me.REG[2] = ATTR_standard___string___AbstractString____items(fra.me.REG[2]);
  fra.me.REG[3] = ATTR_standard___stream___BufferedIStream____buffer(fra.me.REG[0]);
  REGB0 = TAG_Bool(fra.me.REG[3]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
    nit_abort("Reciever is null", NULL, LOCATE_standard___file, 89);
  }
  REGB0 = TAG_Bool(ATTR_standard___string___Buffer____capacity(fra.me.REG[3])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_capacity", LOCATE_standard___file, 89);
  }
  REGB0 = ATTR_standard___string___Buffer____capacity(fra.me.REG[3]);
  REGB1 = TAG_Bool(fra.me.REG[1]==NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
    nit_abort("Reciever is null", NULL, LOCATE_standard___file, 89);
  }
  REGB0 = CALL_standard___file___NativeFile___io_read(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2], REGB0);
  /* ./../lib/standard//file.nit:90 */
  REGB1 = TAG_Int(0);
  /* ./../lib/standard//kernel.nit:214 */
  REGB1 = TAG_Bool(UNTAG_Int(REGB0)<=UNTAG_Int(REGB1));
  /* ./../lib/standard//file.nit:90 */
  if (UNTAG_Bool(REGB1)) {
    /* ./../lib/standard//file.nit:91 */
    REGB1 = TAG_Bool(true);
    ATTR_standard___file___IFStream____end_reached(fra.me.REG[0]) = REGB1;
    /* ./../lib/standard//file.nit:92 */
    REGB1 = TAG_Int(0);
    REGB0 = REGB1;
  }
  /* ./../lib/standard//file.nit:94 */
  fra.me.REG[2] = ATTR_standard___stream___BufferedIStream____buffer(fra.me.REG[0]);
  REGB1 = TAG_Bool(fra.me.REG[2]==NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
    nit_abort("Reciever is null", NULL, LOCATE_standard___file, 94);
  }
  ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[2]) = REGB0;
  /* ./../lib/standard//file.nit:95 */
  REGB0 = TAG_Int(0);
  ATTR_standard___stream___BufferedIStream____buffer_pos(fra.me.REG[0]) = REGB0;
  stack_frame_head = fra.me.prev;
  return;
}
val_t standard___file___IFStream___end_reached(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 98;
  fra.me.meth = LOCATE_standard___file___IFStream___end_reached;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:98 */
  REGB0 = TAG_Bool(ATTR_standard___file___IFStream____end_reached(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_end_reached", LOCATE_standard___file, 98);
  }
  REGB0 = ATTR_standard___file___IFStream____end_reached(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return REGB0;
}
void standard___file___IFStream___open(val_t p0, val_t p1, int* init_table){
  int itpos0 = VAL2OBJ(p0)->vft[INIT_TABLE_POS_standard___file___IFStream].i;
  struct {struct stack_frame_t me; val_t MORE_REG[1];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t tmp;
  if (init_table[itpos0]) return;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 101;
  fra.me.meth = LOCATE_standard___file___IFStream___open;
  fra.me.has_broke = 0;
  fra.me.REG_size = 2;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  /* ./../lib/standard//file.nit:104 */
  ATTR_standard___file___FStream____path(fra.me.REG[0]) = fra.me.REG[1];
  /* ./../lib/standard//file.nit:105 */
  REGB0 = TAG_Int(10);
  CALL_standard___stream___BufferedIStream___prepare_buffer(fra.me.REG[0])(fra.me.REG[0], REGB0);
  /* ./../lib/standard//file.nit:106 */
  fra.me.REG[1] = ATTR_standard___file___FStream____path(fra.me.REG[0]);
  REGB0 = TAG_Bool(fra.me.REG[1]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
    nit_abort("Reciever is null", NULL, LOCATE_standard___file, 106);
  }
  fra.me.REG[1] = CALL_standard___string___String___to_cstring(fra.me.REG[1])(fra.me.REG[1]);
  fra.me.REG[1] = CALL_standard___file___NativeFileCapable___io_open_read(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[1]);
  ATTR_standard___file___FStream____file(fra.me.REG[0]) = fra.me.REG[1];
  /* ./../lib/standard//file.nit:107 */
  fra.me.REG[0] = ATTR_standard___file___FStream____file(fra.me.REG[0]);
  REGB0 = TAG_Bool(fra.me.REG[0]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    REGB1 = TAG_Bool(fra.me.REG[0]==NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
      REGB1 = TAG_Bool(false);
      REGB0 = REGB1;
    } else {
      REGB1 = CALL_standard___kernel___Object_____eqeq(fra.me.REG[0])(fra.me.REG[0], NIT_NULL);
      REGB0 = REGB1;
    }
  }
  REGB0 = TAG_Bool(!UNTAG_Bool(REGB0));
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Assert %s  failed", "'cant_open_file'", LOCATE_standard___file, 107);
  }
  stack_frame_head = fra.me.prev;
  init_table[itpos0] = 1;
  return;
}
void standard___file___IFStream___init(val_t p0, int* init_table){
  int itpos1 = VAL2OBJ(p0)->vft[INIT_TABLE_POS_standard___file___IFStream].i;
  struct {struct stack_frame_t me;} fra;
  val_t tmp;
  if (init_table[itpos1]) return;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 110;
  fra.me.meth = LOCATE_standard___file___IFStream___init;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  stack_frame_head = fra.me.prev;
  init_table[itpos1] = 1;
  return;
}
void standard___file___IFStream___without_file(val_t p0, int* init_table){
  int itpos2 = VAL2OBJ(p0)->vft[INIT_TABLE_POS_standard___file___IFStream].i;
  struct {struct stack_frame_t me;} fra;
  val_t tmp;
  if (init_table[itpos2]) return;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 111;
  fra.me.meth = LOCATE_standard___file___IFStream___without_file;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  stack_frame_head = fra.me.prev;
  init_table[itpos2] = 1;
  return;
}
void standard___file___OFStream___write(val_t p0, val_t p1){
  struct {struct stack_frame_t me; val_t MORE_REG[2];} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 119;
  fra.me.meth = LOCATE_standard___file___OFStream___write;
  fra.me.has_broke = 0;
  fra.me.REG_size = 3;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  /* ./../lib/standard//file.nit:122 */
  REGB0 = TAG_Bool(ATTR_standard___file___OFStream____writable(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_writable", LOCATE_standard___file, 122);
  }
  REGB0 = ATTR_standard___file___OFStream____writable(fra.me.REG[0]);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Assert failed", NULL, LOCATE_standard___file, 122);
  }
  /* ./../lib/standard//file.nit:123 */
  fra.me.REG[2] = CALL_standard___string___String___to_cstring(fra.me.REG[1])(fra.me.REG[1]);
  /* ./../lib/standard//collection//array.nit:23 */
  REGB0 = TAG_Bool(ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[1])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_length", LOCATE_standard___collection___array, 23);
  }
  REGB0 = ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[1]);
  /* ./../lib/standard//file.nit:123 */
  CALL_standard___file___OFStream___write_native(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[2], REGB0);
  stack_frame_head = fra.me.prev;
  return;
}
val_t standard___file___OFStream___is_writable(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 126;
  fra.me.meth = LOCATE_standard___file___OFStream___is_writable;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:126 */
  REGB0 = TAG_Bool(ATTR_standard___file___OFStream____writable(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_writable", LOCATE_standard___file, 126);
  }
  REGB0 = ATTR_standard___file___OFStream____writable(fra.me.REG[0]);
  goto label1;
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return REGB0;
}
void standard___file___OFStream___close(val_t p0){
  struct {struct stack_frame_t me; val_t MORE_REG[1];} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 128;
  fra.me.meth = LOCATE_standard___file___OFStream___close;
  fra.me.has_broke = 0;
  fra.me.REG_size = 2;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:130 */
  fra.me.REG[1] = ATTR_standard___file___FStream____file(fra.me.REG[0]);
  REGB0 = TAG_Bool(fra.me.REG[1]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
    nit_abort("Reciever is null", NULL, LOCATE_standard___file, 130);
  }
  REGB0 = CALL_standard___file___NativeFile___io_close(fra.me.REG[1])(fra.me.REG[1]);
  /* ./../lib/standard//file.nit:131 */
  REGB0 = TAG_Bool(false);
  ATTR_standard___file___OFStream____writable(fra.me.REG[0]) = REGB0;
  stack_frame_head = fra.me.prev;
  return;
}
void standard___file___OFStream___write_native(val_t p0, val_t p1, val_t p2){
  struct {struct stack_frame_t me; val_t MORE_REG[2];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t REGB2;
  val_t REGB3;
  val_t tmp;
    static val_t once_value_1; /* Once value */
    static val_t once_value_2; /* Once value */
    static val_t once_value_3; /* Once value */
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 137;
  fra.me.meth = LOCATE_standard___file___OFStream___write_native;
  fra.me.has_broke = 0;
  fra.me.REG_size = 3;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  REGB0 = p2;
  /* ./../lib/standard//file.nit:140 */
  REGB1 = TAG_Bool(ATTR_standard___file___OFStream____writable(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_writable", LOCATE_standard___file, 140);
  }
  REGB1 = ATTR_standard___file___OFStream____writable(fra.me.REG[0]);
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Assert failed", NULL, LOCATE_standard___file, 140);
  }
  /* ./../lib/standard//file.nit:141 */
  fra.me.REG[2] = ATTR_standard___file___FStream____file(fra.me.REG[0]);
  REGB1 = TAG_Bool(fra.me.REG[2]==NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
    nit_abort("Reciever is null", NULL, LOCATE_standard___file, 141);
  }
  REGB1 = CALL_standard___file___NativeFile___io_write(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[1], REGB0);
  /* ./../lib/standard//file.nit:142 */
  REGB2 = TAG_Bool(IS_EQUAL_OO(REGB1,REGB0));
  if (UNTAG_Bool(REGB2)) {
  } else {
    /* ./../lib/standard//kernel.nit:210 */
    REGB3 = TAG_Bool((REGB1)==(REGB0));
    /* ./../lib/standard//file.nit:142 */
    REGB2 = REGB3;
  }
  REGB2 = TAG_Bool(!UNTAG_Bool(REGB2));
  if (UNTAG_Bool(REGB2)) {
    /* ./../lib/standard//file.nit:144 */
    REGB2 = TAG_Int(4);
    fra.me.REG[1] = NEW_Array_standard___collection___array___Array___with_capacity(REGB2);
    if (!once_value_1) {
      fra.me.REG[2] = BOX_NativeString("Problem in writing : ");
      REGB2 = TAG_Int(21);
      fra.me.REG[2] = NEW_String_standard___string___String___with_native(fra.me.REG[2], REGB2);
      once_value_1 = fra.me.REG[2];
      register_static_object(&once_value_1);
    } else fra.me.REG[2] = once_value_1;
    fra.me.REG[2] = fra.me.REG[2];
    CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
    CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], REGB1);
    if (!once_value_2) {
      fra.me.REG[2] = BOX_NativeString(" ");
      REGB1 = TAG_Int(1);
      fra.me.REG[2] = NEW_String_standard___string___String___with_native(fra.me.REG[2], REGB1);
      once_value_2 = fra.me.REG[2];
      register_static_object(&once_value_2);
    } else fra.me.REG[2] = once_value_2;
    fra.me.REG[2] = fra.me.REG[2];
    CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
    CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], REGB0);
    if (!once_value_3) {
      fra.me.REG[2] = BOX_NativeString("\n");
      REGB0 = TAG_Int(1);
      fra.me.REG[2] = NEW_String_standard___string___String___with_native(fra.me.REG[2], REGB0);
      once_value_3 = fra.me.REG[2];
      register_static_object(&once_value_3);
    } else fra.me.REG[2] = once_value_3;
    fra.me.REG[2] = fra.me.REG[2];
    CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
    CALL_standard___file___Object___printn(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[1]);
  }
  stack_frame_head = fra.me.prev;
  return;
}
void standard___file___OFStream___open(val_t p0, val_t p1, int* init_table){
  int itpos3 = VAL2OBJ(p0)->vft[INIT_TABLE_POS_standard___file___OFStream].i;
  struct {struct stack_frame_t me; val_t MORE_REG[2];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t tmp;
  if (init_table[itpos3]) return;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 148;
  fra.me.meth = LOCATE_standard___file___OFStream___open;
  fra.me.has_broke = 0;
  fra.me.REG_size = 3;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  /* ./../lib/standard//file.nit:151 */
  fra.me.REG[2] = CALL_standard___string___String___to_cstring(fra.me.REG[1])(fra.me.REG[1]);
  fra.me.REG[2] = CALL_standard___file___NativeFileCapable___io_open_write(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[2]);
  ATTR_standard___file___FStream____file(fra.me.REG[0]) = fra.me.REG[2];
  /* ./../lib/standard//file.nit:152 */
  fra.me.REG[2] = ATTR_standard___file___FStream____file(fra.me.REG[0]);
  REGB0 = TAG_Bool(fra.me.REG[2]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    REGB1 = TAG_Bool(fra.me.REG[2]==NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
      REGB1 = TAG_Bool(false);
      REGB0 = REGB1;
    } else {
      REGB1 = CALL_standard___kernel___Object_____eqeq(fra.me.REG[2])(fra.me.REG[2], NIT_NULL);
      REGB0 = REGB1;
    }
  }
  REGB0 = TAG_Bool(!UNTAG_Bool(REGB0));
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Assert %s  failed", "'cant_open_file'", LOCATE_standard___file, 152);
  }
  /* ./../lib/standard//file.nit:153 */
  ATTR_standard___file___FStream____path(fra.me.REG[0]) = fra.me.REG[1];
  /* ./../lib/standard//file.nit:154 */
  REGB0 = TAG_Bool(true);
  ATTR_standard___file___OFStream____writable(fra.me.REG[0]) = REGB0;
  stack_frame_head = fra.me.prev;
  init_table[itpos3] = 1;
  return;
}
void standard___file___OFStream___init(val_t p0, int* init_table){
  int itpos4 = VAL2OBJ(p0)->vft[INIT_TABLE_POS_standard___file___OFStream].i;
  struct {struct stack_frame_t me;} fra;
  val_t tmp;
  if (init_table[itpos4]) return;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 157;
  fra.me.meth = LOCATE_standard___file___OFStream___init;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  stack_frame_head = fra.me.prev;
  init_table[itpos4] = 1;
  return;
}
void standard___file___OFStream___without_file(val_t p0, int* init_table){
  int itpos5 = VAL2OBJ(p0)->vft[INIT_TABLE_POS_standard___file___OFStream].i;
  struct {struct stack_frame_t me;} fra;
  val_t tmp;
  if (init_table[itpos5]) return;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 158;
  fra.me.meth = LOCATE_standard___file___OFStream___without_file;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  stack_frame_head = fra.me.prev;
  init_table[itpos5] = 1;
  return;
}
void standard___file___Stdin___init(val_t p0, int* init_table){
  int itpos6 = VAL2OBJ(p0)->vft[INIT_TABLE_POS_standard___file___Stdin].i;
  struct {struct stack_frame_t me; val_t MORE_REG[1];} fra;
  val_t REGB0;
  val_t tmp;
  static val_t once_value_1; /* Once value */
  if (init_table[itpos6]) return;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 165;
  fra.me.meth = LOCATE_standard___file___Stdin___init;
  fra.me.has_broke = 0;
  fra.me.REG_size = 2;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:165 */
  fra.me.REG[1] = fra.me.REG[0];
  CALL_standard___file___IFStream___init(fra.me.REG[0])(fra.me.REG[0], init_table);
  /* ./../lib/standard//file.nit:166 */
  fra.me.REG[0] = CALL_standard___file___NativeFileCapable___native_stdin(fra.me.REG[1])(fra.me.REG[1]);
  ATTR_standard___file___FStream____file(fra.me.REG[1]) = fra.me.REG[0];
  /* ./../lib/standard//file.nit:167 */
  if (!once_value_1) {
    fra.me.REG[0] = BOX_NativeString("/dev/stdin");
    REGB0 = TAG_Int(10);
    fra.me.REG[0] = NEW_String_standard___string___String___with_native(fra.me.REG[0], REGB0);
    once_value_1 = fra.me.REG[0];
    register_static_object(&once_value_1);
  } else fra.me.REG[0] = once_value_1;
  fra.me.REG[0] = fra.me.REG[0];
  ATTR_standard___file___FStream____path(fra.me.REG[1]) = fra.me.REG[0];
  /* ./../lib/standard//file.nit:168 */
  REGB0 = TAG_Int(1);
  CALL_standard___stream___BufferedIStream___prepare_buffer(fra.me.REG[1])(fra.me.REG[1], REGB0);
  stack_frame_head = fra.me.prev;
  init_table[itpos6] = 1;
  return;
}
void standard___file___Stdout___init(val_t p0, int* init_table){
  int itpos7 = VAL2OBJ(p0)->vft[INIT_TABLE_POS_standard___file___Stdout].i;
  struct {struct stack_frame_t me; val_t MORE_REG[1];} fra;
  val_t REGB0;
  val_t tmp;
  static val_t once_value_1; /* Once value */
  if (init_table[itpos7]) return;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 174;
  fra.me.meth = LOCATE_standard___file___Stdout___init;
  fra.me.has_broke = 0;
  fra.me.REG_size = 2;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:174 */
  fra.me.REG[1] = fra.me.REG[0];
  CALL_standard___file___OFStream___init(fra.me.REG[0])(fra.me.REG[0], init_table);
  /* ./../lib/standard//file.nit:175 */
  fra.me.REG[0] = CALL_standard___file___NativeFileCapable___native_stdout(fra.me.REG[1])(fra.me.REG[1]);
  ATTR_standard___file___FStream____file(fra.me.REG[1]) = fra.me.REG[0];
  /* ./../lib/standard//file.nit:176 */
  if (!once_value_1) {
    fra.me.REG[0] = BOX_NativeString("/dev/stdout");
    REGB0 = TAG_Int(11);
    fra.me.REG[0] = NEW_String_standard___string___String___with_native(fra.me.REG[0], REGB0);
    once_value_1 = fra.me.REG[0];
    register_static_object(&once_value_1);
  } else fra.me.REG[0] = once_value_1;
  fra.me.REG[0] = fra.me.REG[0];
  ATTR_standard___file___FStream____path(fra.me.REG[1]) = fra.me.REG[0];
  /* ./../lib/standard//file.nit:177 */
  REGB0 = TAG_Bool(true);
  ATTR_standard___file___OFStream____writable(fra.me.REG[1]) = REGB0;
  stack_frame_head = fra.me.prev;
  init_table[itpos7] = 1;
  return;
}
void standard___file___Stderr___init(val_t p0, int* init_table){
  int itpos8 = VAL2OBJ(p0)->vft[INIT_TABLE_POS_standard___file___Stderr].i;
  struct {struct stack_frame_t me; val_t MORE_REG[1];} fra;
  val_t REGB0;
  val_t tmp;
  static val_t once_value_1; /* Once value */
  if (init_table[itpos8]) return;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 183;
  fra.me.meth = LOCATE_standard___file___Stderr___init;
  fra.me.has_broke = 0;
  fra.me.REG_size = 2;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:183 */
  fra.me.REG[1] = fra.me.REG[0];
  CALL_standard___file___OFStream___init(fra.me.REG[0])(fra.me.REG[0], init_table);
  /* ./../lib/standard//file.nit:184 */
  fra.me.REG[0] = CALL_standard___file___NativeFileCapable___native_stderr(fra.me.REG[1])(fra.me.REG[1]);
  ATTR_standard___file___FStream____file(fra.me.REG[1]) = fra.me.REG[0];
  /* ./../lib/standard//file.nit:185 */
  if (!once_value_1) {
    fra.me.REG[0] = BOX_NativeString("/dev/stderr");
    REGB0 = TAG_Int(11);
    fra.me.REG[0] = NEW_String_standard___string___String___with_native(fra.me.REG[0], REGB0);
    once_value_1 = fra.me.REG[0];
    register_static_object(&once_value_1);
  } else fra.me.REG[0] = once_value_1;
  fra.me.REG[0] = fra.me.REG[0];
  ATTR_standard___file___FStream____path(fra.me.REG[1]) = fra.me.REG[0];
  /* ./../lib/standard//file.nit:186 */
  REGB0 = TAG_Bool(true);
  ATTR_standard___file___OFStream____writable(fra.me.REG[1]) = REGB0;
  stack_frame_head = fra.me.prev;
  init_table[itpos8] = 1;
  return;
}
val_t standard___file___String___file_exists(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 193;
  fra.me.meth = LOCATE_standard___file___String___file_exists;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:194 */
  fra.me.REG[0] = CALL_standard___string___String___to_cstring(fra.me.REG[0])(fra.me.REG[0]);
  REGB0 = CALL_standard___file___NativeString___file_exists(fra.me.REG[0])(fra.me.REG[0]);
  goto label1;
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return REGB0;
}
val_t standard___file___String___file_stat(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 196;
  fra.me.meth = LOCATE_standard___file___String___file_stat;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:196 */
  fra.me.REG[0] = CALL_standard___string___String___to_cstring(fra.me.REG[0])(fra.me.REG[0]);
  fra.me.REG[0] = CALL_standard___file___NativeString___file_stat(fra.me.REG[0])(fra.me.REG[0]);
  goto label1;
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t standard___file___String___file_delete(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 198;
  fra.me.meth = LOCATE_standard___file___String___file_delete;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:198 */
  fra.me.REG[0] = CALL_standard___string___String___to_cstring(fra.me.REG[0])(fra.me.REG[0]);
  REGB0 = CALL_standard___file___NativeString___file_delete(fra.me.REG[0])(fra.me.REG[0]);
  goto label1;
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return REGB0;
}
val_t standard___file___String___strip_extension(val_t p0, val_t p1){
  struct {struct stack_frame_t me; val_t MORE_REG[1];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t REGB2;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 200;
  fra.me.meth = LOCATE_standard___file___String___strip_extension;
  fra.me.has_broke = 0;
  fra.me.REG_size = 2;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  /* ./../lib/standard//file.nit:202 */
  REGB0 = CALL_standard___string___AbstractString___has_suffix(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[1]);
  if (UNTAG_Bool(REGB0)) {
    /* ./../lib/standard//file.nit:203 */
    REGB0 = TAG_Int(0);
    /* ./../lib/standard//collection//array.nit:23 */
    REGB1 = TAG_Bool(ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[0])!=NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_length", LOCATE_standard___collection___array, 23);
    }
    REGB1 = ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[0]);
    REGB2 = TAG_Bool(ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[1])!=NIT_NULL);
    if (UNTAG_Bool(REGB2)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_length", LOCATE_standard___collection___array, 23);
    }
    REGB2 = ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[1]);
    /* ./../lib/standard//kernel.nit:220 */
    REGB2 = TAG_Int(UNTAG_Int(REGB1)-UNTAG_Int(REGB2));
    /* ./../lib/standard//file.nit:203 */
    fra.me.REG[1] = CALL_standard___string___AbstractString___substring(fra.me.REG[0])(fra.me.REG[0], REGB0, REGB2);
    goto label1;
  }
  /* ./../lib/standard//file.nit:205 */
  fra.me.REG[1] = fra.me.REG[0];
  goto label1;
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[1];
}
val_t standard___file___String___basename(val_t p0, val_t p1){
  struct {struct stack_frame_t me; val_t MORE_REG[2];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t REGB2;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 208;
  fra.me.meth = LOCATE_standard___file___String___basename;
  fra.me.has_broke = 0;
  fra.me.REG_size = 3;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  /* ./../lib/standard//file.nit:210 */
  REGB0 = TAG_Char('/');
  REGB1 = TAG_Bool(ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_length", LOCATE_standard___file, 210);
  }
  REGB1 = ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[0]);
  REGB2 = TAG_Int(1);
  /* ./../lib/standard//kernel.nit:220 */
  REGB2 = TAG_Int(UNTAG_Int(REGB1)-UNTAG_Int(REGB2));
  /* ./../lib/standard//file.nit:210 */
  REGB2 = CALL_standard___collection___array___AbstractArrayRead___last_index_of_from(fra.me.REG[0])(fra.me.REG[0], REGB0, REGB2);
  /* ./../lib/standard//file.nit:211 */
  fra.me.REG[2] = fra.me.REG[0];
  /* ./../lib/standard//file.nit:212 */
  REGB0 = TAG_Int(0);
  /* ./../lib/standard//kernel.nit:216 */
  REGB0 = TAG_Bool(UNTAG_Int(REGB2)>=UNTAG_Int(REGB0));
  /* ./../lib/standard//file.nit:212 */
  if (UNTAG_Bool(REGB0)) {
    /* ./../lib/standard//file.nit:213 */
    REGB0 = TAG_Int(1);
    /* ./../lib/standard//kernel.nit:218 */
    REGB0 = TAG_Int(UNTAG_Int(REGB2)+UNTAG_Int(REGB0));
    /* ./../lib/standard//file.nit:213 */
    fra.me.REG[0] = CALL_standard___string___AbstractString___substring_from(fra.me.REG[0])(fra.me.REG[0], REGB0);
    fra.me.REG[2] = fra.me.REG[0];
  }
  /* ./../lib/standard//file.nit:215 */
  fra.me.REG[1] = CALL_standard___file___String___strip_extension(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[1]);
  goto label1;
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[1];
}
val_t standard___file___String___dirname(val_t p0){
  struct {struct stack_frame_t me; val_t MORE_REG[1];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t REGB2;
  val_t tmp;
    static val_t once_value_2; /* Once value */
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 218;
  fra.me.meth = LOCATE_standard___file___String___dirname;
  fra.me.has_broke = 0;
  fra.me.REG_size = 2;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:220 */
  REGB0 = TAG_Char('/');
  REGB1 = TAG_Bool(ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_length", LOCATE_standard___file, 220);
  }
  REGB1 = ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[0]);
  REGB2 = TAG_Int(1);
  /* ./../lib/standard//kernel.nit:220 */
  REGB2 = TAG_Int(UNTAG_Int(REGB1)-UNTAG_Int(REGB2));
  /* ./../lib/standard//file.nit:220 */
  REGB2 = CALL_standard___collection___array___AbstractArrayRead___last_index_of_from(fra.me.REG[0])(fra.me.REG[0], REGB0, REGB2);
  /* ./../lib/standard//file.nit:221 */
  REGB0 = TAG_Int(0);
  /* ./../lib/standard//kernel.nit:216 */
  REGB0 = TAG_Bool(UNTAG_Int(REGB2)>=UNTAG_Int(REGB0));
  /* ./../lib/standard//file.nit:221 */
  if (UNTAG_Bool(REGB0)) {
    /* ./../lib/standard//file.nit:222 */
    REGB0 = TAG_Int(0);
    fra.me.REG[0] = CALL_standard___string___AbstractString___substring(fra.me.REG[0])(fra.me.REG[0], REGB0, REGB2);
    goto label1;
  } else {
    /* ./../lib/standard//file.nit:224 */
    if (!once_value_2) {
      fra.me.REG[1] = BOX_NativeString(".");
      REGB2 = TAG_Int(1);
      fra.me.REG[1] = NEW_String_standard___string___String___with_native(fra.me.REG[1], REGB2);
      once_value_2 = fra.me.REG[1];
      register_static_object(&once_value_2);
    } else fra.me.REG[1] = once_value_2;
    fra.me.REG[1] = fra.me.REG[1];
    fra.me.REG[0] = fra.me.REG[1];
    goto label1;
  }
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t standard___file___String___file_path(val_t p0){
  struct {struct stack_frame_t me; val_t MORE_REG[1];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t REGB2;
  val_t tmp;
  static val_t once_value_2; /* Once value */
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 228;
  fra.me.meth = LOCATE_standard___file___String___file_path;
  fra.me.has_broke = 0;
  fra.me.REG_size = 2;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:230 */
  REGB0 = TAG_Bool(ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_length", LOCATE_standard___file, 230);
  }
  REGB0 = ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[0]);
  /* ./../lib/standard//file.nit:231 */
  REGB1 = TAG_Char('/');
  REGB2 = TAG_Int(1);
  /* ./../lib/standard//kernel.nit:220 */
  REGB2 = TAG_Int(UNTAG_Int(REGB0)-UNTAG_Int(REGB2));
  /* ./../lib/standard//file.nit:231 */
  REGB2 = CALL_standard___collection___array___AbstractArrayRead___last_index_of_from(fra.me.REG[0])(fra.me.REG[0], REGB1, REGB2);
  /* ./../lib/standard//file.nit:232 */
  REGB1 = TAG_Int(0);
  /* ./../lib/standard//kernel.nit:216 */
  REGB1 = TAG_Bool(UNTAG_Int(REGB2)>=UNTAG_Int(REGB1));
  /* ./../lib/standard//file.nit:232 */
  if (UNTAG_Bool(REGB1)) {
    /* ./../lib/standard//file.nit:233 */
    REGB1 = TAG_Int(0);
    fra.me.REG[0] = CALL_standard___string___AbstractString___substring(fra.me.REG[0])(fra.me.REG[0], REGB1, REGB2);
    goto label1;
  }
  /* ./../lib/standard//file.nit:235 */
  if (!once_value_2) {
    fra.me.REG[1] = BOX_NativeString(".");
    REGB2 = TAG_Int(1);
    fra.me.REG[1] = NEW_String_standard___string___String___with_native(fra.me.REG[1], REGB2);
    once_value_2 = fra.me.REG[1];
    register_static_object(&once_value_2);
  } else fra.me.REG[1] = once_value_2;
  fra.me.REG[1] = fra.me.REG[1];
  fra.me.REG[0] = fra.me.REG[1];
  goto label1;
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
void standard___file___String___mkdir(val_t p0){
  struct {struct stack_frame_t me; val_t MORE_REG[3];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t REGB2;
  val_t tmp;
  static val_t once_value_1; /* Once value */
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 238;
  fra.me.meth = LOCATE_standard___file___String___mkdir;
  fra.me.has_broke = 0;
  fra.me.REG_size = 4;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[3] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:241 */
  if (!once_value_1) {
    fra.me.REG[1] = BOX_NativeString("/");
    REGB0 = TAG_Int(1);
    fra.me.REG[1] = NEW_String_standard___string___String___with_native(fra.me.REG[1], REGB0);
    once_value_1 = fra.me.REG[1];
    register_static_object(&once_value_1);
  } else fra.me.REG[1] = once_value_1;
  fra.me.REG[1] = fra.me.REG[1];
  fra.me.REG[1] = CALL_standard___string_search___String___split_with(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[1]);
  /* ./../lib/standard//file.nit:242 */
  fra.me.REG[0] = NEW_Buffer_standard___string___Buffer___init();
  /* ./../lib/standard//file.nit:243 */
  REGB0 = CALL_standard___collection___abstract_collection___Collection___is_empty(fra.me.REG[1])(fra.me.REG[1]);
  if (UNTAG_Bool(REGB0)) {
    goto label2;
  }
  /* ./../lib/standard//file.nit:244 */
  REGB0 = TAG_Int(0);
  /* ./../lib/standard//collection//array.nit:243 */
  fra.me.REG[2] = fra.me.REG[1];
  /* ./../lib/standard//collection//array.nit:245 */
  REGB1 = TAG_Int(0);
  /* ./../lib/standard//kernel.nit:216 */
  REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
  /* ./../lib/standard//collection//array.nit:245 */
  if (UNTAG_Bool(REGB1)) {
    REGB1 = TAG_Bool(ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[2])!=NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_length", LOCATE_standard___collection___array, 245);
    }
    REGB1 = ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[2]);
    /* ./../lib/standard//kernel.nit:215 */
    REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
  } else {
    /* ./../lib/standard//collection//array.nit:245 */
    REGB2 = TAG_Bool(false);
    REGB1 = REGB2;
  }
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Assert %s  failed", "'index'", LOCATE_standard___collection___array, 245);
  }
  /* ./../lib/standard//collection//array.nit:246 */
  fra.me.REG[2] = ATTR_standard___collection___array___Array____items(fra.me.REG[2]);
  REGB1 = TAG_Bool(fra.me.REG[2]==NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
    nit_abort("Reciever is null", NULL, LOCATE_standard___collection___array, 246);
  }
  /* ./../lib/standard//collection//array.nit:654 */
  fra.me.REG[2] = ((Nit_NativeArray)fra.me.REG[2])->val[UNTAG_Int(REGB0)];
  /* ./../lib/standard//collection//array.nit:246 */
  goto label3;
  label3: while(0);
  /* ./../lib/standard//file.nit:244 */
  REGB0 = TAG_Bool(fra.me.REG[2]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
    nit_abort("Reciever is null", NULL, LOCATE_standard___file, 244);
  }
  REGB0 = CALL_standard___collection___abstract_collection___Collection___is_empty(fra.me.REG[2])(fra.me.REG[2]);
  if (UNTAG_Bool(REGB0)) {
    /* ./../lib/standard//file.nit:246 */
    REGB0 = TAG_Char('/');
    CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[0])(fra.me.REG[0], REGB0);
  }
  /* ./../lib/standard//collection//array.nit:234 */
  REGB0 = TAG_Int(0);
  /* ./../lib/standard//collection//array.nit:235 */
  REGB1 = TAG_Bool(ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[1])!=NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_length", LOCATE_standard___collection___array, 235);
  }
  REGB1 = ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[1]);
  /* ./../lib/standard//collection//array.nit:236 */
  fra.me.REG[2] = ATTR_standard___collection___array___Array____items(fra.me.REG[1]);
  /* ./../lib/standard//collection//array.nit:237 */
  while(1) {
    /* ./../lib/standard//collection//array.nit:23 */
    REGB1 = TAG_Bool(ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[1])!=NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_length", LOCATE_standard___collection___array, 23);
    }
    REGB1 = ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[1]);
    /* ./../lib/standard//kernel.nit:215 */
    REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
    /* ./../lib/standard//collection//array.nit:237 */
    if (UNTAG_Bool(REGB1)) {
      /* ./../lib/standard//collection//array.nit:238 */
      REGB1 = TAG_Bool(fra.me.REG[2]==NIT_NULL);
      if (UNTAG_Bool(REGB1)) {
        nit_abort("Reciever is null", NULL, LOCATE_standard___collection___array, 238);
      }
      /* ./../lib/standard//collection//array.nit:654 */
      fra.me.REG[3] = ((Nit_NativeArray)fra.me.REG[2])->val[UNTAG_Int(REGB0)];
      /* ./../lib/standard//file.nit:249 */
      REGB1 = CALL_standard___collection___abstract_collection___Collection___is_empty(fra.me.REG[3])(fra.me.REG[3]);
      if (UNTAG_Bool(REGB1)) {
        goto label4;
      }
      /* ./../lib/standard//file.nit:250 */
      CALL_standard___collection___abstract_collection___Sequence___append(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[3]);
      /* ./../lib/standard//file.nit:251 */
      REGB1 = TAG_Char('/');
      CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[0])(fra.me.REG[0], REGB1);
      /* ./../lib/standard//file.nit:252 */
      fra.me.REG[3] = CALL_standard___string___Object___to_s(fra.me.REG[0])(fra.me.REG[0]);
      fra.me.REG[3] = CALL_standard___string___String___to_cstring(fra.me.REG[3])(fra.me.REG[3]);
      CALL_standard___file___NativeString___file_mkdir(fra.me.REG[3])(fra.me.REG[3]);
      label4: while(0);
      /* ./../lib/standard//collection//array.nit:239 */
      REGB1 = TAG_Int(1);
      /* ./../lib/standard//kernel.nit:218 */
      REGB1 = TAG_Int(UNTAG_Int(REGB0)+UNTAG_Int(REGB1));
      /* ./../lib/standard//collection//array.nit:239 */
      REGB0 = REGB1;
    } else {
      /* ./../lib/standard//collection//array.nit:237 */
      goto label5;
    }
  }
  label5: while(0);
  label2: while(0);
  stack_frame_head = fra.me.prev;
  return;
}
val_t standard___file___NativeString___file_exists(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 258;
  fra.me.meth = LOCATE_standard___file___NativeString___file_exists;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:258 */
  REGB0 = NativeString_file_exists___out(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return REGB0;
}
val_t standard___file___NativeString___file_stat(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 259;
  fra.me.meth = LOCATE_standard___file___NativeString___file_stat;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:259 */
  fra.me.REG[0] = NativeString_file_stat___out(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t standard___file___NativeString___file_mkdir(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 260;
  fra.me.meth = LOCATE_standard___file___NativeString___file_mkdir;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:260 */
  REGB0 = NativeString_file_mkdir___out(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return REGB0;
}
val_t standard___file___NativeString___file_delete(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 261;
  fra.me.meth = LOCATE_standard___file___NativeString___file_delete;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:261 */
  REGB0 = NativeString_file_delete___out(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return REGB0;
}
val_t standard___file___FileStat___mode(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 266;
  fra.me.meth = LOCATE_standard___file___FileStat___mode;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:266 */
  REGB0 = FileStat_mode___out(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return REGB0;
}
val_t standard___file___FileStat___atime(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 268;
  fra.me.meth = LOCATE_standard___file___FileStat___atime;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:268 */
  REGB0 = FileStat_atime___out(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return REGB0;
}
val_t standard___file___FileStat___ctime(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 269;
  fra.me.meth = LOCATE_standard___file___FileStat___ctime;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:269 */
  REGB0 = FileStat_ctime___out(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return REGB0;
}
val_t standard___file___FileStat___mtime(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 270;
  fra.me.meth = LOCATE_standard___file___FileStat___mtime;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:270 */
  REGB0 = FileStat_mtime___out(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return REGB0;
}
val_t standard___file___FileStat___size(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 271;
  fra.me.meth = LOCATE_standard___file___FileStat___size;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:271 */
  REGB0 = FileStat_size___out(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return REGB0;
}
val_t standard___file___NativeFile___io_read(val_t p0, val_t p1, val_t p2){
  struct {struct stack_frame_t me; val_t MORE_REG[1];} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 277;
  fra.me.meth = LOCATE_standard___file___NativeFile___io_read;
  fra.me.has_broke = 0;
  fra.me.REG_size = 2;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  REGB0 = p2;
  /* ./../lib/standard//file.nit:277 */
  REGB0 = NativeFile_io_read___out(fra.me.REG[0], fra.me.REG[1], REGB0);
  stack_frame_head = fra.me.prev;
  return REGB0;
}
val_t standard___file___NativeFile___io_write(val_t p0, val_t p1, val_t p2){
  struct {struct stack_frame_t me; val_t MORE_REG[1];} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 278;
  fra.me.meth = LOCATE_standard___file___NativeFile___io_write;
  fra.me.has_broke = 0;
  fra.me.REG_size = 2;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  REGB0 = p2;
  /* ./../lib/standard//file.nit:278 */
  REGB0 = NativeFile_io_write___out(fra.me.REG[0], fra.me.REG[1], REGB0);
  stack_frame_head = fra.me.prev;
  return REGB0;
}
val_t standard___file___NativeFile___io_close(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 279;
  fra.me.meth = LOCATE_standard___file___NativeFile___io_close;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:279 */
  REGB0 = NativeFile_io_close___out(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return REGB0;
}
val_t standard___file___NativeFile___file_stat(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 280;
  fra.me.meth = LOCATE_standard___file___NativeFile___file_stat;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:280 */
  fra.me.REG[0] = NativeFile_file_stat___out(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t standard___file___NativeFileCapable___io_open_read(val_t p0, val_t p1){
  struct {struct stack_frame_t me; val_t MORE_REG[1];} fra;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 284;
  fra.me.meth = LOCATE_standard___file___NativeFileCapable___io_open_read;
  fra.me.has_broke = 0;
  fra.me.REG_size = 2;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  /* ./../lib/standard//file.nit:284 */
  fra.me.REG[1] = NativeFileCapable_io_open_read___out(fra.me.REG[0], fra.me.REG[1]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[1];
}
val_t standard___file___NativeFileCapable___io_open_write(val_t p0, val_t p1){
  struct {struct stack_frame_t me; val_t MORE_REG[1];} fra;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 285;
  fra.me.meth = LOCATE_standard___file___NativeFileCapable___io_open_write;
  fra.me.has_broke = 0;
  fra.me.REG_size = 2;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  /* ./../lib/standard//file.nit:285 */
  fra.me.REG[1] = NativeFileCapable_io_open_write___out(fra.me.REG[0], fra.me.REG[1]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[1];
}
val_t standard___file___NativeFileCapable___native_stdin(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 286;
  fra.me.meth = LOCATE_standard___file___NativeFileCapable___native_stdin;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:286 */
  fra.me.REG[0] = NativeFileCapable_native_stdin___out(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t standard___file___NativeFileCapable___native_stdout(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 287;
  fra.me.meth = LOCATE_standard___file___NativeFileCapable___native_stdout;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:287 */
  fra.me.REG[0] = NativeFileCapable_native_stdout___out(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t standard___file___NativeFileCapable___native_stderr(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_standard___file;
  fra.me.line = 288;
  fra.me.meth = LOCATE_standard___file___NativeFileCapable___native_stderr;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./../lib/standard//file.nit:288 */
  fra.me.REG[0] = NativeFileCapable_native_stderr___out(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
