#include "nit.common.h"
#define COLOR_standard__abstract_collection__Collection__length 23
#define COLOR_standard__abstract_collection__Collection__is_empty 24
#define COLOR_standard__abstract_collection__Collection__iterator 25
#define COLOR_standard__abstract_collection__Iterator__is_ok 16
#define COLOR_standard__abstract_collection__Iterator__item 17
extern const struct type type_standard__Int;
extern const char FILE_standard__kernel[];
#define COLOR_standard__abstract_collection__Iterator__next 18
#define COLOR_standard__abstract_collection__Iterator__finish 19
#define COLOR_standard__kernel__Object___61d_61d 4
extern const char FILE_standard__abstract_collection[];
#define COLOR_standard__abstract_collection__Collection__has 28
#define COLOR_standard__abstract_collection__Container___item 0
val* NEW_standard__abstract_collection__ContainerIterator(const struct type* type);
#define COLOR_standard__abstract_collection__ContainerIterator__standard__Container___35dE 2
#define COLOR_standard__abstract_collection__ContainerIterator__container_61d 22
#define COLOR_standard__kernel__Object__init 0
#define COLOR_standard__Container___35dE 3
#define COLOR_standard___standard__Container___standard__kernel__Object__init 18
#define COLOR_standard__abstract_collection__ContainerIterator___container 1
#define COLOR_standard__abstract_collection__ContainerIterator___is_ok 0
#define COLOR_standard__Container__standard__abstract_collection__ContainerIterator___35dE 1
#define COLOR_standard__abstract_collection___standard__abstract_collection__ContainerIterator___standard__kernel__Object__init 24
#define COLOR_standard__Collection__standard__SimpleCollection___35dE 9
#define COLOR_standard__abstract_collection__SimpleCollection__add 45
extern const struct type type_standard__Set__nullable__standard__Object;
short int standard___standard__Collection___has_all(val* self, val* p0);
#define COLOR_standard__kernel__Object__hash 12
#define COLOR_standard__abstract_collection__MapRead__has_key 18
#define COLOR_standard__abstract_collection__MapRead___91d_93d 19
extern const struct type type_standard__MapRead__nullable__standard__Object__nullable__standard__Object;
#define COLOR_standard__abstract_collection__MapRead__length 16
#define COLOR_standard__abstract_collection__MapRead__iterator 17
#define COLOR_standard__abstract_collection__MapIterator__is_ok 16
#define COLOR_standard__abstract_collection__MapIterator__key 17
#define COLOR_standard__abstract_collection__MapIterator__item 18
#define COLOR_standard__kernel__Object___33d_61d 1
#define COLOR_standard__abstract_collection__MapIterator__next 19
#define COLOR_standard__abstract_collection__MapKeysIterator___original_iterator 0
#define COLOR_standard__MapIterator__standard__MapKeysIterator___35dK__standard__MapKeysIterator___35dV 1
#define COLOR_standard___standard__MapKeysIterator___standard__kernel__Object__init 24
#define COLOR_standard__abstract_collection__MapValuesIterator___original_iterator 0
#define COLOR_standard__MapIterator__standard__MapValuesIterator___35dK__standard__MapValuesIterator___35dV 1
#define COLOR_standard___standard__MapValuesIterator___standard__kernel__Object__init 24
#define COLOR_standard__abstract_collection__SequenceRead___91d_93d 31
#define COLOR_standard__abstract_collection__SequenceRead__index_of_from 34
#define COLOR_standard__abstract_collection__SequenceRead__last_index_of_from 37
#define COLOR_standard__abstract_collection__IndexedIterator__index 22
extern const struct type type_standard__SequenceRead__nullable__standard__Object;
#define COLOR_standard__Sequence___35dE 7
#define COLOR_standard__abstract_collection__Sequence___91d_93d_61d 47
#define COLOR_standard__abstract_collection__Sequence__push 46
#define COLOR_standard__Collection__standard__Sequence___35dE 8
#define COLOR_standard__abstract_collection__SimpleCollection__add_all 44
#define COLOR_standard__abstract_collection__Sequence__insert_all 53
#define COLOR_standard__abstract_collection__Sequence__insert 55
val* NEW_standard__abstract_collection__CoupleMapIterator(const struct type* type);
#define COLOR_standard__abstract_collection__CoupleMapIterator__standard__CoupleMap___35dK__standard__CoupleMap___35dV 6
val* standard___standard__ArrayMap___standard__abstract_collection__CoupleMap__couple_iterator(val* self);
#define COLOR_standard__abstract_collection__CoupleMapIterator__iter_61d 21
val* standard___standard__ArrayMap___standard__abstract_collection__CoupleMap__couple_at(val* self, val* p0);
#define COLOR_standard__abstract_collection__CoupleMapIterator___iter 0
#define COLOR_standard__abstract_collection__Couple___second 1
#define COLOR_standard__abstract_collection__Couple___first 0
#define COLOR_standard__Iterator__standard__Couple__standard__abstract_collection__CoupleMapIterator___35dK__standard__abstract_collection__CoupleMapIterator___35dV 0
#define COLOR_standard__abstract_collection___standard__abstract_collection__CoupleMapIterator___standard__kernel__Object__init 22
#define COLOR_standard__Couple___35dF 0
#define COLOR_standard__Couple___35dS 1
#define COLOR_standard___standard__Couple___standard__kernel__Object__init 20
