#include "nit.common.h"
void stream__IOS__close(val* self);
long stream__IStream__read_char(val* self);
val* NEW_string__Buffer(const struct type* type);
extern const struct type type_string__Buffer;
extern const int COLOR_string__Buffer__with_capacity;
extern const struct type type_kernel__Int;
extern const int COLOR_stream__IStream__eof;
extern const int COLOR_stream__IStream__read_char;
extern const int COLOR_abstract_collection__SimpleCollection__add;
extern const int COLOR_string__Object__to_s;
val* stream__IStream__read(val* self, long p0);
extern const int COLOR_string__Buffer__init;
extern const int COLOR_stream__IStream__append_line_to;
val* stream__IStream__read_line(val* self);
val* stream__IStream__read_all(val* self);
extern const int COLOR_abstract_collection__Sequence__push;
void stream__IStream__append_line_to(val* self, val* p0);
short int stream__IStream__eof(val* self);
void stream__OStream__write(val* self, val* p0);
short int stream__OStream__is_writable(val* self);
extern const int COLOR_stream__BufferedIStream___buffer_pos;
extern const int COLOR_stream__BufferedIStream___buffer;
extern const int COLOR_abstract_collection__Collection__length;
extern const int COLOR_stream__BufferedIStream__fill_buffer;
extern const int COLOR_abstract_collection__SequenceRead___91d_93d;
long stream__BufferedIStream__read_char(val* self);
val* stream__BufferedIStream__read(val* self, long p0);
val* stream__BufferedIStream__read_all(val* self);
extern const struct class class_kernel__Char;
extern const int COLOR_array__AbstractArray__enlarge;
extern const int COLOR_stream__BufferedIStream__end_reached;
void stream__BufferedIStream__append_line_to(val* self, val* p0);
short int stream__BufferedIStream__eof(val* self);
void stream__BufferedIStream__fill_buffer(val* self);
short int stream__BufferedIStream__end_reached(val* self);
void stream__BufferedIStream__prepare_buffer(val* self, long p0);
void stream__BufferedIStream__init(val* self);
extern const int COLOR_stream__FDStream___64dfd;
long stream__FDStream__fd(val* self);
void stream__FDStream__fd_61d(val* self, long p0);
extern const int COLOR_stream__FDStream__fd;
extern const int COLOR_stream__FDStream__native_close;
void stream__FDStream__close(val* self);
#include "stream_nit.h"
long stream__FDStream__native_close(val* self, long p0);
long stream__FDStream__native_read_char(val* self, long p0);
long stream__FDStream__native_read(val* self, long p0, char* p1, long p2);
long stream__FDStream__native_write(val* self, long p0, char* p1, long p2);
long stream__FDStream__native_write_char(val* self, long p0, char p1);
extern const int COLOR_stream__FDStream__fd_61d;
void stream__FDStream__init(val* self, long p0);
extern const int COLOR_stream__FDIStream___64deof;
short int stream__FDIStream__eof(val* self);
void stream__FDIStream__eof_61d(val* self, short int p0);
extern const int COLOR_stream__FDStream__native_read_char;
extern const int COLOR_stream__FDIStream__eof_61d;
long stream__FDIStream__read_char(val* self);
extern const int COLOR_stream__FDStream__init;
void stream__FDIStream__init(val* self, long p0);
extern const int COLOR_stream__FDOStream___64dis_writable;
short int stream__FDOStream__is_writable(val* self);
void stream__FDOStream__is_writable_61d(val* self, short int p0);
extern const int COLOR_string__String__to_cstring;
extern const int COLOR_stream__FDStream__native_write;
extern const int COLOR_stream__FDOStream__is_writable_61d;
void stream__FDOStream__write(val* self, val* p0);
void stream__FDOStream__init(val* self, long p0);
extern const int COLOR_stream__FDIStream__init;
extern const int COLOR_stream__FDOStream__init;
void stream__FDIOStream__init(val* self, long p0);
val* NEW_array__Array(const struct type* type);
extern const struct type type_array__Arraykernel__Int;
extern const int COLOR_array__Array__init;
val* NEW_hash_collection__HashMap(const struct type* type);
extern const struct type type_hash_collection__HashMapkernel__Intstream__FDStream;
extern const int COLOR_hash_collection__HashMap__init;
extern const int COLOR_abstract_collection__Collection__iterator;
extern const int COLOR_abstract_collection__Iterator__is_ok;
extern const int COLOR_abstract_collection__Iterator__item;
extern const struct type type_stream__FDIStream;
extern const struct type type_stream__FDOStream;
extern const int COLOR_abstract_collection__Map___91d_93d_61d;
extern const int COLOR_abstract_collection__Iterator__next;
extern const int COLOR_stream__Object__intern_poll;
extern const int COLOR_abstract_collection__MapRead___91d_93d;
val* stream__Object__poll(val* self, val* p0);
val* stream__Object__intern_poll(val* self, val* p0, val* p1);
extern const int COLOR_stream__StringOStream___64dcontent;
val* stream__StringOStream__content(val* self);
void stream__StringOStream__content_61d(val* self, val* p0);
extern const int COLOR_stream__StringOStream__content;
val* stream__StringOStream__to_s(val* self);
short int stream__StringOStream__is_writable(val* self);
void stream__StringOStream__write(val* self, val* p0);
void stream__StringOStream__init(val* self);
