/* This C file is generated by NIT to compile module toolcontext. */
#include "toolcontext._sep.h"
val_t toolcontext___Message___location(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_toolcontext;
  fra.me.line = 29;
  fra.me.meth = LOCATE_toolcontext___Message___location;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.nitni_local_ref_head = NULL;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* toolcontext.nit:29 */
  fra.me.REG[0] = ATTR_toolcontext___Message____location(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t toolcontext___Message___text(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_toolcontext;
  fra.me.line = 30;
  fra.me.meth = LOCATE_toolcontext___Message___text;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.nitni_local_ref_head = NULL;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* toolcontext.nit:30 */
  REGB0 = TAG_Bool(ATTR_toolcontext___Message____text(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_text", LOCATE_toolcontext, 30);
  }
  fra.me.REG[0] = ATTR_toolcontext___Message____text(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t toolcontext___Message_____l(val_t p0, val_t p1){
  struct {struct stack_frame_t me; val_t MORE_REG[3];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t REGB2;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_toolcontext;
  fra.me.line = 32;
  fra.me.meth = LOCATE_toolcontext___Message_____l;
  fra.me.has_broke = 0;
  fra.me.REG_size = 4;
  fra.me.nitni_local_ref_head = NULL;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[3] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  REGB0 = TAG_Bool(VAL_ISA(fra.me.REG[1], VTCOLOR_standard___kernel___Comparable___OTHER(fra.me.REG[0]), VTID_standard___kernel___Comparable___OTHER(fra.me.REG[0]))) /*cast OTHER*/;
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Cast failed", NULL, LOCATE_toolcontext, 0);
  }
  /* toolcontext.nit:32 */
  fra.me.REG[2] = fra.me.REG[0];
  /* toolcontext.nit:33 */
  fra.me.REG[3] = CALL_toolcontext___Message___location(fra.me.REG[2])(fra.me.REG[2]);
  REGB0 = TAG_Bool(fra.me.REG[3]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    REGB1 = TAG_Bool(fra.me.REG[3]==NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
      REGB1 = TAG_Bool(false);
      REGB0 = REGB1;
    } else {
      REGB1 = CALL_standard___kernel___Object_____eqeq(fra.me.REG[3])(fra.me.REG[3], NIT_NULL);
      REGB0 = REGB1;
    }
  }
  if (UNTAG_Bool(REGB0)) {
    REGB0 = TAG_Bool(true);
    goto label1;
  }
  /* toolcontext.nit:34 */
  fra.me.REG[3] = CALL_toolcontext___Message___location(fra.me.REG[1])(fra.me.REG[1]);
  REGB1 = TAG_Bool(fra.me.REG[3]==NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
  } else {
    REGB2 = TAG_Bool(fra.me.REG[3]==NIT_NULL);
    if (UNTAG_Bool(REGB2)) {
      REGB2 = TAG_Bool(false);
      REGB1 = REGB2;
    } else {
      REGB2 = CALL_standard___kernel___Object_____eqeq(fra.me.REG[3])(fra.me.REG[3], NIT_NULL);
      REGB1 = REGB2;
    }
  }
  if (UNTAG_Bool(REGB1)) {
    REGB1 = TAG_Bool(false);
    REGB0 = REGB1;
    goto label1;
  }
  /* toolcontext.nit:36 */
  fra.me.REG[2] = CALL_toolcontext___Message___location(fra.me.REG[2])(fra.me.REG[2]);
  REGB1 = TAG_Bool(fra.me.REG[2]!=NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Cast failed", NULL, LOCATE_toolcontext, 36);
  }
  fra.me.REG[1] = CALL_toolcontext___Message___location(fra.me.REG[1])(fra.me.REG[1]);
  REGB1 = TAG_Bool(fra.me.REG[1]!=NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Cast failed", NULL, LOCATE_toolcontext, 36);
  }
  REGB1 = TAG_Bool(fra.me.REG[2]==NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
    nit_abort("Reciever is null", NULL, LOCATE_toolcontext, 36);
  }
  REGB1 = CALL_standard___kernel___Comparable_____l(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[1]);
  REGB0 = REGB1;
  goto label1;
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return REGB0;
}
val_t toolcontext___Message___to_s(val_t p0){
  struct {struct stack_frame_t me; val_t MORE_REG[4];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t tmp;
    static val_t once_value_2; /* Once value */
    static val_t once_value_3; /* Once value */
    static val_t once_value_4; /* Once value */
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_toolcontext;
  fra.me.line = 39;
  fra.me.meth = LOCATE_toolcontext___Message___to_s;
  fra.me.has_broke = 0;
  fra.me.REG_size = 5;
  fra.me.nitni_local_ref_head = NULL;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[3] = NIT_NULL;
  fra.me.REG[4] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* toolcontext.nit:41 */
  fra.me.REG[1] = CALL_toolcontext___Message___location(fra.me.REG[0])(fra.me.REG[0]);
  /* toolcontext.nit:42 */
  REGB0 = TAG_Bool(fra.me.REG[1]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    REGB1 = TAG_Bool(fra.me.REG[1]==NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
      REGB1 = TAG_Bool(false);
      REGB0 = REGB1;
    } else {
      REGB1 = CALL_standard___kernel___Object_____eqeq(fra.me.REG[1])(fra.me.REG[1], NIT_NULL);
      REGB0 = REGB1;
    }
  }
  if (UNTAG_Bool(REGB0)) {
    /* toolcontext.nit:43 */
    fra.me.REG[2] = CALL_toolcontext___Message___text(fra.me.REG[0])(fra.me.REG[0]);
    goto label1;
  } else {
    /* toolcontext.nit:45 */
    REGB0 = TAG_Int(5);
    fra.me.REG[3] = NEW_Array_standard___collection___array___Array___with_capacity(REGB0);
    if (!once_value_2) {
      fra.me.REG[4] = BOX_NativeString("");
      REGB0 = TAG_Int(0);
      fra.me.REG[4] = NEW_String_standard___string___String___with_native(fra.me.REG[4], REGB0);
      once_value_2 = fra.me.REG[4];
      register_static_object(&once_value_2);
    } else fra.me.REG[4] = once_value_2;
    fra.me.REG[4] = fra.me.REG[4];
    CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[3])(fra.me.REG[3], fra.me.REG[4]);
    fra.me.REG[1] = CALL_standard___string___Object___to_s(fra.me.REG[1])(fra.me.REG[1]);
    CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[3])(fra.me.REG[3], fra.me.REG[1]);
    if (!once_value_3) {
      fra.me.REG[1] = BOX_NativeString(": ");
      REGB0 = TAG_Int(2);
      fra.me.REG[1] = NEW_String_standard___string___String___with_native(fra.me.REG[1], REGB0);
      once_value_3 = fra.me.REG[1];
      register_static_object(&once_value_3);
    } else fra.me.REG[1] = once_value_3;
    fra.me.REG[1] = fra.me.REG[1];
    CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[3])(fra.me.REG[3], fra.me.REG[1]);
    fra.me.REG[0] = CALL_toolcontext___Message___text(fra.me.REG[0])(fra.me.REG[0]);
    CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[3])(fra.me.REG[3], fra.me.REG[0]);
    if (!once_value_4) {
      fra.me.REG[0] = BOX_NativeString("");
      REGB0 = TAG_Int(0);
      fra.me.REG[0] = NEW_String_standard___string___String___with_native(fra.me.REG[0], REGB0);
      once_value_4 = fra.me.REG[0];
      register_static_object(&once_value_4);
    } else fra.me.REG[0] = once_value_4;
    fra.me.REG[0] = fra.me.REG[0];
    CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[3])(fra.me.REG[3], fra.me.REG[0]);
    fra.me.REG[3] = CALL_standard___string___Object___to_s(fra.me.REG[3])(fra.me.REG[3]);
    fra.me.REG[2] = fra.me.REG[3];
    goto label1;
  }
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[2];
}
val_t toolcontext___Message___to_color_string(val_t p0){
  struct {struct stack_frame_t me; val_t MORE_REG[6];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t tmp;
  static val_t once_value_1; /* Once value */
  static val_t once_value_2; /* Once value */
  static val_t once_value_3; /* Once value */
  static val_t once_value_4; /* Once value */
  static val_t once_value_5; /* Once value */
  static val_t once_value_6; /* Once value */
  static val_t once_value_7; /* Once value */
  static val_t once_value_8; /* Once value */
  static val_t once_value_9; /* Once value */
  static val_t once_value_10; /* Once value */
      static val_t once_value_12; /* Once value */
      static val_t once_value_13; /* Once value */
      static val_t once_value_14; /* Once value */
      static val_t once_value_15; /* Once value */
      static val_t once_value_16; /* Once value */
      static val_t once_value_17; /* Once value */
      static val_t once_value_18; /* Once value */
      static val_t once_value_19; /* Once value */
      static val_t once_value_20; /* Once value */
      static val_t once_value_21; /* Once value */
      static val_t once_value_22; /* Once value */
      static val_t once_value_23; /* Once value */
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_toolcontext;
  fra.me.line = 49;
  fra.me.meth = LOCATE_toolcontext___Message___to_color_string;
  fra.me.has_broke = 0;
  fra.me.REG_size = 7;
  fra.me.nitni_local_ref_head = NULL;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[3] = NIT_NULL;
  fra.me.REG[4] = NIT_NULL;
  fra.me.REG[5] = NIT_NULL;
  fra.me.REG[6] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* toolcontext.nit:51 */
  REGB0 = TAG_Int(27);
  /* ../lib/standard/kernel.nit:297 */
  REGB0 = TAG_Char(UNTAG_Int(REGB0));
  /* toolcontext.nit:52 */
  REGB1 = TAG_Int(3);
  fra.me.REG[1] = NEW_Array_standard___collection___array___Array___with_capacity(REGB1);
  if (!once_value_1) {
    fra.me.REG[2] = BOX_NativeString("");
    REGB1 = TAG_Int(0);
    fra.me.REG[2] = NEW_String_standard___string___String___with_native(fra.me.REG[2], REGB1);
    once_value_1 = fra.me.REG[2];
    register_static_object(&once_value_1);
  } else fra.me.REG[2] = once_value_1;
  fra.me.REG[2] = fra.me.REG[2];
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
  fra.me.REG[2] = CALL_standard___string___Object___to_s(REGB0)(REGB0);
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
  if (!once_value_2) {
    fra.me.REG[2] = BOX_NativeString("[0;31m");
    REGB1 = TAG_Int(6);
    fra.me.REG[2] = NEW_String_standard___string___String___with_native(fra.me.REG[2], REGB1);
    once_value_2 = fra.me.REG[2];
    register_static_object(&once_value_2);
  } else fra.me.REG[2] = once_value_2;
  fra.me.REG[2] = fra.me.REG[2];
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
  fra.me.REG[1] = CALL_standard___string___Object___to_s(fra.me.REG[1])(fra.me.REG[1]);
  /* toolcontext.nit:53 */
  REGB1 = TAG_Int(3);
  fra.me.REG[1] = NEW_Array_standard___collection___array___Array___with_capacity(REGB1);
  if (!once_value_3) {
    fra.me.REG[2] = BOX_NativeString("");
    REGB1 = TAG_Int(0);
    fra.me.REG[2] = NEW_String_standard___string___String___with_native(fra.me.REG[2], REGB1);
    once_value_3 = fra.me.REG[2];
    register_static_object(&once_value_3);
  } else fra.me.REG[2] = once_value_3;
  fra.me.REG[2] = fra.me.REG[2];
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
  fra.me.REG[2] = CALL_standard___string___Object___to_s(REGB0)(REGB0);
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
  if (!once_value_4) {
    fra.me.REG[2] = BOX_NativeString("[1;31m");
    REGB1 = TAG_Int(6);
    fra.me.REG[2] = NEW_String_standard___string___String___with_native(fra.me.REG[2], REGB1);
    once_value_4 = fra.me.REG[2];
    register_static_object(&once_value_4);
  } else fra.me.REG[2] = once_value_4;
  fra.me.REG[2] = fra.me.REG[2];
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
  fra.me.REG[1] = CALL_standard___string___Object___to_s(fra.me.REG[1])(fra.me.REG[1]);
  /* toolcontext.nit:54 */
  REGB1 = TAG_Int(3);
  fra.me.REG[1] = NEW_Array_standard___collection___array___Array___with_capacity(REGB1);
  if (!once_value_5) {
    fra.me.REG[2] = BOX_NativeString("");
    REGB1 = TAG_Int(0);
    fra.me.REG[2] = NEW_String_standard___string___String___with_native(fra.me.REG[2], REGB1);
    once_value_5 = fra.me.REG[2];
    register_static_object(&once_value_5);
  } else fra.me.REG[2] = once_value_5;
  fra.me.REG[2] = fra.me.REG[2];
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
  fra.me.REG[2] = CALL_standard___string___Object___to_s(REGB0)(REGB0);
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
  if (!once_value_6) {
    fra.me.REG[2] = BOX_NativeString("[0;32m");
    REGB1 = TAG_Int(6);
    fra.me.REG[2] = NEW_String_standard___string___String___with_native(fra.me.REG[2], REGB1);
    once_value_6 = fra.me.REG[2];
    register_static_object(&once_value_6);
  } else fra.me.REG[2] = once_value_6;
  fra.me.REG[2] = fra.me.REG[2];
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
  fra.me.REG[1] = CALL_standard___string___Object___to_s(fra.me.REG[1])(fra.me.REG[1]);
  /* toolcontext.nit:55 */
  REGB1 = TAG_Int(3);
  fra.me.REG[1] = NEW_Array_standard___collection___array___Array___with_capacity(REGB1);
  if (!once_value_7) {
    fra.me.REG[2] = BOX_NativeString("");
    REGB1 = TAG_Int(0);
    fra.me.REG[2] = NEW_String_standard___string___String___with_native(fra.me.REG[2], REGB1);
    once_value_7 = fra.me.REG[2];
    register_static_object(&once_value_7);
  } else fra.me.REG[2] = once_value_7;
  fra.me.REG[2] = fra.me.REG[2];
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
  fra.me.REG[2] = CALL_standard___string___Object___to_s(REGB0)(REGB0);
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
  if (!once_value_8) {
    fra.me.REG[2] = BOX_NativeString("[0;33m");
    REGB1 = TAG_Int(6);
    fra.me.REG[2] = NEW_String_standard___string___String___with_native(fra.me.REG[2], REGB1);
    once_value_8 = fra.me.REG[2];
    register_static_object(&once_value_8);
  } else fra.me.REG[2] = once_value_8;
  fra.me.REG[2] = fra.me.REG[2];
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
  fra.me.REG[1] = CALL_standard___string___Object___to_s(fra.me.REG[1])(fra.me.REG[1]);
  /* toolcontext.nit:56 */
  REGB1 = TAG_Int(3);
  fra.me.REG[2] = NEW_Array_standard___collection___array___Array___with_capacity(REGB1);
  if (!once_value_9) {
    fra.me.REG[3] = BOX_NativeString("");
    REGB1 = TAG_Int(0);
    fra.me.REG[3] = NEW_String_standard___string___String___with_native(fra.me.REG[3], REGB1);
    once_value_9 = fra.me.REG[3];
    register_static_object(&once_value_9);
  } else fra.me.REG[3] = once_value_9;
  fra.me.REG[3] = fra.me.REG[3];
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[3]);
  fra.me.REG[3] = CALL_standard___string___Object___to_s(REGB0)(REGB0);
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[3]);
  if (!once_value_10) {
    fra.me.REG[3] = BOX_NativeString("[0m");
    REGB0 = TAG_Int(3);
    fra.me.REG[3] = NEW_String_standard___string___String___with_native(fra.me.REG[3], REGB0);
    once_value_10 = fra.me.REG[3];
    register_static_object(&once_value_10);
  } else fra.me.REG[3] = once_value_10;
  fra.me.REG[3] = fra.me.REG[3];
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[3]);
  fra.me.REG[2] = CALL_standard___string___Object___to_s(fra.me.REG[2])(fra.me.REG[2]);
  /* toolcontext.nit:58 */
  fra.me.REG[3] = CALL_toolcontext___Message___location(fra.me.REG[0])(fra.me.REG[0]);
  /* toolcontext.nit:59 */
  REGB0 = TAG_Bool(fra.me.REG[3]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    REGB1 = TAG_Bool(fra.me.REG[3]==NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
      REGB1 = TAG_Bool(false);
      REGB0 = REGB1;
    } else {
      REGB1 = CALL_standard___kernel___Object_____eqeq(fra.me.REG[3])(fra.me.REG[3], NIT_NULL);
      REGB0 = REGB1;
    }
  }
  if (UNTAG_Bool(REGB0)) {
    /* toolcontext.nit:60 */
    fra.me.REG[4] = CALL_toolcontext___Message___text(fra.me.REG[0])(fra.me.REG[0]);
    goto label11;
  } else {
    /* toolcontext.nit:61 */
    REGB0 = TAG_Bool(fra.me.REG[3]==NIT_NULL);
    if (UNTAG_Bool(REGB0)) {
      nit_abort("Reciever is null", NULL, LOCATE_toolcontext, 61);
    }
    fra.me.REG[5] = CALL_location___Location___file(fra.me.REG[3])(fra.me.REG[3]);
    REGB0 = TAG_Bool(fra.me.REG[5]==NIT_NULL);
    if (UNTAG_Bool(REGB0)) {
    } else {
      REGB1 = TAG_Bool(fra.me.REG[5]==NIT_NULL);
      if (UNTAG_Bool(REGB1)) {
        REGB1 = TAG_Bool(false);
        REGB0 = REGB1;
      } else {
        REGB1 = CALL_standard___kernel___Object_____eqeq(fra.me.REG[5])(fra.me.REG[5], NIT_NULL);
        REGB0 = REGB1;
      }
    }
    if (UNTAG_Bool(REGB0)) {
      /* toolcontext.nit:62 */
      REGB0 = TAG_Int(9);
      fra.me.REG[5] = NEW_Array_standard___collection___array___Array___with_capacity(REGB0);
      if (!once_value_12) {
        fra.me.REG[6] = BOX_NativeString("");
        REGB0 = TAG_Int(0);
        fra.me.REG[6] = NEW_String_standard___string___String___with_native(fra.me.REG[6], REGB0);
        once_value_12 = fra.me.REG[6];
        register_static_object(&once_value_12);
      } else fra.me.REG[6] = once_value_12;
      fra.me.REG[6] = fra.me.REG[6];
      CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[5])(fra.me.REG[5], fra.me.REG[6]);
      CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[5])(fra.me.REG[5], fra.me.REG[1]);
      if (!once_value_13) {
        fra.me.REG[6] = BOX_NativeString("");
        REGB0 = TAG_Int(0);
        fra.me.REG[6] = NEW_String_standard___string___String___with_native(fra.me.REG[6], REGB0);
        once_value_13 = fra.me.REG[6];
        register_static_object(&once_value_13);
      } else fra.me.REG[6] = once_value_13;
      fra.me.REG[6] = fra.me.REG[6];
      CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[5])(fra.me.REG[5], fra.me.REG[6]);
      fra.me.REG[6] = CALL_standard___string___Object___to_s(fra.me.REG[3])(fra.me.REG[3]);
      CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[5])(fra.me.REG[5], fra.me.REG[6]);
      if (!once_value_14) {
        fra.me.REG[6] = BOX_NativeString("");
        REGB0 = TAG_Int(0);
        fra.me.REG[6] = NEW_String_standard___string___String___with_native(fra.me.REG[6], REGB0);
        once_value_14 = fra.me.REG[6];
        register_static_object(&once_value_14);
      } else fra.me.REG[6] = once_value_14;
      fra.me.REG[6] = fra.me.REG[6];
      CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[5])(fra.me.REG[5], fra.me.REG[6]);
      CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[5])(fra.me.REG[5], fra.me.REG[2]);
      if (!once_value_15) {
        fra.me.REG[6] = BOX_NativeString(": ");
        REGB0 = TAG_Int(2);
        fra.me.REG[6] = NEW_String_standard___string___String___with_native(fra.me.REG[6], REGB0);
        once_value_15 = fra.me.REG[6];
        register_static_object(&once_value_15);
      } else fra.me.REG[6] = once_value_15;
      fra.me.REG[6] = fra.me.REG[6];
      CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[5])(fra.me.REG[5], fra.me.REG[6]);
      fra.me.REG[6] = CALL_toolcontext___Message___text(fra.me.REG[0])(fra.me.REG[0]);
      CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[5])(fra.me.REG[5], fra.me.REG[6]);
      if (!once_value_16) {
        fra.me.REG[6] = BOX_NativeString("");
        REGB0 = TAG_Int(0);
        fra.me.REG[6] = NEW_String_standard___string___String___with_native(fra.me.REG[6], REGB0);
        once_value_16 = fra.me.REG[6];
        register_static_object(&once_value_16);
      } else fra.me.REG[6] = once_value_16;
      fra.me.REG[6] = fra.me.REG[6];
      CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[5])(fra.me.REG[5], fra.me.REG[6]);
      fra.me.REG[5] = CALL_standard___string___Object___to_s(fra.me.REG[5])(fra.me.REG[5]);
      fra.me.REG[4] = fra.me.REG[5];
      goto label11;
    } else {
      /* toolcontext.nit:64 */
      REGB0 = TAG_Int(11);
      fra.me.REG[5] = NEW_Array_standard___collection___array___Array___with_capacity(REGB0);
      if (!once_value_17) {
        fra.me.REG[6] = BOX_NativeString("");
        REGB0 = TAG_Int(0);
        fra.me.REG[6] = NEW_String_standard___string___String___with_native(fra.me.REG[6], REGB0);
        once_value_17 = fra.me.REG[6];
        register_static_object(&once_value_17);
      } else fra.me.REG[6] = once_value_17;
      fra.me.REG[6] = fra.me.REG[6];
      CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[5])(fra.me.REG[5], fra.me.REG[6]);
      CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[5])(fra.me.REG[5], fra.me.REG[1]);
      if (!once_value_18) {
        fra.me.REG[1] = BOX_NativeString("");
        REGB0 = TAG_Int(0);
        fra.me.REG[1] = NEW_String_standard___string___String___with_native(fra.me.REG[1], REGB0);
        once_value_18 = fra.me.REG[1];
        register_static_object(&once_value_18);
      } else fra.me.REG[1] = once_value_18;
      fra.me.REG[1] = fra.me.REG[1];
      CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[5])(fra.me.REG[5], fra.me.REG[1]);
      fra.me.REG[1] = CALL_standard___string___Object___to_s(fra.me.REG[3])(fra.me.REG[3]);
      CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[5])(fra.me.REG[5], fra.me.REG[1]);
      if (!once_value_19) {
        fra.me.REG[1] = BOX_NativeString("");
        REGB0 = TAG_Int(0);
        fra.me.REG[1] = NEW_String_standard___string___String___with_native(fra.me.REG[1], REGB0);
        once_value_19 = fra.me.REG[1];
        register_static_object(&once_value_19);
      } else fra.me.REG[1] = once_value_19;
      fra.me.REG[1] = fra.me.REG[1];
      CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[5])(fra.me.REG[5], fra.me.REG[1]);
      CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[5])(fra.me.REG[5], fra.me.REG[2]);
      if (!once_value_20) {
        fra.me.REG[2] = BOX_NativeString(": ");
        REGB0 = TAG_Int(2);
        fra.me.REG[2] = NEW_String_standard___string___String___with_native(fra.me.REG[2], REGB0);
        once_value_20 = fra.me.REG[2];
        register_static_object(&once_value_20);
      } else fra.me.REG[2] = once_value_20;
      fra.me.REG[2] = fra.me.REG[2];
      CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[5])(fra.me.REG[5], fra.me.REG[2]);
      fra.me.REG[0] = CALL_toolcontext___Message___text(fra.me.REG[0])(fra.me.REG[0]);
      CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[5])(fra.me.REG[5], fra.me.REG[0]);
      if (!once_value_21) {
        fra.me.REG[0] = BOX_NativeString("\n");
        REGB0 = TAG_Int(1);
        fra.me.REG[0] = NEW_String_standard___string___String___with_native(fra.me.REG[0], REGB0);
        once_value_21 = fra.me.REG[0];
        register_static_object(&once_value_21);
      } else fra.me.REG[0] = once_value_21;
      fra.me.REG[0] = fra.me.REG[0];
      CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[5])(fra.me.REG[5], fra.me.REG[0]);
      if (!once_value_22) {
        fra.me.REG[0] = BOX_NativeString("1;31");
        REGB0 = TAG_Int(4);
        fra.me.REG[0] = NEW_String_standard___string___String___with_native(fra.me.REG[0], REGB0);
        once_value_22 = fra.me.REG[0];
        register_static_object(&once_value_22);
      } else fra.me.REG[0] = once_value_22;
      fra.me.REG[0] = fra.me.REG[0];
      REGB0 = TAG_Bool(fra.me.REG[3]==NIT_NULL);
      if (UNTAG_Bool(REGB0)) {
        nit_abort("Reciever is null", NULL, LOCATE_toolcontext, 64);
      }
      fra.me.REG[0] = CALL_location___Location___colored_line(fra.me.REG[3])(fra.me.REG[3], fra.me.REG[0]);
      CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[5])(fra.me.REG[5], fra.me.REG[0]);
      if (!once_value_23) {
        fra.me.REG[0] = BOX_NativeString("");
        REGB0 = TAG_Int(0);
        fra.me.REG[0] = NEW_String_standard___string___String___with_native(fra.me.REG[0], REGB0);
        once_value_23 = fra.me.REG[0];
        register_static_object(&once_value_23);
      } else fra.me.REG[0] = once_value_23;
      fra.me.REG[0] = fra.me.REG[0];
      CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[5])(fra.me.REG[5], fra.me.REG[0]);
      fra.me.REG[5] = CALL_standard___string___Object___to_s(fra.me.REG[5])(fra.me.REG[5]);
      fra.me.REG[4] = fra.me.REG[5];
      goto label11;
    }
  }
  label11: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[4];
}
void toolcontext___Message___init(val_t p0, val_t p1, val_t p2, int* init_table){
  int itpos0 = VAL2OBJ(p0)->vft[INIT_TABLE_POS_toolcontext___Message].i;
  struct {struct stack_frame_t me; val_t MORE_REG[2];} fra;
  val_t tmp;
  if (init_table[itpos0]) return;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_toolcontext;
  fra.me.line = 0;
  fra.me.meth = LOCATE_toolcontext___Message___init;
  fra.me.has_broke = 0;
  fra.me.REG_size = 3;
  fra.me.nitni_local_ref_head = NULL;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  fra.me.REG[2] = p2;
  ATTR_toolcontext___Message____location(fra.me.REG[0]) = fra.me.REG[1];
  ATTR_toolcontext___Message____text(fra.me.REG[0]) = fra.me.REG[2];
  stack_frame_head = fra.me.prev;
  init_table[itpos0] = 1;
  return;
}
val_t toolcontext___ToolContext___error_count(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_toolcontext;
  fra.me.line = 71;
  fra.me.meth = LOCATE_toolcontext___ToolContext___error_count;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.nitni_local_ref_head = NULL;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* toolcontext.nit:71 */
  REGB0 = TAG_Bool(ATTR_toolcontext___ToolContext____error_count(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_error_count", LOCATE_toolcontext, 71);
  }
  REGB0 = ATTR_toolcontext___ToolContext____error_count(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return REGB0;
}
val_t toolcontext___ToolContext___warning_count(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_toolcontext;
  fra.me.line = 74;
  fra.me.meth = LOCATE_toolcontext___ToolContext___warning_count;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.nitni_local_ref_head = NULL;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* toolcontext.nit:74 */
  REGB0 = TAG_Bool(ATTR_toolcontext___ToolContext____warning_count(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_warning_count", LOCATE_toolcontext, 74);
  }
  REGB0 = ATTR_toolcontext___ToolContext____warning_count(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return REGB0;
}
val_t toolcontext___ToolContext___log_directory(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_toolcontext;
  fra.me.line = 77;
  fra.me.meth = LOCATE_toolcontext___ToolContext___log_directory;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.nitni_local_ref_head = NULL;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* toolcontext.nit:77 */
  REGB0 = TAG_Bool(ATTR_toolcontext___ToolContext____log_directory(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_log_directory", LOCATE_toolcontext, 77);
  }
  fra.me.REG[0] = ATTR_toolcontext___ToolContext____log_directory(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
void toolcontext___ToolContext___check_errors(val_t p0){
  struct {struct stack_frame_t me; val_t MORE_REG[6];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t REGB2;
  val_t tmp;
          static val_t once_value_1; /* Once value */
          static val_t once_value_2; /* Once value */
          static val_t once_value_3; /* Once value */
          static val_t once_value_4; /* Once value */
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_toolcontext;
  fra.me.line = 84;
  fra.me.meth = LOCATE_toolcontext___ToolContext___check_errors;
  fra.me.has_broke = 0;
  fra.me.REG_size = 7;
  fra.me.nitni_local_ref_head = NULL;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[3] = NIT_NULL;
  fra.me.REG[4] = NIT_NULL;
  fra.me.REG[5] = NIT_NULL;
  fra.me.REG[6] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* toolcontext.nit:86 */
  REGB0 = TAG_Bool(ATTR_toolcontext___ToolContext____messages(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_messages", LOCATE_toolcontext, 86);
  }
  fra.me.REG[1] = ATTR_toolcontext___ToolContext____messages(fra.me.REG[0]);
  /* ../lib/standard/collection/array.nit:24 */
  REGB0 = TAG_Bool(ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[1])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_length", LOCATE_standard___collection___array, 24);
  }
  REGB0 = ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[1]);
  /* toolcontext.nit:86 */
  REGB1 = TAG_Int(0);
  REGB2 = TAG_Bool(VAL_ISA(REGB1, VTCOLOR_standard___kernel___Comparable___OTHER(REGB0), VTID_standard___kernel___Comparable___OTHER(REGB0))) /*cast OTHER*/;
  if (UNTAG_Bool(REGB2)) {
  } else {
    nit_abort("Cast failed", NULL, LOCATE_standard___kernel, 0);
  }
  /* ../lib/standard/kernel.nit:234 */
  REGB1 = TAG_Bool(UNTAG_Int(REGB0)>UNTAG_Int(REGB1));
  /* toolcontext.nit:86 */
  if (UNTAG_Bool(REGB1)) {
    /* toolcontext.nit:87 */
    REGB1 = TAG_Bool(ATTR_toolcontext___ToolContext____message_sorter(fra.me.REG[0])!=NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_message_sorter", LOCATE_toolcontext, 87);
    }
    fra.me.REG[1] = ATTR_toolcontext___ToolContext____message_sorter(fra.me.REG[0]);
    REGB1 = TAG_Bool(ATTR_toolcontext___ToolContext____messages(fra.me.REG[0])!=NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_messages", LOCATE_toolcontext, 87);
    }
    fra.me.REG[2] = ATTR_toolcontext___ToolContext____messages(fra.me.REG[0]);
    CALL_standard___collection___sorter___AbstractSorter___sort(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
    /* toolcontext.nit:89 */
    REGB1 = TAG_Bool(ATTR_toolcontext___ToolContext____messages(fra.me.REG[0])!=NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_messages", LOCATE_toolcontext, 89);
    }
    fra.me.REG[2] = ATTR_toolcontext___ToolContext____messages(fra.me.REG[0]);
    /* ../lib/standard/collection/array.nit:269 */
    REGB1 = TAG_Int(0);
    /* ../lib/standard/collection/array.nit:270 */
    REGB0 = TAG_Bool(ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[2])!=NIT_NULL);
    if (UNTAG_Bool(REGB0)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_length", LOCATE_standard___collection___array, 270);
    }
    REGB0 = ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[2]);
    /* ../lib/standard/collection/array.nit:271 */
    fra.me.REG[1] = ATTR_standard___collection___array___Array____items(fra.me.REG[2]);
    /* ../lib/standard/collection/array.nit:272 */
    while(1) {
      /* ../lib/standard/collection/array.nit:24 */
      REGB0 = TAG_Bool(ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[2])!=NIT_NULL);
      if (UNTAG_Bool(REGB0)) {
      } else {
        nit_abort("Uninitialized attribute %s", "_length", LOCATE_standard___collection___array, 24);
      }
      REGB0 = ATTR_standard___collection___array___AbstractArrayRead____length(fra.me.REG[2]);
      REGB2 = TAG_Bool(VAL_ISA(REGB0, VTCOLOR_standard___kernel___Comparable___OTHER(REGB1), VTID_standard___kernel___Comparable___OTHER(REGB1))) /*cast OTHER*/;
      if (UNTAG_Bool(REGB2)) {
      } else {
        nit_abort("Cast failed", NULL, LOCATE_standard___kernel, 0);
      }
      /* ../lib/standard/kernel.nit:232 */
      REGB0 = TAG_Bool(UNTAG_Int(REGB1)<UNTAG_Int(REGB0));
      /* ../lib/standard/collection/array.nit:272 */
      if (UNTAG_Bool(REGB0)) {
        /* ../lib/standard/collection/array.nit:273 */
        REGB0 = TAG_Bool(fra.me.REG[1]==NIT_NULL);
        if (UNTAG_Bool(REGB0)) {
          nit_abort("Reciever is null", NULL, LOCATE_standard___collection___array, 273);
        }
        /* ../lib/standard/collection/array.nit:718 */
        fra.me.REG[3] = ((Nit_NativeArray)fra.me.REG[1])->val[UNTAG_Int(REGB1)];
        /* toolcontext.nit:90 */
        fra.me.REG[4] = CALL_toolcontext___ToolContext___opt_no_color(fra.me.REG[0])(fra.me.REG[0]);
        fra.me.REG[4] = CALL_opts___Option___value(fra.me.REG[4])(fra.me.REG[4]);
        if (UNTAG_Bool(fra.me.REG[4])) {
          /* toolcontext.nit:91 */
          fra.me.REG[4] = CALL_standard___file___Object___stderr(fra.me.REG[0])(fra.me.REG[0]);
          REGB0 = TAG_Int(3);
          fra.me.REG[5] = NEW_Array_standard___collection___array___Array___with_capacity(REGB0);
          if (!once_value_1) {
            fra.me.REG[6] = BOX_NativeString("");
            REGB0 = TAG_Int(0);
            fra.me.REG[6] = NEW_String_standard___string___String___with_native(fra.me.REG[6], REGB0);
            once_value_1 = fra.me.REG[6];
            register_static_object(&once_value_1);
          } else fra.me.REG[6] = once_value_1;
          fra.me.REG[6] = fra.me.REG[6];
          CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[5])(fra.me.REG[5], fra.me.REG[6]);
          fra.me.REG[6] = CALL_standard___string___Object___to_s(fra.me.REG[3])(fra.me.REG[3]);
          CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[5])(fra.me.REG[5], fra.me.REG[6]);
          if (!once_value_2) {
            fra.me.REG[6] = BOX_NativeString("\n");
            REGB0 = TAG_Int(1);
            fra.me.REG[6] = NEW_String_standard___string___String___with_native(fra.me.REG[6], REGB0);
            once_value_2 = fra.me.REG[6];
            register_static_object(&once_value_2);
          } else fra.me.REG[6] = once_value_2;
          fra.me.REG[6] = fra.me.REG[6];
          CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[5])(fra.me.REG[5], fra.me.REG[6]);
          fra.me.REG[5] = CALL_standard___string___Object___to_s(fra.me.REG[5])(fra.me.REG[5]);
          CALL_standard___stream___OStream___write(fra.me.REG[4])(fra.me.REG[4], fra.me.REG[5]);
        } else {
          /* toolcontext.nit:93 */
          fra.me.REG[5] = CALL_standard___file___Object___stderr(fra.me.REG[0])(fra.me.REG[0]);
          REGB0 = TAG_Int(3);
          fra.me.REG[4] = NEW_Array_standard___collection___array___Array___with_capacity(REGB0);
          if (!once_value_3) {
            fra.me.REG[6] = BOX_NativeString("");
            REGB0 = TAG_Int(0);
            fra.me.REG[6] = NEW_String_standard___string___String___with_native(fra.me.REG[6], REGB0);
            once_value_3 = fra.me.REG[6];
            register_static_object(&once_value_3);
          } else fra.me.REG[6] = once_value_3;
          fra.me.REG[6] = fra.me.REG[6];
          CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[4])(fra.me.REG[4], fra.me.REG[6]);
          fra.me.REG[3] = CALL_toolcontext___Message___to_color_string(fra.me.REG[3])(fra.me.REG[3]);
          CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[4])(fra.me.REG[4], fra.me.REG[3]);
          if (!once_value_4) {
            fra.me.REG[3] = BOX_NativeString("\n");
            REGB0 = TAG_Int(1);
            fra.me.REG[3] = NEW_String_standard___string___String___with_native(fra.me.REG[3], REGB0);
            once_value_4 = fra.me.REG[3];
            register_static_object(&once_value_4);
          } else fra.me.REG[3] = once_value_4;
          fra.me.REG[3] = fra.me.REG[3];
          CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[4])(fra.me.REG[4], fra.me.REG[3]);
          fra.me.REG[4] = CALL_standard___string___Object___to_s(fra.me.REG[4])(fra.me.REG[4]);
          CALL_standard___stream___OStream___write(fra.me.REG[5])(fra.me.REG[5], fra.me.REG[4]);
        }
        /* ../lib/standard/collection/array.nit:274 */
        REGB0 = TAG_Int(1);
        /* ../lib/standard/kernel.nit:235 */
        REGB0 = TAG_Int(UNTAG_Int(REGB1)+UNTAG_Int(REGB0));
        /* ../lib/standard/collection/array.nit:274 */
        REGB1 = REGB0;
      } else {
        /* ../lib/standard/collection/array.nit:272 */
        goto label5;
      }
    }
    label5: while(0);
    /* toolcontext.nit:97 */
    REGB1 = TAG_Bool(ATTR_toolcontext___ToolContext____messages(fra.me.REG[0])!=NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_messages", LOCATE_toolcontext, 97);
    }
    fra.me.REG[1] = ATTR_toolcontext___ToolContext____messages(fra.me.REG[0]);
    CALL_standard___collection___abstract_collection___RemovableCollection___clear(fra.me.REG[1])(fra.me.REG[1]);
  }
  /* toolcontext.nit:100 */
  REGB1 = CALL_toolcontext___ToolContext___error_count(fra.me.REG[0])(fra.me.REG[0]);
  REGB0 = TAG_Int(0);
  REGB2 = TAG_Bool(VAL_ISA(REGB0, VTCOLOR_standard___kernel___Comparable___OTHER(REGB1), VTID_standard___kernel___Comparable___OTHER(REGB1))) /*cast OTHER*/;
  if (UNTAG_Bool(REGB2)) {
  } else {
    nit_abort("Cast failed", NULL, LOCATE_standard___kernel, 0);
  }
  /* ../lib/standard/kernel.nit:234 */
  REGB0 = TAG_Bool(UNTAG_Int(REGB1)>UNTAG_Int(REGB0));
  /* toolcontext.nit:100 */
  if (UNTAG_Bool(REGB0)) {
    REGB0 = TAG_Int(1);
    CALL_standard___kernel___Object___exit(fra.me.REG[0])(fra.me.REG[0], REGB0);
  }
  stack_frame_head = fra.me.prev;
  return;
}
void toolcontext___ToolContext___error(val_t p0, val_t p1, val_t p2){
  struct {struct stack_frame_t me; val_t MORE_REG[3];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_toolcontext;
  fra.me.line = 103;
  fra.me.meth = LOCATE_toolcontext___ToolContext___error;
  fra.me.has_broke = 0;
  fra.me.REG_size = 4;
  fra.me.nitni_local_ref_head = NULL;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[3] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  fra.me.REG[2] = p2;
  /* toolcontext.nit:106 */
  REGB0 = TAG_Bool(ATTR_toolcontext___ToolContext____messages(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_messages", LOCATE_toolcontext, 106);
  }
  fra.me.REG[3] = ATTR_toolcontext___ToolContext____messages(fra.me.REG[0]);
  fra.me.REG[2] = NEW_Message_toolcontext___Message___init(fra.me.REG[1], fra.me.REG[2]);
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[3])(fra.me.REG[3], fra.me.REG[2]);
  /* toolcontext.nit:107 */
  REGB0 = TAG_Bool(ATTR_toolcontext___ToolContext____error_count(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_error_count", LOCATE_toolcontext, 107);
  }
  REGB0 = ATTR_toolcontext___ToolContext____error_count(fra.me.REG[0]);
  REGB1 = TAG_Int(1);
  /* ../lib/standard/kernel.nit:235 */
  REGB1 = TAG_Int(UNTAG_Int(REGB0)+UNTAG_Int(REGB1));
  /* toolcontext.nit:107 */
  ATTR_toolcontext___ToolContext____error_count(fra.me.REG[0]) = REGB1;
  /* toolcontext.nit:108 */
  fra.me.REG[2] = CALL_toolcontext___ToolContext___opt_stop_on_first_error(fra.me.REG[0])(fra.me.REG[0]);
  fra.me.REG[2] = CALL_opts___Option___value(fra.me.REG[2])(fra.me.REG[2]);
  if (UNTAG_Bool(fra.me.REG[2])) {
    CALL_toolcontext___ToolContext___check_errors(fra.me.REG[0])(fra.me.REG[0]);
  }
  stack_frame_head = fra.me.prev;
  return;
}
void toolcontext___ToolContext___fatal_error(val_t p0, val_t p1, val_t p2){
  struct {struct stack_frame_t me; val_t MORE_REG[2];} fra;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_toolcontext;
  fra.me.line = 111;
  fra.me.meth = LOCATE_toolcontext___ToolContext___fatal_error;
  fra.me.has_broke = 0;
  fra.me.REG_size = 3;
  fra.me.nitni_local_ref_head = NULL;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  fra.me.REG[2] = p2;
  /* toolcontext.nit:114 */
  CALL_toolcontext___ToolContext___error(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[1], fra.me.REG[2]);
  /* toolcontext.nit:115 */
  CALL_toolcontext___ToolContext___check_errors(fra.me.REG[0])(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return;
}
void toolcontext___ToolContext___warning(val_t p0, val_t p1, val_t p2){
  struct {struct stack_frame_t me; val_t MORE_REG[3];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t REGB2;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_toolcontext;
  fra.me.line = 118;
  fra.me.meth = LOCATE_toolcontext___ToolContext___warning;
  fra.me.has_broke = 0;
  fra.me.REG_size = 4;
  fra.me.nitni_local_ref_head = NULL;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[3] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  fra.me.REG[2] = p2;
  /* toolcontext.nit:121 */
  REGB0 = TAG_Bool(ATTR_toolcontext___ToolContext____opt_warn(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_opt_warn", LOCATE_toolcontext, 121);
  }
  fra.me.REG[3] = ATTR_toolcontext___ToolContext____opt_warn(fra.me.REG[0]);
  fra.me.REG[3] = CALL_opts___Option___value(fra.me.REG[3])(fra.me.REG[3]);
  REGB0 = TAG_Int(0);
  REGB1 = TAG_Bool(IS_EQUAL_ON(REGB0,fra.me.REG[3]));
  if (UNTAG_Bool(REGB1)) {
  } else {
    REGB2 = TAG_Bool(fra.me.REG[3]==NIT_NULL);
    if (UNTAG_Bool(REGB2)) {
      REGB2 = TAG_Bool(false);
      REGB1 = REGB2;
    } else {
      /* ../lib/standard/kernel.nit:227 */
      REGB0 = TAG_Bool((fra.me.REG[3])==(REGB0));
      /* toolcontext.nit:121 */
      REGB1 = REGB0;
    }
  }
  if (UNTAG_Bool(REGB1)) {
    goto label1;
  }
  /* toolcontext.nit:122 */
  REGB1 = TAG_Bool(ATTR_toolcontext___ToolContext____messages(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_messages", LOCATE_toolcontext, 122);
  }
  fra.me.REG[3] = ATTR_toolcontext___ToolContext____messages(fra.me.REG[0]);
  fra.me.REG[2] = NEW_Message_toolcontext___Message___init(fra.me.REG[1], fra.me.REG[2]);
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[3])(fra.me.REG[3], fra.me.REG[2]);
  /* toolcontext.nit:123 */
  REGB1 = TAG_Bool(ATTR_toolcontext___ToolContext____warning_count(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_warning_count", LOCATE_toolcontext, 123);
  }
  REGB1 = ATTR_toolcontext___ToolContext____warning_count(fra.me.REG[0]);
  REGB0 = TAG_Int(1);
  /* ../lib/standard/kernel.nit:235 */
  REGB0 = TAG_Int(UNTAG_Int(REGB1)+UNTAG_Int(REGB0));
  /* toolcontext.nit:123 */
  ATTR_toolcontext___ToolContext____warning_count(fra.me.REG[0]) = REGB0;
  /* toolcontext.nit:124 */
  fra.me.REG[2] = CALL_toolcontext___ToolContext___opt_stop_on_first_error(fra.me.REG[0])(fra.me.REG[0]);
  fra.me.REG[2] = CALL_opts___Option___value(fra.me.REG[2])(fra.me.REG[2]);
  if (UNTAG_Bool(fra.me.REG[2])) {
    CALL_toolcontext___ToolContext___check_errors(fra.me.REG[0])(fra.me.REG[0]);
  }
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return;
}
void toolcontext___ToolContext___info(val_t p0, val_t p1, val_t p2){
  struct {struct stack_frame_t me; val_t MORE_REG[3];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t REGB2;
  val_t tmp;
    static val_t once_value_1; /* Once value */
    static val_t once_value_2; /* Once value */
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_toolcontext;
  fra.me.line = 127;
  fra.me.meth = LOCATE_toolcontext___ToolContext___info;
  fra.me.has_broke = 0;
  fra.me.REG_size = 4;
  fra.me.nitni_local_ref_head = NULL;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[3] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  REGB0 = p2;
  /* toolcontext.nit:130 */
  REGB1 = CALL_toolcontext___ToolContext___verbose_level(fra.me.REG[0])(fra.me.REG[0]);
  REGB2 = TAG_Bool(VAL_ISA(REGB1, VTCOLOR_standard___kernel___Comparable___OTHER(REGB0), VTID_standard___kernel___Comparable___OTHER(REGB0))) /*cast OTHER*/;
  if (UNTAG_Bool(REGB2)) {
  } else {
    nit_abort("Cast failed", NULL, LOCATE_standard___kernel, 0);
  }
  /* ../lib/standard/kernel.nit:231 */
  REGB1 = TAG_Bool(UNTAG_Int(REGB0)<=UNTAG_Int(REGB1));
  /* toolcontext.nit:130 */
  if (UNTAG_Bool(REGB1)) {
    /* toolcontext.nit:131 */
    REGB1 = TAG_Int(3);
    fra.me.REG[2] = NEW_Array_standard___collection___array___Array___with_capacity(REGB1);
    if (!once_value_1) {
      fra.me.REG[3] = BOX_NativeString("");
      REGB1 = TAG_Int(0);
      fra.me.REG[3] = NEW_String_standard___string___String___with_native(fra.me.REG[3], REGB1);
      once_value_1 = fra.me.REG[3];
      register_static_object(&once_value_1);
    } else fra.me.REG[3] = once_value_1;
    fra.me.REG[3] = fra.me.REG[3];
    CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[3]);
    CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[1]);
    if (!once_value_2) {
      fra.me.REG[1] = BOX_NativeString("");
      REGB1 = TAG_Int(0);
      fra.me.REG[1] = NEW_String_standard___string___String___with_native(fra.me.REG[1], REGB1);
      once_value_2 = fra.me.REG[1];
      register_static_object(&once_value_2);
    } else fra.me.REG[1] = once_value_2;
    fra.me.REG[1] = fra.me.REG[1];
    CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[1]);
    fra.me.REG[2] = CALL_standard___string___Object___to_s(fra.me.REG[2])(fra.me.REG[2]);
    CALL_standard___file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[2]);
  }
  stack_frame_head = fra.me.prev;
  return;
}
val_t toolcontext___ToolContext___option_context(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_toolcontext;
  fra.me.line = 135;
  fra.me.meth = LOCATE_toolcontext___ToolContext___option_context;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.nitni_local_ref_head = NULL;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* toolcontext.nit:135 */
  REGB0 = TAG_Bool(ATTR_toolcontext___ToolContext____option_context(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_option_context", LOCATE_toolcontext, 135);
  }
  fra.me.REG[0] = ATTR_toolcontext___ToolContext____option_context(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t toolcontext___ToolContext___opt_warn(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_toolcontext;
  fra.me.line = 138;
  fra.me.meth = LOCATE_toolcontext___ToolContext___opt_warn;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.nitni_local_ref_head = NULL;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* toolcontext.nit:138 */
  REGB0 = TAG_Bool(ATTR_toolcontext___ToolContext____opt_warn(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_opt_warn", LOCATE_toolcontext, 138);
  }
  fra.me.REG[0] = ATTR_toolcontext___ToolContext____opt_warn(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t toolcontext___ToolContext___opt_quiet(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_toolcontext;
  fra.me.line = 141;
  fra.me.meth = LOCATE_toolcontext___ToolContext___opt_quiet;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.nitni_local_ref_head = NULL;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* toolcontext.nit:141 */
  REGB0 = TAG_Bool(ATTR_toolcontext___ToolContext____opt_quiet(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_opt_quiet", LOCATE_toolcontext, 141);
  }
  fra.me.REG[0] = ATTR_toolcontext___ToolContext____opt_quiet(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t toolcontext___ToolContext___opt_log(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_toolcontext;
  fra.me.line = 144;
  fra.me.meth = LOCATE_toolcontext___ToolContext___opt_log;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.nitni_local_ref_head = NULL;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* toolcontext.nit:144 */
  REGB0 = TAG_Bool(ATTR_toolcontext___ToolContext____opt_log(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_opt_log", LOCATE_toolcontext, 144);
  }
  fra.me.REG[0] = ATTR_toolcontext___ToolContext____opt_log(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t toolcontext___ToolContext___opt_log_dir(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_toolcontext;
  fra.me.line = 147;
  fra.me.meth = LOCATE_toolcontext___ToolContext___opt_log_dir;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.nitni_local_ref_head = NULL;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* toolcontext.nit:147 */
  REGB0 = TAG_Bool(ATTR_toolcontext___ToolContext____opt_log_dir(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_opt_log_dir", LOCATE_toolcontext, 147);
  }
  fra.me.REG[0] = ATTR_toolcontext___ToolContext____opt_log_dir(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t toolcontext___ToolContext___opt_help(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_toolcontext;
  fra.me.line = 150;
  fra.me.meth = LOCATE_toolcontext___ToolContext___opt_help;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.nitni_local_ref_head = NULL;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* toolcontext.nit:150 */
  REGB0 = TAG_Bool(ATTR_toolcontext___ToolContext____opt_help(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_opt_help", LOCATE_toolcontext, 150);
  }
  fra.me.REG[0] = ATTR_toolcontext___ToolContext____opt_help(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t toolcontext___ToolContext___opt_version(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_toolcontext;
  fra.me.line = 153;
  fra.me.meth = LOCATE_toolcontext___ToolContext___opt_version;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.nitni_local_ref_head = NULL;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* toolcontext.nit:153 */
  REGB0 = TAG_Bool(ATTR_toolcontext___ToolContext____opt_version(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_opt_version", LOCATE_toolcontext, 153);
  }
  fra.me.REG[0] = ATTR_toolcontext___ToolContext____opt_version(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t toolcontext___ToolContext___opt_verbose(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_toolcontext;
  fra.me.line = 156;
  fra.me.meth = LOCATE_toolcontext___ToolContext___opt_verbose;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.nitni_local_ref_head = NULL;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* toolcontext.nit:156 */
  REGB0 = TAG_Bool(ATTR_toolcontext___ToolContext____opt_verbose(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_opt_verbose", LOCATE_toolcontext, 156);
  }
  fra.me.REG[0] = ATTR_toolcontext___ToolContext____opt_verbose(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t toolcontext___ToolContext___opt_stop_on_first_error(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_toolcontext;
  fra.me.line = 159;
  fra.me.meth = LOCATE_toolcontext___ToolContext___opt_stop_on_first_error;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.nitni_local_ref_head = NULL;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* toolcontext.nit:159 */
  REGB0 = TAG_Bool(ATTR_toolcontext___ToolContext____opt_stop_on_first_error(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_opt_stop_on_first_error", LOCATE_toolcontext, 159);
  }
  fra.me.REG[0] = ATTR_toolcontext___ToolContext____opt_stop_on_first_error(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t toolcontext___ToolContext___opt_no_color(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_toolcontext;
  fra.me.line = 162;
  fra.me.meth = LOCATE_toolcontext___ToolContext___opt_no_color;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.nitni_local_ref_head = NULL;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* toolcontext.nit:162 */
  REGB0 = TAG_Bool(ATTR_toolcontext___ToolContext____opt_no_color(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_opt_no_color", LOCATE_toolcontext, 162);
  }
  fra.me.REG[0] = ATTR_toolcontext___ToolContext____opt_no_color(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t toolcontext___ToolContext___verbose_level(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_toolcontext;
  fra.me.line = 165;
  fra.me.meth = LOCATE_toolcontext___ToolContext___verbose_level;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.nitni_local_ref_head = NULL;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* toolcontext.nit:165 */
  REGB0 = TAG_Bool(ATTR_toolcontext___ToolContext____verbose_level(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_verbose_level", LOCATE_toolcontext, 165);
  }
  REGB0 = ATTR_toolcontext___ToolContext____verbose_level(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return REGB0;
}
void toolcontext___ToolContext___init(val_t p0, int* init_table){
  int itpos1 = VAL2OBJ(p0)->vft[INIT_TABLE_POS_toolcontext___ToolContext].i;
  struct {struct stack_frame_t me; val_t MORE_REG[3];} fra;
  val_t REGB0;
  val_t tmp;
  if (init_table[itpos1]) return;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_toolcontext;
  fra.me.line = 168;
  fra.me.meth = LOCATE_toolcontext___ToolContext___init;
  fra.me.has_broke = 0;
  fra.me.REG_size = 4;
  fra.me.nitni_local_ref_head = NULL;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[3] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* toolcontext.nit:170 */
  fra.me.REG[1] = CALL_toolcontext___ToolContext___option_context(fra.me.REG[0])(fra.me.REG[0]);
  REGB0 = TAG_Int(8);
  fra.me.REG[2] = NEW_Array_standard___collection___array___Array___with_capacity(REGB0);
  fra.me.REG[3] = CALL_toolcontext___ToolContext___opt_warn(fra.me.REG[0])(fra.me.REG[0]);
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[3]);
  fra.me.REG[3] = CALL_toolcontext___ToolContext___opt_quiet(fra.me.REG[0])(fra.me.REG[0]);
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[3]);
  fra.me.REG[3] = CALL_toolcontext___ToolContext___opt_stop_on_first_error(fra.me.REG[0])(fra.me.REG[0]);
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[3]);
  fra.me.REG[3] = CALL_toolcontext___ToolContext___opt_no_color(fra.me.REG[0])(fra.me.REG[0]);
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[3]);
  fra.me.REG[3] = CALL_toolcontext___ToolContext___opt_log(fra.me.REG[0])(fra.me.REG[0]);
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[3]);
  fra.me.REG[3] = CALL_toolcontext___ToolContext___opt_log_dir(fra.me.REG[0])(fra.me.REG[0]);
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[3]);
  fra.me.REG[3] = CALL_toolcontext___ToolContext___opt_help(fra.me.REG[0])(fra.me.REG[0]);
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[3]);
  fra.me.REG[3] = CALL_toolcontext___ToolContext___opt_version(fra.me.REG[0])(fra.me.REG[0]);
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[3]);
  fra.me.REG[0] = CALL_toolcontext___ToolContext___opt_verbose(fra.me.REG[0])(fra.me.REG[0]);
  CALL_standard___collection___abstract_collection___SimpleCollection___add(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[0]);
  CALL_opts___OptionContext___add_option(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
  stack_frame_head = fra.me.prev;
  init_table[itpos1] = 1;
  return;
}
void toolcontext___ToolContext___process_options(val_t p0){
  struct {struct stack_frame_t me; val_t MORE_REG[3];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_toolcontext;
  fra.me.line = 173;
  fra.me.meth = LOCATE_toolcontext___ToolContext___process_options;
  fra.me.has_broke = 0;
  fra.me.REG_size = 4;
  fra.me.nitni_local_ref_head = NULL;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[3] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* toolcontext.nit:173 */
  fra.me.REG[1] = fra.me.REG[0];
  /* toolcontext.nit:176 */
  fra.me.REG[2] = CALL_toolcontext___ToolContext___opt_warn(fra.me.REG[1])(fra.me.REG[1]);
  REGB0 = TAG_Int(1);
  CALL_opts___Option___value__eq(fra.me.REG[2])(fra.me.REG[2], REGB0);
  /* toolcontext.nit:179 */
  fra.me.REG[2] = CALL_toolcontext___ToolContext___option_context(fra.me.REG[1])(fra.me.REG[1]);
  fra.me.REG[3] = CALL_standard___string___Object___args(fra.me.REG[1])(fra.me.REG[1]);
  CALL_opts___OptionContext___parse(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[3]);
  /* toolcontext.nit:182 */
  fra.me.REG[3] = CALL_toolcontext___ToolContext___opt_verbose(fra.me.REG[1])(fra.me.REG[1]);
  fra.me.REG[3] = CALL_opts___Option___value(fra.me.REG[3])(fra.me.REG[3]);
  ATTR_toolcontext___ToolContext____verbose_level(fra.me.REG[1]) = fra.me.REG[3];
  /* toolcontext.nit:184 */
  fra.me.REG[3] = CALL_toolcontext___ToolContext___opt_quiet(fra.me.REG[1])(fra.me.REG[1]);
  fra.me.REG[3] = CALL_opts___Option___value(fra.me.REG[3])(fra.me.REG[3]);
  if (UNTAG_Bool(fra.me.REG[3])) {
    fra.me.REG[3] = CALL_toolcontext___ToolContext___opt_warn(fra.me.REG[1])(fra.me.REG[1]);
    REGB0 = TAG_Int(0);
    CALL_opts___Option___value__eq(fra.me.REG[3])(fra.me.REG[3], REGB0);
  }
  /* toolcontext.nit:186 */
  fra.me.REG[3] = CALL_toolcontext___ToolContext___opt_log_dir(fra.me.REG[1])(fra.me.REG[1]);
  fra.me.REG[3] = CALL_opts___Option___value(fra.me.REG[3])(fra.me.REG[3]);
  REGB0 = TAG_Bool(fra.me.REG[3]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    REGB1 = TAG_Bool(fra.me.REG[3]==NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
      REGB1 = TAG_Bool(false);
      REGB0 = REGB1;
    } else {
      REGB1 = CALL_standard___kernel___Object_____eqeq(fra.me.REG[3])(fra.me.REG[3], NIT_NULL);
      REGB0 = REGB1;
    }
  }
  REGB0 = TAG_Bool(!UNTAG_Bool(REGB0));
  if (UNTAG_Bool(REGB0)) {
    fra.me.REG[3] = CALL_toolcontext___ToolContext___opt_log_dir(fra.me.REG[1])(fra.me.REG[1]);
    fra.me.REG[3] = CALL_opts___Option___value(fra.me.REG[3])(fra.me.REG[3]);
    REGB0 = TAG_Bool((fra.me.REG[3]!=NIT_NULL) && VAL_ISA(fra.me.REG[3], COLOR_standard___string___String, ID_standard___string___String)) /*cast String*/;
    if (UNTAG_Bool(REGB0)) {
    } else {
      nit_abort("Cast failed", NULL, LOCATE_toolcontext, 186);
    }
    ATTR_toolcontext___ToolContext____log_directory(fra.me.REG[1]) = fra.me.REG[3];
  }
  /* toolcontext.nit:187 */
  REGB0 = TAG_Bool(ATTR_toolcontext___ToolContext____opt_log(fra.me.REG[1])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_opt_log", LOCATE_toolcontext, 187);
  }
  fra.me.REG[3] = ATTR_toolcontext___ToolContext____opt_log(fra.me.REG[1]);
  fra.me.REG[3] = CALL_opts___Option___value(fra.me.REG[3])(fra.me.REG[3]);
  if (UNTAG_Bool(fra.me.REG[3])) {
    /* toolcontext.nit:189 */
    fra.me.REG[1] = CALL_toolcontext___ToolContext___log_directory(fra.me.REG[1])(fra.me.REG[1]);
    CALL_standard___file___String___mkdir(fra.me.REG[1])(fra.me.REG[1]);
  }
  stack_frame_head = fra.me.prev;
  return;
}
