#include "nit.common.h"
extern const int COLOR_toolcontext__Message___64dlocation;
val* toolcontext__Message__location(val* self);
void toolcontext__Message__location_61d(val* self, val* p0);
extern const int COLOR_toolcontext__Message___64dtext;
val* toolcontext__Message__text(val* self);
void toolcontext__Message__text_61d(val* self, val* p0);
extern const int COLOR_kernel__Comparable_VTOTHER;
extern const int COLOR_toolcontext__Message__location;
extern const int COLOR_kernel__Comparable___60d;
short int toolcontext__Message___60d(val* self, val* p0);
extern const int COLOR_toolcontext__Message__text;
val* NEW_array__Array(const struct type* type);
extern const struct type type_array__Arraykernel__Object;
extern const int COLOR_array__Array__with_capacity;
val* string__NativeString__to_s_with_length(char* self, long p0);
extern const int COLOR_abstract_collection__SimpleCollection__add;
extern const int COLOR_string__Object__to_s;
val* toolcontext__Message__to_s(val* self);
extern const int COLOR_location__Location__file;
extern const int COLOR_location__Location__colored_line;
val* toolcontext__Message__to_color_string(val* self);
void toolcontext__Message__init(val* self, val* p0, val* p1);
extern const int COLOR_toolcontext__ToolContext___64derror_count;
long toolcontext__ToolContext__error_count(val* self);
void toolcontext__ToolContext__error_count_61d(val* self, long p0);
extern const int COLOR_toolcontext__ToolContext___64dwarning_count;
long toolcontext__ToolContext__warning_count(val* self);
void toolcontext__ToolContext__warning_count_61d(val* self, long p0);
extern const int COLOR_toolcontext__ToolContext___64dlog_directory;
val* toolcontext__ToolContext__log_directory(val* self);
void toolcontext__ToolContext__log_directory_61d(val* self, val* p0);
extern const int COLOR_toolcontext__ToolContext___64dmessages;
val* toolcontext__ToolContext__messages(val* self);
void toolcontext__ToolContext__messages_61d(val* self, val* p0);
extern const int COLOR_toolcontext__ToolContext___64dmessage_sorter;
val* toolcontext__ToolContext__message_sorter(val* self);
void toolcontext__ToolContext__message_sorter_61d(val* self, val* p0);
extern const int COLOR_toolcontext__ToolContext__messages;
extern const int COLOR_abstract_collection__Collection__length;
extern const struct type type_kernel__Int;
extern const int COLOR_toolcontext__ToolContext__message_sorter;
extern const int COLOR_sorter__AbstractSorter__sort;
extern const int COLOR_abstract_collection__Collection__iterator;
extern const int COLOR_abstract_collection__Iterator__is_ok;
extern const int COLOR_abstract_collection__Iterator__item;
extern const int COLOR_toolcontext__ToolContext__opt_no_color;
extern const int COLOR_opts__Option__value;
extern const int COLOR_file__Object__stderr;
val* NEW_array__NativeArray(int length, const struct type* type);
extern const struct type type_array__NativeArraykernel__Object;
extern const int COLOR_array__Array__with_native;
extern const int COLOR_stream__OStream__write;
extern const int COLOR_toolcontext__Message__to_color_string;
extern const int COLOR_abstract_collection__Iterator__next;
extern const int COLOR_abstract_collection__RemovableCollection__clear;
extern const int COLOR_toolcontext__ToolContext__error_count;
extern const int COLOR_kernel__Object__exit;
void toolcontext__ToolContext__check_errors(val* self);
val* NEW_toolcontext__Message(const struct type* type);
extern const struct type type_toolcontext__Message;
extern const int COLOR_toolcontext__Message__init;
extern const int COLOR_toolcontext__ToolContext__error_count_61d;
extern const int COLOR_toolcontext__ToolContext__opt_stop_on_first_error;
extern const int COLOR_toolcontext__ToolContext__check_errors;
void toolcontext__ToolContext__error(val* self, val* p0, val* p1);
extern const int COLOR_toolcontext__ToolContext__error;
void toolcontext__ToolContext__fatal_error(val* self, val* p0, val* p1);
extern const int COLOR_toolcontext__ToolContext__opt_warn;
extern const struct class class_kernel__Int;
extern const int COLOR_toolcontext__ToolContext__warning_count;
extern const int COLOR_toolcontext__ToolContext__warning_count_61d;
void toolcontext__ToolContext__warning(val* self, val* p0, val* p1);
extern const int COLOR_toolcontext__ToolContext__verbose_level;
extern const int COLOR_file__Object__print;
void toolcontext__ToolContext__info(val* self, val* p0, long p1);
extern const int COLOR_toolcontext__ToolContext___64doption_context;
val* toolcontext__ToolContext__option_context(val* self);
void toolcontext__ToolContext__option_context_61d(val* self, val* p0);
extern const int COLOR_toolcontext__ToolContext___64dopt_warn;
val* toolcontext__ToolContext__opt_warn(val* self);
void toolcontext__ToolContext__opt_warn_61d(val* self, val* p0);
extern const int COLOR_toolcontext__ToolContext___64dopt_quiet;
val* toolcontext__ToolContext__opt_quiet(val* self);
void toolcontext__ToolContext__opt_quiet_61d(val* self, val* p0);
extern const int COLOR_toolcontext__ToolContext___64dopt_log;
val* toolcontext__ToolContext__opt_log(val* self);
void toolcontext__ToolContext__opt_log_61d(val* self, val* p0);
extern const int COLOR_toolcontext__ToolContext___64dopt_log_dir;
val* toolcontext__ToolContext__opt_log_dir(val* self);
void toolcontext__ToolContext__opt_log_dir_61d(val* self, val* p0);
extern const int COLOR_toolcontext__ToolContext___64dopt_help;
val* toolcontext__ToolContext__opt_help(val* self);
void toolcontext__ToolContext__opt_help_61d(val* self, val* p0);
extern const int COLOR_toolcontext__ToolContext___64dopt_version;
val* toolcontext__ToolContext__opt_version(val* self);
void toolcontext__ToolContext__opt_version_61d(val* self, val* p0);
extern const int COLOR_toolcontext__ToolContext___64dopt_verbose;
val* toolcontext__ToolContext__opt_verbose(val* self);
void toolcontext__ToolContext__opt_verbose_61d(val* self, val* p0);
extern const int COLOR_toolcontext__ToolContext___64dopt_stop_on_first_error;
val* toolcontext__ToolContext__opt_stop_on_first_error(val* self);
void toolcontext__ToolContext__opt_stop_on_first_error_61d(val* self, val* p0);
extern const int COLOR_toolcontext__ToolContext___64dopt_no_color;
val* toolcontext__ToolContext__opt_no_color(val* self);
void toolcontext__ToolContext__opt_no_color_61d(val* self, val* p0);
extern const int COLOR_toolcontext__ToolContext___64dverbose_level;
long toolcontext__ToolContext__verbose_level(val* self);
void toolcontext__ToolContext__verbose_level_61d(val* self, long p0);
extern const int COLOR_toolcontext__ToolContext__option_context;
extern const int COLOR_toolcontext__ToolContext__opt_quiet;
extern const int COLOR_toolcontext__ToolContext__opt_log;
extern const int COLOR_toolcontext__ToolContext__opt_log_dir;
extern const int COLOR_toolcontext__ToolContext__opt_help;
extern const int COLOR_toolcontext__ToolContext__opt_version;
extern const int COLOR_toolcontext__ToolContext__opt_verbose;
extern const struct type type_array__Arrayopts__Option;
extern const struct type type_array__NativeArrayopts__Option;
extern const int COLOR_opts__OptionContext__add_option;
void toolcontext__ToolContext__init(val* self);
extern const int COLOR_opts__Option__value_61d;
extern const int COLOR_string__Object__args;
extern const int COLOR_opts__OptionContext__parse;
extern const int COLOR_toolcontext__ToolContext__verbose_level_61d;
extern const int COLOR_toolcontext__ToolContext__log_directory_61d;
extern const int COLOR_toolcontext__ToolContext__log_directory;
extern const int COLOR_file__String__mkdir;
void toolcontext__ToolContext__process_options(val* self);
