alt/base_attr3_alt1.nit:22,3--8: Visibility error: Property base_attr2::A::a1= is private.
alt/base_attr3_alt1.nit:24,3--8: Visibility error: Property base_attr2::A::a2= is private.
alt/base_attr3_alt1.nit:25,3--4: Visibility error: Property base_attr2::A::a3 is private.
alt/base_attr3_alt1.nit:26,3--8: Visibility error: Property base_attr2::A::a3= is private.
alt/base_attr3_alt1.nit:31,3--4: Visibility error: Property base_attr2::A::a6 is private.
alt/base_attr3_alt1.nit:37,3--4: Visibility error: Property base_attr2::A::a9 is private.
alt/base_attr3_alt1.nit:40,3--9: Visibility error: Property base_attr2::A::a10= is private.
alt/base_attr3_alt1.nit:42,3--9: Visibility error: Property base_attr2::A::a11= is private.
alt/base_attr3_alt1.nit:43,3--5: Visibility error: Property base_attr2::A::a12 is private.
alt/base_attr3_alt1.nit:44,3--9: Visibility error: Property base_attr2::A::a12= is private.
